### ISSUE TITLE
Could you please put all gz files in archive?

### ISSUE THREAD

**Issue by endrebak** [weizhouUMICH/SAIGE#10]
When you move the new versions to archive/ it breaks my build scripts. The best practice is to have a fixed link to each version that is never changed. 

Thanks.

**Comment by weizhouUMICH** [comment]
Sorry for the inconvenience! 
Now all previous versions are stored here in the dropbox folder https://www.dropbox.com/home/Lee_Group_Team_Folder/SAIGE-source-code 

Thanks,
Wei

**Comment by endrebak** [comment]
Thanks a bunch!

And thanks for SAIGE :)
