### ISSUE TITLE
Does the latest version have issue of LOCO = TRUE? 

### ISSUE THREAD

**Issue by gaojianjunxf** [weizhouUMICH/SAIGE#101]

**Comment by gaojianjunxf** [comment]
I am using UKBiobank data. LOCO = FALSE works but LOCO = TRUE doesn't.

**Comment by longmanz** [comment]
Hi Wei,
I am experiencing the same issue here with v0.35.8.1. The error message is as followed:


6  threads are set to be used  
leave-one-chromosome-out is activated! Note this option will only be applied to autosomal variants
Error in if (chromosomeStartIndexVec[i] <= chromosomeStartIndexVec[i -  : 
  argument is of length zero
Calls: fitNULLGLMM
Execution halted

Could you help to see what is going on? When I set the --LOCO==FALSE, everything went well without a problem (both step 1 & 2 are fine).

Thank you in advance.

Best,
Longda

**Comment by carbocation** [comment]
We're seeing the same issue (also discussed in Issue #95 )

**Comment by lineskotte** [comment]
I am seeing the same issue, on in-house data.

**Comment by weizhouUMICH** [comment]
Sorry for having this bug for a long time. I've now tried to fixed it in the version 0.35.8.7

**Comment by gaojianjunxf** [comment]
Hi Wei;
Thanks a lot! I am going to try the latest version.
Most sincerely
jianjun
