### ISSUE TITLE
Is there a way to limit the number of threads for step2?

### ISSUE THREAD

**Issue by jhchung** [weizhouUMICH/SAIGE#102]
Hi,

I am trying to run SAIGE in a shared HPC environment using the docker image. Is there a way to limit the number of cores used by Step2? I see that Step1 has the `--nThreads` option, but don't see any similar parameter for Step2. 

* SAIGE version 0.35.8.2
* Docker image 0.35.8.3 

Thanks,
-Jonathan

**Comment by weizhouUMICH** [comment]
Hi,
Step 2 only uses one node per each job.

Thanks,
Wei

**Comment by jhchung** [comment]
Hmm... interesting. By node, do you mean all available cores on a given machine or that it should run on a single core?

When I run Step 2 on bgen input data, it spawns several slave instances (enough to fill all the cores). 

The processes look like this example:
```/usr/local/lib/R/bin/exec/R --slave --no-restore --file=/usr/local/bin/step2_SPAtests.R --args <...>```

When I kill the main process, the following error message is shown:

```
Error in getDosage_bgen_noquery() :
A C++ exception occurred (unknown reason)
Calls: SPAGMMATtest -> getDosage_bgen_noquery
```


Could the problem be related to the bgen import? Does SAIGE still use Bolt-LMM code for importing data?

**Comment by weizhouUMICH** [comment]
It could be possible. SAIGE still uses BOLT-LMM code for importing the bgen
data where is no query.
This is an interesting problem.

**Comment by jhchung** [comment]
I see. 

I think I've found a workaround to this issue. Setting the openMP num threads flag (`OMP_NUM_THREADS`)

 `export OMP_NUM_THREADS="1"`

**Comment by jhchung** [comment]
I will close the issue now.
