### ISSUE TITLE
Error fitting binary trait null model with no covariates.

### ISSUE THREAD

**Issue by achilleasNP** [weizhouUMICH/SAIGE#103]
Using version 35.8.3. I get an error when using no covariates:
194  samples will be used for analysis
Error in X1[, i] : subscript out of bounds
Calls: fitNULLGLMM -> checkPerfectSep -> unique
Execution halted

The problem goes away when I add a a covariate to my model.

**Comment by agilly** [comment]
Same issue. Hope it will be fixed in the next release.

**Comment by weizhouUMICH** [comment]
Please try the version 0.35.8.7
