### ISSUE TITLE
perfect seperation is detected

### ISSUE THREAD

**Issue by hhx037** [weizhouUMICH/SAIGE#105]
Hi,

I'm trying to run step1 using sex, age, and the first five PCs as covariates (for a binary phenotype), and I'm getting many warnings regarding the PCs:

formula is  phen~sex+age+PC1+PC2+PC3+PC4+PC5
6414  samples have non-missing phenotypes
237  samples in geno file do not have phenotypes
6414  samples will be used for analysis
perfect seperation is detected!  PC1-0.000127566  will be excluded in the model
perfect seperation is detected!  PC1-0.0001420265  will be excluded in the model
perfect seperation is detected!  PC1-0.00014333  will be excluded in the model
...

There are 90415 variants in my bim file, and the PCs were calculated using the step1 input plink files (with flashpca).

When I plot cases and controls for the various PCs (PC1 vs PC2, PC1 vs PC3, PC2 vs PC3 etc.) I cannot see any single PC that separates my cases from my controls.

Could you please tell me what you think is the cause of this, and what I could do to remedy it?

Thanks,

Steph

**Comment by weizhouUMICH** [comment]
Hi Steph, 

The log shows "PC1-0.000127566" and "PC1-0.0001420265" were identified as covariates, which is incorrect. It is possible that the phenotype file is not correctly read in. Would you mind double checking the format of the phenotype file? 
The following command line is used to read in the file in the SAIGE library.  
ydat = data.table:::fread(phenoFile, header=T, stringsAsFactors=FALSE, colClasses=list(character = sampleIDColinphenoFile))
Can you try it in R to see if the phenoFile can be read in correctly? 

Thanks,
Wei

**Comment by hhx037** [comment]
Hi Wei,

thanks for your prompt answer. 
I loaded my phenotype file into R using your command, it worked perfectly well. I made a brand new phenotype file, also tested in R (it loaded fine), and tried again... same error.

This is the full command I'm using:

Rscript /home/ubuntu/SAIGE/extdata/step1_fitNULLGLMM.R --plinkFile=./MALMO_GRM --phenoFile=./MALMO_GRM_phenotypes.txt --phenoCol=phen --covarColList=sex,age,PC1,PC2,PC3,PC4,PC5 --sampleIDColinphenoFile=IID --traitType=binary --outputPrefix=./MALMO_GRM --nThreads=4 --LOCO=FALSE

Cheers,
Steph

**Comment by weizhouUMICH** [comment]
Hi Steph, 
Would you mind trying the example commands here
https://github.com/weizhouUMICH/SAIGE/blob/master/extdata/cmd.sh

Rscript step1_fitNULLGLMM.R     \
        --plinkFile=./input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly \
        --phenoFile=./input/pheno_1000samples.txt_withdosages_withBothTraitTypes.txt \
        --phenoCol=y_binary \
        --covarColList=x1,x2 \
        --sampleIDColinphenoFile=IID \
        --traitType=binary        \
        --outputPrefix=./output/example_binary \
        --nThreads=4 \
        --LOCO=FALSE

The example phenotype file should work. Also comparing the file formats of this file and your phenotype file might give some clues. 

Thanks,
Wei

**Comment by hhx037** [comment]
Hi Wei,

the example data runs fine. I compared my input file (which I tried space-separated and tab-separated), and the only difference I can see is the position of the IID column, which is the first column in my phenotype file:

IID     sex     age     weight  height  phen2 phen3  phen     PC1     PC2     PC3     PC4     PC5
TG1100002       1       62.22587269     76.5    168     0       0       0       -0.02064993     -0.01650371     -0.04339838     0.001251126     0.01208816
TG1100021       1       66.32169747     104     187     0       0       0       -0.08099236     0.02089657      -0.0117886      0.02148127      -0.005900715
TG1100031       2       64.28199863     82.6    170.5   0       0       0       0.02574503      0.006604107     -0.001291619    0.01118626      0.002146787

Cheers,
Steph

**Comment by weizhouUMICH** [comment]
The position of the ID column does not matter. Maybe try to use fewer decimal places for the PCs?

**Comment by hhx037** [comment]
Hi,

I wasn't keen on rounding the PCs, so I investigated further. Somehow there must have been some hidden characters in the phenotype file, carried over from the flashpca file. Though it loaded fine in R, Saige was throwing this weird error. I made a new phenotype file from the original UK Biobank PCs and all seems well now. Thought you'd like to know.

Thanks for your help,
Steph
