### ISSUE TITLE
Installation compile error

### ISSUE THREAD

**Issue by mwaldron104** [weizhouUMICH/SAIGE#106]
I'm trying to install it from source, but the compile is failing with the errors shown below. Any suggestions for what might be wrong? This is the 0.35.8.7 version, on RHEL-7, GCC 6.3.0, cmake 3.12.4, R 3.6.0.

g++ -std=gnu++11 -shared -L/nas/longleaf/apps/r/3.6.0/lib64/R/lib -L/usr/local/lib64 -o SAIGE.so RcppExports.o test.o matrixMultiEigen.o SAIGE_fitGLMM_fast.o SAIGE_readDosage_bgen.o SAIGE_readDosage_plain.o SAIGE_readDosage_vcf.o SAIGE_GENE_readDosageMatrix_vcf.o ../thirdParty/bgen/build/src/IndexQuery.cpp.2.o ../thirdParty/bgen/build/src/MissingValue.cpp.2.o ../thirdParty/bgen/build/src/bgen.cpp.2.o ../thirdParty/bgen/build/src/zlib.cpp.2.o ../thirdParty/bgen/build/src/View.cpp.2.o ../thirdParty/bgen/build/db/libdb.a ../thirdParty/bgen/build/3rd_party/zstd-1.1.0/libzstd.a ../thirdParty/bgen/build/3rd_party/sqlite3/libsqlite3.a ../thirdParty/bgen/build/3rd_party/boost_1_55_0/libboost.a ../thirdParty/cget/lib64/libsuperlu.a ../thirdParty/cget/lib64/libsavvy.a -L/nas/longleaf/apps/r/3.6.0/lib64/R/lib -lRlapack -L/nas/longleaf/apps/r/3.6.0/lib64/R/lib -lRblas -lgfortran -lm -lquadmath -L../bgen/3rd_party/boost_1_55_0/boost/iostreams -lboost_iostreams -L../thirdParty/cget/lib/ -L../thirdParty/cget/lib64/ -lsavvy -lhts -lsuperlu -L/nas/longleaf/apps/r/3.6.0/lib64/R/lib -lR
/usr/bin/ld: ../thirdParty/cget/lib64/libsuperlu.a(util.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../thirdParty/cget/lib64/libsuperlu.a(memory.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../thirdParty/cget/lib64/libsuperlu.a(sp_ienv.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../thirdParty/cget/lib64/libsuperlu.a(input_error.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../thirdParty/cget/lib64/libsuperlu.a(dgssv.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../thirdParty/cget/lib64/libsuperlu.a(dgssvx.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC

.... more of the same .....

/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make: *** [SAIGE.so] Error 1
ERROR: compilation failed for package ‘SAIGE’

**Comment by wavefancy** [comment]
Hi @mwaldron104,

Please try my conda way if you want to. I struggled one day, finally succeeded. Please check [here](https://github.com/wavefancy/WallaceBroad/tree/master/SAIGE). 


Best regards
Wallace
