### ISSUE TITLE
Error when running SAIGE scripts

### ISSUE THREAD

**Issue by RNLUMC** [weizhouUMICH/SAIGE#107]
Hi,
For a collaborative project, we need to use SAIGE to run genetic association analyses. We have been able to install SAIGE_0.29.5 on our servers (eventually; newer versions did not work), but we are running into trouble running the analyses.

Already in the test runs, we received the following error message:

Error in fitNULLGLMM(plinkFile = opt$plinkFile, phenoFile = opt$phenoFile,  :
  unused arguments (SPAcutoff = opt$SPAcutoff, outputPrefix_varRatio = opt$outputPrefix_varRatio, IsSparseKin = opt$IsSparseKin, sparseGRMFile = opt$sparseGRMFile, sparseGRMSampleIDFile = opt$sparseGRMSampleIDFile, numRandomMarkerforSparseKin = opt$numRandomMarkerforSparseKin, relatednessCutoff = opt$relatednessCutoff, isCateVarianceRatio = opt$isCateVarianceRatio, cateVarRatioMinMACVecExclude = cateVarRatioMinMACVecExclude, cateVarRatioMaxMACVecInclude = cateVarRatioMaxMACVecInclude, isCovariateTransform = opt$isCovariateTransform, isDiagofKinSetAsOne = opt$isDiagofKinSetAsOne, useSparseSigmaConditionerforPCG = opt$useSparseSigmaConditionerforPCG, useSparseSigmaforInitTau = opt$useSparseSigmaforInitTau)
Execution halted

Your help will be much appreciated.

**Comment by shantanubafna** [comment]
I'm having the same error 
Rscript step1_fitNULLGLMM.R \
--plinkFile="input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly"\
--phenoFile="input/pheno_1000samples.txt_withdosages_withBothTraitTypes.txt"\
--phenoCol=y_quantitative\
--traitType=quantitative\
--invNormalize=FALSE\
--covarColList=x1,x2\
--sampleIDColinphenoFile=IID\
--nThreads=4\
--tauInit=1,0\
--LOCO=FALSE\
--outputPrefix="output/example_quantitative"
This is an example run(same as provided in the github)

Error : Error in fitNULLGLMM(plinkFile = opt$plinkFile, phenoFile = opt$phenoFile,  : 
  unused argument (minMAFforGRM = opt$minMAFforGRM)
Execution halted

**Comment by weizhouUMICH** [comment]
Hi, 
The argument minMAFforGRM is added in version 0.35.8.6. If an older version is used, this argument needs to removed from the script. 

Thanks,
Wei

**Comment by shantanubafna** [comment]
Thank you so much!

Best,
Shantanu Bafna

On Sep 23, 2019, at 4:19 PM, weizhouUMICH <notifications@github.com<mailto:notifications@github.com>> wrote:

USE CAUTION: External Message.

Hi,
The argument minMAFforGRM is added in version 0.35.8.6<https://urldefense.proofpoint.com/v2/url?u=http-3A__0.35.8.6&d=DwQCaQ&c=shNJtf5dKgNcPZ6Yh64b-A&r=8LoBh67cxFNOpWm_ZqYqat2dL_IBRF-OJCHkZ5WiB4o&m=yOm-9popUgq2drIa5-ku3cB2hjNROt8FMghTLtD_nTY&s=iWI8_tUGE4FDC2YkqKwCCmcZunyCoBxs_YraOHKT644&e=>. If an older version is used, this argument needs to removed from the script.

Thanks,
Wei
