### ISSUE TITLE
X chromosome: minimum ploidy = 1 (not 2) (with LOCO=FALSE)

### ISSUE THREAD

**Issue by hhx037** [weizhouUMICH/SAIGE#109]
Hi,

I can't seem to get step2 to run for the X chromosome, though I use --LOCO=FALSE
It crashes right away: ERROR: X:2700157_G_A has minimum ploidy = 1 (not 2)

This is the command I'm using:
Rscript step2_SPAtests.R --bgenFile=cohort_for_SAIGE_X.bgen --bgenFileIndex=cohort_for_SAIGE_X.bgen.bgi --minMAF=0 --minMAC=3 --sampleFile=cohort_for_SAIGE_X.sample --GMMATmodelFile=cohort_GRM.rda --varianceRatioFile=cohort_GRM.varianceRatio.txt --SAIGEOutputFile=./X.SAIGE.bgen.txt --numLinesOutput=2 --IsOutputAFinCaseCtrl=TRUE --LOCO=FALSE

Is there an other option I need to add?

Kind regards,

Steph

**Comment by hhx037** [comment]
Hi,

I still haven't figured out a way to run the X, anyone?

Cheers,

Steph

**Comment by IoannaTach** [comment]
HI Steph,

I am getting the same errore message for chrX. Did you figure it out in the end?

Best,
Ioanna

**Comment by hhx037** [comment]
Hi Ioanna,

the only way I got it to work was by converting male genotypes into diploid (homozygous) (done that using a script on the genotypes in vcf format).

Hope this helps,

Cheers,

Steph

**Comment by IoannaTach** [comment]
Thanks Steph, do you know how to do this in plink when you have bed files?  have been searching, but it is not obvious.

**Comment by IoannaTach** [comment]
I was using this, but did not do the trick:
plink2 --bed myfile.bed --bim myfile.bim --fam myfile.fam --split-par b38 --set-hh-missing --make-bed --out myfile_chrX_fixed

**Comment by hhx037** [comment]
Nothing I tried with Plink worked, hence the use of a script on the vcf.

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
