### ISSUE TITLE
Error inputting range of plink files, each of which is a chromosome

### ISSUE THREAD

**Issue by isforrest** [weizhouUMICH/SAIGE#110]
Hello Wei,

For step1 input, we are not able to specify a range of plink files (each of which corresponds to a different chromosome): 
**--plinkFile=/UKBB_PLINK/ukb.imp.chr{1:22}.v3.plink**

I've tried curly brackets and wildcards, but each time we get the error: 
**Error in fitNULLGLMM(plinkFile = opt$plinkFile, phenoFile = opt$phenoFile,  : 
  ERROR! /UKBB_PLINK/ukb.imp.chr{1:22}.v3.plink.bed does not exsit
Execution halted**

I am successfully able to input one chromsome eg.
**--plinkFile=/UKBB_PLINK/ukb.imp.chr21.v3.plink**
However, it's critical that we run step1 genome-wide (hopefully without having to combine all our individual large plink files into 1 plink file). Please let us know how we may resolve this, thanks.

Best,
Iain Forrest
MD-PhD student, MP 1 | Icahn School of Medicine at Mount Sinai
B.S. Cell Biology & Molecular Genetics | University of Maryland

**Comment by weizhouUMICH** [comment]
Hello Iain, 

The plink file used in step 1 is to construct the genetic relationship matrix (GRM), so we don't need to include all imputed markers in the file. As you may tell, a plink file with genome-wide imputed markers is too large to work with.  For example, for UK Biobank jobs, we just need to use pruned genotyped markers, so we may include markers from all different chromosomes for step 1. 

Thanks,
Wei
