### ISSUE TITLE
Error calculating glm even with no covariates

### ISSUE THREAD

**Issue by AYChong** [weizhouUMICH/SAIGE#111]
Hi Wei, 

I'm using SAIGE 0.29.1 and have been getting the following error when calculating the glm for all of my phenotypes (substituted with #### below):

####################
7155  samples have genotypes
formula is  ####~ 1
4540  samples have non-missing phenotypes
2615  samples in geno file do not have phenotypes
4540  samples will be used for analysis
colnames(data.new) is  Y minus1
out.transform$Param.transform$qrr:  1 1
####  is a binary trait

Call:  glm(formula = formula.new, family = binomial, data = data.new)

Coefficients:
minus1
  8.42

Degrees of Freedom: 4540 Total (i.e. Null);  4539 Residual
Null Deviance:      6294
Residual Deviance: 18.84        AIC: 20.84
[1] "Start reading genotype plink file here"
nbyte: 1789
nbyte: 1135
reserve: 465314976

M: 409248, N: 7155
size of genoVecofPointers: 1
here
setgeno mark1
setgeno mark2
setgeno mark5
setgeno mark6
time: 35570
[1] "Genotype reading is done"
inital tau is  1 0.5
iGet_Coef:  1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1

error: inv_sympd(): matrix is singular or not positive definite
###############################

I previously ran this using sex and age as covariates or with just age as a covariate and have the same error.
I have also tried with all genotyped SNPs and with MAF filtered (MAF>=0.01) SNPs, with the same result.

Any ideas on what might be causing the error?

I should note that R 3.4 is the latest version of R available to me currently.

Thanks

**Comment by weizhouUMICH** [comment]
Hi, 

The  arma::inv_sympd() function has strict requirements for matrix inversion. In version 0.35.8.8, we've solved this issue using arma::pinv() function. 
Would you mind using the docker image to run the newer version of SAIGE if R 3.5 is not available? 

Thanks,
Wei
