### ISSUE TITLE
Negative SE and p.value in the output of step 2.

### ISSUE THREAD

**Issue by cjlee13** [weizhouUMICH/SAIGE#114]
Hi Zhou,

We recently installed the latest SAIGE package. But we got something weird during testing the installation with the dataset you provide. Some of the output SE and p.value are negative, and one p.value are greater than 1. It seems that column names are shifted by one place. Or could we set some flags incorrectly?

Your help will be much appreciated. 

Scripts we run:
```bash
#step 1: fit the NULL GLMM
Rscript step1_fitNULLGLMM.R \
	--plinkFile=plinkforGRM_1000samples_10kMarkers \
	--phenoFile=pheno_1000samples.txt \
	--phenoCol=y \
	--covarColList=x1,x2 \
	--sampleIDColinphenoFile=IID \
	--traitType=binary \
	--outputPrefix=example \
	--nThreads=4 \
	--LOCO=TRUE

##step 2: perfrom score test with SPA applied for each marker
######plain text dosage file
 Rscript step2_SPAtests.R \
	--dosageFile=dosage_10markers.txt \
	--dosageFileNrowSkip=1 \
	--dosageFileNcolSkip=6 \
	--dosageFilecolnamesSkip=CHR,SNP,CM,POS,EFFECT_ALLELE,ALT_ALLELE \
	--minMAF=0.0001 \
	--sampleFile=sampleIDindosage.txt \
	--GMMATmodelFile=example.rda \
	--varianceRatioFile=example.varianceRatio.txt \
	--SAIGEOutputFile=example.plainDosage.SAIGE.txt \
	--numLinesOutput=2 \
        --IsOutputAFinCaseCtrl=TRUE
```
Result we get:
![saige_result](https://user-images.githubusercontent.com/35333285/65945002-8a062880-e465-11e9-993e-8f4483dcec2e.png)

R session info:
>\> sessionInfo()       
>R version 3.6.1 (2019-07-05)
>Platform: x86_64-pc-linux-gnu (64-bit)
>Running under: CentOS Linux 7 (Core)
>
>Matrix products: default
>BLAS:   /home/linkage/R-3.6.1/lib/libRblas.so
>LAPACK: /home/linkage/R-3.6.1/lib/libRlapack.so
>
>locale:
> [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
> [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
> [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
> [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
> [9] LC_ADDRESS=C               LC_TELEPHONE=C            
>[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
>
>attached base packages:
>[1] stats     graphics  grDevices utils     datasets  methods   base     
>
>other attached packages:
>[1] SAIGE_0.35.8.8
>
>loaded via a namespace (and not attached):
>[1] compiler_3.6.1     Matrix_1.2-17      Rcpp_1.0.2         grid_3.6.1        
>[5] RcppParallel_4.4.3 lattice_0.20-38

**Comment by weizhouUMICH** [comment]
Hi cjlee13 , 

Thank you for reporting this issue. 
It seems the header has missed "info" for the imputation score (all entries are 1 in your results), so if you add "info" between "AF" and "N", the results should look correct. The info column was added in a more recent version so it has been missed for the output when a plain text input is used. I will fix this bug. 

Thanks,
Wei

**Comment by cjlee13** [comment]
> It seems the header has missed "info" for the imputation score (all entries are 1 in your results), so if you add "info" between "AF" and "N", the results should look correct.

Cool! Thanks for your help.

CJ
