### ISSUE TITLE
Non-conformable argument issue

### ISSUE THREAD

**Issue by randomNumber298347** [weizhouUMICH/SAIGE#115]
Hello,

Using the latest version of SAIGE-GENE (0.35.8.8) I am getting the following error when running Step 2:

Error in G2_adj_n %*% diag(rep(1/r, dim(G2_adj_n)[2])) : 
  non-conformable arguments
Calls: SPAGMMATtest ... SAIGE_SKAT_withRatioVec -> Related_ER -> \<Anonymous\> -> nrow -> as.matrix

Any thoughts on what may be causing this?

BW.

**Comment by weizhouUMICH** [comment]
Hello, 

Happy to help! Would you mind sharing more information? How many variants are there in the tested gene? 
What did the log file output for the gene? 

Thanks,
Wei

**Comment by randomNumber298347** [comment]
Hi, 

I think it might have something to do with missing phenotypes in my file. Can you say how/if SAIGE-GENE handles missing phenotypes as I can not seem to find any information on the main page re. this.

Thanks.

**Comment by weizhouUMICH** [comment]
Hi, 

The phenotype file is written using fread in the data.table library. Then any sample with missing data in any covariate or phenotype is removed using the following code, so the log file, you will find "XX sample have non-missing phenotypes"

formula.null = as.formula(formula)
mmat = model.frame(formula.null, data, na.action=NULL)
mmat$IID = data[,which(sampleIDColinphenoFile == colnames(data))]
mmat_nomissing = mmat[complete.cases(mmat),]
mmat_nomissing$IndexPheno = seq(1,nrow(mmat_nomissing), by=1)
cat(nrow(mmat_nomissing), " samples have non-missing phenotypes\n")

Thanks,
Wei

**Comment by ruthchia** [comment]
Hi Wei, 
I have the same error message when running SAIGE-GENE using the latest build. 
I ran step2 for all chromosomes on > 500 genes/chromosome in parallel and some was successful and some failed.

The code I ran is:
Rscript ../scripts/SAIGE/extdata/step2_SPAtests.R \
--vcfFile=../vcf/FILTERED.LBD.controls.noDuplicates.keepRelated.hwe1e-10_chr20.vcf.gz \
--vcfFileIndex=../vcf/FILTERED.LBD.controls.noDuplicates.keepRelated.hwe1e-10_chr${CHNUM}.vcf.gz.tbi \
--vcfField=GT \
--chrom=${CHNUM} \
--minMAF=0 \
--minMAC=0.5 \
--sampleFile=../sampleIID_VCF.txt \
--maxMAFforGroupTest=0.01 \
--GMMATmodelFile=./output/LBD.controls.noDuplicates.keepRelated.rda \
--varianceRatioFile=./output/LBD.controls.noDuplicates.keepRelated_cate.varianceRatio.txt \
--SAIGEOutputFile=./output/nonSYN.CADD12/LBD.controls.noDuplicates.keepRelated.SAIGE.gene.CODING.nonSYN.chr20.txt \
--numLinesOutput=1 \
--groupFile=./GeneSNPs/nonSYN.CADD12/chr20.nonSYN.CADD12.SAIGEgeneInputSetv0.txt \
--sparseSigmaFile=./output/LBD.controls.noDuplicates.keepRelated_cate.varianceRatio.txt_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseSigma.mtx \
--IsOutputAFinCaseCtrl=TRUE     \
--IsSingleVarinGroupTest=TRUE

The error is:
Error in G2_adj_n %*% diag(rep(1/r, dim(G2_adj_n)[2])) :
  non-conformable arguments
Calls: SPAGMMATtest ... SAIGE_SKAT_withRatioVec -> Related_ER -> <Anonymous> -> nrow -> as.matrix
Timing stopped at: 0.155 0 0.155
Execution halted

For example, the one that failed when execution halted was at this gene set:
PRPF6	20:63999619_C/T	20:64027738_T/G

What do you think is the problem? If useful, I can email you the geneInput set and results from Step0 and Step1. Please let me know which email to send it to.

Thanks!
Ruth

**Comment by weizhouUMICH** [comment]
Hi Ruth, 

Thank you very much for reporting this issue. Would you mind sharing more details from the log file for this gene? It would be also extremely helpful if you email us the input for step 2 and results from step 0 and step 1 (Zhangchen Zhao zczhao@umich.edu  and myself zhowei@umich.edu). 

Thank you!
Wei

**Comment by nkgx** [comment]
I encountered the same problem a while ago. I don't have any example input handy but it only seemed to occur for variants with very low allele frequency (eg. MAC 1) and also only for binary phenotypes. So maybe something about unexpected zeros or a data frame becoming one-dimensional?

**Comment by ruthchia** [comment]
Hey Nils, thanks for sharing your experience.
What is your workaround to get it to work?
Did you remove SNPs that had MAC < 2 prior to running SAIGE-GENE?
Thanks!
Ruth

**Comment by nkgx** [comment]
Yes, my workaround was to remove SNPs with very low MAC (I used `< 3`) from the input. That's not a very useful workaround though since the whole point of running SAIGE-GENE was to test these kinds of ultra-rare SNPs.

**Comment by ruthchia** [comment]
Hi Wei,
Sorry it took me long to get back to you. I would really want to send you the files, but the input vcf files for step2 are huge.
What would you suggest? Would results from step 0 and step 1 be sufficient for now for you to figure out what went wrong?
Thanks
Ruth

**Comment by randomNumber298347** [comment]
Hi,

Just thought I would follow up given the conversation above.

I still have not been able to get SAIGE-GENE to work having tried so many things (re-installs, library updates, checking phenotype/genotype files etc.).

Note that I had the some observation as Nills in that if I set a min MAC to 2 then everything worked fine - but this is far from ideal as pointed out above.

Would like to use this program so let me know if I can provide any additional information that may be of assistance.

Thanks.

**Comment by randomNumber298347** [comment]
Hi - just wondered if there was any update on this - or if we can expect an update?
Thanks,

**Comment by weizhouUMICH** [comment]
Hi- The bug should have been fixed in the version 0.36.1.
Please have a try to see if it works. Note that the version 0.36.1 will be
updated to 0.36.2 later today with a few other issues fixed.

Thanks,
Wei
