### ISSUE TITLE
calculated results are different between R-3.5.1 and R-3.6.1

### ISSUE THREAD

**Issue by kgerman73** [weizhouUMICH/SAIGE#120]
We are seeing differences in calculated results from R 3.5.1 & 3.6.1.  Any idea why?

We also see this message when using SAIGE with R 3.5.1:
	Warning message:
	package ‘SAIGE’ was built under R version 3.6.1

Is this expected?  Which version of R should we be using?

Thanks,
Keith

**Comment by weizhouUMICH** [comment]
Hi Keith,

Which version of SAIGE is used? R version should not affect the results.

Thanks,
Wei

**Comment by kgerman73** [comment]
The latest version, 0.35.8.8

**Comment by weizhouUMICH** [comment]
Thanks! So the log files are also the same? Which step are you referring to?

**Comment by kgerman73** [comment]
Turns out its an issue with the binary package.  When I try to install using devtools or from source this is the error I get with R 3.5.1.  Works fine on the same host with R 3.6.1.

installing to /app/R/v3.5.1/lib64/R/library/SAIGE/libs
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘SAIGE’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/app/R/v3.5.1/lib64/R/library/SAIGE/libs/SAIGE.so':
  /app/R/v3.5.1/lib64/R/library/SAIGE/libs/SAIGE.so: undefined symbol: sgecon_
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/app/R/v3.5.1/lib64/R/library/SAIGE’
* restoring previous ‘/app/R/v3.5.1/lib64/R/library/SAIGE’

Thanks,
Keith

**Comment by weizhouUMICH** [comment]
Hi @kgerman73, 
Please feel free to try the latest version 0.36.2, which has a few bugs fixed.
Thanks,
Wei

**Comment by weizhouUMICH** [comment]
Hi @kgerman73, 
Please reopen if you still encounter this issue. 
Thanks!
Wei
