### ISSUE TITLE
Complie Error (boost_iostreams)

### ISSUE THREAD

**Issue by kbsssu** [weizhouUMICH/SAIGE#121]
Hi,
I'm trying to install the SAIGE, but the install installation was failed.
(CentOS7, R-3.5.1, gcc-7.3.1, cmake-3.14.4)

> ** libs
g++ -m64 -std=gnu++11 -shared -L/usr/lib64/R/lib -Wl,-z,relro -o SAIGE.so RcppExports.o test.o matrixMultiEigen.o SAIGE_fitGLMM_fast.o SAIGE_readDosage_bgen.o SAIGE_readDosage_plain.o SAIGE_readDosage_vcf.o SAIGE_GENE_readDosageMatrix_vcf.o ../thirdParty/bgen/build/src/IndexQuery.cpp.2.o ../thirdParty/bgen/build/src/MissingValue.cpp.2.o ../thirdParty/bgen/build/src/bgen.cpp.2.o ../thirdParty/bgen/build/src/zlib.cpp.2.o ../thirdParty/bgen/build/src/View.cpp.2.o ../thirdParty/bgen/build/db/libdb.a ../thirdParty/bgen/build/3rd_party/zstd-1.1.0/libzstd.a ../thirdParty/bgen/build/3rd_party/sqlite3/libsqlite3.a ../thirdParty/bgen/build/3rd_party/boost_1_55_0/libboost.a ../thirdParty/cget/lib64/libsuperlu.a ../thirdParty/cget/lib64/libsavvy.a -L/usr/lib64/R/lib -lRlapack -L/usr/lib64/R/lib -lRblas -lgfortran -lm -lquadmath -L../bgen/3rd_party/boost_1_55_0/boost/iostreams -lboost_iostreams -L../thirdParty/cget/lib/ -L../thirdParty/cget/lib64/ -lsavvy -lhts -lsuperlu -L/usr/lib64/R/lib -lR
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -lboost_iostreams
collect2: error: ld returned 1 exit status
make: *** [SAIGE.so] Error 1
ERROR: compilation failed for package ‘SAIGE’
\* removing ‘/usr/lib64/R/library/SAIGE’

I think the syntax below is the cause of the problem.
>-L../bgen/3rd_party/boost_1_55_0/boost/iostreams

The parent directory, "thirdParty", is missing only in the above syntax, and it is related to the "boost_iostreams"

Then, how can I complete the installation of the SAIGE?

Best regards,
Beomsu Kim

**Comment by weizhouUMICH** [comment]
Hi Beomsu, 

Thanks for reporting this. As boost_iostreams causes compiling issues, I'm working on avoid using this library by removing the option for a plain text input in step 2.  I will upload a new version soon. 
In the meanwhile, please try the docker image if you can or @Wallace describes how to create the conda environment file for SAIGE. 

Thanks,
Wei

**Comment by kbsssu** [comment]
Thanks for your prompt response.
We are not working on the conda environment, but I'll try the docker image.
I'll be looking forward to a new version!

Thanks,
Beomsu Kim.

**Comment by weizhouUMICH** [comment]
Hi @kbsssu, now the new version 0.36.2 is ready to use. Please have a try and let me know if you have any question. 

Thanks,
Wei
