### ISSUE TITLE
conditional test error

### ISSUE THREAD

**Issue by momo1210** [weizhouUMICH/SAIGE#123]
Hi Wei,
I'm trying to use the conditional test but can't run successfully. Could you please take a look for me? Thanks! 

Log:-----------------------------------

R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] optparse_1.6.2 SAIGE_0.35.8.8

loaded via a namespace (and not attached):
[1] compiler_3.6.1     Matrix_1.2-17      Rcpp_0.12.19       getopt_1.20.3
[5] grid_3.6.1         RcppParallel_4.4.3 lattice_0.20-38
$dosageFile
[1] ""

$dosageFileNrowSkip
[1] 0

$dosageFileNcolSkip
[1] 5

$dosageFilecolnamesSkip
[1] ""

$vcfFile
[1] "rh_match_UBC_SCAD_MGI_21ratio_GWAS_update_pheno_withfamily_1st_10122019.vcf.gz"

$vcfFileIndex
[1] "rh_match_UBC_SCAD_MGI_21ratio_GWAS_update_pheno_withfamily_1st_10122019.vcf.gz.tbi"

$vcfField
[1] "GT"

$bgenFile
[1] ""

$bgenFileIndex
[1] ""

$savFile
[1] ""

$savFileIndex
[1] ""

$idstoExcludeFile
[1] ""

$idstoIncludeFile
[1] ""

$rangestoExcludeFile
[1] ""

$rangestoIncludeFile
[1] ""

$chrom
[1] "1"

$start
[1] 1

$end
[1] 2.5e+08

$IsDropMissingDosages
[1] FALSE

$minMAF
[1] 0

$minMAC
[1] 5

$maxMAFforGroupTest
[1] 0.5

$minInfo
[1] 0

$sampleFile
[1] "sample_list_1st.txt"

$GMMATmodelFile
[1] "out.UBC.SCAD_21R_1st_adjustPC_v2.rda"

$varianceRatioFile
[1] "out.UBC.SCAD_21R_1st_adjustPC_v2.varianceRatio.txt"

$SAIGEOutputFile
[1] "cond_1_150262270_chr1.UBC.SCAD_21R_1st_adjustPC_v2.SAIGE.vcf.txt"

$numLinesOutput
[1] 2

$IsSparse
[1] TRUE

$IsOutputAFinCaseCtrl
[1] TRUE

$IsOutputNinCaseCtrl
[1] FALSE

$LOCO
[1] FALSE

$condition
[1] "1:150262270:C:G"

$groupFile
[1] ""

$sparseSigmaFile
[1] ""

$kernel
[1] "linear.weighted"

$method
[1] "optimal.adj"

$weights.beta
[1] "1,25"

$r.corr
[1] "0"

$IsSingleVarinGroupTest
[1] FALSE

$cateVarRatioMinMACVecExclude
[1] "0.5,1.5,2.5,3.5,4.5,5.5,10.5,20.5"

$cateVarRatioMaxMACVecInclude
[1] "1.5,2.5,3.5,4.5,5.5,10.5,20.5"

$singleGClambda
[1] 1

$IsOutputPvalueNAinGroupTestforBinary
[1] FALSE

$help
[1] FALSE

[1]  0.5  1.5  2.5  3.5  4.5  5.5 10.5 20.5
[1]  1.5  2.5  3.5  4.5  5.5 10.5 20.5
[1]  1 25
single-variant association test will be performed
5577  samples have been used to fit the glmm null model
obj.glmm.null$LOCO:  FALSE
Leave-one-chromosome-out option is not applied
Single variance ratio is provided, so categorical variance ratio won't be used!
variance Ratio is  0.969
5577  sample IDs are found in sample file
[1] 5577    4
[1] "IID"          "IndexInModel" "IndexDose.x"  "IndexDose.y"
5577  samples were used in fitting the NULL glmm model and are found in sample file
sparse kinship matrix is not used
Missing dosages will be mean imputed for the analysis
Analysis started at  1.57e+09 Seconds
conditionlist is  condMarkers   1:150262270:C:G
Open VCF done
To read the field GT
Number of meta lines in the vcf file (lines starting with ##): 28
Number of samples in the vcf file: 5577

 *** caught segfault ***
address 0x4c, cause 'memory not mapped'

Traceback:
 1: getGenoOfGene_vcf(conditionlist, 0)
 2: SPAGMMATtest(dosageFile = opt$dosageFile, dosageFileNrowSkip = opt$dosageFileNrowSkip,     dosageFileNcolSkip = opt$dosageFileNcolSkip, dosageFilecolnamesSkip = dosageFilecolnames,     vcfFile = opt$vcfFile, vcfFileIndex = opt$vcfFileIndex, vcfField = opt$vcfField,     bgenFile = opt$bgenFile, bgenFileIndex = opt$bgenFileIndex,     savFile = opt$savFile, savFileIndex = opt$savFileIndex, sampleFile = opt$sampleFile,     idstoExcludeFile = opt$idstoExcludeFile, idstoIncludeFile = opt$idstoIncludeFile,     rangestoExcludeFile = opt$rangestoExcludeFile, rangestoIncludeFile = opt$rangestoIncludeFile,     chrom = opt$chrom, start = opt$start, end = opt$end, IsDropMissingDosages = opt$IsDropMissingDosages,     minMAF = opt$minMAF, minMAC = opt$minMAC, maxMAFforGroupTest = opt$maxMAFforGroupTest,     minInfo = opt$minInfo, GMMATmodelFile = opt$GMMATmodelFile,     varianceRatioFile = opt$varianceRatioFile, SAIGEOutputFile = opt$SAIGEOutputFile,     numLinesOutput = opt$numLinesOutput, IsSparse = opt$IsSparse,     IsOutputAFinCaseCtrl = opt$IsOutputAFinCaseCtrl, IsOutputNinCaseCtrl = opt$IsOutputNinCaseCtrl,     LOCO = opt$LOCO, condition = opt$condition, sparseSigmaFile = opt$sparseSigmaFile,     groupFile = opt$groupFile, kernel = opt$kernel, method = opt$method,     weights.beta = weights.beta, r.corr = opt$r.corr, IsSingleVarinGroupTest = opt$IsSingleVarinGroupTest,     cateVarRatioMinMACVecExclude = cateVarRatioMinMACVecExclude,     cateVarRatioMaxMACVecInclude = cateVarRatioMaxMACVecInclude,     singleGClambda = opt$singleGClambda, IsOutputPvalueNAinGroupTestforBinary = opt$IsOutputPvalueNAinGroupTestforBinary)
An irrecoverable exception occurred. R is aborting now ...

[1]    Segmentation fault

**Comment by npatel22526** [comment]
@momo1210, I had the exact same error, my issue was the marker ID in the group file. 
For VCF file the marker ID = chr:pos_ref/alt. 
Also remove all white space at the end of the line. 

Hope that helps.
Nick

**Comment by weizhouUMICH** [comment]
Thanks so much @npatel22526!
@momo1210 For conditional analysis of gene-based tests for binary traits, please use the version 0.36.1, which accounts for unbalanced case-control ratios in conditional analysis of gene-based tests.

**Comment by weizhouUMICH** [comment]
Hi @momo1210 and @npatel22526, now the version 0.36.2 is ready to use. Thanks!
