### ISSUE TITLE
step2_SPAtests.R missing header

### ISSUE THREAD

**Issue by nkgx** [weizhouUMICH/SAIGE#126]
step2_SPAtests.R is missing the `#!/usr/bin/env Rscript` line on top, which means you get this error when you try to execute it as a script (like you can with step 0 and step 1):

`/usr/local/bin//step2_SPAtests.R: 1: /usr/local/bin//step2_SPAtests.R: Syntax error: word unexpected (expecting ")")`

**Comment by weizhouUMICH** [comment]
Thanks for the note! I will add the header in the next version.

**Comment by weizhouUMICH** [comment]
This has been now fixed in the version 0.36.2. Thanks!
