### ISSUE TITLE
Using example data and commands got problem "argument 38 matches multiple formal arguments"

### ISSUE THREAD

**Issue by Moya8946** [weizhouUMICH/SAIGE#127]
Dear Dr. Zhou,

I am trying GENE-SAIGE with the example data using the following commands. But I got the problem: 

Error in SPAGMMATtest(dosageFile = opt$dosageFile, dosageFileNrowSkip = opt$dosageFileNrowSkip,  :
  argument 38 matches multiple formal arguments

Could you help me to solve the problem?

Here is the command from your introduction:
Rscript step2_SPAtests.R \
        --vcfFile=./input/genotype_10markers.vcf.gz \
        --vcfFileIndex=./input/genotype_10markers.vcf.gz.tbi \
        --vcfField=GT \
        --chrom=1 \
	--minMAF=0 \
        --minMAC=0.5 \
        --maxMAFforGroupTest=0.01       \
        --sampleFile=./input/samplelist.txt \
        --GMMATmodelFile=./output/example_quantitative.rda \
        --varianceRatioFile=./output/example_quantitative_cate.varianceRatio.txt \
        --SAIGEOutputFile=./output/example_quantitative.SAIGE.gene.txt \
        --numLinesOutput=1 \
        --groupFile=./input/groupFile_geneBasedtest_simulation.txt    \
        --sparseSigmaFile=./output/example_quantitative_cate.varianceRatio.txt_relatednessCutoff_0.125.sparseSigma.mtx       \
        --IsSingleVarinGroupTest=TRUE

**Comment by weizhouUMICH** [comment]
Hello,
Thanks for trying SAIGE-GENE!
I wonder if you are using the new version of SAIGE-GENE library but old
wrapper R scripts? The arguments dosageFile and dosageFileNrowSkip have
been removed in versions 0.36.1 and 0.36.2.
Could you please trying the new wrapper files in the extdata?
https://github.com/weizhouUMICH/SAIGE/blob/master/extdata/step2_SPAtests.R

Thanks!

Wei

**Comment by Moya8946** [comment]
Thank you Dr. Zhou, I used the updated version and got another error:

Error in SPAGMMATtest(vcfFile = opt$vcfFile, vcfFileIndex = opt$vcfFileIndex,  : 
  unused arguments (weightsIncludeinGroupFile = opt$weightsIncludeinGroupFile, weights_for_G2_cond = weights_for_G2_cond)

**Comment by weizhouUMICH** [comment]
Thanks! Then I guess the version of SAIGE-GENE you are using is 0.36.1,
would you mind trying to use version 0.36.2?

 In v0.36.2, the arguments weightsIncludeinGroupFile and
weights_for_G2_cond were added to allow for customized weights for markers
in gene-based tests.
