### ISSUE TITLE
Error: unexpected end of input Execution halted

### ISSUE THREAD

**Issue by audoushka** [weizhouUMICH/SAIGE#128]

**Comment by audoushka** [comment]
When trying to run step 1 of SAIGE on data on one chromosome output from plink as bed/bim/fam, this is the error message that I get.
There does not appear to be anything wrong with the input file.
Has anyone had the same error?
Is there an easy fix?
Thank you!!

**Comment by weizhouUMICH** [comment]
Hi audoushka, 

Are you using the most recent version 0.36.2? Have you tried the example scripts for step 1 in the file cmd.sh? Do you get the same errors? 
https://github.com/weizhouUMICH/SAIGE/blob/master/extdata/cmd.sh

Thanks!

Wei
