### ISSUE TITLE
SAIGE-GENE effect size for burden test

### ISSUE THREAD

**Issue by IoannaTach** [weizhouUMICH/SAIGE#129]
Hello,

Am I correct to think that SAIGE-GENE does not return an effect size and standard error for the burden test? Is there any way to output these too please? Many thanks .

Best,
Ioanna

**Comment by weizhouUMICH** [comment]
Hello Ioanna,

You are right. SAIGE-GENE does not return an effect size for burden tests.
We will try to output it in the next version soon.

Best,
Wei

**Comment by weizhouUMICH** [comment]
Hello Ioanna, 
SAIGE-GENE 0.36.3 and 0.36.3.1 now output an effect size for burden tests with the option IsOutputBETASEinBurdenTest in step2. Please note that the magnitude of the effect size is difficult to interpret.  
Thanks,
Wei
