### ISSUE TITLE
Issue step 2: Error in SPAGMMATtest

### ISSUE THREAD

**Issue by genokaro** [weizhouUMICH/SAIGE#130]
Hello,

I try to run SAIGE on dosages in a vcf file. But I get an error message for the SPAGMMATtest and I have no idea what to do. I would be very thankful for some help! :)

> R version 3.6.1 (2019-07-05)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS: libRblas.so
> LAPACK:bRlapack.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] SAIGE_0.35.8.8
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.6.1     Matrix_1.2-17      Rcpp_1.0.2         grid_3.6.1        
> [5] RcppParallel_4.4.3 lattice_0.20-38   
> $vcfFile
> [1] "chr10.vcf.gz"
> 
> $vcfFileIndex
> [1] "/hr10.vcf.gz.tbi"
> 
> $vcfField
> [1] "DS"
> 
> $bgenFile
> [1] ""
> 
> $bgenFileIndex
> [1] ""
> 
> $savFile
> [1] ""
> 
> $savFileIndex
> [1] ""
> 
> $idstoExcludeFile
> [1] ""
> 
> $idstoIncludeFile
> [1] ""
> 
> $rangestoExcludeFile
> [1] ""
> 
> $rangestoIncludeFile
> [1] ""
> 
> $chrom
> [1] "10"
> 
> $start
> [1] 1
> 
> $end
> [1] 2.5e+08
> 
> $IsDropMissingDosages
> [1] FALSE
> 
> $minMAF
> [1] 0
> 
> $minMAC
> [1] 3
> 
> $maxMAFforGroupTest
> [1] 0.5
> 
> $minInfo
> [1] 0
> 
> $sampleFile
> [1] "samplefile.txt"
> 
> $GMMATmodelFile
> [1] "prefix.rda"
> 
> $varianceRatioFile
> [1] "prefix_varianceRatio.txt"
> 
> $SAIGEOutputFile
> [1] "test"
> 
> $numLinesOutput
> [1] 2
> 
> $IsSparse
> [1] TRUE
> 
> $IsOutputAFinCaseCtrl
> [1] TRUE
> 
> $IsOutputNinCaseCtrl
> [1] FALSE
> 
> $LOCO
> [1] FALSE
> 
> $condition
> [1] ""
> 
> $sparseSigmaFile
> [1] ""
> 
> $groupFile
> [1] ""
> 
> $kernel
> [1] "linear.weighted"
> 
> $method
> [1] "optimal.adj"
> 
> $weights.beta.rare
> [1] "1,25"
> 
> $weights.beta.common
> [1] "0.5,0.5"
> 
> $weightMAFcutoff
> [1] 0.01
> 
> $r.corr
> [1] "0"
> 
> $IsSingleVarinGroupTest
> [1] FALSE
> 
> $cateVarRatioMinMACVecExclude
> [1] "0.5,1.5,2.5,3.5,4.5,5.5,10.5,20.5"
> 
> $cateVarRatioMaxMACVecInclude
> [1] "1.5,2.5,3.5,4.5,5.5,10.5,20.5"
> 
> $dosageZerodCutoff
> [1] 0.2
> 
> $IsOutputPvalueNAinGroupTestforBinary
> [1] FALSE
> 
> $IsAccountforCasecontrolImbalanceinGroupTest
> [1] TRUE
> 
> $help
> [1] FALSE
> 
> [1]  0.5  1.5  2.5  3.5  4.5  5.5 10.5 20.5
> [1]  1.5  2.5  3.5  4.5  5.5 10.5 20.5
> Error in SPAGMMATtest(vcfFile = opt$vcfFile, vcfFileIndex = opt$vcfFileIndex,  : 
>   unused arguments (dosageZerodCutoff = opt$dosageZerodCutoff, IsAccountforCasecontrolImbalanceinGroupTest = opt$IsAccountforCasecontrolImbalanceinGroupTest, weights.beta.rare = weights.beta.rare, weights.beta.common = weights.beta.common, weightMAFcutoff = opt$weightMAFcutoff)
> Execution halted
>

**Comment by weizhouUMICH** [comment]
Hi, 

This error is because that the SAIGE version you are using (0.35.8.8) is older than the step 1R wrapper for SPAGMMATtest. If you update SAIGE to the newest version 0.36.2, the problem should be solved. 

Thanks!

Wei

**Comment by genokaro** [comment]
Thanks a lot!! :)

**Comment by genokaro** [comment]
Hello again,

thanks again a lot for your super quick reply!!!! :-) I was wondering if it could also work with an older version of R instead of updating SAIGE?

Best regards,

Franziska

**Comment by weizhouUMICH** [comment]
Hi Franziska,

To try it with an older version of R, you may need to compile from the
source code (method 3 and 5 in
https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE
)

Thanks!
Wei
