### ISSUE TITLE
errors in running the template code

### ISSUE THREAD

**Issue by wym0072003** [weizhouUMICH/SAIGE#133]
Hi,

I got some errors in running the first step of SAIGE-GENE:

Rscript createSparseGRM.R	\
	--plinkFile=./input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly \
	--nThreads=4  \
	--outputPrefix=./output/sparseGRM	\
	--numRandomMarkerforSparseKin=2000	\
	--relatednessCutoff=0.125

Error gives:

sparse GRM will be created
Markers in the Plink file with MAF >=  0.01  will be used to construct GRM
write sample IDs for the sparse GRM to  sparseGRM_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseGRM.mtx.sampleIDs.txt
Error! fam file not open!time: 0.049
0  markers have MAF >=  0.01
2000  genetic markers are randomly selected to decide which samples are related
Error in createSparseGRM(plinkFile = opt$plinkFile, outputPrefix = opt$outputPrefix,  :
  ERROR! not enough genetic markers with MAF >= 0.01 to detect which samples are related
Try include at least 2000 genetic markers with MAF >= 0.01 in the plink file
Execution halted

May I ask how can I modify the code, or the template data has some issue?Thanks.

Best,

Yiming

**Comment by weizhouUMICH** [comment]
Hi,
The error message "Error! fam file not open!" indicates the file
./input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly.fam is not
found. Could you please have a look?
Thanks!

Wei

**Comment by wym0072003** [comment]
Thanks Wei! Issue is solved when I replace the '~' with '/home/yiming/' in the directory to the plink files.

Best,

Yiming

**Comment by FrederikFilip** [comment]
Could this be stated somewhere in the guide?
