### ISSUE TITLE
Required minimum sample size?

### ISSUE THREAD

**Issue by victoriaemilyjackson** [weizhouUMICH/SAIGE#134]
Hi,

Great software! :) 

I wanted to enquire whether you recommended a minimum sample size for running SAIGE, either a minimum no. of cases, or minimum overall? I note that the BOLT-LMM authors recommend a minimum sample size of ~5000; as SAIGE also uses the PCG approach for fitting the null model, I wondered whether you would recommend a similar minimum?

Many thanks!
Vicki

**Comment by jccensin** [comment]
I'm also wondering about this - would a sample size of 400-1500 be sufficient? Thanks!

**Comment by weizhouUMICH** [comment]
Hi, 
Thanks for the question! We haven't throughly tested the program on a small sample size. All simulation studies were done using 10,000 samples. Similar to BOLT-LMM, SAIGE uses asymptotic approaches to for feasibility on large samples. Based on our previous real-data analysis, we saw the performance on 3,000 samples were fine. 
Thanks,
Wei

**Comment by jccensin** [comment]
Hi Wei - thank you so much for the response, really appreciate it!
