### ISSUE TITLE
correlation between step 1 and step2 in SAIGE-GENE

### ISSUE THREAD

**Issue by wym0072003** [weizhouUMICH/SAIGE#135]
Hi Wei,

I am applying SAIGE-GENE on my data recently. I have a simple question on the correlation between step 1 and step2.
From my understanding, some output files result from step1 should be the input files in step2. However, I can't figure out which output files in step1 are the inputs for step2. Can you please specify those files, thus we can easily check if we have already get outputs and inputs successfully in managing the process. Thanks very much!

Best,

Yiming

**Comment by weizhouUMICH** [comment]
Hi Yiming, 
Sorry for my late reply. Through this link, you may find the list of input files for step 2 for SAIGE-GENE: 
https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE#input-files-3

3, 4, and 6  are files from step 1 which are model file (.rda), the variance ratio file (.varianceRatio.txt), and the sparse Sigma file (.sparseSigma.mtx)

Thanks!
Wei

**Comment by wym0072003** [comment]
Thanks very much Wei!
I have got the final results from SAIGE-GENE. Not sure why only output a subset of genes in the group file (not all genes). I gusse using default setting for MAF filters will force saige to consider all input variants? --minMAC=0.5 means variants with allele count >=1 will be used in the test, that's right?

Best regards

Yiming

**Comment by weizhouUMICH** [comment]
Hi Yiming,

Yes, --minMAC=0.5 is to exclude monomorphic variants.
minMAC and minMAF (whichever is higher ) are used to specify the minimum
frequency for markers, maxMAFforGroupTest is for maximum MAF. minInfo is
used for minimum imputation info if the markers are imputed.

Thanks,
Wei

**Comment by wym0072003** [comment]
Thanks very much Wei! Hope you are safe and well.

Best regards

Yiming
