### ISSUE TITLE
Chromosome X error

### ISSUE THREAD

**Issue by fadista** [weizhouUMICH/SAIGE#137]
Hi,

I am using SAIGE v0.29 on R v3.2.1 for a binary UK Biobank trait (using bgen files). For step1 I use SPAtest v3.0.0 and for step2 I use SPAtest v2.0.2.

For step 1 all works fine but for step 2 all the autosomes also work fine (including also chrXY) but for chrX the summary stats for only the first 7559 variants are output and after that the follwing error message appears:

`Error` in X1 %*% Z : non-conformable arguments
Calls: SPAGMMATtest ... rbind -> scoreTest_SAIGE_binaryTrait -> Score_Test_Sparse
Execution halted``

Could there be something in chrX (some ploidy issue) that leads to this error? Is there some quick fix one could do to the SPAGMMATtest to make it work for chromosome X on these SAIGE and SPAtest versions?
I don´t have rights to update SAIGE and all your ways of trying to update SAIGE without root access fail.

Thank you,
João

**Comment by weizhouUMICH** [comment]
Hi, 
can you please try the current version of SAIGE?

**Comment by fadista** [comment]
Hi,
I have no root permissions to install the current version of SAIGE while all your described ways to update SAIGE without root access fail.

**Comment by weizhouUMICH** [comment]
Hi @fadista, 
You may install SAIGE using the conda environment file to your specified directory without requiring root access. Could you please try that? The error you described has been fixed in the more recent version. 

Thanks!
Wei
