### ISSUE TITLE
Installing SAIGE 0.36.3 from option #2 fails

### ISSUE THREAD

**Issue by carbocation** [weizhouUMICH/SAIGE#139]
From the [README](https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE#installing-saige), one of the options for installing SAIGE is via devtools in R. However, I currently get the following error when trying to do so:

`devtools::install_github("weizhouUMICH/SAIGE")`:

```sh
** libs
Error: package ‘SPAtest’ 3.0.2 was found, but == 3.0.0 is required by ‘SAIGE’
* removing ‘/usr/local/lib/R/library/SAIGE’
Error: Failed to install 'SAIGE' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmpvl8OTR/file71a08bc12/SAIGE_0.36.3.tar.gz’ had non-zero exit status
```

It seems that the installer expects SPAtest to be exactly version 3.0.0, but it has installed 3.0.2 and therefore fails.

**Comment by weizhouUMICH** [comment]
Thanks for the note! 
Please try again, 'SPAtest' 3.0.2' should be automatically installed in the current version (SAIGE 0.36.3.1)

**Comment by szeestraten-ntnu** [comment]
Hi @weizhouUMICH, I am hitting the same issue when trying to use a slightly older version of SAIGE,`0.36.1`.

I see that [`DESCRIPTION`](https://github.com/weizhouUMICH/SAIGE/blob/0.36.1/DESCRIPTION#L11) pins the version of `SPAtest`, but the [`install_packages.R`](https://github.com/weizhouUMICH/SAIGE/blob/0.36.1/extdata/install_packages.R) script for installing dependencies just gets the latest version, which can break the install when using older versions of SAIGE.

Would it be possible to pin the `SPAtest` version somewhere so for future releases you are ensured to get the required dependency version?

I understand that `install.packages()` does not handle versions so I think `devtools` might be a better option as it has `install_version()` which I am currently using to get version `3.0.0`.

(I am new to R package management so please forgive me if I am missing something obvious or a best practice.)

**Comment by weizhouUMICH** [comment]
Hi @szeestraten-ntnu, 
Thanks for the suggestion, which would be really helpful for users who use old version of SAIGE. And I would recommend you to always use the newest version of SAIGE as there are always issues are fixed in the newer versions. 

Thanks,
Wei
