### ISSUE TITLE
General default SAIGE parameter rationale

### ISSUE THREAD

**Issue by tbrunetti** [weizhouUMICH/SAIGE#140]
I have been reading your paper and I have a couple questions that I may have either missed in your paper or I couldn't easily find addressed.

1.  In step 1, if I supply a pre-calculated GRM, the plink file is then only used to estimate the variance ratio and not the kinship estimates.  Therefore, do you require an LD-pruned plink file or not?  If I use an LD-pruned file, since the algorithm is randomly selecting markers, could I effectively reduce the number of snps required to accurately estimate the variance ratio since all markers will be LD?

2.  In step 1, the --isCovariateTransform parameter is by default set to TRUE.  According to your documentation this means that all non-genetic covariates have a qr transform applied to it.    Is this shorthand for quadratic transform?  Additionally, how does this affect binary covariates such as sex or covariates that are already normally distributed?

**Comment by weizhouUMICH** [comment]
Hi, sorry for any confusion. 
1. In step 1, the plink file is still used for calculating GRM. The pre-calculated sparse GRM is used for variance ratio estimation. For single-variant association tests, we estimate variance ratio using the full GRM (from plink) and null (no GRM), while in gene-based association tests, we estimate variance ratio using the full GRM (from plink) and pre-calculated sparse GRM to make this approach work for extremely rare markers. 
2. in step 1, qr transformation is not for quadratic transformation. Here is a relevant paper https://en.wikipedia.org/wiki/QR_decomposition. The transformation is to make the covariate matrix orthogonal and the estimation of fixed effect coefficients easier to converge.

**Comment by tbrunetti** [comment]
Hi,

I am still a little confused by your response in step 1, question 1.  When I run step1 and look at the log file, the variance ratio is only finished once the plink file is finished, so I feel like it isn't dependent on the input GRM?  The GRM and generation of the null model is very quick  and happens without the plink file as it would seem from the log file, as long at the trait is binary. i can paste an example snippet of the log here.

**Comment by tbrunetti** [comment]
Hmm, I think I may see what you mean.  My supplied pre-calculated GRM is never being used for single variant association analysis.  It is only being used as a calculation into the sigma.mtx file, correct?  If this is true, is there a way I can force SAIGE to use the sigma file in single variant analysis across the whole genome, instead of just region or gene-based?

**Comment by weizhouUMICH** [comment]
We don't have this option yet. We are adding an option to allow for using a specified sparse GRM to fit the null model. It should be ready soon. Thanks!

**Comment by tbrunetti** [comment]
Great, thank you so much!  I look forward to the release of that feature!
