### ISSUE TITLE
Very large betas from SAIGE

### ISSUE THREAD

**Issue by nkgx** [weizhouUMICH/SAIGE#143]
SAIGE often seems to return unrealistically high betas, especially for case/control phenotypes and low-MAC variants.

For example in one case I see a beta of 33 which would imply an odds-ratio in the order of 10^14. The MAFs of the variant in this case are 0.006349 for cases and 0.000100 for controls. Logistic regression for that example with PLINK gives me a beta of 4.5 (ie. an OR of ~90) which seems much more realistic.

Is this expected because of the way SAIGE estimates the betas? Is there anything one could do to get a more reasonable estimate?

This is with the latest version but I have previously seen the same for older version as well.

**Comment by weizhouUMICH** [comment]
Hi Nils, 

Thanks for reporting this issue! The betas estimated from score tests are biased. The bias gets larger for larger true betas. We have also seen the extremely large beta estimates for those very rare variants. For example, the HBB locus (nearly Mendelian) for Hereditary hemolytic anemias in UKBB
http://pheweb.sph.umich.edu/SAIGE-UKB/pheno/282

One possible way to obtain more accurate betas for those significant loci with rare variants are running the Firth test on unrelated samples. I've just implemented an option to output numbers of heterozygotes and homozygotes for each variant, so a rough estimates for betas can be obtained based on those numbers. The script is still under testing and will be uploaded within next week. 

Thanks!
Wei

**Comment by nkgx** [comment]
Thank you Wei, that's good to know.
