### ISSUE TITLE
SAIGE - which version?

### ISSUE THREAD

**Issue by manygaard** [weizhouUMICH/SAIGE#145]
Hi,

I would very much like to use the SAIGE software for an analysis. 
Unfortunately I am stuck on an older platform, so I have a problem with the requirements.
The platform is debian jessie (debian 8), R 3.5.2, gcc version 4.9.2, cmake 3.0.2-1 and python-pip (1.5.6-5).
I can see that you have been so kind to put old versions of the software on the website, so my question is which of these versions would have the best chance to run on our platform?

Kind regards 
Marianne

**Comment by weizhouUMICH** [comment]
Hi Marianne, 

We have been continuously developing the program by fixing bugS and adding new functions, so I would recommend you to use the most recent version. If you use an older platform,  the conda environment for installing and running SAIGE should work best (the 5th approach).
https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE#installing-saige

Thanks!
Wei
