### ISSUE TITLE
SAIGE conditioned on a single nucleotide deletion variant

### ISSUE THREAD

**Issue by ruthchia** [weizhouUMICH/SAIGE#146]
Hi, I am trying to perform conditional analysis on a variant which happens to be a single nucleotide deletion. In the vcf file the the alt allele (which is the deletion) is represented as "*". This is causing a problem because the script thinks it is a wild card. Is there some thing I can do to tell the script to take "*" as a literal asterisks?
thanks
Ruth

**Comment by weizhouUMICH** [comment]
Hi Ruth, 

Thanks for reporting this issue. Let me talk to the developers of savvy library to see how to best query indels from vcf files. In the meanwhile, for any urgent job, I would recommend you to update the alleles for indels in the vcf files to some "fake" SNPs with alleles A,C,G,T. You may also try convert vcf to bgen, which theoretically can handle indels. 

Thanks!
Wei

**Comment by jonathonl** [comment]
Hi Ruth,

I'm not aware of any wildcard logic that would be at play here. Can you elaborate on this? Which script are you referring to? What is the specific behavior you are observing?

**Comment by ruthchia** [comment]
Hi, so sorry I brought this up. I resolved it as it was a mistake I made in my script. Apologies. 
The conditional option works just fine even when there is a "*".
