### ISSUE TITLE
Move installation guide to README.md?

### ISSUE THREAD

**Issue by szeestraten-ntnu** [weizhouUMICH/SAIGE#148]
Hi @weizhouUMICH, 

Would it be possible to move the installation guide from the wiki to the README.md so folks can contribute documentation updates and fixes using PRs and issues?

P.S. There is a small typo in the dependency list in the installation section (see excerpt below) where it should be `cget` and not `cgen`:

```
* R-3.6.1, gcc >= 5.4.0, cmake 3.14.1, cgen
```

**Comment by weizhouUMICH** [comment]
Hi @szeestraten-ntnu, 
Just done. Thanks!
Wei
