### ISSUE TITLE
Improvements on Dockerfile and simple build tests

### ISSUE THREAD

**Issue by szeestraten-ntnu** [weizhouUMICH/SAIGE#149]
Hi @weizhouUMICH, 

I would like to contribute a couple of Dockerfile tweaks that could cut down the Docker image size and perhaps a PR that introduces a simple Docker build test using [GitHub Actions](https://help.github.com/en/actions) so other contributors can easily get feedback if they broke the build or not when they submit PRs.

Would you be open to a PR to move the Docker parts over from [weizhouUMICH/Docker](https://github.com/weizhouUMICH/Docker/tree/master/SAIGE) into this repository?

**Comment by weizhouUMICH** [comment]
Sure @szeestraten-ntnu. Thank you very much for contributing!
Please feel free to submit PRs.

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
