### ISSUE TITLE
memory not mapped 

### ISSUE THREAD

**Issue by oalavijeh** [weizhouUMICH/SAIGE#150]
Dear Wei, 

I am using SAIGE-Gene (0.36.2) to run a gene based association test on 100K genome project data but am running into the following error:

- ** caught segfault ***  address 0x4c, cause 'memory not mapped'. 

- We work within an airlock so typing out the inputs would take a very long time but the log looks a little like this:
8474 samples used in fitting the NULL glmm model and are found in the sample file
sparse kinship matrix is going to be used
sparseSigmaFileL correct path to sigma txt 
etc
geneID: #gene 
** caught segfault ***  address 0x4c, cause 'memory not mapped

Traceback: 
1: getGeneOfGene_vcf(marker_group_line, minInfo)
2. SPAGMMATtest (whole query in full written here) 

My group file is as per your wiki a list of genes in the first column followed by the relevant variants for each gene tab separated.  There is no header for this. 

The VCF for analysis was used to generate the plink files and phenotype list as well as fit the null model.

I'm a bit stuck and would welcome your help! 

All the best

**Comment by weizhouUMICH** [comment]
Dear oalavijeh, 

Does the problem only occurs for one gene or all genes? Have you tried the example codes and do they work? ./SAIGE/extdata/cmd.sh

Thanks!
Wei

**Comment by oalavijeh** [comment]
Dear Wei, 

It was failing for all genes and your example data worked. After some reformatting for the group file it seemed to work! 

Thanks for taking the time to respond. 

All the best

Omid
