### ISSUE TITLE
Constructing genotype matrix 

### ISSUE THREAD

**Issue by oalavijeh** [weizhouUMICH/SAIGE#151]
Dear Wei, 

I wanted to run a single chromosome as a test of SAIGE-GENE and was wondering:

- Does the sparse GRM need to be created from a plink file of the entire genome or would the chromosome plink file be sufficient. 
- Does the plink file need to be made up of all the snps not filtered on allele frequency. At present I am using multi-sample vcfs divided by chromosome but filtered for rare variants and those annotated to be likely deleterious - could one turn this into the plink file to create the GRM or does it have to be all allele frequencies. 

Many thanks

Omid

**Comment by weizhouUMICH** [comment]
Dear Omid, 

For the first question, the sparse GRM and the full GRM, which will be constructed on-the-fly from the same plink file, are used to account for sample relatedness that needs to be accounted for as a potential confounder for the assoc tests.  Usually we use a plink file of the entire genome. We haven't tried and tested the case when a GRM is created from a plink file of a single chromosome. 

For the second question, we also recommend a MAF cutoff for GRM to avoid the scenario that rare variants drive sample relatedness coefficient estimation. By default, SAIGE applies MAF >= 1% to the plink file to construct GRM, You may use the option --minMAFforGRM to change the cutoff. 

Thanks!
Wei

**Comment by oalavijeh** [comment]
Dear Wei, 

Thanks for the comprehensive answer! 

All the best
