### ISSUE TITLE
constructing GRM

### ISSUE THREAD

**Issue by quinne5** [weizhouUMICH/SAIGE#152]
Hi, 
We are generating an LD pruned genotype file as input for step 1 and just had some questions on whether we should conduct this pruning only using the samples we are using downstream in step 2 or if this should be performed on a larger set of samples if available e.g. if i was testing one phenotype versus another in the UKBB say 1000 versus 1000 should my pruned plink input for step one just be those 2000 samples or the whole UKBB dataset

**Comment by weizhouUMICH** [comment]
Hi,

I think LD pruning on a larger set of samples would be better as the LD
values can be more accurately estimated based on larger sample sizes. Once
you have LD pruned genotype file, you may use the same one for all
phenotypes.

Thanks!
Wei

**Comment by quinne5** [comment]
Great thanks so much for replying so quickly!

**Comment by frahimov** [comment]
Hi.
Do you generate LD pruned genotype file using all chromosomes, just autosomes or a subset of chromosomes is sufficient?
