### ISSUE TITLE
SAIGE-GENE analysis on a single variant

### ISSUE THREAD

**Issue by ruthchia** [weizhouUMICH/SAIGE#153]
Hi Wei, 
I used SAIGE-GENE to perform the rare variant test. Upon interrogation of a gene that came up as significant, I noticed that only one variant was included in the analysis.
My understanding is that variants (i.e. > 1) within a gene are aggregated in such analysis. My question is:  is the output valid given that only one variant occurring 5 times was used SAIGE-GENE?

Here's an example:

Gene |  Pvalue           |     Nmarker_MACCate_1  |  Nmarker_MACCate_2  | Nmarker_MACCate_3  | Nmarker_MACCate_4 |  Nmarker_MACCate_5  | Nmarker_MACCate_6  | Nmarker_MACCate_7  | Nmarker_MACCate_8  | markerIDs       | markerAFs             | Pvalue_Burden  | Pvalue_SKAT
----- | -----| ----- | ----- | ----- | -----| ----- | ----- | ----- | -----| ----- | ----- | ----- | ----
DAB1  | 7.87906111379784e-12  | 0                  | 0                  | 0                  | 0                  | 1                  | 0                  | 0                  | 0                  | 1:57072362_A/G  | 0.000369439920177683  | NA            |  NA

Thanks,
Ruth

**Comment by weizhouUMICH** [comment]
Hi Ruth, 

For this single variant with MAC <= 10, the p-value is obtained by efficient re-sampling, which theoretically can account for unbalanced case-control ratio of the binary traits for extremely rare variants (if the trait is binary). For quantitative traits, there is no such issue. Overall, the output is supposed to be valid. 

Thanks,
Wei
