### ISSUE TITLE
Multi-ethnic analysis

### ISSUE THREAD

**Issue by andronekomimi** [weizhouUMICH/SAIGE#155]
Hello,
Is it possible (and coherent) to run a multi-ethnic analysis (keep all individuals in the same set without separate according to ancestry) with SAIGE?

Thank you!

**Comment by weizhouUMICH** [comment]
Hello,
 
We haven't throughly tested the performance of SAIGE on multi-ethnic samples. 
Theoretically, SAIGE uses a random effect to account for sample relatedness/population sub-stratification through the genetic relationship matrix. If there are multiple ethnics, the GRM will mainly represent population stratification and sample relatedness won't be well accounted for. Therefore, we would not recommend to run a multi-ethnic analysis with SAIGE. 
Thanks!

Wei

**Comment by andronekomimi** [comment]
Hello Wei,

Thank you very much for the prompt reply. 
So, we'll filter on the ethnicity before running the analysis.
Best,

Audrey

**Comment by oalavijeh** [comment]
Sorry to jump in but if one added PCA as a covariate or the input files had been through something such as KING to remove relatedness would SAIGE perform better with multi-ethnic samples?

**Comment by weizhouUMICH** [comment]
Hi @oalavijeh, 
No problem! I think adding PCs with the GRM, which mainly reflect sample relatedness may work. You may check the performance of the QQ plot. One concern that I have is that the effect sizes from the assoc tests may not be easy to interpret if there are heterogeneity of effect sizes in multi-ethnic samples. 

Thanks!
Wei
