### ISSUE TITLE
Error: The first variance component parameter estimate is 0

### ISSUE THREAD

**Issue by nkgx** [weizhouUMICH/SAIGE#156]
I'm trying to generate a null model for a quant trait with SAIGE 0.36.3.1. It seems to start okay but after 1-2 minutes it says:

```
Iteration  1 :
iGet_Coef:  1
iter from getPCG1ofSigmaAndVector 1
(...)
Tau:
[1,] -1.521256e-08
(...)
iter from getPCG1ofSigmaAndVector 1
(...)
Variance component estimates:
[1] 0 0
Fixed-effect coefficients:
               [,1]
 [1,] -1.521256e-08
(...)
Error in glmmkin.ai_PCG_Rcpp_Quantitative(plinkFile, fit0, tau = c(0,  :
  ERROR! The first variance component parameter estimate is 0
Calls: fitNULLGLMM -> system.time -> glmmkin.ai_PCG_Rcpp_Quantitative
Timing stopped at: 324.3 53.62 202
Execution halted
```

Does anybody have an idea what could be causing this? I have tried running with and without `--invNormalize=TRUE`.

**Comment by weizhouUMICH** [comment]
Hi @nkgx, 
The same error occurs with and without --invNormalize=TRUE? What is the sample size? 

Thanks!
Wei

**Comment by msarguru** [comment]
Dear Wei,
The errors occurs with and without the inverse normalization being TRUE. 
In my case the sample size is 1350, while a phenotype with lower sample size (n=800) ran just fine. Many thanks in advance for your insight. 
The raw values of the trait of our interest is normally distributed, with the skewness value approaching close to 0
