### ISSUE TITLE
Unusual results from SAIGE - 

### ISSUE THREAD

**Issue by oalavijeh** [weizhouUMICH/SAIGE#158]
Dear Wei,

Many thanks for your continuing support with SAIGE-GENE.

- I have been running it on a multi-sample vcf of chromosome 16 of 800 cases and 8000 controls.
- This has been prefiltered to a MAF0.0001, VEP annotations that assign the variant as high to moderate and a CADD score greater than 20.  
- Half of these 800 cases have a known rare variant in a single gene on chr16 but when running SAIGE-GENE the gene of interest is not significant.
-  In Nmarker_MACCate_1 (with default values) there are 180 markers and then a couple of cases per bin  but with Nmarjer_MACCate_6 there are 185 markers suddenly

- If I filter the VCF to only those with a "HIGH" impact variant and re-run the analysis the Nmarker_MACCate_1 for the gene of interest falls to 6 but the Nmarker_MACCate_6 drops by 5 to 180. 

- However, with IsSingleVarrinGroupTest set to TRUE the top 5 SNPs with significant P-values are all in the gene of interest in every iteration of the test I run.

My questions are:

- Is this a situation you have seen before? It seems highly unusual that there would be 180 rare deleterious variants  5.5 < MAC <=  10.5? 
- When the case control imbalance is corrected for can it "over-correct" and downplay differences. 
- What is the explanation for all the most significant SNP hits being in a single gene the not being borne out in the collapsed SKAT-O function. 

Sorry I can't share specific data as I work within an airlock environment. 

Many thanks for your time

**Comment by weizhouUMICH** [comment]
Dear @oalavijeh, 

1. Can you manually check the MAC for the tested variants to see whether their MAC fall in the category 5.5 < MAC <= 10.5? 
2. We haven't seen the "over-correct"  before. 
3. What are the p-values for most significant SNP hits in single-variant assoc test? 
Did you see this behavior for other genes or only this gene? 

Thanks!
Wei

**Comment by oalavijeh** [comment]
Dear @weizhouUMICH ,

1. Yes manually checked and can't find this many variants so not sure where the number has come from
2. Here is a screenshot of the values (ordered by p-value)
![image](https://user-images.githubusercontent.com/56344383/76883896-b6c3c600-6874-11ea-95d8-7aaadf8faf05.png)

![image](https://user-images.githubusercontent.com/56344383/76883949-cf33e080-6874-11ea-9d42-245023dcb243.png)

and this image above the cumulative results in PKD gene

Is the helpful?

Many thanks

**Comment by weizhouUMICH** [comment]
Hi @oalavijeh, 

Sorry for taking so long to get back to you. Please try the newest version and the issue should have been fixed. Please re-open the issue if the error persists.

Thanks!
Wei
