### ISSUE TITLE
Where did centerVariables in fitNULLGLMM go? (SAIGE 0.25)

### ISSUE THREAD

**Issue by endrebak** [weizhouUMICH/SAIGE#16]
I used to center age: how do I do that in the new SAIGE (0.25)?

The option seems to be gone.

**Comment by weizhouUMICH** [comment]
A qr transformation is applied to the covariate matrix, so the centerVariable option is removed in this version.

**Comment by endrebak** [comment]
Does this include the phenotype if it is continuous?

**Comment by endrebak** [comment]
Should we still normalize continuous variables (for example using [genabels rntransform](http://www.genabel.org/GenABEL/ztransform.html)) before sending it to SAIGE? Thanks for your reply :)

**Comment by weizhouUMICH** [comment]
If the continuous phenotypes need to be normalized, the invNormalize should still be specified to be TRUE.
