### ISSUE TITLE
Using SAIGE to run analyses on ~10 SNPs at a time on multiple phenotypes

### ISSUE THREAD

**Issue by Richard-Packer** [weizhouUMICH/SAIGE#161]
Hi Wei,

I'm looking to run analyses on up to say 10 SNP's at a time but against ~2000 phenotypes. For the single variant analysis, do I need to run step 1 (null model) for each phenotype with the full Plink file? Or can it be run with only the SNP's required with the GRM component done once for all SNP/phenotype tests?

Best,
Richard

**Comment by weizhouUMICH** [comment]
Hi Richard, 

You will need to run step 1 for each phenotype with the plink file that contains SNPs you'd like to use for constructing GRM. Once the null model is fit, you may test any SNP in step 2 for the phenotype. 

Best,
Wei
