### ISSUE TITLE
SAIGE analysis on chrX

### ISSUE THREAD

**Issue by ruthchia** [weizhouUMICH/SAIGE#163]
Hi Wei, 
I wanted to confirm with you if SAIGE and SAIGE-GENE are able to handle chr23 (i.e. chrX) analysis. I see several literature stating the standard analysis for autosomes may not necessarily apply directly to the sex chromosome without some presumptions and tweaking. I looked through your wiki page, and your paper, but didn't find specific information pertaining to this.  
Can you briefly tell me how you've adapted SAIGE/SAIGE-GENE for chr23 (or X) analysis? Have you benched mark this against RVTEST or XWAS?
Thanks
Ruth

**Comment by weizhouUMICH** [comment]
Hi Ruth, 

SAIGE and SAIGE-GENE do not take special care of chrX so we haven't benched mark this against other programs. As we use the variance ratio approach in SAIGE and SAIGE-GENE, in previous versions, only autosomal variants were used to estimate the variance ratio. In the most recent version 0.36.4, we've added a new option includeNonautoMarkersforVarRatio in step 1. It can be set to be TRUE, so non-autosomal variants can be also used to estimate the variance ratio, which will make the algorithm more appropriate for assoc tests for non-autosomal markers. Still, more tweaking might be needed in the input genotype file for appropriate association tests for chrX. 

Thanks,
Wei

**Comment by ruthchia** [comment]
Hi Wei,
Thanks for clarifying this. I saw some other users used SAIGE for chr X analysis and wanted to be sure that it may not quite be ready for sex chr analysis yet.
Best wishes
Ruth

**Comment by ruthchia** [comment]
One more question: so, if my plink binaries used for step1 variance ration estimation contains chrX, would I need to remove it first before proceeding, or will it knows to exclude chrX/23?
Thanks
Ruth

**Comment by weizhouUMICH** [comment]
You will need to exclude them if you don't want to use them for GRM.

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
