### ISSUE TITLE
Sharing step 1 models between SAIGE and SAIGE-GENE

### ISSUE THREAD

**Issue by glp-p4** [weizhouUMICH/SAIGE#164]
Hi, I have a question about how to properly construct step 1 null linear/logistic mixed models so that they can be used interchangably between SAIGE (single variant) and SAIGE-GENE (region- or gene- based) use cases. I am hoping to avoid having to build two separate models if that is at all possible.

Based on your SAIGE-GENE documentation:
"Step 1 model result from the single-variant assoc test can be re-used, except that for gene-based tests, variance ratios for multiple MAC categories and a sparse GRM need to be used (IsSparseKin=TRUE)."

Does this imply that, if I want to be able to share step 1 models between SAIGE and SAIGE-GENE, I will always need to build the models using a step 0 sparse GRM and set isCateVarianceRatio = TRUE?

Additionally:
If I have a step 1 model that was previously constructed for SAIGE (for performing single-variant association tests) and the model was created at the time using isSparseKin = FALSE (no step 0 was performed), is there any way to somehow use this model now that I want to perform analysis with SAIGE-GENE (for performing region- or gene- based associations)?

**Comment by glp-p4** [comment]
Hi Wei,

After reviewing your code, it looks like I might be able to reuse a model that was previously generated without a sparse GRM and with IsSparseKin = FALSE and isCateVarianceRatio = FALSE for use with SAIGE-GENE by:

- Creating a sparse GRM (step 0) using the same data from which the existing model was built.
- Placing the existing model (named <outputPrefix>.rda) in the working directory.
- Running SAIGE::fitNULLGLMM again, but with the following parameters:
    - skipModelFitting = TRUE
    - IsSparseKin = TRUE
    - sparseGRMFile = <grm_path>
    - sparseGRMSampleIDFile = <grm_sample_path>
    - isCateVarianceRatio = TRUE
    - outputPrefix = <existing_model_output_prefix>

If I understand correctly, the fitNULLGLMM will preserve the existing model and output a new variance ratio file and a sparse sigma matrix that are suitable for SAIGE-GENE.

Does this sound correct?

Best,
G

**Comment by weizhouUMICH** [comment]
Hi, 

Thank you so much for the follow-up message! What you've figured out is correct. The null model can be shared by SAIGE and SAIGE-GENE. The difference is in the variance ratio estimation part (step 1b)
In SAIGE, a single variant ratio is estimated without using the sparse GRM, while in SAIGE-GENE, categorical variance ratio are estimated with the sparse GRM incorporated. Given the null model from SAIGE, you can estimate the categorical variance ratios by those parameters you listed.

If the single variance ratio from SAIGE has been estimated, you may use outputPrefix_varRatio to specify a name for the file with categorical variance ratio.  Another point that you may need to pay extra attention is that for the categorical variance ratio estimation in SAIGE-GENE, the PLINK file needs to contain those extremely rare variants with MAC = 1, 2, 3, 4, 5, 6-10, 11-15 and 16-20 besides MAC > 20. Each category needs to have at least 30 variants.  Additional 10 variants will be needed until the variance estimation converges, so I'd say usually 50 variants for each category are enough. 

Thanks!
Wei

**Comment by glp-p4** [comment]
Hi Wei,

Much appreciated for the taking the time to write this up... Very helpful!

Best,
G
