### ISSUE TITLE
Post-hoc excision of participant data from step 1 models

### ISSUE THREAD

**Issue by glp-p4** [weizhouUMICH/SAIGE#165]
This is a question about the possibility of post-hoc removal of participant data from null logistic/linear mixed models. We have a use-case where models have been built (at potentially great expense) from the data of a certain set of participants, but later we need to exclude a small percentage of those participants from analysis (e.g. due to opt-out procedures).

If we understand correctly, the safest approach would be to completely rebuild the step 1 models from the reduced set of active participants.

However, for the sake of practical argument, how mathematically unsafe is it to attempt to surgically remove a small number of participant data points from a model and use that resulting model for analysis? Is it completely ill-advised?

**Comment by weizhouUMICH** [comment]
Thanks for this question, which also has been asked by other users. I think if only a small proportion of participant data points is removed, it would be fine to just remove them from the results of the null model fitting, specifically, from the model residuals and use the same variance component parameter estimates for step 2 . Ideally, as it is important to have a valid distribution of the model residuals, we can firstly remove those participants and run one iteration of the algorithm to update the variance component parameter and update the model residuals. This option is on my to-do list.

**Comment by glp-p4** [comment]
Hi Wei,

Thank you for the clarification. I think that will be a handy feature!

Best,
G
