### ISSUE TITLE
SAIGE install fails, multiple methods (Centos 6.x)

### ISSUE THREAD

**Issue by jbsysadmin** [weizhouUMICH/SAIGE#166]
Greetings.
The install method below fails with the output shown at bottom. gcc 8.2, R 3.6.3. Any leads?
"devtools::install_github("weizhouUMICH/SAIGE"" did not work either.
Centos 6.10
Method: 
git clone --depth 1 -b master https://github.com/weizhouUMICH/SAIGE
R CMD INSTALL SAIGE

Output:
* installing to library ‘/nfs/<project>/R-3.6.3-x86_64/lib64/R/library’
* installing *source* package ‘SAIGE’ ...
** using staged installation
Downloading https://github.com/statgen/savvy/archive/5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz
  [----------------------------------------------------------------------]    0%
Download failed with error 400 for: //github.com/statgen/savvy/archive/5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz
Failed to build package statgen/savvy
Waf: The wscript in '/usr/local/installs/saige/SAIGE/thirdParty/bgen' is unreadable

**Comment by weizhouUMICH** [comment]
Hi, 
The error is probably is probably due to some website down for downloading some dependency for savvy, which happened before. If you try again later, you may not see the error. 
But note that as we develop SAIGE/SAIGE-GENE on UBUNTU, installing on Centos usually needs much more manual set up for dependent libraries. Using conda env is the easiest way to install SAIGE/SAIGE-GENE on Centos. 
Could you please try that https://github.com/weizhouUMICH/SAIGE (approach 5a or 5b)? 
Thanks!
Wei

**Comment by jbsysadmin** [comment]
Greetings!
I am able to retrieve the file in the failed step at any time using wget.
Perhaps the install doesn’t accept system-declared or user-declared proxy server values.

Where can “<long_ID_number>.tar.gz” (or the resulting directory “savvy-<long_ID_number>”) be placed so that this command succeeds?

R CMD INSTALL SAIGE

Is there any file to edit under the git-pulled “SAIGE” directory?

** using staged installation
Downloading https://github.com/statgen/savvy/archive/<long_ID_number>.tar.gz
  [----------------------------------------------------------------------]    0%
Download failed with error 400 for: //github.com/statgen/savvy/archive/<long_ID_number>.tar.gz

-John

**Comment by jbsysadmin** [comment]
Also, if I do the following in R:
httr::set_config(httr::use_proxy("<url_for_proxy_server>",port=8080));
the other method (“devtools::install_github("weizhouUMICH/SAIGE");”) fails for the exact same reason.

It isn’t that savvy/archive/<long_ID_number>.tar.gz is sometimes available, sometimes not. It is *never* available using whatever retrieval method is in your installer. It is always retrievable with wget, or clicking link in Windows. There is some kind of re-direct /aliasing in play.

So if there is some way to tell your installer the savvy archive file is present, or to put a local location instead of the download attempt, this could move forward….

From: Burns, W. J.
Sent: Tuesday, March 24, 2020 4:19 PM
To: weizhouUMICH/SAIGE <reply@reply.github.com>; weizhouUMICH/SAIGE <SAIGE@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [weizhouUMICH/SAIGE] SAIGE install fails, multiple methods (Centos 6.x) (#166)

Greetings!
I am able to retrieve the file in the failed step at any time using wget.
Perhaps the install doesn’t accept system-declared or user-declared proxy server values.

Where can “<long_ID_number>.tar.gz” (or the resulting directory “savvy-<long_ID_number>”) be placed so that this command succeeds?

R CMD INSTALL SAIGE

Is there any file to edit under the git-pulled “SAIGE” directory?

** using staged installation
Downloading https://github.com/statgen/savvy/archive/<long_ID_number>.tar.gz<https://github.com/statgen/savvy/archive/%3clong_ID_number%3e.tar.gz>
  [----------------------------------------------------------------------]    0%
Download failed with error 400 for: //github.com/statgen/savvy/archive/<long_ID_number>.tar.gz

-John

**Comment by weizhouUMICH** [comment]
Hi @jonathonl 
Have you seen this problem before? Download error while installing savvy was seen by cget but not wget. https://github.com/statgen/savvy

**Comment by jonathonl** [comment]
I have not seen this error before. It seems a little odd that the error message prints `//github.com/...` and not `https://github.com/`.  @jbsysadmin, what version of cget do you have (`cget --version`)? Do you get the same error when you run `cget install statgen/savvy@5cf549634d535c07f08af4e52de67ecbf960d78e`?

**Comment by jbsysadmin** [comment]
cget, version 0.1.8
Same error, “Download failed with error 400 for: //github.com/statgen/savvy/archive/5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz”

If I try to install the wget-retrieved file directly (cget install 5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz) I get:

Download failed with error 400 for: //github.com/jonathonl/shrinkwrap/archive/v1.0.0-beta.tar.gz
Failed to build package 5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz

**Comment by jonathonl** [comment]
Hmm... can you run `pip install --upgrade --force-reinstall cget` and see if it installs with any warnings?

**Comment by jbsysadmin** [comment]
It did re-install (cget, version 0.1.8)
However, the same error occurs, under all previous scenarios.

**Comment by jonathonl** [comment]
I just spun up a Centos 6 VM and was able to use cget to install savvy without receiving that error. Do you have pip3 installed? If so, I would try uninstalling cget and then installing with pip3 instead?

Since Centos 6 is pretty old, you may run into other issues as well. You'll need a g++ version >= v5.0 and cmake >= 3.2. The default centos 6 packages do not meet these requirements.

**Comment by jbsysadmin** [comment]
The pip I uses in in Python 3.8.1. Any dependencies listed on your site (cmake/ gcc) are answered in custom compiles of later versions.
Re-installing with pip3 made no difference.
Was your VM behind a proxy? Do you know of any cget accommodation for that?

**Comment by jonathonl** [comment]
If your web traffic is being proxied, then that could very well be the problem you could try adding the --insecure flag to `cget install` in hopes that http behaves better than https (see https://github.com/pfultz2/cget/issues/52). 

Alternatively, you could install dependencies manually, but there are multiple layers of dependencies so this approach is quite involved. 

Another option would be to build a SAIGE binary package (`R CMD INSTALL --build`) on a centos 6 machine that has normal access to the internet.  And then install that package tarball within your destination environment.

**Comment by jbsysadmin** [comment]
I tried “—insecure” earlier today, but forgot to mention.
Thanks for the suggestions,
-John

You wrote:

If your web traffic is being proxied, then that could very well be the problem you could try adding the --insecure flag to cget install in hopes that http behaves better than https (see pfultz2/cget#52<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pfultz2_cget_issues_52&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=Lcm_WqJ_rUVrU3IQt7ALp57NrOU09lZVgNzJYrKHguE&m=ml9eMMIJdoYbtC0avFV89ZRhyvCVMjujI2R92fNVPR0&s=Nq_dF_CyazAqD69nPb4wBhALg7f9a7GUd4AyoyCsXjw&e=>).

Alternatively, you could install dependencies manually, but there are multiple layers of dependencies so this approach is quite involved.

**Comment by jonathonl** [comment]
You could try working with the cget maintainer to get this resolved (https://github.com/pfultz2/cget/issues/52).

Otherwise, these are the dependencies that would need to be manually installed:
zlib
https://github.com/facebook/zstd/archive/v1.3.2.tar.gz
https://github.com/jonathonl/shrinkwrap/archive/v1.0.0-beta.tar.gz
https://github.com/samtools/htslib/releases/download/1.6/htslib-1.6.tar.bz2
https://github.com/statgen/savvy/archive/5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz

You would then need to modify the configure script in SAIGE to not run cget.

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
