### ISSUE TITLE
Installing SAIGE

### ISSUE THREAD

**Issue by MostPJ** [weizhouUMICH/SAIGE#167]
Apologies for asking a beginner's question, but can you help me with installing SAIGE?

Recently, SAIGE allowed me to resolve the problems in a long-delayed, troublesome GWAS project. Therefor, I want to try SAIGE in a new, larger project. Unfortunately, the cluster does not have SAIGE installed. The helpdesk is refusing to install it, citing dependency and reproducibility issues, and invited me to try it myself.

So my question is: how does a novice UNIX user install SAIGE? Unfortunately, the cluster does not have condo or docker either.

However, the dependencies are all available, except for cmake (version 3.12 is available, but it needs to be upgraded) and cget. I think I only need to install those, and then I can install the package itself from inside R.

Any help or suggestions would be appreciated.

**Comment by glp-p4** [comment]
Since nobody has responded here yet, I will share how I build SAIGE. I find this to be the most reliable approach in my environment. Wei has documented other approaches which are easier, but I have sometimes run into problems with them. So, presuming you have all the necessary dependencies installed:

1. Clone the SAIGE respository:
```
git clone https://github.com/weizhouUMICH/SAIGE.git
```
2. Run configure:
```
cd SAIGE
./configure
```
3. Build the SAIGE package:
```
cd ..
R CMD build SAIGE
```
4. Install the resulting package:
```
R CMD INSTALL SAIGE_0.36.5.tar.gz
```

**Comment by MostPJ** [comment]
Thank you for your suggestion. Unfortunately, I wasn't able to install cget. Is there an easy way (for a not-very-experienced UNIX user) to do that?

**Comment by glp-p4** [comment]
Have you tried installing it using pip?
```
pip install cget
```

**Comment by MostPJ** [comment]
> 
> 
> Have you tried installing it using pip?
> 
> ```
> pip install cget
> ```

Sorry, forgot to mention that one. Yes, it does not know pip either. It says:

-bash: pip: command not found

**Comment by glp-p4** [comment]
Oh ok. You might be able to install pip yourself...
https://pip.pypa.io/en/stable/installing/

**Comment by MostPJ** [comment]
> 
> 
> Oh ok. You might be able to install pip yourself...
> https://pip.pypa.io/en/stable/installing/

Thank you for the suggestion - and apologies for the slow reply. Unfortunately, due to deadlines I had to abandon the attempt to use SAIGE and used another package instead.
