### ISSUE TITLE
Allow option to overwrite varianceRatio file

### ISSUE THREAD

**Issue by nshrine** [weizhouUMICH/SAIGE#168]
Line 683 in SAIGE_fitGLMM_fast.R is causing problems:

    stop("WARNING: The variance ratio file ", varRatioFile, " already exists. The new variance ratios will be output to ", varRatioFile,". In order to avoid over-writting, please remove the ", varRatioFile, " or use the argument outputPrefix_varRatio to specify a different prefix to output the variance ratio(s)\n")

I am running a pipeline based on GNU make whereby if any of the input files are updated, the SAIGE step1 needs to be run again, however this line above is causing my pipeline to stop.

Can an option be included to allow overwriting of the varianceRatio file?

**Comment by weizhouUMICH** [comment]
Hi @nshrine, 

Yes, as the warning message shows, you may specify a new variance ratio file using --outputPrefix_varRatio when the input file is updated. 

Thanks!
Wei

**Comment by nshrine** [comment]
I don't want to have to specify a new filename every time I run my pipeline, otherwise subsequent operations in the pipeline will also have to be updated with the new filename. I just want to overwrite the previous file e.g. with an option like --force --clobber --overwrite whatever. I have tried changing the stop() in the source code to warning() so that the program doesn't exit but I'm having real trouble getting the dependencies to compile.

**Comment by weizhouUMICH** [comment]
Hi @nshrine, 
In v0.38, an option --IsOverwriteVarianceRatioFile has been added for this problem. if  --IsOverwriteVarianceRatioFile=TRUE, the varianceRatioFile will be overwritten. 
Thanks,
Wei
