### ISSUE TITLE
Problem installing saige

### ISSUE THREAD

**Issue by pvo93** [weizhouUMICH/SAIGE#169]
I'm trying to install SAIGE for a medical researcher on a Linux CentOS 6 system for which I don't have root access. I managed to install the required Python modules and a more recent version of cmake, but I'm still getting the following errors. I get the same errors with gcc 4.9.4 and 6.3.1. Any insight you could provide would be greatly appreciated.

   Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     'SAIGE/thirdParty/bgen/build/3rd_party/boost_1_55_0/libs/filesystem/src/codecvt_error_category.cpp.1.o'
   Warning in utils::tar(filepath, pkgname, compression = "gzip", compression_level = 9L,  :
     using GNU extension for long pathname
   
Installing package into â/usr/local/biotools/rpackages/R-3.5.2-latestâ
(as âlibâ is unspecified)
    Set stringsAsFactors option to False
* installing *source* package âSAIGEâ ...
Downloading https://github.com/statgen/savvy/archive/5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz
  [######################################################################]  100%
Extracting archive /tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/cget/cget/build/tmp-9bf50c6788114c9599595de3231d4fc5/5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz ...
Downloading https://github.com/jonathonl/shrinkwrap/archive/v1.0.0-beta.tar.gz
  [######################################################################]  100%
Extracting archive /tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/cget/cget/build/tmp-b05cc2cac0bb4dd98c2847bcc2d8a926/v1.0.0-beta.tar.gz ...
Downloading https://tukaani.org/xz/xz-5.2.3.tar.bz2
  [######################################################################]  100%             
Extracting archive /tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/cget/cget/build/tmp-cc0d0a84e2794ac48f3094aa1a1f4ac7/xz-5.2.3.tar.bz2 ...
/research/bsi/tools/biotools/cmake/3.11.2/bin/cmake: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /research/bsi/tools/biotools/cmake/3.11.2/bin/cmake)
/research/bsi/tools/biotools/cmake/3.11.2/bin/cmake: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /research/bsi/tools/biotools/cmake/3.11.2/bin/cmake)
/research/bsi/tools/biotools/cmake/3.11.2/bin/cmake: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /research/bsi/tools/biotools/cmake/3.11.2/bin/cmake)
/research/bsi/tools/biotools/cmake/3.11.2/bin/cmake: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /research/bsi/tools/biotools/cmake/3.11.2/bin/cmake)
/research/bsi/tools/biotools/cmake/3.11.2/bin/cmake: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /research/bsi/tools/biotools/cmake/3.11.2/bin/cmake)
Command failed: ['/research/bsi/tools/biotools/cmake/3.11.2/bin/cmake', '-DCMAKE_TOOLCHAIN_FILE=/tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/cget/cget/cget.cmake', '/tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/cget/cget/build/tmp-cc0d0a84e2794ac48f3094aa1a1f4ac7/xz-5.2.3', '-DCGET_CMAKE_DIR=/research/bsi/tools/biotools/python/3.5.2/lib/python3.5/site-packages/cget/cmake', '-DCGET_CMAKE_ORIGINAL_SOURCE_FILE=/tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/cget/cget/build/tmp-cc0d0a84e2794ac48f3094aa1a1f4ac7/xz-5.2.3/__cget_original_cmake_file__.cmake', '-DCMAKE_C_FLAGS=-fPIC', '-DCMAKE_CXX_FLAGS=-fPIC', '-DBUILD_TESTING=Off', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/cget/cget/pkg/xz/install']
Failed to build package statgen/savvy
Waf: The wscript in '/tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/bgen' is unreadable
Traceback (most recent call last):
  File "/tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 101, in waf_entry_point
    set_main_module(os.path.normpath(os.path.join(Context.run_dir,Context.WSCRIPT_FILE)))
  File "/tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 141, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Context.py", line 360, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/bgen/wscript", line 33
    print "Creating %s build..." % bld.options.mode
                               ^
SyntaxError: Missing parentheses in call to 'print'
Waf: The wscript in '/tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/bgen' is unreadable
Traceback (most recent call last):
  File "/tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 101, in waf_entry_point
    set_main_module(os.path.normpath(os.path.join(Context.run_dir,Context.WSCRIPT_FILE)))
  File "/tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Scripting.py", line 141, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/bgen/.waf3-2.0.6-f8aee10f7730da942389d88501d489e8/waflib/Context.py", line 360, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/tmp/RtmpQo75u6/R.INSTALL116df1171bdb/SAIGE/thirdParty/bgen/wscript", line 33
    print "Creating %s build..." % bld.options.mode
                               ^
SyntaxError: Missing parentheses in call to 'print'
ERROR: configuration failed for package âSAIGEâ
* removing â/usr/local/biotools/rpackages/R-3.5.2-latest/SAIGEâ
Error: Failed to install 'SAIGE' from GitHub:
  (converted from warning) installation of package â/tmp/Rtmpnh2VS1/filef73718720400/SAIGE_0.36.4.1.tar.gzâ had non-zero exit status

**Comment by weizhouUMICH** [comment]
Hi @pvo93, 

As the library is developed on Ubuntu, we've found the best way to install and run it on Centos 6 is using conda env. Could you please try this approach (approach 5 https://github.com/weizhouUMICH/SAIGE)? 

Thanks!
Wei

**Comment by pvo93** [comment]
Unfortunately, that's not an option for us. Our organization hasn't approved the use of conda due to security concerns.
