### ISSUE TITLE
error: Mat::operator(): index out of bounds

### ISSUE THREAD

**Issue by glp-p4** [weizhouUMICH/SAIGE#171]
Hi Wei,

I have hit another snag while trying to build a sparse GRM on SAIGE Version: 0.36.3.1
When running the command:
```
SAIGE::createSparseGRM(
  plinkFile = 'ref',
  numRandomMarkerforSparseKin = n_eid,
  nThreads = parallel::detectCores()
)
```
I am getting the following error (see [error_log.txt](https://github.com/weizhouUMICH/SAIGE/files/4464658/error_log.txt)):
```
Error in refineKin(relatednessCutoff) : 
  Mat::operator(): index out of bounds
Calls: do.call ... <Anonymous> -> createSparseKinParallel -> refineKin
Execution halted
```
Any idea what might be wrong here? One thing that looks a bit odd in the log is that it says:
```
171972 markers with MAF >= 0.01 are used for GRM.
```
But there are only 100,000 markers total in the reference file.

Best,
G

**Comment by glp-p4** [comment]
I updated to the current master branch (rather than 0.36.3.1) and this problem appears to have gone away. Perhaps it was addressed by a recent check-in.

**Comment by glp-p4** [comment]
Actually, upon further research, I have found that this error still occurs in the newest version of SAIGE. However, what causes it is when SAIGE::createSparseGRM is called more than once in the same R session against different plink data sets. Maybe some internal state is not being cleared / reset between runs?

**Comment by weizhouUMICH** [comment]
Hi @glp-p4, 

Thanks for sharing the log file. I think the genotype in plink file has not been read correctly. Can you try the example data to see if it works? The script (line 92 in the extdata/cmd.sh) is
https://github.com/weizhouUMICH/SAIGE/blob/master/extdata/cmd.sh 
```
Rscript createSparseGRM.R       \
        --plinkFile=./input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly \
        --nThreads=4  \
        --outputPrefix=./output/sparseGRM       \
        --numRandomMarkerforSparseKin=1000      \
        --relatednessCutoff=0.125
```
Thanks!
Wei

**Comment by glp-p4** [comment]
Hi Wei,

No problem!

From my experience, running `Rscript createSparseGRM.R` will not reproduce the error, because createSparseGRM will be invoked only once within the context of an R session.

Where I ran into the problem was when calling `SAIGE::createSparseGRM` within a loop in R over multiple distinct plink file sets.

My work-around is ensure I call this function only once per R session. I have a feeling that some internal state does not get reset when it is invoked more than once.

Best,
G

**Comment by glp-p4** [comment]
I believe I have isolated one potential problem...

On this line:
https://github.com/weizhouUMICH/SAIGE/blob/79d5adde456a7fb4c291a298761b2587c5bc2e9a/src/SAIGE_fitGLMM_fast.cpp#L635

Within the setGenoObj method, you are incrementing `numberofMarkerswithMAFge_minMAFtoConstructGRM`, however, you have only zerod that value out when the `genoClass` is instantiated. If you call `setGenoObj` multiple times in a given R session, this count will just keep increasing. 

I am not sure if this is the root cause of the exception, but I think something of this nature is.

**Comment by weizhouUMICH** [comment]
Hi @glp-p4, 
Yes you are right. setGenoObj should not be called several times. 
So createSparseGRM function has an argument isSetGeno (by default, it is TRUE), so if setGenoObj has already been called previously, isSetGeno can be set to be FALSE. Can you please try this? 
https://github.com/weizhouUMICH/SAIGE/blob/master/R/SAIGE_createSparseGRM.R
Thanks!
Wei

**Comment by glp-p4** [comment]
Just to be clear, though, that would only work as expected if I call createSparseGRM on the same PLINK file, right? If I want to loop through different PLINK files, wouldn't that just cause the data from the first one to be used over and over?

**Comment by weizhouUMICH** [comment]
Yes. it is not for different PLINK files.

**Comment by glp-p4** [comment]
Ok, thanks for the clarification Wei. Now that I understand how createSparseGRM works, and its limitations with an R session, I can just be sure to never use it for multiple PLINK files within the same R session. However, it is not obvious that this is a limitation. It might be a good idea for the setGenoObj function to simply error out if it is called more than once for a given instantiation of the geno object to prevent unforeseen errors downstream.
