### ISSUE TITLE
Error in running step1_fitNULLGLMM: "_SAIGE_setminMAFforGRM" not available

### ISSUE THREAD

**Issue by tmatsui2** [weizhouUMICH/SAIGE#172]
Hi Wei,

After initially struggling to install SAIGE, I was finally able to install it using method 5 using the conda environment. However, after installation, I tried running the step1 example shown in cmd.sh file, and I got this error:

Error in .Call("_SAIGE_setminMAFforGRM", PACKAGE = "SAIGE", minMAFforGRM) : 
  "_SAIGE_setminMAFforGRM" not available for .Call() for package "SAIGE"
Calls: fitNULLGLMM -> setminMAFforGRM
Execution halted

Any idea what might be wrong here? I tried re-installing SAIGE but it did not seem to correct the problem.

Thank you for your help!

**Comment by weizhouUMICH** [comment]
Hi @tmatsui2, 

Which version of SAIGE have you installed? This error was seen when you load the package? 

Thanks,
Wei

**Comment by tmatsui2** [comment]
Hi Wei,

I have the latest version 0.36.5 installed. I do not see this error when I load the package.

Thanks!

**Comment by weizhouUMICH** [comment]
Thanks! What script did you run when you see the error?

**Comment by tmatsui2** [comment]
I ran this: 
Rscript step1_fitNULLGLMM.R     \
        --plinkFile=./input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly \
        --phenoFile=./input/pheno_1000samples.txt_withdosages_withBothTraitTypes.txt \
        --phenoCol=y_binary \
        --covarColList=x1,x2 \
        --sampleIDColinphenoFile=IID \
        --traitType=binary        \
        --outputPrefix=./output/example_binary_includenonAutoforvarRatio \
        --nThreads=4	\
	--LOCO=FALSE	\
	--minMAFforGRM=0.01

And this is what I got for the output:
Loading required package: optparse
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS/LAPACK: /Users/tmatsui2/opt/anaconda3/envs/RSAIGE/lib/R/lib/libRblas.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] optparse_1.6.4 SAIGE_0.36.5  

loaded via a namespace (and not attached):
[1] compiler_3.6.1     Matrix_1.2-18      Rcpp_1.0.1         getopt_1.20.3     
[5] grid_3.6.1         RcppParallel_4.4.4 lattice_0.20-38   
Warning message:
In value[[3L]](cond) :
  integer expected, got “4--LOCO=FALSE--minMAFforGRM=0.01”
$plinkFile
[1] "./input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly"

$phenoFile
[1] "./input/pheno_1000samples.txt_withdosages_withBothTraitTypes.txt"

$phenoCol
[1] "y_binary"

$traitType
[1] "binary"

$invNormalize
[1] FALSE

$covarColList
[1] "x1,x2"

$sampleIDColinphenoFile
[1] "IID"

$tol
[1] 0.02

$maxiter
[1] 20

$tolPCG
[1] 1e-05

$maxiterPCG
[1] 500

$nThreads
[1] "4--LOCO=FALSE--minMAFforGRM=0.01"

$SPAcutoff
[1] 2

$numRandomMarkerforVarianceRatio
[1] 30

$skipModelFitting
[1] FALSE

$memoryChunk
[1] 2

$tauInit
[1] "0,0"

$LOCO
[1] FALSE

$traceCVcutoff
[1] 0.0025

$ratioCVcutoff
[1] 0.001

$outputPrefix
[1] "./output/example_binary_includenonAutoforvarRatio"

$IsSparseKin
[1] FALSE

$numRandomMarkerforSparseKin
[1] 2000

$isCateVarianceRatio
[1] FALSE

$relatednessCutoff
[1] 0.125

$cateVarRatioMinMACVecExclude
[1] "0.5,1.5,2.5,3.5,4.5,5.5,10.5,20.5"

$cateVarRatioMaxMACVecInclude
[1] "1.5,2.5,3.5,4.5,5.5,10.5,20.5"

$isCovariateTransform
[1] TRUE

$isDiagofKinSetAsOne
[1] FALSE

$useSparseSigmaConditionerforPCG
[1] FALSE

$useSparseSigmaforInitTau
[1] FALSE

$minMAFforGRM
[1] 0.01

$minCovariateCount
[1] -1

$includeNonautoMarkersforVarRatio
[1] FALSE

$help
[1] FALSE

tauInit  is  0 0 
cateVarRatioMinMACVecExclude  is  0.5 1.5 2.5 3.5 4.5 5.5 10.5 20.5 
cateVarRatioMaxMACVecInclude  is  1.5 2.5 3.5 4.5 5.5 10.5 20.5 
Error in .Call("_SAIGE_setminMAFforGRM", PACKAGE = "SAIGE", minMAFforGRM) : 
  "_SAIGE_setminMAFforGRM" not available for .Call() for package "SAIGE"
Calls: fitNULLGLMM -> setminMAFforGRM
Execution halted

**Comment by weizhouUMICH** [comment]
Thanks! I see. It seems in the code you are running. The three lines are put in one
$nThreads
[1] "4--LOCO=FALSE--minMAFforGRM=0.01"

You may be useing --nThreads=4--LOCO=FALSE--minMAFforGRM=0.01

The specifications need to be on three lines: 
--nThreads=4
--LOCO=FALSE
--minMAFforGRM=0.01

**Comment by tmatsui2** [comment]
Thanks! That fixed the warning:
$nThreads
[1] "4--LOCO=FALSE--minMAFforGRM=0.01"

but I'm unfortunately still getting the error:
Error in .Call("_SAIGE_setminMAFforGRM", PACKAGE = "SAIGE", minMAFforGRM) : 
  "_SAIGE_setminMAFforGRM" not available for .Call() for package "SAIGE"
Calls: fitNULLGLMM -> setminMAFforGRM

**Comment by weizhouUMICH** [comment]
Could you please share the log file again?

**Comment by tmatsui2** [comment]
Loading required package: optparse
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS/LAPACK: /Users/tmatsui2/opt/anaconda3/envs/RSAIGE/lib/R/lib/libRblas.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] optparse_1.6.4 SAIGE_0.36.5  

loaded via a namespace (and not attached):
[1] compiler_3.6.1     Matrix_1.2-18      Rcpp_1.0.1         getopt_1.20.3     
[5] grid_3.6.1         RcppParallel_4.4.4 lattice_0.20-38   
$plinkFile
[1] "./input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly"

$phenoFile
[1] "./input/pheno_1000samples.txt_withdosages_withBothTraitTypes.txt"

$phenoCol
[1] "y_binary"

$traitType
[1] "binary"

$invNormalize
[1] FALSE

$covarColList
[1] "x1,x2"

$sampleIDColinphenoFile
[1] "IID"

$tol
[1] 0.02

$maxiter
[1] 20

$tolPCG
[1] 1e-05

$maxiterPCG
[1] 500

$nThreads
[1] 4

$SPAcutoff
[1] 2

$numRandomMarkerforVarianceRatio
[1] 30

$skipModelFitting
[1] FALSE

$memoryChunk
[1] 2

$tauInit
[1] "0,0"

$LOCO
[1] FALSE

$traceCVcutoff
[1] 0.0025

$ratioCVcutoff
[1] 0.001

$outputPrefix
[1] "./output/example_binary_includenonAutoforvarRatio"

$IsSparseKin
[1] FALSE

$numRandomMarkerforSparseKin
[1] 2000

$isCateVarianceRatio
[1] FALSE

$relatednessCutoff
[1] 0.125

$cateVarRatioMinMACVecExclude
[1] "0.5,1.5,2.5,3.5,4.5,5.5,10.5,20.5"

$cateVarRatioMaxMACVecInclude
[1] "1.5,2.5,3.5,4.5,5.5,10.5,20.5"

$isCovariateTransform
[1] TRUE

$isDiagofKinSetAsOne
[1] FALSE

$useSparseSigmaConditionerforPCG
[1] FALSE

$useSparseSigmaforInitTau
[1] FALSE

$minMAFforGRM
[1] 0.01

$minCovariateCount
[1] -1

$includeNonautoMarkersforVarRatio
[1] FALSE

$help
[1] FALSE

tauInit  is  0 0 
cateVarRatioMinMACVecExclude  is  0.5 1.5 2.5 3.5 4.5 5.5 10.5 20.5 
cateVarRatioMaxMACVecInclude  is  1.5 2.5 3.5 4.5 5.5 10.5 20.5 
Error in .Call("_SAIGE_setminMAFforGRM", PACKAGE = "SAIGE", minMAFforGRM) : 
  "_SAIGE_setminMAFforGRM" not available for .Call() for package "SAIGE"
Calls: fitNULLGLMM -> setminMAFforGRM
Execution halted

**Comment by weizhouUMICH** [comment]
Thank you! It's quite strange. Also the error suggests that it is possible the C++ codes were not compiled successfully. 
Could you please try the example code here? 
https://github.com/weizhouUMICH/SAIGE/blob/master/extdata/cmd.sh

**Comment by tmatsui2** [comment]
Thank you very much for your help so far Wei! 

Unfortunately I'm still getting the same error message, regardless of which code I try. I will re-installing SAIGE again, perhaps with an earlier version and see if I have better luck.

**Comment by weizhouUMICH** [comment]
Hi @tmatsui2, Thank you for your patience! I've noticed that you are installing on a MAC? I think if you'd like to run on a MAC, using the docker might be a better way.
