### ISSUE TITLE
Way(s) to perform QC?

### ISSUE THREAD

**Issue by catlisboa** [weizhouUMICH/SAIGE#173]
Hi! Is there anyway to perform quality control steps (besides the minMAC or minMAF) using SAIGE?

Thank you very much,
Kind regards,
Catarina

**Comment by weizhouUMICH** [comment]
Hi Catarina, 

Poorly imputed variants can be filtered out by minInfo based on their imputation score. Other than there, there is no way to perform quality control within SAIGE. 

Thanks,
Wei
