### ISSUE TITLE
MAF of males in chrX

### ISSUE THREAD

**Issue by fadista** [weizhouUMICH/SAIGE#175]
Hi,

I have been working with the chrX using the UK Biobank bgen files. All is good but when I work with another dataset from another cohort in vcf dosage format it seems that the SAIGE output MAFs are wrong for males. Frequencies in males are about half of females. 

Could it be that in the vcf dosage format input, the calculation of MAF for males is wrong?  
Thanks.

Best,
João

**Comment by weizhouUMICH** [comment]
Hi @fadista, 
Sorry for missing your issue. How is the vcf doage coded for Males and Females? 
Thanks,
Wei

**Comment by fadista** [comment]
Hi Wei. Males were coded haploid. I changed them to diploid so the MAF now is good. Thanks
