### ISSUE TITLE
Update wiki to indicate which allele is the effect allele

### ISSUE THREAD

**Issue by carbocation** [weizhouUMICH/SAIGE#176]
Currently the [Wiki hands-on practical](https://github.com/weizhouUMICH/SAIGE/wiki/SAIGE-Hands-On-Practical) doesn't indicate whether A1 or A2 is the effect allele from SAIGE:

```
CHR: chromosome
POS: genome position 
SNPID: variant ID
Allele1: Ref allele
Allele2: Alt allele
AC_Allele2: allele count of Alt allele
AF_Allele2: allele frequency of Alt allele
N: sample size
BETA: effect size
SE: standard error of BETA
Tstat: score statistic
p.value: p value with SPA applied
p.value.NA: p value when SPA is not applied
Is.SPA.converge: whether SPA is converged or not
varT: estimated variance of score statistic with sample related incorporated
varTstar: variance of score statistic without sample related incorporated
```

It would be great to indicate under `BETA` whether this is the effect of Allele1 or Allele2.

**Comment by Ojami** [comment]
Hi,

I assume `Allele2` is the effect allele as shown [here](https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE):

> Association results are with regard to Allele2.

Best/Oveis

**Comment by weizhouUMICH** [comment]
Hi James,

Association results are with regard to Allele2.
The hands-on practical is outdated and not maintained.
Please check the following page for examples and notes. Sorry for the
confusion.
https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE

Thanks,
Wei
