### ISSUE TITLE
SIAGE output POS format

### ISSUE THREAD

**Issue by chiayenchen** [weizhouUMICH/SAIGE#177]
Hi,

It happens occasionally that the POS of a variant is an integer like 93000000, and it will be reported in scientific notation (9.3e+07) in the SAIGE single variant test output (v0.36.6). I'm wondering if it's possible to alway have POS printed as strings in the SAIGE output to avoid this? Thanks a lot.

Best,
Chia-Yen

**Comment by weizhouUMICH** [comment]
Hi Chia-Yen, 

Thanks for reporting this issue.  @juhis tried to convert scientific notations back using the bash script `printf "\t%d", $i`. Maybe adding `options(scipen=999)` to the beginning of the R wrapper script of step 2 can work. I will try this later today and update here. We've also tried use the format() function within the R scripts of SAIGE and it made the program really slow. 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
Hi Chia-Yen, 

Sorry for my late reply. I've tried options(scipen=999) in a google VM with ubuntu 16.04 and the POS is not output to scientific notation... Still not sure how to avoid the scientific notation. 

Wei

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
