### ISSUE TITLE
Few questions regarding SAIGE step 2 on BGEN with idstoIncludeFile/rangestoIncludeFile flag

### ISSUE THREAD

**Issue by Ojami** [weizhouUMICH/SAIGE#178]
Hi Wei,

I try to run step 2 on BGEN files as input for a subset of variants (_bgensnps.1.tmpb.txt_):
`SPAGMMATtest(bgenFile="chr22.bgen",bgenFileIndex="chr22.bgen.bgi",GMMATmodelFile="step1_nullmodel_bgen.rda",idstoIncludeFile="bgensnps.1.tmpb.txt",IsDropMissingDosages=TRUE,IsOutputAFinCaseCtrl=TRUE,IsOutputNinCaseCtrl=TRUE,LOCO=FALSE,minMAC=3,minMAF=0,SAIGEOutputFile="chr22.SAIGEspa.1.txt",sampleFile="chr22.txt",varianceRatioFile="step1_nullmodel.varianceRatio.txt")`

in which the head of file introduced to `idstoIncludeFile` flag look lite this:

> rs370772954
> rs3949130
> rs200167968
> rs79847867

Then, it throws this error:

> single-variant association test will be performed
432781  samples have been used to fit the glmm null model
obj.glmm.null$LOCO:  FALSE 
Leave-one-chromosome-out option is not applied
Single variance ratio is provided, so categorical variance ratio won't be used!
variance Ratio is  1 
434601  sample IDs are found in sample file
[1] 434601      4
[1] "IID"          "IndexInModel" "IndexDose.x"  "IndexDose.y" 
432781  samples were used in fitting the NULL glmm model and are found in sample file
sparse kinship matrix is not used
Samples with missing dosages will be dropped from the analysis
Analysis started at  1587982040 Seconds
minMAC:  3 
minMAF:  0 
Minimum MAF of markers to be tested is  3.465956e-06 
isCondition is  FALSE 
It is a binary trait
Analyzing  1831  cases and  430950  controls 
isCondition is  FALSE 
Analysis started at  1587982041 Seconds
TEST 9800
TEST 1 OK
TEST2 9800
ranges_to_include.nrow() 0
ranges_to_exclude.nrow() 0
ids_to_include.size() 9800
ids_to_exclude.size() 0
Error in setgenoTest_bgenDosage(bgenFile, bgenFileIndex, ranges_to_exclude = ranges_to_exclude,  : 
  db::StatementStepError
Calls: SPAGMMATtest -> setgenoTest_bgenDosage
Execution halted

I should mention that I included variant ids ([_rsid_ field in bgenix](https://bitbucket.org/gavinband/bgen/wiki/The_bgenix_index_file_format)), but I assume SIAGE needs _varid_ ([as shown here](https://docs.google.com/spreadsheets/d/1kvPoupSzsSFBNSztMzl04xMoSC3Kcx3CrjVf4yBmESU/edit?ts=5b5f17db#gid=227859291)), am I right? If yes, how should someone generates _varid_ without parsing the whole BGEN file (given the fact that bgenix does not include _varid_)?

While the error resolves when I use `rangestoIncludeFile` for the  same _rsids_ using the index file from bgenix, the main drawback is the [sqlite3 limitations](https://bitbucket.org/gavinband/bgen/issues/37/inclusion-of-9998-ranges-from-file-results) for number of markers in the subset.

Given the larger marker size in BGEN files (I specifically talk about UKBB), and the fact that step 2 is single-threaded, running SAIGE step 2 for BGEN files is not efficient. I tried also to parallelize step 2 by marker subsetting (indeed, that's why I use _rangestoIncludeFile_ and _idstoIncludeFile_ flags), however the above-mentioned issues hinder an efficient process.
So, I appreciate if you could share your thoughts on that.

Thanks in advance,
Best/Oveis

**Comment by weizhouUMICH** [comment]
Hi Oveis, 
Last time when I saw the error, it is due to the duplicates of variant IDs in the specified idstoIncludeFile. Could you please have a check to see if any variant IDs appear more than once in the list? We have also parallel the step 2 jobs for UKBB by querying with lists of variant ids. 

Thanks,
Wei

**Comment by Ojami** [comment]
Dear Wei,

Yes, that was the problem! Thanks for your help.

Best/Oveis
