### ISSUE TITLE
step2: No Error / no Output

### ISSUE THREAD

**Issue by vivek-verma202** [weizhouUMICH/SAIGE#179]
Dear Wei,
There is no output in 30markers.SAIGE.results.txt file (except the headers).
I have used "--chrom=21" as the original file had CHROM as 21 (and not chr_21, etc.)

### The code I ran:
>Rscript /home/R/x86_64-pc-linux-gnu-library/3.6/SAIGE/extdata/step2_SPAtests.R \
        --vcfFile=/scratch/geno/vcf/21.vcf.gz \
        --vcfFileIndex=/scratch/geno/vcf/21.vcf.gz.tbi \
         --vcfField=DS \
        --chrom=21 \
        --minMAF=0.0001 \
        --minMAC=1 \
        --sampleFile=/scratch/geno/vcf/id \
        --GMMATmodelFile=/scratch/saige/out1_21.rda \
        --varianceRatioFile=/scratch/saige/out1_21.varianceRatio.txt \
        --SAIGEOutputFile=/scratch/saige/out1_21_30markers.SAIGE.results.txt \
        --numLinesOutput=2 \
        --IsOutputAFinCaseCtrl=TRUE \
	--IsDropMissingDosages=TRUE 

### The R output looks as follows:

> R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)
Matrix products: default
BLAS/LAPACK: /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/imkl/2018.3.222/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so
locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
other attached packages:
[1] SAIGE_0.36.3.1
loaded via a namespace (and not attached):
[1] compiler_3.6.1     Matrix_1.2-17      Rcpp_1.0.4.6       grid_3.6.1
[5] RcppParallel_5.0.0 lattice_0.20-38
$vcfFile
[1] "/scratch/geno/vcf/21.vcf.gz"
$vcfFileIndex
[1] "/scratch/geno/vcf/21.vcf.gz.tbi"
$vcfField
[1] "DS"
$bgenFile
[1] ""
$bgenFileIndex
[1] ""
$savFile
[1] ""
$savFileIndex
[1] ""
$idstoExcludeFile
[1] ""
$idstoIncludeFile
[1] ""
$rangestoExcludeFile
[1] ""
$rangestoIncludeFile
[1] ""
$chrom
[1] "21"
$start
[1] 1
$end
[1] 2.5e+08
$IsDropMissingDosages
[1] TRUE
$minMAF
[1] 1e-04
$minMAC
[1] 1
$maxMAFforGroupTest
[1] 0.5
$minInfo
[1] 0
$sampleFile
[1] "/scratch/geno/vcf/id"
$GMMATmodelFile
[1] "/scratch/saige/out1_21.rda"
$varianceRatioFile
[1] "/scratch/saige/out1_21.varianceRatio.txt"
$SAIGEOutputFile
[1] "/scratch/saige/out1_21_30markers.SAIGE.results.txt"
$numLinesOutput
[1] 2
$IsSparse
[1] TRUE
$IsOutputAFinCaseCtrl
[1] TRUE
$IsOutputNinCaseCtrl
[1] FALSE
$LOCO
[1] FALSE
$condition
[1] ""
$sparseSigmaFile
[1] ""
$groupFile
[1] ""
$kernel
[1] "linear.weighted"
$method
[1] "optimal.adj"
$weights.beta.rare
[1] "1,25"
$weights.beta.common
[1] "1,25"
$weightMAFcutoff
[1] 0.01
$r.corr
[1] "0"
$IsSingleVarinGroupTest
[1] FALSE
$cateVarRatioMinMACVecExclude
[1] "0.5,1.5,2.5,3.5,4.5,5.5,10.5,20.5"
$cateVarRatioMaxMACVecInclude
[1] "1.5,2.5,3.5,4.5,5.5,10.5,20.5"
$dosageZerodCutoff
[1] 0.2
$IsOutputPvalueNAinGroupTestforBinary
[1] FALSE
$IsAccountforCasecontrolImbalanceinGroupTest
[1] TRUE
$weightsIncludeinGroupFile
[1] FALSE
$IsOutputBETASEinBurdenTest
[1] FALSE
$help
[1] FALSE
weights.beta.rare  is  1 25
weights.beta.common  is  1 25
cateVarRatioMinMACVecExclude  is  0.5 1.5 2.5 3.5 4.5 5.5 10.5 20.5
cateVarRatioMaxMACVecInclude  is  1.5 2.5 3.5 4.5 5.5 10.5 20.5
single-variant association test will be performed
192958  samples have been used to fit the glmm null model
obj.glmm.null$LOCO:  FALSE
Leave-one-chromosome-out option is not applied
Single variance ratio is provided, so categorical variance ratio won't be used!
variance Ratio is  0.8427152
193114  sample IDs are found in sample file
[1] 193278      4
[1] "IID"          "IndexInModel" "IndexDose.x"  "IndexDose.y"
192958  samples were used in fitting the NULL glmm model and are found in sample file
sparse kinship matrix is not used
Samples with missing dosages will be dropped from the analysis
Analysis started at  1588179538 Seconds
minMAC:  1
minMAF:  1e-04
Minimum MAF of markers to be tested is  1e-04
isCondition is  FALSE
It is a binary trait
Analyzing  1759  cases and  191199  controls
isCondition is  FALSE
Analysis started at  1588179539 Seconds
Open VCF done
To read the field DS
Number of meta lines in the vcf file (lines starting with ##): 7
Number of samples in in the vcf file: 193114
Variant is missing requested data format type.
closed the genofile!
Analysis ended at  1588179542 Seconds
Analysis took  3.159133 Seconds

### vcf.gz and vcf.gz.tbi files were generated using bcftools and tabix:

> bcftools view -Oz --no-version --threads 40 ${i}.vcf > ${i}.vcf.gz
> tabix -p vcf ${i}.vcf.gz

### Head of the original input files:
> head /scratch/geno/vcf/21.vcf.gz
##fileformat=VCFv4.3
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=20200426
##source=PLINKv2.00
##contig=<ID=21,length=48119635>
##INFO=<ID=PR,Number=0,Type=Flag,Description="Provisional reference allele, may not be based on real reference genome">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  1_4287785       2_4571397       3_1597785       4_3794156       5_5226821       6_4181511       7_2985098       8_590$
21      9574185 rs537417111     C       G       .       .       PR      GT      1/1     1/1     1/1     1/1     1/1     1/1     1/1     1/1     1/1     1/1     1/1     1/1     1/1     1/1  $
21      9660864 rs572757938     A       G       .       .       PR      GT      ./.     0/1     1/1     1/1     1/1     ./.     1/1     ./.     1/1     1/1     1/1     1/1     1/1     1/1  $

> head /scratch/geno/vcf/id
4287785
4571397
1597785
3794156
5226821
4181511
2985098
5900421
2234260
3757050 ...

> head /scratch/saige/out1_21.varianceRatio.txt
0.842715194735574

> head original_step1_output/saige/out1_21_30markers.SAIGE.results.txt
CHR SNPID POS A1 A2 p.value p.value.NA Is.converge var1 var2 N AC AF
21 rs71317630 17238511 T C 0.824945631241943 0.824945631241943 TRUE 0.00841180893595239 0.00876125714285074 192958 9649 0.0250028503612185
21 rs758615407 40880881 CTTGAA C 0.957489551369459 0.957489551369459 TRUE 0.00233112878891263 0.00448451496239141 192958 187456 0.48574301143254
21 rs140999481 43095492 T C 0.476585101019323 0.476585101019323 TRUE 0.00805744906675341 0.00832943708184011 192958 2666 0.00690823909866396
21 rs8129849 22448866 A G 0.540057200365741 0.540057200365741 TRUE 0.0155721292407171 0.0158680010250071 192958 709 0.00183718736719908 ...

### inside .rda file:

> df <- load("./test/out1_21.rda")
> dim(df)
NULL
> df
[1] "modglmm"
> summary(df)
   Length     Class      Mode
        1 character character
> modglmm$coefficients
                     [,1]
(Intercept) -3.5385427480
AGE         -0.0133970235
UKBL         0.3868877815
MALE        -1.9488836293
PC1          0.0006369664
PC2          0.0029986328
PC3          0.0122692414
PC4          0.0003426195 ....

Thank you for your help!!

**Comment by giorkala** [comment]
Hello
I think you ask SAIGE to process dosages but your VCF file contains genotypes. 
I assume "--vcfField=GT" might solve your issue.
Kind regards,
Yiorgos

**Comment by weizhouUMICH** [comment]
That's a good catch! Thanks Yiorgos!

**Comment by vivek-verma202** [comment]
Yes, that fixed my problem. Thank you so much!
