### ISSUE TITLE
covariates

### ISSUE THREAD

**Issue by wuyeda** [weizhouUMICH/SAIGE#18]
To whom it may concern,

I'd like to ask that when we run GWAS using SAIGE, do we need to fit PCs as covariates since SAIGE calculated GRM itself?

Best wishes,
Yeda

**Comment by weizhouUMICH** [comment]
Hi Yeda, 
PCs are still needed as covariates to account for population stratifications.
Thanks,
Wei

**Comment by wuyeda** [comment]
Hi Wei,

Thanks for that. I have another question. You mentioned that M is the pruned markers used for estimating the genetic relationship matrix. I would like to know when you pruned the markers, what kind of parameters did you set to get 93, 511 markers?

Best wishes,

Yeda

**Comment by weizhouUMICH** [comment]
Hi Yeda, 

The 93,511 markers are markers included by the UK Biobank for kinship estimation. The standard used for the selection can be found in this paper 

https://www.biorxiv.org/content/early/2017/07/20/166298

Thanks,
Wei
