### ISSUE TITLE
Possible LOCO issue with BGEN input

### ISSUE THREAD

**Issue by Ojami** [weizhouUMICH/SAIGE#180]
Dear Wei,

I noticed the following error when applying `LOCO` flag to input BGEN files (separate files for each chromosome) for step 2. I didn't get this error when trying VCF input (with all chromosomes being in the same file). 

> "single-variant association test will be performed
> 1790  samples have been used to fit the glmm null model
> Single variance ratio is provided, so categorical variance ratio won't be used!
> variance Ratio is  1 
> 434601  sample IDs are found in sample file
> [1] 434601      4
> [1] ""IID""          ""IndexInModel"" ""IndexDose.x""  ""IndexDose.y"" 
> 1890  samples were used in fitting the NULL glmm model and are found in sample file
> sparse kinship matrix is not used
> Samples with missing dosages will be dropped from the analysis
> Analysis started at  1588417686 Seconds
> minMAC:  3 
> minMAF:  0 
> Minimum MAF of markers to be tested is  0.0008379888 
> isCondition is  FALSE 
> It is a binary trait
> Analyzing  796 cases and  1094  controls 
> Error in obj.glmm.null$LOCOResult[[chrom_v3]] : 
>   attempt to select less than one element in get1index <real>
> Calls: SPAGMMATtest
> Execution halted
> "

Does this have something to do with reading dosage data from separate files?
Thanks!
Best/Oveis

**Comment by weizhouUMICH** [comment]
HI Oveis, 
Thanks for reporting this error. It may be because the "chrom_v3" is not among 1 to 22. What is the value of the specified "chrom" in your script? 

Thanks,
Wei

**Comment by Ojami** [comment]
Hi Wei,

You are right, I set to "0" and that's the source of error, when I change it to chromosome being tested it's resolved.
however, I don't understand why SAIGE took "chrom_v3" as chromosome? 

Best/Oveis

**Comment by weizhouUMICH** [comment]
Hi Oveis, 

It takes chrom as input and convert it to number 1-22 so the LOCO model results from step 1 for that chromosome can be extracted. If chrom is not specified, the program needs to find out chromosome for each marker first and then extract the LOCO result, which cost additional computation time.   
https://github.com/weizhouUMICH/SAIGE/blob/master/R/SAIGE_SPATest.R#L489

Thanks,
Wei
