### ISSUE TITLE
SAIGE (038) newest version tar.gz file

### ISSUE THREAD

**Issue by yanhuaumich** [weizhouUMICH/SAIGE#181]
Do you have SAIGE_038 version of linux tar.gz file? Some version have, but some version does not. Could you published on website if possible?

Thanks.

**Comment by weizhouUMICH** [comment]
Just uploaded the binary file for v0.38. Thanks!

**Comment by Esther19960123** [comment]
> Do you have SAIGE_038 version of linux tar.gz file? Some version have, but some version does not. Could you published on website if possible?
> 
> Thanks.

Could you find the SAIGE version 0.38 eventually? And how about sharing the location with me ?
