### ISSUE TITLE
GC Lambda < 1

### ISSUE THREAD

**Issue by vivek-verma202** [weizhouUMICH/SAIGE#183]
Hi!
Thank-you for SAIGE!

I have noticed that it is not uncommon to get GC lambda values below 1 with SAIGE results, especially in cases of severe case:control imbalance. 

Is something wrong with my results if lambda < 1?
Should I correct p-values to artificially fix lambda to 1?

Thanks.

**Comment by weizhouUMICH** [comment]
Hi Vivek, 

When case:control ratio is very unbalanced,  the allele copies in cases for relatively rare variants can be low and the association tests lack of power for those variants, so we usually see deflation in the bottom left corner in the QQ plot. For example, the thyroid cancer GWAS in the UK Biobank http://pheweb.sph.umich.edu/SAIGE-UKB/pheno/193

You can see the GC lambda at percentile 0.5 is quite inflated as most of the imputed variants are less frequent one, so we usually look at the GC lambda at different percentiles, e.g. 0.01, 0.001. 

Thanks,
Wei

**Comment by vivek-verma202** [comment]
I thought so, Thanks a lot!
