### ISSUE TITLE
multiallelic variants

### ISSUE THREAD

**Issue by olszewskip** [weizhouUMICH/SAIGE#187]
Hi!
Apologies if this is answered elsewhere, but I was hoping You can clarify for me the following matter:
How are multiallelic variants handled by Saige?
1) Are they split into several binary REF vs ALT# tests?
2) Are the alternative alleles aggregated in a given variant before fitting?
3) Or maybe each alternative allele of a variant has its own \beta# coefficient in the regression, and the returned p-value is associated with null hypothesis that all of those \betas are equal to zero?

**Comment by olszewskip** [comment]
Found the answer in the Wiki:
"SAIGE/SAIGE-GENE uses the savvy library to handle VCF files. For the multi-allelic variants, genotypes/dosages for all alt alleles in one line in VCF files is not supported. The best solution is to split the variants by alleles".
My bad, and thank You.

**Comment by weizhouUMICH** [comment]
Sorry for my late response!  Great you've figure it out by yourself:)
