### ISSUE TITLE
ERROR! The first variance component parameter estimate is 0 (with InvNormalize TRUE or FALSE)

### ISSUE THREAD

**Issue by msarguru** [weizhouUMICH/SAIGE#190]
Dear Wei,
The errors occurs with and without the inverse normalization being TRUE.
In my case the sample size is 1350, while a phenotype with lower sample size (n=800) ran just fine. Many thanks in advance for your insight.
The raw values of the trait of our interest is normally distributed, with the skewness value approaching close to 0

**Comment by weizhouUMICH** [comment]
Dear @msarguru, 

Would you mind sharing the log file? 

Thanks,
Wei

**Comment by msarguru** [comment]
Dear Wei,

Please find it attached. Many thanks again !!!

Regards
Murali
[error.variance.log](https://github.com/weizhouUMICH/SAIGE/files/4645492/error.variance.log)

**Comment by weizhouUMICH** [comment]
Dear Murali, 

Thank you for sharing the log file! I haven't been able to identify any obvious reason for this error from the log yet. My guess is that one or two covariates can explain very large proportion of variance of y (e.g. icv and age2) and the residuals becomes not normally distributed. BTW, for sample size N=1703, you don't need to use 11 million variants for the GRM in step 1. 10,000 pruned variants will be sufficient.

Thanks,
Wei

**Comment by msarguru** [comment]
Dear Wei,

Removing the covariate does not solve the error, it fails pretty much for the all the combinations of covariates. I could not think of any other issue, the raw untransformed phenotype is already normally distributed. 
Please find attached log file for one that successfully runs and the other that doesn't. 
Any suggestions would be greatly appreciated. 

Thanks
Murali


[success.run.txt](https://github.com/weizhouUMICH/SAIGE/files/4837436/success.run.txt)
[failure.run.txt](https://github.com/weizhouUMICH/SAIGE/files/4837438/failure.run.txt)

**Comment by nerdybo** [comment]
I had the same issue when trying to run step1_fitNULLGLMM.R. I did not include any covariates at all and it still failed.

_My command looks like this:_
    Rscript ~/dependencies/saige/SAIGE/extdata/step1_fitNULLGLMM.R     \
      --plinkFile=ccls."${SET}"."${RACE}" \
      --phenoFile=saige.pheno."${SET}"."${RACE}".step1.txt \
      --phenoCol=phenotype \
      --sampleIDColinphenoFile=IID \
      --traitType=quantitative \
      --invNormalize=TRUE	\
      --outputPrefix=ccls."${SET}"."${RACE}".step1 \
      --nThreads=400 \
      --LOCO=FALSE	\
    	--tauInit=1,0 \
    	--IsOverwriteVarianceRatioFile=TRUE

_The error message looks like this:_
Variance component estimates:
[1] 0.0000000 0.9738852
Fixed-effect coefficients:
             [,1]
[1,] -0.002296607
Error in glmmkin.ai_PCG_Rcpp_Quantitative(plinkFile, fit0, tau = c(0,  :
  ERROR! The first variance component parameter estimate is 0
Calls: fitNULLGLMM -> system.time -> glmmkin.ai_PCG_Rcpp_Quantitative

**Comment by xiekunwhy** [comment]
Hi,

I had the same issue when trying to run step1_fitNULLGLMM.R. 

Best,
Kun

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
