### ISSUE TITLE
Error for number of samples not matching for conditional analysis

### ISSUE THREAD

**Issue by sarahgra** [weizhouUMICH/SAIGE#192]
I'm trying to run a conditional analysis for single-variant analysis in step 2.  I keep running into "ERROR! The number of samples specified in the sample file does not equal to the number of samples in the VCF file".  Is SAIGE expecting that the vcf will be subset to individuals used for step 1 when doing conditional analysis?
This works fine if I'm not adding the conditional analysis option

Version: SAIGE_0.38

Number of samples in the vcf file: 487409
487409  sample IDs are found in the vcf file
[1] 487409      4
[1] "IID"          "IndexInModel" "IndexDose.x"  "IndexDose.y"
388629  samples were used in fitting the NULL glmm model and are found in sample file
sparse kinship matrix is not used
Missing dosages will be mean imputed for the analysis
Analysis started at  1590066523 Seconds
minMAC:  3
minMAF:  0
Minimum MAF of markers to be tested is  3.859722e-06
conditionlist is  condMarkers   1:55505647_G/T
std::size_t sample_size = marker_file.samples().size();487409
conditioning on  1:55505647_G/T
isCondition is  TRUE
It is a quantitative trait
isCondition is  TRUE
Analysis started at  1590066551 Seconds
Error in SPAGMMATtest(vcfFile = opt$vcfFile, vcfFileIndex = opt$vcfFileIndex,  :
  ERROR! The number of samples specified in the sample file does not equal to the number of samples in the VCF file
Please check again. Please note that the sample file needs to have no header.
Execution halted

**Comment by weizhouUMICH** [comment]
Hi Sarah, 

This must an error newly appears in 0.38 for vcf input. 
I will fix the bug in a new version today. To quickly run the conditional analysis, please use v0.37. 

Thanks,
Wei

**Comment by davideurac** [comment]
Hi Wei,  Do you have an eta for this bug fix?  We just installed v0.38 here at Eurac and I'm getting the same error as sarahgra for conditional analysis. I can ask our poor sysadmin to install v0.37 as you recommend, but don't want to turn around and ask him to install a newer version -- don't want to make him mad at me!  ;)    Many thanks, -David

**Comment by weizhouUMICH** [comment]
Hi @davideurac, 
I'm working on it now. Sorry for the delay...

Wei

**Comment by weizhouUMICH** [comment]
Hi @sarahgra and @davideurac, 
Please try 0.39, which has the error fixed. 

Thanks!
Wei
