### ISSUE TITLE
Error in setgenoTest_bgenDosage_v2(bgenFile, bgenFileIndex, ranges_to_exclude = ranges_to_exclude

### ISSUE THREAD

**Issue by Qiaolan** [weizhouUMICH/SAIGE#193]
Hi Wei,

Thanks for your time.

I got the error message below when I do saige-gene analysis:

`Error in setgenoTest_bgenDosage_v2(bgenFile, bgenFileIndex, ranges_to_exclude = ranges_to_exclude`

An interesting thing is that if I use first 100 snps in the group file, there would be no error.
In total, I have about 18000 snps in the group file.

My code is below:

Rscript /fs/ess/PAS1501/gaolab/software/saige/SAIGE/extdata/step2_SPAtests.R \
--bgenFile=/fs/ess/PAS1501/gaolab/qldeng/Eden/saige/chr${N}/${x}/saige_chr${N}_${x}.bgen \
--bgenFileIndex=/fs/ess/PAS1501/gaolab/qldeng/Eden/saige/chr${N}/${x}/saige_chr${N}_${x}.bgen.bgi \
--sampleFile=/fs/ess/PAS1501/gaolab/qldeng/Eden/saige/chr${N}/${x}/sample_ID.txt \
--GMMATmodelFile=/fs/ess/PAS1501/gaolab/qldeng/Eden/saige_gene_chr19/chr${N}/${x}/chr${N}_${x}_nullmodel.rda   \
--varianceRatioFile=/fs/ess/PAS1501/gaolab/qldeng/Eden/saige_gene_chr19/chr${N}/${x}/chr${N}_${x}_varianceRatio.txt.varianceRatio.txt \
--SAIGEOutputFile=/fs/ess/PAS1501/gaolab/qldeng/Eden/saige_gene_chr19/chr${N}/${x}/output_saige_chr${N}_${x}.txt \
--numLinesOutput=1 \
--groupFile=/fs/ess/PAS1501/gaolab/qldeng/Eden/saige_gene_chr19/chr${N}/${x}/tab_group_splicing_exonic_chr${N}_${x}.txt \
--sparseSigmaFile=/fs/ess/PAS1501/gaolab/qldeng/Eden/saige_gene_chr19/chr${N}/${x}/chr${N}_${x}_varianceRatio.sparseSigma.mtx \
--IsOutputAFinCaseCtrl=TRUE 

Thank you!

Qiaolan

**Comment by Ojami** [comment]
Just a thought. As I ran into a [similar problem](https://github.com/weizhouUMICH/SAIGE/issues/178), it maybe because of duplicate variants in you BGEN files (if you use idstoIncludeFile flag).
Otherwise, if you use rangestoIncludeFile flag, the maximum range you can set it 9999.

Hope it helps! /Oveis

**Comment by weizhouUMICH** [comment]
Thanks @Ojami !
@Qiaolan That's also my guess. Could you please try to see if there are any duplicated variant IDs among the 1800 variants in the variant set? 

Thanks,
Wei

**Comment by Qiaolan** [comment]
Thank you, @Ojami and @weizhouUMICH ! I will have have a try today and keep you updated.

**Comment by Qiaolan** [comment]
I sill had the same error message after I removed duplicated snps in my bgen file.

For example, for gene PSG1:

geneID:  PSG1  
[1] "PSG1 \t19:43375918\t19:43375918"
genetic variants with  0.0002944641 <= MAF <=  0.5 are included for gene-based tests
[1] "ids_to_include"
[1] "19:43375918" "19:43375918"
TEST 2
TEST 1 OK
TEST2 2
ranges_to_include.nrow() 0
ranges_to_exclude.nrow() 0
ids_to_include.size() 2
ids_to_exclude.size() 0
Error in setgenoTest_bgenDosage_v2(bgenFile, bgenFileIndex, ranges_to_exclude = ranges_to_exclude,  : 
  db::StatementStepError
Calls: SPAGMMATtest -> getGenoOfGene_bgen -> setgenoTest_bgenDosage_v2
Execution halted


Initially, 19:43375918 had duplicates in the bgen file. After I removed duplicates, I still got the error above.

Thanks for your help! @weizhouUMICH  @Ojami

**Comment by Qiaolan** [comment]
Problem has been solved. I also need to modify my group file. Thank you anyway!
