### ISSUE TITLE
Ordinal categorical phenotypes

### ISSUE THREAD

**Issue by SiyangLiu** [weizhouUMICH/SAIGE#195]
Hi Wei,
Thanks for the very useful software. 
Does saige allows association test for ordinal, categorical phenotypes for example like disease status (undiagnosed, pre-disease, mild, moderate, severe)? Any suggestions on how to deal with this kind of phenotype?

**Comment by weizhouUMICH** [comment]
Hi @SiyangLiu, 

SAIGE can't analyze ordinal categorical phenotypes yet, but a colleague of mine from the Lee group is developing this feature. 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! 
Feel free to try POLMM for categorical phenotypes. 
https://github.com/WenjianBI/POLMM

We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
