### ISSUE TITLE
Whether or not to include PCs as covariates

### ISSUE THREAD

**Issue by SiyangLiu** [weizhouUMICH/SAIGE#196]
Hi Wei,
For cohorts that include family members, the PCs will always reflect their relatedness. In this case, should we include PCs as fixed effects in the linear mixed model? What if we don't include PCs - will this lead to inflation?

**Comment by weizhouUMICH** [comment]
Hi @SiyangLiu, 

I would still recommend including PCs to account for sample relatedness/population stratifications as fixed effects. 

Thanks,
Wei

**Comment by ttbek** [comment]
@SiyangLiu You can separate them to some with techniques like PC-Air.  This works by calculating a GRM, e.g. with KING, then using it to identify related/unrelated individuals and getting the PCs from only the unrelated subset.  
https://pubmed.ncbi.nlm.nih.gov/25810074/

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
