### ISSUE TITLE
Problem in AF value 

### ISSUE THREAD

**Issue by NewtonLeibniz** [weizhouUMICH/SAIGE#197]
Hi, Wei.
Thanks for the SAIGE,it helps a lot!
I set a task for each chromsome,some chromosomes finished running normally, but some stopped.The problem stopped the mission only while running SAIGE.It is normal in running SAIGE-GENE.
the error message as follows:
         _Error in if (AF > 0.5) { : missing value where TRUE/FALSE needed
         Calls: SPAGMMATtest
         Execution halted_ 
I also checked the vcf file(joint-calling).In some position,AF=1.
I want to determine if this is the cause of the error.
How can I avoid this problem?

Thanks again!
RongLiu

**Comment by weizhouUMICH** [comment]
Hi RongLiu, 
Thank you very much for reporting this issue and tracking down the problematic variants. 
SAIGE is supposed to drop the monomorphic variants automatically. 
Which version of SAIGE are you using? Would you mind sharing the log file? 

Thanks,
Wei

**Comment by NewtonLeibniz** [comment]
Hi Wei,
Thanks  for your response!
The version of SAIGE is SAIGE_0.36.3.1,and I will provide two sets of log files(including almost all situations), including successful tasks(chr8) and failed tasks(chr7). They use the same parameters to run chromosomes 7 and 8, respectively. the files are as follows:

failed task(chr7)
[SRe_00007.e.log](https://github.com/weizhouUMICH/SAIGE/files/4707039/SRe_00007.e.log)
[SRe_00007.o.log](https://github.com/weizhouUMICH/SAIGE/files/4707040/SRe_00007.o.log)
successful task(chr8)
[SRe_00008.e.log](https://github.com/weizhouUMICH/SAIGE/files/4707041/SRe_00008.e.log)
[SRe_00008.o.log](https://github.com/weizhouUMICH/SAIGE/files/4707042/SRe_00008.o.log)

Another situation is that I also found the position of AF = 1 in the vcf file of chromosome 8, so this may not be the main reason for the error, but it should still be relevant.

Thanks again!
RongLiu

**Comment by weizhouUMICH** [comment]
Hi RongLiu, 

Thank you so much for sharing the log files and the error files. 
It seems an issue reported before and should have been fixed in the current version 
https://github.com/weizhouUMICH/SAIGE/issues/154

Could you please try the most current version? 

Thanks!
Wei

**Comment by NewtonLeibniz** [comment]
Hi Wei,
Thanks for response.

I tried to install the current version of SAIGE(ubuntu 18.04.4), but there was such an error at the end of the installation, such as the log file content:
[error.install.log](https://github.com/weizhouUMICH/SAIGE/files/4774710/error.install.log)
The way I install SAIGE is through the command: R CMD INSTALL SAIGE

Am I missing something? Or have you encountered similar problems?

Many Thanks！

RongLiu

**Comment by weizhouUMICH** [comment]
Sorry for my late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
