### ISSUE TITLE
issues about result comparision between SAIGE029 and SAIGE038

### ISSUE THREAD

**Issue by yanhuaumich** [weizhouUMICH/SAIGE#198]
Hi, Wei zhou,
I applied SAIGE029 (used >1 year) and SAIGE038 (just updated > 2 weeks) to do single-variant association tests for same input data/same parameters. 

I found that the different result between them for same snp, for example:
 (1) SAIGE029
CHR | POS | SNPID | Allele1 | Allele2 | AC_Allele2 | AF_Allele2 | N | BETA | SE | Tstat | p.value | p.value.NA | Is.SPA.converge | varT | varTstar | AF.Cases | AF.Controls
22 | 44324730 | 22:44324730:C:T | C | T | 23823.63 | 0.231073 | 51550 | 0.479813 | 0.033382 | 3.031864 | 7.60E-47 | 9.27E-51 | 1 | 0.040939 | 0.041374 | 0.309147 | 0.226218

(2) SAIGE038
CHR | POS | SNPID | Allele1 | Allele2 | AC_Allele2 | AF_Allele2 | N | BETA | SE | Tstat | p.value | p.value.NA | Is.SPA.converge | varT | varTstar | AF.Cases | AF.Controls
22 | 44324730 | 22:44324730:C:T | C | T | 23823.63 | 0.231073 | 51550 | 0.475135 | 0.033489 | 459.8593 | 1.09E-45 | 1.93E-49 | 1 | 967.8508 | 989.4332 | 0.309147 | 0.226218

My questions are as follows:
(A) p.value and p.value.NA in SAIGE038 is higher than SAIGE029. 
It seems that the newer version provides more conservative pvalues.  is it because new version applied SPA3.0.2, but older version applied SPA3.0.0 ?

(B) The other values are similar, except 3 columns: Tstat, varT, and varTstar. 
Why there is big difference between two versions (for example, Tstat_new=23823.63 and Tstat_old=3.031864)? Is it the formula changed for 3 values calculation? 

Yanhua

**Comment by weizhouUMICH** [comment]
Hi Yanhua, 
The Tstat and varT on the two different versions were on different scales and v0.29 is scaled by AC. Tstat in 0.29 = Tstat in 0.38/sqrt(AC) and varT in 0.29 = varT in 0.38/AC, so the beta and se are all on the same scales using the two different versions. 

I don't think the SPA test changes much. One different in the 0.38 version is that for GRM, minMAFforGRM = 0.01 (by default) was used in 0.38 so only common variants from the plink file was used for GRM. 

Could you please check the log file to see if different number of markers were used for step 1? 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
