### ISSUE TITLE
Relatedness matrix,

### ISSUE THREAD

**Issue by vinodhsri** [weizhouUMICH/SAIGE#199]
Hi,

I am working on a cohort with 350k individuals and performing Step 1: fitting the null logistic mixed model part of single-variant module, is time taking and memory bound too. My cohort can be considered unrelated and for that reason is an expedited way of fitting the null logistic model
and not worry about the relatedness matrix.

thanks

**Comment by weizhouUMICH** [comment]
Hi @vinodhsri, 

If there is no sample relatedness in your data set and would like to account for unbalanced case control ratios, you may consider turn the SPA test directly, which has been implemented in EPACTS https://genome.sph.umich.edu/wiki/EPACTS
(b.spa2) 

Thanks,
Wei

**Comment by vinodhsri** [comment]
Thanks Wei. That's exactly what i am doing now, but also stuck with a road block invoking spa2 in EPACTS

When running epacts single-varaint spa2 module, i am hitting a road block. Any pointers will be helpful. Here is the EPACTS error message:


******************************************************

Detected phenotypes with 2 unique values - 0 and 1 - considering them as binary phenotypes... re-encoding them into 1 and 2

Successfully written phenotypes and 11 covariates across 294694 individuals

Processing chromosome 7...

Loading required package: epactsR

Loading required package: epactsR

Loading required package: epactsR

Loading required package: epactsR

Loading required package: epactsR

Error in obj.SA.null$XV %*% G : non-conformable arguments

Calls: func -> ScoreTest_wSaddleApprox_NewNR

Execution halted

make: *** spa2/test_output_file_chr7.7.114200000.120000000.epacts] Error 1

Error in running make -f spa2/test_output_file_chr7.Makefile -j 10. Exit code is 2

**Comment by weizhouUMICH** [comment]
I see. The implementation of spa test in EPACTS might not have been updated using the newest version of SPA test. This error might be due to some singletons or extremely rare variants. Could you please try increase the allele frequency cutoff?

**Comment by vinodhsri** [comment]
I have set my min-maf to be 1%, yet get the same error

epacts single --vcf chr7.vcf.gz --ped pheno_final_v2.ped --min-maf 0.01 --pheno bin_pheno --cov age --cov sex_recode --cov PC1 --cov PC2 --cov PC3 --cov PC4 --cov PC5 --cov PC6 --cov PC7 --cov PC8 --out spa2/$2_output_file_chr$1 --test b.spa2 --run 10


Loading required package: epactsR
Loading required package: epactsR
Loading required package: epactsR
Loading required package: epactsR
Loading required package: epactsR
Error in obj.SA.null$XV %*% G : non-conformable arguments
Calls: func -> ScoreTest_wSaddleApprox_NewNR
Execution halted

**Comment by weizhouUMICH** [comment]
Sorry for my late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
