### ISSUE TITLE
Can't open archive

### ISSUE THREAD

**Issue by jhchung** [weizhouUMICH/SAIGE#2]
I saw your poster at ASHG and I'd like to try out SAIGE, but can't seem to open the archive. When I try running gunzip, it returns an error that the file is not in gzip format.

Thanks,
-Jonathan

**Comment by weizhouUMICH** [comment]
Hello Jonathan, 
Could you please try "tar -xzvf SAIGE_0.1.tar.gz"? 
Thanks,
Wei

**Comment by jhchung** [comment]
Ok. Seems to work now. I also tried just downloading the tarball before rather than cloning the project.

Thanks
