### ISSUE TITLE
Running SAIGE genome wide?

### ISSUE THREAD

**Issue by zd1** [weizhouUMICH/SAIGE#20]
Hi there, 

The "--chrom=" argument is mandatory at the moment for step2_SPAtests.R. For some of my tasks this means I need to break my input vcf down by chroms, which is good for large vcfs but not so much for small vcfs. I was wondering if you would have a version that simply scans through an input vcf? 

Many thanks,
Zhihao

**Comment by mjsduncan** [comment]
you don't have to subset the input vcf by chromosome.  i have successfully run `SPAGMMATtest` in parallel by chromosome from one whole genome vcf:
```
library(foreach)
library(doParallel)
registerDoParallel(8)
autosomeSaigeOut <- foreach(i = c(1:22), .combine = "rbind")  %dopar% {
  SPAGMMATtest(
    vcfFile="whole/genome.vcf.gz",
    vcfFileIndex="whole/genome.vcf.gz.csi",
    vcfField="GT",
    chrom=as.character(i),
    start=1,
    end=2.5e+08,
    ...
    SAIGEOutputFile=paste0("saigeChr", i, ".out"),
    ...)
```
hope that helps!
