### ISSUE TITLE
Error in if (MAF >= testMinMAF & markerInfo >= minInfo)

### ISSUE THREAD

**Issue by Qiaolan** [weizhouUMICH/SAIGE#201]
Hi Wei,

I got the following error in step 2 of single variant analysis:

numPassMarker:  283 
Error in if (!(markerInfo >= 0 & markerInfo <= 1)) { : 
  missing value where TRUE/FALSE needed
Calls: SPAGMMATtest
Execution halted

I have 22 chromosomes to analyze. Only chr22 ran successfully, the rest 21 chrs failed. I used saige for many times in the past and it was the first time I got this error.

I checked previous issues and found that this might be related to .bgen file. However, I followed the same procedure to process .bgen, which transformed the plink file to .bgen file. The codes are below:

# plink to .bgen
`plink2 --bfile ${path2}/chr${N}/ukb_exome_chr${N} --export bgen-1.2 bits=8 --out ${path2}/chr${N}/ukb_exome_chr${N}`

# generate .bgen.bgi
`bgenix -g ${path2}/chr${N}/ukb_exome_chr${N}.bgen -index`

Thanks for your help!

**Comment by weizhouUMICH** [comment]
Hi @Qiaolan, 

Sorry for my late reply!. Thanks for reporting the error!
I'm very happy to help!
Would you mind sharing more details about the jobs with error? Are there samples with missing dosages? Is the entire bgen file being test or a query file is used? 

Thanks!
Wei

**Comment by Qiaolan** [comment]
> Hi @Qiaolan,
> 
> Sorry for my late reply!. Thanks for reporting the error!
> I'm very happy to help!
> Would you mind sharing more details about the jobs with error? Are there samples with missing dosages? Is the entire bgen file being test or a query file is used?
> 
> Thanks!
> Wei

Thank you @weizhouUMICH. The problem has been solved by quality control. I think the snps causing the error were removed and now there is no error.
