### ISSUE TITLE
Error on step 2 of SAIGE-Gene

### ISSUE THREAD

**Issue by oalavijeh** [weizhouUMICH/SAIGE#203]
Dear Wei, 

Firstly, congratulations on the Nature Genetics paper! 

I am using SAIGE-Gene and have created a GRM and fit the null model on set of case/controls. 

When running the SPAGMMATtest it starts running and then stops on the same gene in the group file with the error:

- Error in Matrix : ::sparseMatrix(i = as.vector(Gx$iIndex), j = as.vector(Gx$jIndex), : all(dims >= dims.min) is not TRUE. 

Again I'm afraid I can't share the full code as I work in an airlock environment. I suspect the issue is in the groupfile but I'm not sure. 

Many thanks 

O

**Comment by weizhouUMICH** [comment]
Thank you @oalavijeh
Are there duplicated marker IDs in the group file?

**Comment by oalavijeh** [comment]
Dear @weizhouUMICH ,

I don't think there are, the error is at a specific gene in the group file, although the gene sometimes varies. In full:

- gene ID: AC239809.3
std::size_t sample_size = marker_file.samples().size();8479
missing_cnt >0!
missing_cnt >0!
missing_cnt >0!
missing_cnt >0!
cntMarker: 4
Error in Matrix: : : : sparseMatrix(i = as.vector(Gx$iIndex), j = as.vector(Gx$jIndex), : all(dims >= dims.min) is not TRUE.
In addition: Warning message: 
In .Internal(gc(verbose, reset, full)) : 
closing unused connection 4 (./group_files/group_file_chr1.txt) 


- Looking at the gene line in the group file there are 4 variants none of which are repeated, the format is chr:start_ref/alt 

Many thanks

**Comment by weizhouUMICH** [comment]
Sorry for my late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
