### ISSUE TITLE
Meta-analysis of gene-based tests for binary traits across different cohorts using SAIGE

### ISSUE THREAD

**Issue by seanjosephjurgens** [weizhouUMICH/SAIGE#205]
Hi!

Thanks for developing this amazing tool for genetic analysis in large cohorts. I was wondering if you are planning to implement a meta-analysis function for gene-based analyses that can account for case control imbalance for binary traits. We are dealing with multiple large cohorts with WGS/WES that cannot be merged for an omnibus analysis. We would love to be able to run SAIGE-GENE separately in each cohort and meta-analyze. Is this possible?

**Comment by weizhouUMICH** [comment]
Hi @seanjosephjurgens, 

Thank you for the comments! It is possible to implement the meta-analysis for gene-based test based on the MetaSKAT R package. I agree that this feature will be quite useful and will aim to incorporate the feature in the package within a couple of months. 

Thanks,
Wei

**Comment by seanjosephjurgens** [comment]
Thanks @weizhouUMICH,

I look forward to the implementation of this feature in the future. For now I have been looking at your methods, code and the documentation of MetaSKAT to try and apply meta-analysis myself.  I was wondering if you could tell me whether I understand some of the following things correctly.

In gene-based tests you correct for case-control imbalance by computing an adjusted phi, while  variant score statistics are left unchanged. Does this mean that I can't just simply feed score statistics (from SAIGE-GENE) and variant covariance information into MetaSKAT, as correction for case-control imbalance will be lost, am I correct? Is there a way to incorporate adjustment for case-control imbalance from individual studies into MetaSKAT?

I appreciate all the hard work that went into this package and thanks again,

Sean

**Comment by weizhouUMICH** [comment]
Sorry for my late reply! 
We plan to implement the metaSKAT feature in SAIGE-GENE next. 

We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
