### ISSUE TITLE
Error: No queried variant is found in the bgen file

### ISSUE THREAD

**Issue by Qiaolan** [weizhouUMICH/SAIGE#206]
Hi @weizhouUMICH ,

I saw your new paper, congratulations!

I get the error below in the step 2 of saige gene-based:

`geneID:  SLC37A1  
[1] "SLC37A1 \t21:43959666\t21:43959714"
genetic variants with  6.052829e-06 <= MAF <=  0.5 are included for gene-based tests
[1] "ids_to_include"
[1] "21:43959666" "21:43959714"
TEST 2
TEST 1 OK
TEST2 2
ranges_to_include.nrow() 0
ranges_to_exclude.nrow() 0
ids_to_include.size() 2
ids_to_exclude.size() 0
No queried variant is found in the bgen file! All variants bgen file will be analyzed
Mtest:  0 
closed the genofile!
cntMarker:  0 
[1] "No samples are left after removing samples with missing dosages/genotypes of variants in the gene"
closed the genofile!`

However, snp 21:43959666 is actually in my bgen file:

`-bash-4.2$ grep 21:43959666 *`
`Binary file ega_exome_chr21.bgen matches`
`Binary file ega_exome_chr21.bgen.bgi matches`
`ega_exome_chr21.bim:21	21:43959666:G:A	0	43959666	A	G`

Do you know why I got this error? Thanks!

**Comment by Ojami** [comment]
Just a thought: min/maj alleles missing?
e.g. it is supposed to be in the following format:

`SLC37A1  121:43959666_G/A`

Best/Oveis
