### ISSUE TITLE
Gene-based tests: sites used for step 0 and step 1

### ISSUE THREAD

**Issue by kousathanas** [weizhouUMICH/SAIGE#207]
Hi @weizhouUMICH

in your faq for gene-based tests you mention that the same sites have to be used for step 0 and step 1. I wanted to ask if its possible to use a set of common SNPs (maf>0.01) for step 0 and then add rare SNPs to those for step 1 as separate plink files. 
As far as I understand your method, variance ratios are calculated when the null model with random effects + covariates are fitted (step 1). So am I right to assume that the output of step0 wouldn't be affected if a plink file with common-only variants is used (as this filter is already there, default>0.01)?

best,
Thanos

**Comment by weizhouUMICH** [comment]
Hi Thanos, 

That's good question. It is ok to to add rare variants in step 1 in the plink file. 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
