### ISSUE TITLE
Python 3.6 compatibility

### ISSUE THREAD

**Issue by tbrunetti** [weizhouUMICH/SAIGE#208]
Hello,

I am installing SAIGE and one of the issues is installing bgen and not being compatible wiht python 3.6 and above.  I can liftover the code myself, but just for future builds would it be possible to liftover the github master branch to pyton 3.6 and above?  Python 2 and lower versions of 3.5 are to be deprecated at the end of the year.

Thanks

**Comment by weizhouUMICH** [comment]
Hi @tbrunetti, 

Sorry for my late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The new version does not depend on the bgen library. 
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
