### ISSUE TITLE
ambiguous text in the wiki

### ISSUE THREAD

**Issue by cburik** [weizhouUMICH/SAIGE#210]
Hi, 

I had a small question. I received GWAS results from an analyst that told me their info scores were calculated by SAIGE. 

Now I've read in the wiki:

"imputationInfo: imputation info. If not in dosage/genotype input file, will output 1"

I was wondering if SAIGE calculates the imputationInfo, or if it just outputs "1" for each SNP that has missing info scores. And if it calculates the imputationInfo, whether it's comparable to MaCH or IMPUTE2 or something else? 

best,

Casper

**Comment by weizhouUMICH** [comment]
Hi Casper, 

Sorry for the ambiguous. 
For bgen files with haplotype probabilities, SAIGE calculates the imputation score in the same way as IMPUTE2
For VCF and SAV files, SAIGE extract the R2 value in the info field as output by MaCH. 
If there is no R2 value, the imputationInfo will be 1. 

Thanks
Wei

**Comment by cburik** [comment]
Thank you!

**Comment by cburik** [comment]
Hi Wei, 

I've dug a little bit deeper into our data (inputted as bgen files) and it turns out that for a couple SNPs, with very low imputation accuracy. SAIGE output's a "1" while in previous software it those SNPs were rounded down to a 0. So maybe there are edge cases where something goes wrong. 

best,

Casper

**Comment by weizhouUMICH** [comment]
Sorry for my late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
