### ISSUE TITLE
Error missing dosages

### ISSUE THREAD

**Issue by jameskozubek** [weizhouUMICH/SAIGE#212]
I received this error at step 2:
ERROR!84950 samples used in glmm model fit do not have dosages
Execution halted

I am running on a SNP chip without dosages. how do I bypass this?

**Comment by weizhouUMICH** [comment]
Hi @jameskozubek, 

Currently SAIGE requires all samples used in glmm model are in the dosage file. It would be ideal if step 1 can be re-run with samples in the dosage file. If you'd like to avoid re-running step 1, you may add the samples who are in glmm model fit to the dosage files and then use --IsDropMissingDosages=TRUE in step 2. 

Thanks,
Wei
