### ISSUE TITLE
A question about multiple chromosome in Step 2(single-variant)

### ISSUE THREAD

**Issue by Jiangyuan-Liu** [weizhouUMICH/SAIGE#214]
Dear Dr. Zhou,

I am wondering if I can use multiple chromosomes in step 2 as shown below.

Thanks,
Jiangyuan

Rscript step2_SPAtests.R \
        --vcfFile=./input/dosage_10markers.vcf.gz \
        --vcfFileIndex=./input/dosage_10markers.vcf.gz.tbi \
        --vcfField=DS \
        **--chrom=1,2,3** \

**Comment by weizhouUMICH** [comment]
Dear @Jiangyuan-Liu, 

No we can't do that for now. I will see if we can make it work soon. 

Thanks,
Wei
