### ISSUE TITLE
Rationale for out-of-bounds BGEN INFO: if(!(markerInfo >= 0 & markerInfo <= 1)){markerInfo=1}

### ISSUE THREAD

**Issue by rkarlssonlinner** [weizhouUMICH/SAIGE#215]
Hi,

What is the rationale behind assigning out-of-bounds BGEN INFO scores a value of 1 in SAIGE_SPATest.R?
Line 676: if(!(markerInfo >= 0 & markerInfo <= 1)){markerInfo=1}

In my opinion, this line is nonsensical as INFO can occasionally take negative values when the imputation is very uncertain.

**Comment by weizhouUMICH** [comment]
That's a good point! I think my original point is that if markerInfo is not applied or applied with some non-meaningful values VCF, we don't apply the cutoff for markerInfo. But it seems it shouldn't be applied to the bgen file. 

I will remove this for bgen file input. 

Thanks,
Wei

**Comment by rkarlssonlinner** [comment]
Thanks, Wei.

Could you point me to the code underlying the function getMarkerInfo()?

Also, I would suggest that if markerInfo is somehow missing from VCF, why not assign a value of NA and change the condition to something like:
`if(MAF >= testMinMAF & (markerInfo >= minInfo | is.na(markerInfo))`
simply to avoid forcing a value to a parameter that is actually missing which can be confusing for down-stream QC and other analyses.

**Comment by weizhouUMICH** [comment]
Sorry for my late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
