### ISSUE TITLE
problem with LOCO

### ISSUE THREAD

**Issue by laisktrn** [weizhouUMICH/SAIGE#216]
Dear Wei,

I'm running SAIGE 0.38 with the LOCO=TRUE option in UKBB data. In the log file for Step I, I see that LOCO is applied ("leave-one-chromosome-out is activated! Note this option will only be applied to autosomal variants") and all seems OK. However, in Step II the log file states LOCO is not applied ("single-variant association test will be performed
386564  samples have been used to fit the glmm null model
obj.glmm.null$LOCO:  FALSE 
Leave-one-chromosome-out option is not applied"), although I've specified that LOCO=TRUE.

Could you help me figure out what might be causing this?

Here's the script I've used for Step I:

module load broadwell/SAIGE/0.38

Rscript /for_saige_038/step1_fitNULLGLMM.R \
--plinkFile=/ukb_autosomes_merged \
--phenoFile=/pheno_GWAS_file_allCTRL_noRELexcl.txt \
--phenoCol=pheno \
--covarColList=age,sex,PC1,PC2,PC3,PC4 \
--sampleIDColinphenoFile=f.eid \
--traitType=binary \
--outputPrefix=/ukb_pheno_loco_nullglm \
--nThreads=30 \
--LOCO=TRUE

and Step II:

module load broadwell/SAIGE/0.38

Rscript /for_saige_038/step2_SPAtests.R \
--bgenFile=/UKBiobankData500K/GENOTYPE_DATA_500K_v3/ukb_imp_chr${j}_v3.bgen \
--bgenFileIndex=/UKBiobankData500K/GENOTYPE_DATA_500K_v3/ukb_imp_chr${j}_v3.bgen.bgi \
--chrom=${j} \
--minMAC=20 \
--sampleFile=/ukb_sample.txt \
--GMMATmodelFile=/ukb_pheno_loco_nullglm.rda \
--varianceRatioFile=/ukb_pheno_loco_nullglm.varianceRatio.txt \
--SAIGEOutputFile=/SAIGE_pheno_loco_chr${j}.txt \
--LOCO=TRUE \
--IsOutputAFinCaseCtrl=TRUE \

Thanks!

Triin

**Comment by weizhouUMICH** [comment]
Hi Triin, 
It seems step 2 jobs were run by chromosome. Was LOCO applied for some chromosomes or not applied for all chromosomes? 
Would you mind sharing  the log file? 

Thanks,
Wei

**Comment by laisktrn** [comment]
Hi Wei,

yes, step II is run in parallel by chromosome. Step I was done using a plink file with all autosomal chromosomes, so LOCO was applied to all chromosomes (see the attached log file for Step I).

I've attached the log files for both steps (for Step II only the beginning of the log file for a random chromosome).

Thanks!

Best wishes
Triin

[saige_stepI.log](https://github.com/weizhouUMICH/SAIGE/files/4860197/saige_stepI.log)

[saige_stepII.log](https://github.com/weizhouUMICH/SAIGE/files/4860216/saige_stepII.log)

**Comment by weizhouUMICH** [comment]
Thanks Triin. 

Could you please check two things?
 
1. use R: 
load("/ukb_pheno_loco_nullglm.rda")
obj.glmm.null = modglmm
obj.glmm.null$LOCO
#see if it returns TRUE

2. check the step 2 R script used in your job. 
https://github.com/weizhouUMICH/SAIGE/blob/master/extdata/step2_SPAtests.R#L152

It seems in the step 2 function in the R wrapper function does not specify LOCO, even though the wrapper function step2_SPAtests.R has the argument. 
I just added the LOCO to the function 
https://github.com/weizhouUMICH/SAIGE/blob/master/extdata/step2_SPAtests.R#L198

Thanks,
Wei

**Comment by laisktrn** [comment]
Hi Wei,

updating the step 2 script did the trick, thanks!


Best wishes
Triin
