### ISSUE TITLE
step 1 error in getCoefficients

### ISSUE THREAD

**Issue by Qiaolan** [weizhouUMICH/SAIGE#217]
Hi Wei,

I got the error below in step 1: 

Error in getCoefficients(Y, X, W, tau, maxiter = maxiterPCG, tol = tolPCG) : 
  vector::_M_range_check: __n (which is 18446744071562080724) >= this->size() (which is 97664681524)
Calls: fitNULLGLMM ... glmmkin.ai_PCG_Rcpp_Quantitative -> Get_Coef -> getCoefficients

I used SAIGE many times and this is the first time I got this error. I have about 500k snps in my bed file and 9000 individuals. When I reduced the number of snps to 100k and 500 individuals, the error disappeared. Is this error due to large data size?

Thanks for your help!

Qiaolan

**Comment by Qiaolan** [comment]
I have modified memory chunk to a smaller size. I will see if this works.

**Comment by weizhouUMICH** [comment]
Hi Qiaolan, 

I haven't seen this error before. Is it possible among the 9000 individuals there some duplicated samples IDs in the phenotype file? 

Thanks,
Wei

**Comment by Qiaolan** [comment]
> Hi Qiaolan,
> 
> I haven't seen this error before. Is it possible among the 9000 individuals there some duplicated samples IDs in the phenotype file?
> 
> Thanks,
> Wei

You are right. The problem has been solved by updating IDs. Thank you! @weizhouUMICH

**Comment by orozcodelpinopedro** [comment]
Hi! I have the same error but I don't have any repeated IDs in my phenotype file. Any other suggestions?
