### ISSUE TITLE
Range of weight values

### ISSUE THREAD

**Issue by myragyst** [weizhouUMICH/SAIGE#218]
Dear Wei,

I would like to add weights with "--weightsIncludeinGroupFile" into a group file.
Are there any limitation or recommendation of range of weight values?

Best regards,

**Comment by weizhouUMICH** [comment]
Hi @myragyst, 

This is a great question. I don't think there are specific limitations for the range of weight values. 
The by default setting for weights is computed in R using  `dbeta(MAF, 1, 25)`, which gives rare variants higher weights than more frequent variants. 

Thanks,
Wei

**Comment by myragyst** [comment]
Dear Wei,

Thank you very much for your answer.

Best regards,

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
