### ISSUE TITLE
SAIGE-GENE: step1; fitNULLGLMM() in R; ERROR! phenotype value needs to be 0 or 1

### ISSUE THREAD

**Issue by SillySabertooth** [weizhouUMICH/SAIGE#219]
Hello! There is one simple question:

I run this command through R

```
fitNULLGLMM(plinkFile="all_data",
            phenoFile="pheno_changed.txt",
            phenoCol="y_binary",
            sampleIDColinphenoFile="IID",
            traitType="binary",
            invNormalize=TRUE,
            outputPrefix="fitted_all_data_binary",
            outputPrefix_varRatio="fitted_all_data_varRatio_binary",
            sparseGRMFile="sparseGRM_all_data_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseGRM.mtx",
            sparseGRMSampleIDFile="sparseGRM_all_data_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseGRM.mtx.sampleIDs.txt",
            nThreads=15,
            LOCO=FALSE,
            skipModelFitting=FALSE,
            IsSparseKin=TRUE,
            isCateVarianceRatio=TRUE)
```
And then got this output:

```
formula is  y_binary~ 1 
9795  samples have non-missing phenotypes
9795  samples will be used for analysis
Perform the inverse nomalization for  y_binary 
qr transformation has been performed on covariates
colnames(data.new) is  Y minus1 
out.transform$Param.transform$qrr:  1 1 
y_binary  is a binary trait
Error in fitNULLGLMM(plinkFile = "all_data", phenoFile = "pheno_changed.txt",  : 
  ERROR! phenotype value needs to be 0 or 1 
```

I got this error every time with different pheno.txt files, but I always had binary data in the feature column . Here it is, and I have no idea why it doesn't work. It works fine (but, i think, without any sence) when I changed traitType to "quantitative"
[pheno_changed.txt](https://github.com/weizhouUMICH/SAIGE/files/4885939/pheno_changed.txt)

```
9525 0
270 1
1 y_binary
```

**Comment by davideurac** [comment]
Hey Smilodon,    

If you remove the "invNormalize=TRUE" it should take care of the error.   Have a look at the docs to understand why...

**Comment by SillySabertooth** [comment]
Oh, thanks! I looked through the single variant association tests manual fast and didn't pay enough attention to some information since I was interested in gene-based test . And then when I changed obvious for me options to binary and got such error message, I concentrated on my "bad" pheno file. Now I see, sorry for my absentmindedness :(
