### ISSUE TITLE
ERROR: step2_SPAtests.R  ... has B = 16 (not 8)

### ISSUE THREAD

**Issue by luanjianan** [weizhouUMICH/SAIGE#22]
I got an error message in Step2_SPAtests below, where "1:214154719_G_T" is the first SNP's name in my BGEN file.  My BGEN file includes only 38 SNPs and are in GP (genotype probabilities) format.  
Your help will be appreciated very much.
Jianan

> ......
450106  samples have been used to fit the glmm null model 
variance Ratio is  0.849
487409  sample IDs are found in sample file
[1] 487409      4
[1] "IID"          "IndexInModel" "IndexDose.x"  "IndexDose.y"
450106  samples were used in fitting the NULL glmm model and are found in sample file
minMAC:  1
minMAF:  1e-04
Minimum MAF of markers to be testd is  1e-04
Analysis started at  1.52e+09 Seconds
no query list is provided
487409 samples are found in the bgen file
38 markers are found in the bgen file
isVariant:  TRUE
It is a binary trait
Analyzing  25529  cases and  424577  controls
ERROR: 1:214154719_G_T has B = 16 (not 8)

**Comment by joshbTerps** [comment]
You need to use 8-bit compression. Run qctool v2 with "-bgen-bits 8"

**Comment by luanjianan** [comment]
The trick works.  Thank you very much **joshbTerps**.
