### ISSUE TITLE
Error in `diag<-`(`*tmp*`, value = getDiagOfSigma(W, tauVecNew))  in SAIGE-GENE step1 

### ISSUE THREAD

**Issue by davideurac** [weizhouUMICH/SAIGE#220]
Hi Wei,

I'm trying to run SAIGE-GENE step1 on binary traits and hitting this error:

read in sparse GRM from  /scratch/demmert/work/rls/mg_saige_gene/step0_output/sparseGRM_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseGRM.mtx
length(sparseGRMSampleID$IndexGRM):  3603
nrow(sparseGRMSampleID):  3603
2943  samples have been used to fit the glmm null model
[1] 0 3
[1] IID          IndexInModel IndexGRM
<0 rows> (or 0-length row.names)
**Error in `diag<-`(`*tmp*`, value = getDiagOfSigma(W, tauVecNew)) :
  replacement diagonal has wrong length
Calls: fitNULLGLMM ... scoreTest_SPAGMMAT_forVarianceRatio_binaryTrait -> getSparseSigma -> diag<- -> diag<-
Execution halted**

Step 0 seems to have executed fine...   its not obvious to me what I'm doing wrong here...   Any advice how to proceed?

Many thanks,    -David

**Comment by weizhouUMICH** [comment]
Hi David, 

It seems the sample ids used in the PLINK file does not match the sample IDs in the sparseGRMSampleIDFile. Can you please have a check to see if this is the case? 

Thanks,
Wei

**Comment by davideurac** [comment]
Thank you, Wei!

Yes it looks like something is going wrong with sample IDs.

Here's the first few lines of the .fam file from the plink set I'm working with:

0010500022 0010500022 0 0 0 -9
0010060177 0010060177 0 0 0 -9
0017000196 0017000196 0 0 0 -9
0010003300 0010003300 0 0 0 -9
0010001328 0010001328 0 0 0 -9

And here's the first few lines of the sparseGRMSampleIDFile I generated in step0

10500022
10060177
17000196
10003300
10001328

It looks like the leading "00" in our sample IDs are getting inadvertently stripped-out in step 0...

**Comment by weizhouUMICH** [comment]
Sorry for my late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
