### ISSUE TITLE
pheweb.sph.umich.edu server is down?

### ISSUE THREAD

**Issue by Shicheng-Guo** [weizhouUMICH/SAIGE#221]
Dear Dr. Zhou, 

I find website `pheweb.sph.umich.edu` can not be accessed. Can you make a check to the server? another question is I am wondering is there any links to download the summary statistics of `pheweb.sph.umich.edu`. 

Thanks. 

Shicheng

**Comment by weizhouUMICH** [comment]
Dear Shicheng, 

Thank you for using the UKBB SAIGE PheWeb! The summary statistics can be downloaded from here
ftp://anonymous@share.sph.umich.edu/UKBB_SAIGE_HRC .

Btw, folks from the Broad Institute have recently run UKBB using SAIGE on > 7000 phenotypes, including PheCode ones, for all six ancestry samples, which may be also useful for your project. 
https://pan.ukbb.broadinstitute.org/
The summary stats can be downloaded from 
https://pan.ukbb.broadinstitute.org/downloads

Please feel free to let me know if you have any questions. 
Thanks,
Wei

**Comment by Shicheng-Guo** [comment]
Dear Wei, 

Thank you so much for the information about Broad Pan-UKB pheWAS project which is really helpful!!  

Best,

Shicheng

**Comment by Shicheng-Guo** [comment]
Dear Wei,

Do you know is there any pheWeb service to show gene-based association result to UKBB dataset? 

Thanks

Shicheng

**Comment by weizhouUMICH** [comment]
Hi Shicheng, 

We have run gene-based tests for UK-Biobank 50k WES data for 791 binary phenotypes. Here is the browser: 
http://ukb-50kexome.leelabsg.org/
and the manuscript (Zhao et al, 2020)
https://www.sciencedirect.com/science/article/pii/S0002929719304331

Thanks,
Wei
