### ISSUE TITLE
Variant is missing requested data format type.

### ISSUE THREAD

**Issue by psychrb** [weizhouUMICH/SAIGE#222]
I am getting an error message: Variant is missing requested data format type.
numPassMarker:  0 
For my vcf file, genotype probabilities, Format=GP.
For SAIGE, for SPAGMMATtest(), I've inputted vcfField="DS", and I get this error message, I've also tried "GT"...
Still no markers in output file...help??

**Comment by weizhouUMICH** [comment]
Hmm, the current library we are using to read VCF file can only take either GT or DS, not GP. Can you please generate DS using GP in the VCF file and then use  vcfField="DS"? 

Thanks!

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
