### ISSUE TITLE
Does Saige Gene require very rare variants?

### ISSUE THREAD

**Issue by jameskozubek** [weizhouUMICH/SAIGE#226]
I'm trying to run Saige Gene on UK Biobank's snp chip with more than 550K snps after some filtering. However, it seems like I got an error saying I do not have enough rare variants in my data. Is there anyway around this? Or do you recommend that I must go back and re-add the very rare variants into my plink file. 
 
 ERROR! number of genetic variants in 0.5< MAC <= 1.5 is lower than 30
Please include more markers in this MAC category in the plink file

**Comment by weizhouUMICH** [comment]
The extremely rare variants are needed in the plink file to compute the variance ratios for variants in the corresponding MAC category, which will be used in step 2 for gene-based tests.  I would recommend go back to add the very rare variants into plink file and run step 1 with the --skipModelFitting=TRUE to estimate variance ratios only.

**Comment by sariya** [comment]
@weizhouUMICH -Hi
I am running into same error using whole exome sequenced data. 
If they are unavailable in data, how do we get step 2 complete? 

In addition, data imputed from topmed reference panel may not have 30 variants for the mac categories saige needs for high-quality variants.

thank you,

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei

**Comment by lis262** [comment]
I'm also running gene based analysis for UKBB WES data using saige 1.1.6. But I got a kind of opposite error which indicates my input file doesn't have enough high MAC variants.

ERROR! number of genetic variants in 20.5< MAC  is lower than 30

Then I tried to run using saige 0.45, which can finish successfully. 

Anyone have the similar error while using newer versions of saige > 1?
