### ISSUE TITLE
Error in creating index file for bgen files

### ISSUE THREAD

**Issue by PradoVarathan** [weizhouUMICH/SAIGE#227]
Hi!
Thank you for the amazing tools!
I keep getting the same error when I try to create an index file using bgenix for a concatenated version of all chromosomes together but can create individual index files. The following is the error:

bgenix: creating index for "concatenated.bgen" in "concatenated.bgen.bgi"...
bgenix: Opened "concatenated.bgen" with 93095623 variants...
Building BGEN index                                         : [************************      ] (74578515/93095623,9347.7s,7978.3/s)bgenix: ../apps/bgenix.cpp:323: db::Connection::UniquePtr IndexBgenApplication::create_bgen_index_direct(const string&, const string&): Assertion `(file_end_pos - file_pos) > 0' failed.
Aborted (core dumped)

Is there an memory issue or is it because of something else?

Thanks in advance!

**Comment by weizhouUMICH** [comment]
Hi @PradoVarathan, 

I haven't seen the error before when I used bgenix. Could you please submit an issue to the bgenix webpage? 

Thanks,
Wei

**Comment by PradoVarathan** [comment]
Hi Wei!
 I sure will do. Thank you!
