### ISSUE TITLE
PheWAS question

### ISSUE THREAD

**Issue by psychrb** [weizhouUMICH/SAIGE#228]
Can SAIGE be applied to PheWAS for a multi-allelic variant class...and if so in which format should the multi-allelic variant be coded? i.e. can GT handle more than a binary variable or should the multi-allelic genotype calls be converted to DS?

**Comment by weizhouUMICH** [comment]
SAIGE/SAIGE-GENE uses the savvy library to handle VCF files. For the multi-allelic variants, genotypes/dosages for all alt alleles in one line in VCF files is not supported. The best solution is to split the variants by alleles.

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
