### ISSUE TITLE
How to account for case/control imbalance with Saige?

### ISSUE THREAD

**Issue by montenegrina** [weizhouUMICH/SAIGE#229]
Hello,

I have 2999 cases, 334143 controls…so very imbalanced. Data is from UK Biobank.
And I plan to run SAIGE like this:

#For Binary traits:
Rscript step1_fitNULLGLMM.R     \
        --plinkFile=./input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly \
        --phenoFile=./input/pheno_1000samples.txt_withdosages_withBothTraitTypes.txt \
        --phenoCol=y_binary \
        --covarColList=x1,x2 \
        --sampleIDColinphenoFile=IID \
        --traitType=binary        \
        --outputPrefix=./output/example_binary \
        --nThreads=4 \
        --LOCO=FALSE \
        --IsOverwriteVarianceRatioFile

I am wondering is there is a flag I can specify for my imbalance of cases and controls?

I saw that you have for another function --IsAccountforCasecontrolImbalanceinGroupTest=TRUE can I use the same flag for step1_fitNULLGLMM.R? Also do I need to speciafy traceCVcutoff and ratioCVcutoff?

Cheers,
Ana

**Comment by weizhouUMICH** [comment]
Hi Ana, 

Your step 1 script should work and you don't need to specify traceCVcutoff and ratioCVcutoff. 
For Binary traits, step 2 (null model fitting) automatically account for case-control imbalance for both single-variant and gene-based association tests (with  --IsAccountforCasecontrolImbalanceinGroupTest=TRUE, which is the default setting). 

Thanks,
Wei

**Comment by montenegrina** [comment]
Hi Wei,

Thank you so much for getting back to me. So step 1 does not do the GWAS
analysis?
It does preparation for step 2?

If so does that mean that I will run something like this after completing
step 1?

Rscript step2_SPAtests.R	\
        --vcfFile=./input/genotype_10markers.missingness.vcf.gz \
        --vcfFileIndex=./input/genotype_10markers.missingness.vcf.gz.tbi \
        --vcfField=GT \
        --chrom=1 \
        --minMAF=0.0001 \
        --minMAC=1 \
        --sampleFile=./input/sampleIDindosage.txt \
        --GMMATmodelFile=./output/example_binary.rda \
        --varianceRatioFile=./output/example_binary.varianceRatio.txt \
        --SAIGEOutputFile=./output/example_binary.SAIGE.vcf.genotype.txt \
        --numLinesOutput=2 \
        --IsOutputAFinCaseCtrl=TRUE

Will step 1 give me this output like this:
genotype_10markers.missingness.vcf.gz,
genotype_10markers.missingness.vcf.gz.tbi?

I should run step 1 for merged all CHR ? And step 2 per chromosome?

Just a note I am doing this for UK Biobank data.

Thanks

Ana

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
