### ISSUE TITLE
double free or corruption error

### ISSUE THREAD

**Issue by zd1** [weizhouUMICH/SAIGE#23]
Hi there, 

I am getting an error message of "R: double free or corruption (!prev)" - full log pasted at the bottom. I was wondering if you have encountered this error before? 

Thanks,
Zhihao

`
486801  samples have genotypes
formula is  age_at_menopause~age+chip+pc1+pc2+pc3+pc4+pc5
34080  samples have non-missing phenotypes
452737  samples in geno file do not have phenotypes
34064  samples will be used for analysis
colnames(data.new) is  Y minus1 age chip pc1 pc2 pc3 pc4 pc5
out.transform$Param.transform$qrr:  8 8
age_at_menopause  is a quantitative trait
[1] "Start reading genotype plink file here"
nbyte: 121701
nbyte: 8516
reserve: 85180000

M: 10000, N: 486801
size of genoVecofPointers: 1
here
time: 22784.1
[1] "Genotype reading is done"
Fixed-effect coefficients:
minus1           age          chip           pc1           pc2
-3.899318e+00  1.565513e-02 -4.877275e-03 -6.925518e-04  2.302982e-04
pc3           pc4           pc5
8.042034e-06  3.747540e-03 -1.672029e-03
inital tau is  0.005859873 0.005859873
[1] "ok1"
iter from getPCG1ofSigmaAndVector 26
iter from getPCG1ofSigmaAndVector 22
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 25
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 26
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 26
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 26
iter from getPCG1ofSigmaAndVector 26
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 26
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 26
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 26
iter from getPCG1ofSigmaAndVector 28
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 26
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 28
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 26
iter from getPCG1ofSigmaAndVector 26
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 26
iter from getPCG1ofSigmaAndVector 27
iter from getPCG1ofSigmaAndVector 26
iter from getPCG1ofSigmaAndVector 26
iter from getPCG1ofSigmaAndVector 33
A1(0,0) 1.39036e+09
iter from getPCG1ofSigmaAndVector 29
AI    1.3904e+09   3.1515e+07
3.1515e+07   7.1666e+07

Trace    4.6066e+06
1.2052e+06

YPAPY 604621
cov    1.7203e-07   1.2404e-14   8.0786e-14  -1.1885e-14  -3.0021e-14   1.6740e-14   4.4670e-14  -2.6604e-14
-1.3932e-14   2.1842e-07  -4.2133e-08  -1.3894e-09  -6.2503e-11   1.2665e-09   7.5174e-09  -7.4913e-09
-7.6886e-15  -4.2132e-08   1.5268e-06   2.0266e-11   1.3647e-09   1.5490e-09  -1.1190e-10   5.7976e-09
7.3620e-15  -1.3894e-09   1.9793e-11   2.3279e-07   1.7434e-09  -9.7932e-09  -3.2563e-08   2.3300e-08
-2.2561e-15  -6.2528e-11   1.3653e-09   1.7434e-09   2.2588e-07  -2.7287e-09  -1.3776e-08   1.2486e-08
1.5910e-14   1.2665e-09   1.5491e-09  -9.7932e-09  -2.7287e-09   2.3176e-07   2.7183e-08  -1.9142e-08
1.9238e-14   7.5174e-09  -1.1164e-10  -3.2563e-08  -1.3776e-08   2.7183e-08   3.3390e-07  -9.0709e-08
-2.7797e-15  -7.4913e-09   5.7974e-09   2.3300e-08   1.2486e-08  -1.9142e-08  -9.0709e-08   3.1626e-07

tauv3  0.009632391 0.005254446

Iteration  1 :
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 16
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 18
iter from getPCG1ofSigmaAndVector 18
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 20
iter from getPCG1ofSigmaAndVector 20
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 20
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 20
iter from getPCG1ofSigmaAndVector 18
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 20
iter from getPCG1ofSigmaAndVector 20
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 20
iter from getPCG1ofSigmaAndVector 20
iter from getPCG1ofSigmaAndVector 20
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 20
iter from getPCG1ofSigmaAndVector 20
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 18
iter from getPCG1ofSigmaAndVector 20
iter from getPCG1ofSigmaAndVector 20
iter from getPCG1ofSigmaAndVector 18
iter from getPCG1ofSigmaAndVector 20
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 22
A1(0,0) 3.19269e+08
iter from getPCG1ofSigmaAndVector 21
AI    3.1927e+08   2.0894e+07
2.0894e+07   5.4824e+07

Trace    2.9273e+06
1.1153e+06

YPAPY 489333
cov    2.8277e-07  -3.5684e-15   7.2558e-14   5.8791e-14  -1.5673e-14  -1.1703e-14   2.4636e-14  -1.9592e-14
-3.1248e-14   3.4329e-07  -5.3851e-08  -1.8603e-09  -1.0478e-10   1.7017e-09   9.8410e-09  -9.7593e-09
1.7753e-13  -5.3851e-08   2.0257e-06   2.8053e-10   1.7084e-09   1.9096e-09   1.6526e-10   8.1851e-09
-4.9256e-15  -1.8603e-09   2.8038e-10   3.6227e-07   2.2353e-09  -1.2903e-08  -4.2687e-08   3.0489e-08
-1.7443e-14  -1.0474e-10   1.7068e-09   2.2354e-09   3.5313e-07  -3.5739e-09  -1.8037e-08   1.6416e-08
-1.1821e-15   1.7017e-09   1.9100e-09  -1.2903e-08  -3.5739e-09   3.6069e-07   3.5759e-08  -2.5054e-08
2.3638e-14   9.8410e-09   1.6807e-10  -4.2687e-08  -1.8037e-08   3.5759e-08   4.9483e-07  -1.1870e-07
-7.8719e-15  -9.7593e-09   8.1840e-09   3.0489e-08   1.6416e-08  -2.5054e-08  -1.1870e-07   4.7153e-07

0,03.19269e+08
0,12.08942e+07
1,02.08942e+07
1,15.48242e+07
tau2 0 0
Variance component estimates:
[1] 0 0
Fixed-effect coefficients:
[1] -3.898816e+00  1.555553e-02 -4.100984e-03 -7.062043e-04  2.671797e-04
[6]  3.221108e-05  3.851775e-03 -1.980942e-03

Iteration  2 :
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 0
A1(0,0) -nan
iter from getPCG1ofSigmaAndVector 0
AI       nan      nan
nan      nan

Trace       nan
nan

YPAPY -nan
cov           nan          nan          nan          nan          nan          nan          nan            0
0          nan          nan          nan          nan          nan          nan            0
2.7816e-42          nan          nan          nan          nan          nan          nan            0
0          nan          nan          nan          nan          nan          nan            0
3.3637e-34          nan          nan          nan          nan          nan          nan            0
0          nan          nan          nan          nan          nan          nan            0
2.0000e+00          nan          nan          nan          nan          nan          nan            0
0          nan          nan          nan          nan          nan          nan          nan
*** Error in `/path/to/executable/R': double free or corruption (!prev): 0x0000000007e091d0 ***
`

**Comment by weizhouUMICH** [comment]
Hi @zd1, 

This error seems because the variance of the phenotype is quite large. Please try to set invNormalize=TRUE to inverse normalize the phenotype. 

Thanks,
Wei
