### ISSUE TITLE
v0.39 Question vs older v0.35 version

### ISSUE THREAD

**Issue by tbrunetti** [weizhouUMICH/SAIGE#230]
I have a few questions about the new version of SAIGE (v0.39) vs what I used previously (v0.35.8.3)

1.  I noticed that in step1 of the fitting the null model, the argument `--numMarkers` has now been replaced by two new parameters: `--numRandomMarkerforVarianceRatio` and `--numRandomMarkerforSparseKin`   It looks like `--numRandomMarkerforVarianceRatio` maps to `--numMarkers` but what does  `--numRandomMarkerforSparseKin` map to in the old version?  How do you determine the best value to set for this? I know the default is 30 for variance ratio and 2000 for the kin.

2.  It seems that the `--LOCO` flag now works during step1 in v0.39, (thank you, this is great!) however, how what is the rough computational time difference of setting the LOCO flag vs not setting the flag?

3.  Lastly, I have a question about the threading and parallel capabilities of STEP1.  With the `--nThreads` option, which part of step 1 is parallelizable, i.e. using the `--nThreads` argument?  It is the varianceRatio calculation or just the very beginning to generating the null model or the kinship estimation or all 3?  I feel like when I run STEP1 on v.0.39 it is taking a lot longer than with v.0.35.  However, I do have the LOCO flag set to true, so maybe that takes a lot longer?

Thanks!

**Comment by weizhouUMICH** [comment]
Sorry for my late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
