### ISSUE TITLE
cntMarker:  0

### ISSUE THREAD

**Issue by jameskozubek** [weizhouUMICH/SAIGE#231]
Saige Gene (step 2) does not seem to be reading my Markers. Do you have any advice?

I get this error for every gene. 

geneID:  NOC2L
std::size_t sample_size = marker_file.samples().size();84950
cntMarker:  0
[1] "No samples are left after removing samples with missing dosages/genotypes of variants in the gene"

I used plink to check my VCF file and it looks fine with markers having <1% missingness. 

My groups file is tab delimited and looks fine. 

NOC2L   chr1:880238_G/A chr1:880483_A/G chr1:881918_G/A chr1:884767_G/A chr1:888659_C/T chr1:889238_G/A chr1:891898_T/C chr1:894330_G/A chr1:897009_A/G     chr1:897738_C/T chr1:898153_C/A chr1:898787_G/T

My command line is this:

Rscript /mnt/BIOINFX/SAIGE-master/extdata/step2_SPAtests.R --vcfFile=DT2rare.vcf.gz --vcfFileIndex=DT2rare.vcf.gz.tbi --minMAF=0.05 --minMAC=2 --maxMAFforGroupTest=0.10 --sampleFile=DT2_relatednessCutoff_0.125_200_randomMarkersUsed.sparseGRM.mtx.sampleIDs.txt --GMMATmodelFile=./saigegene/DT2.rda --varianceRatioFile=./saigegene/DT2.varianceRatio.txt --numLinesOutput=1 --sparseSigmaFile=./saigegene/DT2.varianceRatio.txt_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseSigma.mtx --IsSingleVarinGroupTest=FALSE --IsOutputAFinCaseCtrl=TRUE --SAIGEOutputFile=./saigegene/example_quantitative.SAIGE.gene.chr1.txt --LOCO=FALSE --groupFile=./saigegene/new_group.txt --chrom=1 --vcfField=GT

**Comment by weizhouUMICH** [comment]
It seems the --chrom=1 is used in the job command but "chr1" is used in the group file. These two need to be consistent to the chromosome string in the VCF file.

**Comment by jameskozubek** [comment]
If I change the group file to a format such as 1:12345_A/G
then I get this error:

weights:  0.02678286 0.1119522 0.2203334
Error in SI_XXVX_inv %*% XV_G2[, i] : non-conformable arguments
Calls: SPAGMMATtest ... system.time -> SAIGE_SKAT_withRatioVec -> getCovM_nopcg
Timing stopped at: 23.43 0.291 23.74
Execution halted

**Comment by weizhouUMICH** [comment]
Sorry for my late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
