### ISSUE TITLE
Install without conda

### ISSUE THREAD

**Issue by wrathematics** [weizhouUMICH/SAIGE#232]
Is it possible to install the package without conda?

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply!
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
There are multiple options for installation. 
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
