### ISSUE TITLE
Installation on Linux subsystem

### ISSUE THREAD

**Issue by rakinitopo** [weizhouUMICH/SAIGE#234]
Hi! I've been trying to install SAIGE for a while now but I keep struggling. I'm  using an Ubuntu subsystem for Windows 10 (I have already checked the previous issues related to my problem but none of the solutions worked). 

When I try the first option (R CMD INSTALL...), I get the following error: 

_** R
** byte-compile and prepare package for lazy loading
Error in library.dynam(lib, package, package.lib) :
  shared object ‘Rcpp.so’ not found
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace -> library.dynam
Execution halted
ERROR: lazy loading failed for package ‘SAIGE’_

I uninstalled Rcpp but it didn't work. 
Also, when I try option 2 (devtools), I get this one:

_Error: Failed to install 'SAIGE' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   over-long path
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   problem copying .\weizhouUMICH-SAIGE-246f8d0\thirdParty\bgen\3rd_party\boost_1_55_0\libs\numeric\ublas\doc\html\structboost_1_1numeric_1_1ublas_1_1vector__temporary__traits_3_01vector__indirect_3_01_v_01_4_01_4.html to C:\Users\Silvia\AppData\Local\Temp\Rtmp6L9rjp\Rbuild7cc11ee6\weizhouUMICH-SAIGE-246f8d0\thirdParty\bgen\3rd_party\boost_1_55_0\libs\numeric\ublas\doc\html\structboost_1_1numeric_1_1ublas_1_1vector__temporary__traits_3_01vector__indirect_3_01_v_01_4_01_4.html: No such file or directory
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   problem copying .\weizhouUMICH-SAIGE-246f8d0\thirdParty\bgen\3rd_party\boost_1_55_0\libs\numeric\ublas
In addition: Warning message:
In utils::untar(tarfile, ...) :   ‘tar.exe -xf "C:\Users\Silvia\AppData\Local\Temp\RtmpCUN5L9\file6c46a450cb.tar.gz" -C "C:/Users/Silvia/AppData/Local/Temp/RtmpCUN5L9/remotes6c43b826920"’ returned error code 1_

I would much appreciate some  help here.
Thank you,
Silvia

**Comment by unepanthere** [comment]
Hi Silvia,

  the best would be to let R install whichever dependencies it requires;

R --quiet --no-save
devtools::install_github("weizhouUMICH/SAIGE")
# a menu will appear for you to choose which packages to update; choose option 1.

**Comment by rakinitopo** [comment]
Thank you for your help, unepanthere!
I was trying to run the devtools script in RStudio instead.
Closing issue!
