### ISSUE TITLE
Error in SI_XXVX_inv %*% XV_G2[, i] : non-conformable arguments

### ISSUE THREAD

**Issue by jameskozubek** [weizhouUMICH/SAIGE#235]
Hello Wei and team, 
I put the rare variants back into my file, and made sure to use 1:1234_C/G format. However, I am still getting a step 2 error for Saige Gene. 

whereas my command line is:

Rscript /mnt/BIOINFX/SAIGE-master/extdata/step2_SPAtests.R --vcfFile=DT2rare.vcf.gz --vcfFileIndex=DT2rare.vcf.gz.tbi --minMAC=0.5 --maxMAFforGroupTest=0.01 --sampleFile=./DT2rare/DT2_relatednessCutoff_0.125_200_randomMarkersUsed.sparseGRM.mtx.sampleIDs.txt --GMMATmodelFile=./DT2rare/DT2.rda --varianceRatioFile=./DT2rare/DT2.varianceRatio.txt --numLinesOutput=1 --sparseSigmaFile=./DT2rare/DT2.varianceRatio.txt_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseSigma.mtx --IsSingleVarinGroupTest=FALSE --SAIGEOutputFile=./DT2rare/example_quantitative.SAIGE.gene.chr1.txt --LOCO=FALSE  --groupFile=./saigegene/1.txt --chrom=1 --vcfField=GT --IsOutputAFinCaseCtrl=TRUE

I get the log such as:

84950  samples were used in fitting the NULL glmm model and are found in sample file
sparse kinship matrix is going to be used
sparseSigmaFile:  ./DT2rare/DT2.varianceRatio.txt_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseSigma.mtx
Missing dosages will be mean imputed for the analysis
Analysis started at  1596720835 Seconds
minMAC:  0.5
minMAF:  0
Minimum MAF of markers to be tested is  2.942908e-06
It is a binary trait
Analyzing  28138  cases and  56812  controls
isCondition is  FALSE
Analysis started at  1596720835 Seconds
genetic variants with  2.942908e-06 <= MAF <=  0.01 are included for gene-based tests
It is a binary trait
Case-control imbalance is adjusted for binary traits.
isCondition is  FALSE
geneID:  ACAP3
[W::vcf_parse] INFO '0.8' is not defined in the header, assuming Type=String
std::size_t sample_size = marker_file.samples().size();84950
missing_cnt > 0!
missing_cnt > 0!
missing_cnt > 0!
missing_cnt > 0!
missing_cnt > 0!
missing_cnt > 0!
missing_cnt > 0!
missing_cnt > 0!
cntMarker:  8
indexforMissing:  48 54 949 1216 2018 .....

isCondition is  FALSE
weights:  21.12772 24.33358 24.79924 24.7014 23.76356 24.86947 24.80292 24.94
Error in SI_XXVX_inv %*% XV_G2[, i] : non-conformable arguments
Calls: SPAGMMATtest ... system.time -> SAIGE_SKAT_withRatioVec -> getCovM_nopcg
Timing stopped at: 68.55 0.697 72.71
Execution halted

**Comment by weizhouUMICH** [comment]
Hi @jameskozubek, 

Can you please try to mean impute the missing dosages instead of removing them with --IsDropMissingDosages=FALSE? so we can see if the error is because that removing missing dosages causes some dimension problem. 

Thanks!
Wei

**Comment by jameskozubek** [comment]
I get the same error if I add --IsDropMissingDosages=FALSE
I also tried --IsDropMissingDosages=TRUE but it also caused the same error

**Comment by jameskozubek** [comment]
note I don't have dosages in the file, only genotypes as in 0/1 or 0/0 or ./.

**Comment by weizhouUMICH** [comment]
Hi James,

Do you see this error for every gene or just one gene?

Thanks,
Wei

**Comment by jameskozubek** [comment]
all genes.

**Comment by jameskozubek** [comment]
I corrected it by reset the tab on my group file.
awk '{$1=$1}1' OFS="\t"
and make sure snps in order,
also snps must be assigned to correct genes.
