### ISSUE TITLE
error installing SAIGE

### ISSUE THREAD

**Issue by unepanthere** [weizhouUMICH/SAIGE#236]
Hi Everyone,

  I'm trying to install SAIGE on linux using R:

R --quiet --no-save
devtools::install_github("weizhouUMICH/SAIGE")

I've updated everything it asked to update.
Then, half hour later, I get this:

** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘SAIGE’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/mparis15/R/x86_64-redhat-linux-gnu-library/3.6/00LOCK-SAIGE/00new/SAIGE/libs/SAIGE.so':
  /home/mparis15/R/x86_64-redhat-linux-gnu-library/3.6/00LOCK-SAIGE/00new/SAIGE/libs/SAIGE.so: undefined symbol: _ZN5savvy9site_info12empty_stringB5cxx11E

Any ideas how to fix this? Yes, I installed Python's savvy lib.
Thanks!

**Comment by weizhouUMICH** [comment]
Hi @unepanthere, 

Are you using conda env to install SAIGE? I think there might be errors before this final error in the installation. 

Thanks,
Wei

**Comment by unepanthere** [comment]
Hi Dr. Zhou,

  thank you for your prompt reply;


> Hi @unepanthere,
> Are you using conda env to install SAIGE? I think there might be errors before this final error in the installation.


After failed “method 2” attempt;
devtools::install_github("weizhouUMICH/SAIGE")


I just tried “method 1”;
src_branch=master
repo_src_url=https://github.com/weizhouUMICH/SAIGE
git clone --depth 1 -b $src_branch $repo_src_url
R CMD INSTALL --library=path_to_final_SAIGE_library SAIGE


And I still got this error (both methods):
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘SAIGE’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/mparis15/R/x86_64-redhat-linux-gnu-library/3.6/SAIGE/00LOCK-SAIGE/00new/SAIGE/libs/SAIGE.so':
  /home/mparis15/R/x86_64-redhat-linux-gnu-library/3.6/SAIGE/00LOCK-SAIGE/00new/SAIGE/libs/SAIGE.so: undefined symbol: _ZN5savvy9site_info12empty_stringB5cxx11E
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/mparis15/R/x86_64-redhat-linux-gnu-library/3.6/SAIGE/SAIGE’


The undefined symbol: _ZN5savvy9site_info12empty_stringB5cxx11E
This is because something is calling that, but it’s nowhere to be found in one of the (very many) libs/.so files.

I have R 3.6; you ask for 3.6.1, sure, that might be it.


conda?
$ conda
-bash: conda: command not found


I will check with other people in the lab if/how they got SAIGE running…

Very Best,
   Marc.

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
