### ISSUE TITLE
chr Y support?

### ISSUE THREAD

**Issue by sgagliano** [weizhouUMICH/SAIGE#237]
Hi Wei, 

I was wondering if SAIGE supports chr Y association analyses in males, and if so, what is the implementation?

Thanks!

Sarah

**Comment by weizhouUMICH** [comment]
Hi Sarah,

SAIGE does not handle chr Y association analysis differently.
Option 1: Ideally, you will need to run Step 1 for males only and then may
run Step 2 jobs for chromosome Y using males.
Option 2: Alternatively, you may directly use the Step 1 output with all
samples, in Step 2, set --IsDropMissingDosages=TRUE to remove females (with
missing dosages on Y chromosome) in the association tests.

Thanks,
Wei

**Comment by sgagliano** [comment]
Thanks Wei!
