### ISSUE TITLE
Error in step2 of SAIGE-GENE

### ISSUE THREAD

**Issue by elenasorokin** [weizhouUMICH/SAIGE#238]
Dear Wei,

Congrats on your recent NG paper! 

I'm using SAIGE-GENE and have created a GRM and fit the null model using LD-thinned array markers from my cases and controls for a binary trait. When running step2, using a VCF of rare variants from a sequencing dataset for ~15,000 genes, I only get around 800 lines (one per gene) in the results file, whereas I expect ~11,000 lines/genes in the result file. 

And I see ~14,100 of this error message in the log file for step2:

geneID:  ENSG00000123572
std::size_t sample_size = marker_file.samples().size();11829
cntMarker:  0
[1] "No samples are left after removing samples with missing dosages/genotypes of variants in the gene"

Do all the rare variants in the VCF have to be represented in the PLINK file from step 1?

Thank you, 
Elena

**Comment by elenasorokin** [comment]
hi Wei,
Here is an example SPAtest output with a quantitative trait. For this example gene, there are 416 minor alleles across 25 variants in my VCF, yet my output seems to indicate that only the first of the variants  is being recorded. 

Gene Pvalue Nmarker_MACCate_1 Nmarker_MACCate_2 Nmarker_MACCate_3 Nmarker_MACCate_4 Nmarker_MACCate_5 Nmarker_MACCate_6 Nmarker_MACCate_7 Nmarker_MACCate_8 markerIDs markerAFs Pvalue_Burden Pvalue_SKAT
ENSG00000005469 0.668829067336023 0 0 0 1 0 0 0 0 7:87349102_C/T 0.000170227256603539 NA NA

GroupFile: 
ENSG00000005469	7:87349102_C/T	 7:87349112_AG/A	 7:87349163_TA/T	 7:87349163_T/TA	 7:87357530_AG/A	 7:87357540_AT/A	 7:87359265_C/T	 7:87361728_A/AG	 7:87361783_C/T	 7:87361830_C/CA	 7:87361846_AGGACT/A	 7:87369390_T/TC	 7:87369417_C/T	 7:87375708_C/T	 7:87375714_C/T	 7:87377349_AT/A	 7:87382179_G/T	 7:87382441_CCTTT/C	 7:87391653_C/T	 7:87391713_G/A	 7:87392631_T/A	 7:87392643_AG/A	 7:87392758_AC/A	 7:87392810_C/CT	 7:87393003_C/T

**Comment by weizhouUMICH** [comment]
Hi Elena,

Thank you for using SAIGE-GENE! Rare variants in the VCF do not need to be
included in the Plink file from step 1. Actually, by default, only common
variants in the Plink file (with MAF >= 1%) will be used for GRM. It seems
there is some issue reading the group file  the VCF input.

In the group file, elements in each line need to be separated by tab. Is
this true in the group file you are using?

Thanks,
Wei

**Comment by elenasorokin** [comment]
Got it working now. Thank you!
