### ISSUE TITLE
Can you include option to read bfile from plink? for Step-2

### ISSUE THREAD

**Issue by gpcr** [weizhouUMICH/SAIGE#24]
Even though we can convert plink to vcf, it might be impractical for large files 

Can you please add this option

Thanks

**Comment by IoannaTach** [comment]
I would have really appreciated this option too for step 2 right now. As far as I can tell, it has not been implemented yet, is that correct please?

**Comment by xwBio** [comment]
I think that support of plink format input would make it more popular.

**Comment by weizhouUMICH** [comment]
Hi,

Thank you for the good suggestion! 
Will try to implement this option in a future version. 

Thanks,
Wei
