### ISSUE TITLE
Error code in SAIGE for single gene association test

### ISSUE THREAD

**Issue by oalavijeh** [weizhouUMICH/SAIGE#240]
Dear Wei, 

I a running into the following error when trying to run single variant association testing. I'm afraid I work on an airlocked HPC so can only share a screenshot of the issue but the error reads:

"Error in setgenoTest_vcf_dosage...Expecting a single string value. 

I am looping through all the chromosome on an interactive node just to get the algorithm working. 

![image](https://user-images.githubusercontent.com/56344383/90630505-0d18a480-e219-11ea-9dbf-50099e3260fc.png)

Many thanks for your time

**Comment by weizhou0** [comment]
Dear @oalavijeh, 

sorry for my late reply. The error is because the argument chrom requires a string instead of a number. 
Could you please try it? 

Thanks,
Wei

**Comment by oalavijeh** [comment]
Thanks for getting back to me @weizhou0 , 

How would I do that?

Many thanks

**Comment by oalavijeh** [comment]
All sorted thanks!
