### ISSUE TITLE
Deflation Issue with One Strata - Other Strata Runs Okay - Issue? 

### ISSUE THREAD

**Issue by bgynr** [weizhouUMICH/SAIGE#241]
We are using SAIGE_0.36.3.1 to run case/control analysis on a binary trait. We have ~15 separate strata that are run through SAIGE separately then meta-analyzed. All strata besides one worked successfully. This one strata has major deflation and we are not sure why. Script for this strata is exactly same as others and plink/vcf files were formed exactly the same way. 

We noticed the variance ratio in this strata is much lower like ~0.7-0.8 whereas the other strata gave a variance ratio of ~1. What are the general causes for lowering of the variance ratio? Or causes for any change in variance ratio? 
What could cause so much deflation in this strata? I have attached the log from step1 as well as the QQ/manhattan plot which shows the dramatic deflation. We assume the issue is coming in step1 because of the variance ratio difference. 

Just to note.. We have checked the phenotype file and all is okay with it (spacing and coding), we checked relatedness (pi-hat) and all is okay with this as well. We have rerun to make sure it was not a runtime issue and both runs have same issue. We have changed minMAF of step1 from 0.01 to 0.05 and the variance ratio actually got worse with 0.05.

Any help is appreciated. Thank you.

[SAIGE_step1_Log_for_GITHUB.txt](https://github.com/weizhouUMICH/SAIGE/files/5109208/SAIGE_step1_Log_for_GITHUB.txt)
![QQ_deflation](https://user-images.githubusercontent.com/42152555/90899058-5beb4900-e395-11ea-8bcb-45ca198f4d14.jpg)
![manhattan_deflation](https://user-images.githubusercontent.com/42152555/90899067-5f7ed000-e395-11ea-953a-95b2806ba3fb.jpg)

**Comment by bgynr** [comment]
Hello, 

Pinging this issue again. Any help is appreciated.

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
