### ISSUE TITLE
Samples used in glmm model fit do not have dosages

### ISSUE THREAD

**Issue by aritra90** [weizhouUMICH/SAIGE#242]
Hi Wei, 

I am trying to use SAIGE for doing association tests on an unbalanced dataset. I use pruned markers to run Step1 and it runs fine generating the .rda and variance ratio files. However in Step2 when I compute with the original unpruned data I get the following error: 

`Error in SPAGMMATtest(vcfFile = opt$vcfFile, vcfFileIndex = opt$vcfFileIndex,  :          
  ERROR!12550 samples used in glmm model fit do not have dosages`

I saw there was a similar issue before where you suggested doing PLINK's `--fill-missing-a2` on the genotypes and inserting the sample ID file. I have done both and still getting the same error. Also, the genotyping rate as shown in PLINK is 0.9945. It'd be great if you can help me get an idea of what's going and/or how to get around this issue. 

Thanks.

**Comment by weizhou0** [comment]
Hi @aritra90, 

Could you please check the sample IDs in step 1 using the following script? 

```
#open R
load("step1 output.rda")
modglmm$sampleID. #this is a vector of sample IDs included in Step 1
```
Then you may check to see if all sample IDs in Step 1 are included in the VCF file in Step 2. 

Thanks,
Wei

**Comment by aritra90** [comment]
Thanks a lot Wei. That fixed it, I spotted the error :)
