### ISSUE TITLE
using subset of samples on stage2 of SAIGE-GENE

### ISSUE THREAD

**Issue by oalavijeh** [weizhouUMICH/SAIGE#243]
Dear Wei, 

I am using SAIGE Gene to do genome wide burden analysis. I have multisample vcfs per chromosome of cases AND controls in the same vcf. I have a plink .bed file of a subset of million markers to create the sparse GRM. This has been working well. 

I want to run the analysis on a subset of the cases and all the controls, all of the cases are already in the total vcf and plink files. Do I need to recreate the whole analysis from step 0? Can I jump to step two but just alter the sample file IDs I give the algorithm? 

"Sample file - This file contains one column for sample IDs corresponding to the sample order in the dosage file. No header is included. The option was originally for BGEN file that does not contain sample information." 

I don't understand the part where you say it has to be in the same order as the dosage file. Does that mean if I want to use a subset of sample I need to create a new vcf with only those samples in it? 

Many thanks for your time

**Comment by weizhou0** [comment]
Hi oalavijeh, 

The sample file, which contains sample IDs,  is required for bgen input as there are no sample IDs stored in some bgen files. For VCF input, for version >= 0.38, sample files are not required as VCF files contain sample IDs. 

To create the sparse GRM (Step 0) and run Step 1, you don't need millions of markers as the computation time and memory increases linearly as the number of markers increases. Q4 in the [FAQ](https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE) has more details on the number of markers) needed for Step 1 and Step 0. The same Plink file can be used for Step 0 and Step 1. By default, markers with >= 1% from the Plink file will be used to create a sparse GRM in Step 0 and the full GRM on the fly in Step 1. In Step 1, rare markers (MAC <= 20) are needed in the Plink file to estimate the variance ratios for MAC = 1, 2, 3, 4, 5, 6-10, and 10-20. For each MAC category, you may include 30 ~ 100 markers in the Plink file. 

You would need to run Step 0 for once for all samples and the sparse GRM can be used in all tests with different sample subsets. 
However, all samples tested in Step 2 need to be used to fit the null model in Step 1, so for each sample subset, you would need to run Step 1 and Step 2. 
You don't need to create multiple VCF files or Plink files for different sample subsets. The same Plink file and VCF file with all samples can be used for all jobs. Jobs can be run with different phenotype files with different sample sets. In Step 1, samples with non-missing phenotypes (in the phenotype file) and non-missing genotypes (in the Plink file) will be used to fit the null model. In Step 2, samples included in Step 1 will be included for association tests. 

Thanks,
Wei

**Comment by oalavijeh** [comment]
Thanks! Makes sense now. This whole answer could be in the FAQ as I know a few people who have been asking the same thing. Many thanks.
