### ISSUE TITLE
Failure to install savvy library 

### ISSUE THREAD

**Issue by MFutschik-ImperialCollege** [weizhouUMICH/SAIGE#244]
Hello, 
I tried to install SAIGE in a conda enviroment on CentOS Linux 7 (Core) following 
https://github.com/weizhouUMICH/SAIGE
Both methods fail with the error 
SAIGE_readDosage_vcf.cpp:1:10: fatal error: ../thirdParty/cget/include/savvy/reader.hpp: No such file or directory
 #include "../thirdParty/cget/include/savvy/reader.hpp"

I also followed some alternative ways proposed at 
https://github.com/weizhouUMICH/SAIGE/issues/83
https://github.com/weizhouUMICH/SAIGE/issues/167
but run into the same problem. 

I tried to run separately the configure file  in the SAIGE directory and got this results (my home directory is replaced with XXX):

##################################
XZ Utils 5.2.3

System type:
checking build system type... mkdir: cannot create directory '/tmp/cg28216-2372': Permission denied
mkdir: cannot create directory '/tmp/cg-28216': Permission denied
config.guess: cannot create a temporary directory in /tmp
configure: error: cannot guess build type; you must specify one
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING
    CGET_CMAKE_DIR
    CGET_CMAKE_ORIGINAL_SOURCE_FILE

-- Build files have been written to: XXX/home/software/SAIGE/thirdParty/cget/cget/build/tmp-fc261a128cbf4130a5231856cb6585ca/build
Scanning dependencies of target xz
[100%] Building xz ...
make[3]: *** No targets specified and no makefile found.  Stop.
gmake[2]: *** [CMakeFiles/xz] Error 2
gmake[1]: *** [CMakeFiles/xz.dir/all] Error 2
gmake: *** [all] Error 2
Command failed: ['XXX/anaconda3/envs/RSAIGE/bin/cmake', '--build', u'XXX/home/software/SAIGE/thirdParty/cget/cget/build/tmp-fc261a128cbf4130a5231856cb6585ca/build', '--config', 'Release', '--', '-j', '24']
Failed to build package statgen/savvy
#######################################

What I noticed is the message in the first part. On our system we do not have permisson to write on /tmp. Could this lead to the error in building the savvy package, and if so, how can this be fixed?  

My package versions are: 

cget, version 0.1.9
cmake version 3.14.0
Python 2.7.17 :: Anaconda, Inc.
R version 3.6.1
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

Any help is greatly appreciated!

kind regards, 
Matthias.

**Comment by weizhou0** [comment]
Hi Matthias, 

The website for xz downloading sometimes has hiccups. Could you please try the installation again? 

Thanks,
Wei

**Comment by MFutschik-ImperialCollege** [comment]
Dear Wei, 
thanks for picking up this issue. 
I rerun the installation (again without success). It does not seems that the downloading the xz file is a problem:

Downloading https://tukaani.org/xz/xz-5.2.3.tar.bz2
Extracting archive XXX/software/RSAIGE/SAIGE/thirdParty/cget/cget/build/tmp-4a0f8d6a2c6547238d2670d356a8e96a/xz-5.2.3.tar.bz2 ...

But now I get following error message before the installaiton (method 1) stops:
x86_64-conda_cos6-linux-gnu-c++: error: Fatal: No such file or directory
x86_64-conda_cos6-linux-gnu-c++: error: error:: No such file or directory
x86_64-conda_cos6-linux-gnu-c++: error: creating: No such file or directory
x86_64-conda_cos6-linux-gnu-c++: error: temporary: No such file or directory
x86_64-conda_cos6-linux-gnu-c++: error: file: No such file or directory
x86_64-conda_cos6-linux-gnu-c++: error: for: No such file or directory
make: *** [XXX/anaconda3/envs/RSAIGE/lib/R/share/make/shlib.mk:6: SAIGE.so] Error 1:

I attached the full output for the R installation process below. 

Any idea what could be the problem?

kind regards, 
Matthias. 

###############################################################

* installing to library ‘XXX/anaconda3/envs/RSAIGE/lib/R/library’
* installing *source* package ‘SAIGE’ ...
** using staged installation
Fatal error: creating temporary file for '-e' failed
Downloading https://github.com/statgen/savvy/archive/5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz
Extracting archive XXX/software/RSAIGE/SAIGE/thirdParty/cget/cget/build/tmp-854ee1f962324a738a9444add2834d89/5cf549634d535c07f08af4e52de67ecbf960d78e.tar.gz ...
Downloading https://github.com/jonathonl/shrinkwrap/archive/v1.0.0-beta.tar.gz
Extracting archive XXX/software/RSAIGE/SAIGE/thirdParty/cget/cget/build/tmp-36c9e3a34b6d4c0ea1f7bad0b259d9dc/v1.0.0-beta.tar.gz ...
Downloading https://tukaani.org/xz/xz-5.2.3.tar.bz2
Extracting archive XXX/software/RSAIGE/SAIGE/thirdParty/cget/cget/build/tmp-4a0f8d6a2c6547238d2670d356a8e96a/xz-5.2.3.tar.bz2 ...
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: XXX/anaconda3/envs/RSAIGE/bin/x86_64-conda_cos6-linux-gnu-cc
-- Check for working C compiler: XXX/anaconda3/envs/RSAIGE/bin/x86_64-conda_cos6-linux-gnu-cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: XXX/anaconda3/envs/RSAIGE/bin/x86_64-conda_cos6-linux-gnu-c++
-- Check for working CXX compiler: XXX/anaconda3/envs/RSAIGE/bin/x86_64-conda_cos6-linux-gnu-c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

XZ Utils 5.2.3

System type:
checking build system type... mkdir: cannot create directory '/tmp/cg19860-16294': Permission denied
mkdir: cannot create directory '/tmp/cg-19860': Permission denied
config.guess: cannot create a temporary directory in /tmp
configure: error: cannot guess build type; you must specify one
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING
    CGET_CMAKE_DIR
    CGET_CMAKE_ORIGINAL_SOURCE_FILE


-- Build files have been written to: XXX/software/RSAIGE/SAIGE/thirdParty/cget/cget/build/tmp-4a0f8d6a2c6547238d2670d356a8e96a/build
Scanning dependencies of target xz
[100%] Building xz ...
make[3]: *** No targets specified and no makefile found.  Stop.
make[2]: *** [CMakeFiles/xz.dir/build.make:58: CMakeFiles/xz] Error 2
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/xz.dir/all] Error 2
gmake: *** [all] Error 2
Command failed: ['XXX/anaconda3/envs/RSAIGE/bin/cmake', '--build', u'XXX/software/RSAIGE/SAIGE/thirdParty/cget/cget/build/tmp-4a0f8d6a2c6547238d2670d356a8e96a/build', '--config', 'Release', '--', '-j', '24']
Failed to build package statgen/savvy
Setting top to                           : XXX/software/RSAIGE/SAIGE/thirdParty/bgen 
Setting out to                           : XXX/software/RSAIGE/SAIGE/thirdParty/bgen/build 
Checking for 'gcc' (C compiler)          : XXX/anaconda3/envs/RSAIGE/bin/x86_64-conda_cos6-linux-gnu-cc 
Checking for 'g++' (C++ compiler)        : XXX/anaconda3/envs/RSAIGE/bin/x86_64-conda_cos6-linux-gnu-c++ 
zlib                                     : yes 
rt                                       : yes 
pthread                                  : yes 
dl                                       : yes 
'configure' finished successfully (1.957s)
Waf: Entering directory `XXX/software/RSAIGE/SAIGE/thirdParty/bgen/build'
Creating release build...
[73/84] Creating build/bgen_revision_autogenerated.hpp
[74/84] Compiling src/IndexQuery.cpp
[75/84] Compiling src/MissingValue.cpp
[76/84] Compiling src/View.cpp
[77/84] Compiling src/bgen.cpp
[78/84] Compiling src/zlib.cpp
Waf: Leaving directory `XXX/software/RSAIGE/SAIGE/thirdParty/bgen/build'
'build' finished successfully (2.068s)
** libs
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -shared -LXXX/anaconda3/envs/RSAIGE/lib/R/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,XXX/anaconda3/envs/RSAIGE/lib -Wl,-rpath-link,XXX/anaconda3/envs/RSAIGE/lib -LXXX/anaconda3/envs/RSAIGE/lib -LXXX/anaconda3/envs/RSAIGE/lib -Wl,-rpath-link,XXX/anaconda3/envs/RSAIGE/lib -o SAIGE.so RcppExports.o test.o matrixMultiEigen.o SAIGE_fitGLMM_fast.o SAIGE_readDosage_bgen.o SAIGE_readDosage_vcf.o SAIGE_GENE_readDosageMatrix_vcf.o ../thirdParty/bgen/build/src/IndexQuery.cpp.2.o ../thirdParty/bgen/build/src/MissingValue.cpp.2.o ../thirdParty/bgen/build/src/bgen.cpp.2.o ../thirdParty/bgen/build/src/zlib.cpp.2.o ../thirdParty/bgen/build/src/View.cpp.2.o ../thirdParty/bgen/build/db/libdb.a ../thirdParty/bgen/build/3rd_party/zstd-1.1.0/libzstd.a ../thirdParty/bgen/build/3rd_party/sqlite3/libsqlite3.a ../thirdParty/bgen/build/3rd_party/boost_1_55_0/libboost.a -LXXX/anaconda3/envs/RSAIGE/lib/R/lib -lRlapack -LXXX/anaconda3/envs/RSAIGE/lib/R/lib -lRblas -lgfortran -lm -lgomp -lquadmath -lpthread -L../bgen/3rd_party/boost_1_55_0/boost/iostreams -L../thirdParty/cget/lib/ -L../thirdParty/cget/lib64/ -lsavvy -lhts -lsuperlu Fatal error: creating temporary file for -e failed -LXXX/anaconda3/envs/RSAIGE/lib/R/lib -lR
x86_64-conda_cos6-linux-gnu-c++: error: Fatal: No such file or directory
x86_64-conda_cos6-linux-gnu-c++: error: error:: No such file or directory
x86_64-conda_cos6-linux-gnu-c++: error: creating: No such file or directory
x86_64-conda_cos6-linux-gnu-c++: error: temporary: No such file or directory
x86_64-conda_cos6-linux-gnu-c++: error: file: No such file or directory
x86_64-conda_cos6-linux-gnu-c++: error: for: No such file or directory
make: *** [XXX/anaconda3/envs/RSAIGE/lib/R/share/make/shlib.mk:6: SAIGE.so] Error 1
ERROR: compilation failed for package ‘SAIGE’
* removing ‘XXX/anaconda3/envs/RSAIGE/lib/R/library/SAIGE’

**Comment by matuskosut** [comment]
Hi @MFutschik-ImperialCollege , do you have proper permission to /tmp and enough space left on that partition?
```
mkdir: cannot create directory '/tmp/cg19860-16294': Permission denied
mkdir: cannot create directory '/tmp/cg-19860': Permission denied
config.guess: cannot create a temporary directory in /tmp
```
followed with:
```
Fatal error: creating temporary file for -e failed -LXXX/anaconda3/envs/RSAIGE/lib/R/lib -lR
```

**Comment by MFutschik-ImperialCollege** [comment]
Thanks for the observation. I was already following up this error message and indeed it was the case that (within the screen session I was running) the path to the temporary directory (which is not the default one on our system) was unset. For me, NOT using screen for installation, fixed the error. So all good now.
