### ISSUE TITLE
Error: package ‘SPAtest’ 3.0.2 was found, but == 3.1.2 is required by ‘SAIGE’

### ISSUE THREAD

**Issue by xiekunwhy** [weizhouUMICH/SAIGE#245]
Hi,

When I install SAIGE using devtools::install_github("weizhouUMICH/SAIGE"), I got the following errors,
Error: package ‘SPAtest’ 3.0.2 was found, but == 3.1.2 is required by ‘SAIGE’

But I found that the latest version of SPAtest is 3.0.2, is there something wrong?

Best,
Kun

**Comment by matuskosut** [comment]
@xiekunwhy no one dared to request an update on cran, here just a few days ago finally 3.1.2 available: https://cran.r-project.org/web/packages/SPAtest/index.html

Otherwise previous recommendation was to use installation from repository https://github.com/leeshawn/SPAtest:
```
Rscript -e 'devtools::install_github("leeshawn/SPAtest")'
```

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
