### ISSUE TITLE
Error on step 2 of SAIGE-Gene

### ISSUE THREAD

**Issue by Kateahn** [weizhouUMICH/SAIGE#247]
Hi Wei,

I am running the step 2 of SAIGE-Gene (SAIGE 0.39.4), and had the following error message. 
It will be appreciated if you could help me to resolve this issue. 

Thanks,
Kate 

++++++++++++++++++++
Error in GratioMatrixall[1:m, 1:m] : subscript out of bounds
Calls: SPAGMMATtest ... groupTest -> system.time -> SAIGE_SKAT_withRatioVec
Timing stopped at: 0

**Comment by weizhouUMICH** [comment]
Hi Kate, 

The error might be because markers do not have a corresponding variance ratio estimated. Can you please provide more details of the log file for this gene? 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
