### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'  what():  std::bad_alloc

### ISSUE THREAD

**Issue by endrebak** [weizhouUMICH/SAIGE#25]
```
During startup - Warning message:
Setting LC_CTYPE failed, using "C"
Warning message:
package 'SAIGE' was built under R version 3.4.3
24  threads are set to be used
69716  samples have genotypes
formula is  LDL~Sex+batch+BirthYear+PC1+PC2+PC3+PC4
54888  samples have non-missing phenotypes
14828  samples in geno file do not have phenotypes
54888  samples will be used for analysis
colnames(data.new) is  Y minus1 Sex batch BirthYear PC1 PC2 PC3 PC4
out.transform$Param.transform$qrr:  8 8
LDL  is a quantitative trait
[1] "Start reading genotype plink file here"
nbyte: 17429
nbyte: 13722
reserve: 3427555328

M: 249749, N: 69716
size of genoVecofPointers: 2
here
2terminate called after throwing an instance of 'std::bad_alloc'
 what():  std::bad_alloc
```

Do you have an idea what might cause this? We're using 0.26. We have restarted the run with `memoryChunk=0.5`, we used 2 when the error above occured.

**Comment by weizhouUMICH** [comment]
The memoryChunk option is for large Plink files. Before this option was implemented, genotypes from the specified plink file are stored in a binary vector, which takes continuous memory. For large plink files, we intend to used multiple binary vectors to avoid the usage of the very large continuous memory. "memoryChunk" is to set the size of each smaller binary vector. The error above can occur when the machine you use does not have two 2Gb continuous memory chunks available.
