### ISSUE TITLE
Requesting tags for versions

### ISSUE THREAD

**Issue by CanWood** [weizhouUMICH/SAIGE#250]
Hi folks,

When reading the documentation, I see references to using `src_branch=0.39.2` to grab specific versions and that `Current version is 0.42.1`. but when reviewing existing tags and releases, there seems to be no recent ones.  In the interests of reproducability, would your team consider tagging versions when they are at a point that you consider to be "that version"?  Short of getting the git revision of the `DESCRIPTION` file where the comment is "`update doc for 0.x.y`", and checking that out, I'm not sure i'm actually using a given version number.

Thanks!

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
