### ISSUE TITLE
Pan-UKB chrX data looks weird

### ISSUE THREAD

**Issue by Shicheng-Guo** [weizhouUMICH/SAIGE#252]
Dear Wei, 

I notice you are also the key team member of Pan-UKB. I find a weird thing.  I checked there were 4 million SNPs in chrX in UKB imputation data, however, only about 913,562 SNPs in summary statistics from Pan-UKB project, >75% are lost in the final summary statistics indicating there is very strong filtering for chrX. Really want to know what kind of criterion could make such strong selection in chrX. Hope to receive some reply. Thanks. 

Shicheng

![image](https://user-images.githubusercontent.com/6641283/95641985-b2ab0000-0a73-11eb-896d-d54c9d5e9572.png)

**Comment by weizhou0** [comment]
Dear @Shicheng-Guo, 

Thanks for the question! Will get back to you asap. 

Wei
