### ISSUE TITLE
Error in FitNullGLMM: unused arguments (sexCol = opt$sexCol...)

### ISSUE THREAD

**Issue by Apb58** [weizhouUMICH/SAIGE#253]
Hi Wei,

I have just downloaded the latest version (0.42.1) and tried running the example code from the Wiki to fit the null linear model for the quantitative trait condition for a single variant association test. Below is the command:

```
Rscript SAIGE/extdata/step1_fitNULLGLMM.R \
        --plinkFile=SAIGE/extdata/input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly \
        --phenoFile=SAIGE/extdata/input/pheno_1000samples.txt_withdosages_withBothTraitTypes.txt \
        --phenoCol=y_quantitative \
        --covarColList=x1,x2 \
        --sampleIDColinphenoFile=IID \
        --traitType=quantitative       \
	--invNormalize=TRUE	\
        --outputPrefix=example_quantitative \
        --nThreads=4 \
        --LOCO=FALSE	\
	--tauInit=1,0
```

The script immediately exits with:

```
Warning message:
In getopt(spec = spec, opt = args) : long flag LOCO given a bad argument
$plinkFile
[1] "SAIGE/extdata/input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly"

$phenoFile
[1] "SAIGE/extdata/input/pheno_1000samples.txt_withdosages_withBothTraitTypes.txt"

$phenoCol
[1] "y_quantitative"

$traitType
[1] "quantitative"

$invNormalize
[1] TRUE

$covarColList
[1] "x1,x2"

$sampleIDColinphenoFile
[1] "IID"

$tol
[1] 0.02

$maxiter
[1] 20

$tolPCG
[1] 1e-05

$maxiterPCG
[1] 500

$nThreads
[1] 4

$SPAcutoff
[1] 2

$numRandomMarkerforVarianceRatio
[1] 30

$skipModelFitting
[1] FALSE

$memoryChunk
[1] 2

$tauInit
[1] "0,0"

$LOCO
[1] NA

$traceCVcutoff
[1] 0.0025

$ratioCVcutoff
[1] 0.001

$outputPrefix
[1] "example_quantitative"

$IsOverwriteVarianceRatioFile
[1] FALSE

$IsSparseKin
[1] FALSE

$numRandomMarkerforSparseKin
[1] 2000

$isCateVarianceRatio
[1] FALSE

$relatednessCutoff
[1] 0.125

$cateVarRatioMinMACVecExclude
[1] "0.5,1.5,2.5,3.5,4.5,5.5,10.5,20.5"

$cateVarRatioMaxMACVecInclude
[1] "1.5,2.5,3.5,4.5,5.5,10.5,20.5"

$isCovariateTransform
[1] TRUE

$isDiagofKinSetAsOne
[1] FALSE

$useSparseSigmaConditionerforPCG
[1] FALSE

$useSparseSigmaforInitTau
[1] FALSE

$minMAFforGRM
[1] 0.01

$minCovariateCount
[1] -1

$includeNonautoMarkersforVarRatio
[1] FALSE

$FemaleOnly
[1] FALSE

$MaleOnly
[1] FALSE

$sexCol
[1] ""

$FemaleCode
[1] "1"

$MaleCode
[1] "0"

$noEstFixedEff
[1] FALSE

$help
[1] FALSE

tauInit  is  0 0 
cateVarRatioMinMACVecExclude  is  0.5 1.5 2.5 3.5 4.5 5.5 10.5 20.5 
cateVarRatioMaxMACVecInclude  is  1.5 2.5 3.5 4.5 5.5 10.5 20.5 
Error in fitNULLGLMM(plinkFile = opt$plinkFile, phenoFile = opt$phenoFile,  : 
  unused arguments (sexCol = opt$sexCol, FemaleCode = opt$FemaleCode, FemaleOnly = opt$FemaleOnly, MaleCode = opt$MaleCode, MaleOnly = opt$MaleOnly, noEstFixedEff = opt$noEstFixedEff)
Execution halted
```

Any thoughts?

**Comment by weizhou0** [comment]
Hi @Apb58, 

It seems the SAIGE version that you are using does not have those arguments implemented. 
Can you please check the version of SAIGE? It should be shown in the first few lines of the log message. 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei

**Comment by williajb02** [comment]
Was there ever a solution proposed to this problem. I have the same issue and am running SAIGE_1.1.5 having followed the prompts at https://github.com/saigegit/SAIGE

**Comment by chaudhry123** [comment]
Was there ever a solution, Error in fitNULLGLMM(plinkFile = opt$plinkFile, phenoFile = opt$phenoFile,  : 
  unused arguments (IsSparseKin = opt$IsSparseKin, useSparseSigmaConditionerforPCG = opt$useSparseSigmaConditionerforPCG, useSparseSigmaforInitTau = opt$useSparseSigmaforInitTau, noEstFixedEff = opt$noEstFixedEff)
Execution halted. Package is not functioning

**Comment by jinheong** [comment]
> Was there ever a solution, Error in fitNULLGLMM(plinkFile = opt$plinkFile, phenoFile = opt$phenoFile, : unused arguments (IsSparseKin = opt$IsSparseKin, useSparseSigmaConditionerforPCG = opt$useSparseSigmaConditionerforPCG, useSparseSigmaforInitTau = opt$useSparseSigmaforInitTau, noEstFixedEff = opt$noEstFixedEff) Execution halted. Package is not functioning

Same problem when trying to run SAIGE_v0.44.6.2 on a remote server. I even did not specify the arguments that were reported to be unused.
