### ISSUE TITLE
The impact of MAF filter on constructing GRM and estimating variance ratio

### ISSUE THREAD

**Issue by ypnngaa-py** [weizhouUMICH/SAIGE#256]
Hi,
Is there documentation on how to choose `minMAFforGRM` for single-variance analysis? I noticed the default is 0.01. But I am not sure in what cases we are recommended to use it. 
For a data set with 10k samples with WES called SNPs, I noticed using the default MAF>0.01 vs MAF>0 makes a huge difference in estimated variance ratio, genomic inflation factor(lambda) and the final result. Specifically, the default MAF>0.01 is actually causing the lambda to be much less than 1 (0.7-0.8) while the MAF>0 returned just fine (lambda=1.02). Should I adjust `minMAFforGRM` based on lambda?  Thanks!

**Comment by weizhou0** [comment]
Hi @ypnngaa-py, 

I think MAF> 1% is the right one to use. Can you please try the job with LOCO=T? 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
