### ISSUE TITLE
Error running step 2 with VCF

### ISSUE THREAD

**Issue by FinSalMar** [weizhouUMICH/SAIGE#26]
**My script is as follows (see below). How do I solve this error, (also below)? I do not specify a dosage file, but the default setting seem to look for one.**

```
Rscript step2_SPAtests.R \
        --vcfFile=VCF.file.vcf \
        --vcfField=GT \
        --chrom=$number \
        --minMAF=0.0001 \
        --minMAC=1 \
        --GMMATmodelFile=file.chr$number.rda \
        --varianceRatioFile=file.chr$number.varianceRatio.txt \
        --SAIGEOutputFile=out.file.chr$number \
        --numLinesOutput=2 \
        --IsOutputAFinCaseCtrl=TRUE
```

**I get this error:**

Warning message:
package ‘SAIGE’ was built under R version 3.4.3 
$dosageFile
[1] ""

$dosageFileNrowSkip
[1] 0

$dosageFileNcolSkip
[1] 5

$dosageFilecolnamesSkip
[1] ""

$vcfFile
[1] "file.vcf"

$vcfFileIndex
[1] ""

$vcfField
[1] "GT"

$bgenFile
[1] ""

$bgenFileIndex
[1] ""

$savFile
[1] ""

$savFileIndex
[1] ""

$chrom
[1] "1"

$start
[1] 1

$end
[1] 2.5e+08

$minMAF
[1] 1e-04

$minMAC
[1] 1

$sampleFile
[1] ""

$GMMATmodelFile
[1] "/mnt/users/masincla/aquagen_data/SAIGE/output/file.rda"

$varianceRatioFile
[1] "/mnt/users/masincla/aquagen_data/SAIGE/output/file.varianceRatio.txt"

$SAIGEOutputFile
[1] "output/file"

$numLinesOutput
[1] 2

$IsOutputAFinCaseCtrl
[1] TRUE

$help
[1] FALSE

Error in try(if (length(which(opt == "")) > 0) stop("Missing arguments")) : 
  Missing arguments
11115  samples have been used to fit the glmm null model
variance Ratio is  0.222 
Error in SPAGMMATtest(dosageFile = opt$dosageFile, dosageFileNrowSkip = opt$dosageFileNrowSkip,  : 
  ERROR! sampleFile  does not exsit

**Comment by byenj** [comment]
As the error message suggested, you need to provide sampleFile, which is a single column text file, containing the sample ids **in the same order** as in your vcf file header line

**Comment by mswaters** [comment]
Thanks - I have added a sample file, however, it still seems to be looking for dosages when I have specified GT. 

**ERROR:**
Error in try(if (length(which(opt == "")) > 0) stop("Missing arguments")) : 
  Missing arguments
11115  samples have been used to fit the glmm null model
variance Ratio is  0.234 
11257  sample IDs are found in sample file
Error in SPAGMMATtest(dosageFile = opt$dosageFile, dosageFileNrowSkip = opt$dosageFileNrowSkip,  : 
  ERROR!2724 samples used in glmm model fit do not have dosages
Execution halted

**INPUT:**
```
Rscript step2_SPAtests.R \
--vcfFile=file.vcf \
--vcfFileIndex=file.vcf.gz.tbi \
--vcfField=GT \
--chrom=1 \
--minMAF=0.0001 \
--minMAC=1 \
--sampleFile=sample.file.txt \
--GMMATmodelFile=file.rda \
--varianceRatioFile=file.varianceRatio.txt \
--SAIGEOutputFile=out.file \
--numLinesOutput=2 \
--IsOutputAFinCaseCtrl=TRUE
```

**Comment by weizhouUMICH** [comment]
SAIGE requires that all samples used in glmm model fit (step 1) have non-missing phenotypes and non-missing dosages.

**Comment by JingatSanger** [comment]
> SAIGE requires that all samples used in glmm model fit (step 1) have non-missing phenotypes and non-missing dosages.

Dear author,

I am having the same ERROR as shown in this thread. Would you please provide further advice about how to check if the input PLINK file for step1 have non-missing dosages?

Thanks!
VJ

**Comment by JingatSanger** [comment]
> SAIGE requires that all samples used in glmm model fit (step 1) have non-missing phenotypes and non-missing dosages.

Dear author,

I am having the same ERROR as shown in this thread. Would you please provide further advice about how to check if the input PLINK file for step1 have non-missing dosages?

Thanks!
VJ

**Comment by AfzalBioinfo** [comment]
On 2nd Step, we tried to run the below command with our data of index file and input file

Rscript step2_SPAtests.R **--vcfFile=./input/plate_1_to_6.vcf.gz --vcfFileIndex=./input/plate_1_to_6_dec_rec_ped_bprob.vcf.gz.tbi** -- vcfField=GT --chrom=chrX --minMAF=0.0001 --minMAC=1 --sampleFile=./input/plate_1_to_6_dec_rec_ped_bprob_samples.txt --GMMATmodelFile=./output/plate_1_to_6_dec_rec_ped_bprob_pheno_step1.rda --varianceRatioFile=./output/plate_1_to_6_dec_rec_ped_bprob_pheno_step1.varianceRatio.txt --SAIGEOutputFile=./output/plate_1_to_6_dec_rec_ped_bprob_pheno_step2.SAIGE.vcf.dosage.txt --numLinesOutput=2 --IsOutputAFinCaseCtrl=TRUE

**We are getting below error:**

weights.beta.rare  is  1 25
weights.beta.common  is  1 25
cateVarRatioMinMACVecExclude  is  0.5 1.5 2.5 3.5 4.5 5.5 10.5 20.5
cateVarRatioMaxMACVecInclude  is  1.5 2.5 3.5 4.5 5.5 10.5 20.5
single-variant association test will be performed
Garbage collection 14 = 8+2+4 (level 2) ...
79.1 Mbytes of cons cells used (59%)
19.8 Mbytes of vectors used (31%)
414  samples have been used to fit the glmm null model
[1] "Leave-one-chromosome-out is not applied"
Single variance ratio is provided, so categorical variance ratio won't be used!
variance Ratio is  0.9662084
isCondition is  FALSE
Open VCF done
To read the field DS
Number of meta lines in the vcf file (lines starting with ##): 61
Number of samples in in the vcf file: 414
Variant is missing requested data format type.
414  sample IDs are found in the vcf file
Error in SPAGMMATtest(vcfFile = opt$vcfFile, vcfFileIndex = opt$vcfFileIndex,  :
  **ERROR!414 samples used in glmm model fit do not have dosages**
**Execution halted**


If anyone can help us to solve this error.

**Comment by privefl** [comment]
I had the same issue.
For some reason, the VCF file converted the sample IDs to `<FID>_<IID>`.
Then, to solve this issue, you can `load()` the `.rda` file from Step1, change `$sampleID` accordingly, and `save()` it again.
