### ISSUE TITLE
Modified SPAtest to use for SAIGE

### ISSUE THREAD

**Issue by palVJ** [weizhouUMICH/SAIGE#261]
Hi,

if I have a modified SPAtest package, meaning the functions have been modified, but the structureis the same, how much work would it be to run SAIGE based on this modified package?

Is it enough to make an own package "ModifiedSPAtest" and include this as a dependency (in LinkingTo:) in the DESCRIPTION-file?

**Comment by weizhouUMICH** [comment]
Hi palVJ,

You will need to add ModifiedSPAtest in the DESCRIPTION file and change the
command lines here
https://github.com/weizhouUMICH/SAIGE/blob/master/R/SAIGE_SPATest.R#L2088

Thanks,
Wei

**Comment by palVJ** [comment]
Thank you very much,

best,
Pål

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
