### ISSUE TITLE
'gettimeofday' was not declared

### ISSUE THREAD

**Issue by matuskosut** [weizhouUMICH/SAIGE#265]
Get error during compilation on master:

```
SAIGE_fitGLMM_fast.cpp: In function 'double get_wall_time()':
SAIGE_fitGLMM_fast.cpp:1723:9: error: 'gettimeofday' was not declared in this scope
     if (gettimeofday(&time,NULL)){
         ^~~~~~~~~~~~
```

Proposed fix: https://github.com/weizhouUMICH/SAIGE/pull/264

Boost is perhaps more portable, but alternative to proposed PR would be to import sys/time.h:
```
#include <sys/time.h>
```

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
