### ISSUE TITLE
missing return clauses in non-void c++ functions fills up the RAM

### ISSUE THREAD

**Issue by laurent-ntnu** [weizhouUMICH/SAIGE#266]
Hi Wei,

When I run SAIGE, step2 gets stuck in function `SetSampleIdx` in file `src/SAIGE_readDosage_bgen.cpp` and fills up the RAM until it is full and the process gets killed. It seems to happen in ubuntu 20 but not in 18 or 16.

`SetSampleIdx` is defined as returning an `int` but does not have a return clause. I am not sure what it is returning in that case, maybe a pointer to the heap? I think the return value is used by `Rcpp::wrap()` and tries to convert is to R and allocates recursively.

Adding `return(0);` at the end of the function seems to solve the problem.
Could you add return clauses to your c++ non-void functions or define them as void, please?

Thanks

**Comment by matuskosut** [comment]
@laurent-ntnu could you try if it would work with this patch? https://raw.githubusercontent.com/bioconda/bioconda-recipes/master/recipes/r-saige/patches/0002-fix-rcpp-returns.patch

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
