### ISSUE TITLE
step4 installation new error

### ISSUE THREAD

**Issue by Esther19960123** [weizhouUMICH/SAIGE#270]
I meet an error when I install SAIGE as the step 4 described . Anyone who know it ?
Ubuntu 18.04.5
r=3.6.1 python=2.7
error : 
/mnt/ukb_data/ltt/anaconda3/envs/tsaige/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lsavvy
/mnt/ukb_data/ltt/anaconda3/envs/tsaige/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lhts
/mnt/ukb_data/ltt/anaconda3/envs/tsaige/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lsuperlu
collect2: error: ld returned 1 exit status
/mnt/ukb_data/ltt/anaconda3/envs/tsaige/lib/R/share/make/shlib.mk:6: recipe for target 'SAIGE.so' failed
make: *** [SAIGE.so] Error 1
ERROR: compilation failed for package ‘SAIGE’

**Comment by matuskosut** [comment]
Hi @Esther19960123 
you probably don't have cget installed, you could confirm if you look a bit up in the log where savvy is actually installed.

**Comment by Esther19960123** [comment]
> Hi @Esther19960123
> you probably don't have cget installed, you could confirm if you look a bit up in the log where savvy is actually installed.
> 
> ```
> python3 -m pip install --user cget
> ```
> 
> or:
> 
> ```
> conda install -n root -c conda-forge cget
> ```

Thank you so much. I would try as you recommend. I am so sorry for missing your reply for a long time

**Comment by Esther19960123** [comment]
> > Hi @Esther19960123
> > you probably don't have cget installed, you could confirm if you look a bit up in the log where savvy is actually installed.
> > ```
> > python3 -m pip install --user cget
> > ```
> > 
> > 
> > or:
> > ```
> > conda install -n root -c conda-forge cget
> > ```
> 
> Thank you so much. I would try as you recommend. I am so sorry for missing your reply for a long time

I have checked that I didn't install savvy at all which is not accessed anaconda

**Comment by matuskosut** [comment]
@Esther19960123 you may need to add bioconda channel and then you could try my new package SAIGE: https://github.com/weizhouUMICH/SAIGE/issues/272
```
conda config --add channels bioconda
```

**Comment by Esther19960123** [comment]
> @Esther19960123 you may need to add bioconda channel and then you could try my new SAIGE package: #272
> 
> ```
> conda config --add channels bioconda
> conda config --add channels conda-forge
> ```
> 
> PS: savvy is also in bioconda, and it's also important to re-add conda-forge after adding bioconda

You are the sweetest！

**Comment by kavitashah** [comment]
@matuskosut : Can u please help me installation of SAIGE. I am unable to install.

**Comment by matuskosut** [comment]
@kavitashah have you checked the info in the issue https://github.com/weizhouUMICH/SAIGE/issues/272 ?

**Comment by kavitashah** [comment]
@matuskosut : thanks installed finally. 272 worked. Thanks again

**Comment by kavitashah** [comment]
@matuskosut : Could you help me with following error

I am running the script
Rscript step1_fitNULLGLMM.R     \
        --plinkFile=./input/dr \
        --phenoFile=./input/dr_0_pheno.txt \
        --phenoCol=trait \
        --covarColList=trait,IID \
        --sampleIDColinphenoFile=IID \
        --traitType=binary        \
        --outputPrefix=./output/dr \
        --nThreads=4	\
	--LOCO=FALSE	\
	--minMAFforGRM=0.01
and getting error


[1]   0 NaN
tau:  1 Inf
tau0:  1 0.1
Error in if (max(abs(tau - tau0)/(abs(tau) + abs(tau0) + tol)) < tol) break :
  missing value where TRUE/FALSE needed
Calls: fitNULLGLMM -> system.time -> glmmkin.ai_PCG_Rcpp_Binary
In addition: Warning messages:
1: In model.matrix.default(formula, data = data) :
  the response appeared on the right-hand side and was dropped
2: In model.matrix.default(formula, data = data) :
  problem with term 1 in model.matrix: no columns are assigned
3: In model.matrix.default(formula, data = data) :
  the response appeared on the right-hand side and was dropped
4: In model.matrix.default(formula, data = data) :
  problem with term 1 in model.matrix: no columns are assigned
5: glm.fit: algorithm did not converge
Timing stopped at: 1301 302.5 309.8
Execution halted

**Comment by kavitashah** [comment]
Can anyone please help me in solving this issue.

414  samples were used in fitting the NULL glmm model and are found in sample file
sparse kinship matrix is not used
Missing dosages will be mean imputed for the analysis
Analysis started at  1618927584 Seconds
minMAC:  1
minMAF:  1e-04
Minimum MAF of markers to be tested is  0.001207729
It is a binary trait
Analyzing  94  cases and  320  controls
isCondition is  FALSE
Analysis started at  1618927584 Seconds
Warning: missing FMT field (DS)
Error in if (markerInfo >= 0 & markerInfo <= 1) { :
  argument is of length zero
Calls: SPAGMMATtest
Execution halted

**Comment by matuskosut** [comment]
@kavitashah you might be better of creating a separate issue. This is old issue specific to step4.
I myself only handle packaging of saige to conda - I am not from genomics field - pure computer science.

So my best advice is to search for issues that are asking about the same step as you (e.g. step1) and had same problem and maybe you will find the solution. 

Second best advice is to try different versions of r-saige (for conda you can base on the numbers mentioned in this list https://anaconda.org/bioconda/r-saige/files)

**Comment by kavitashah** [comment]
Thank you for your reply. Sure will try your suggestions.

Kind regards
Indra

**Comment by kavitashah** [comment]
R: /home/afzal/miniconda3/envs/saige/lib/R/library/RcppEigen/include/Eigen/src/Core/Product.h:95: Eigen::Product<Lhs, Rhs, Option>::Product(const Lhs&, const Rhs&) [with _Lhs = Eigen::Map<Eigen::Matrix<double, -1, -1> >; _Rhs = Eigen::Map<Eigen::Matrix<double, -1, -1> >; int Option = 0; Eigen::Product<Lhs, Rhs, Option>::Lhs = Eigen::Map<Eigen::Matrix<double, -1, -1> >; Eigen::Product<Lhs, Rhs, Option>::Rhs = Eigen::Map<Eigen::Matrix<double, -1, -1> >]: Assertion `lhs.cols() == rhs.rows() && "invalid matrix product" && "if you wanted a coeff-wise or a dot product use the respective explicit functions"' failed.
Aborted (core dumped)
 Got this issue. Can anyone help me out please.

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
