### ISSUE TITLE
How to get single marker R2 according to SAIGE results?

### ISSUE THREAD

**Issue by xiekunwhy** [weizhouUMICH/SAIGE#275]
Hi,

How to get single marker R2 according to SAIGE results, can I use formula R2 = 2p(1-p)*BETA^2, where p is frequency of one allele?

Best,
Kun

**Comment by weizhou0** [comment]
Hi Kun, 

By R2, do you mean the variance of phenotypes explained by the marker? 

Wei

**Comment by xiekunwhy** [comment]
Hi Wei,

Yes, I mean the variance of phenotypes explained by a single marker.

Best,
Kun

**Comment by weizhou0** [comment]
Hi Kun,

The absolute value of p(1-p)*beta^2 is not equal to R2, unless the variance
of the phenotype is 1, e.g if the quantitative phenotype is inverse
normalized.

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
