### ISSUE TITLE
Getting SAIGE-Gene Step 2 to go faster?

### ISSUE THREAD

**Issue by apoliakov** [weizhouUMICH/SAIGE#277]
Hi @weizhouUMICH !

I wanted to check with you on how Step 2 of SAIGE-Gene could potentially be sped up. I'm seeing that, the bigger the "gene size" (number of variants in a single gene / list) the more work it is to compute.

For example, if I take a dataset of ~200,000 variants and ~300,000 people and I split it into lists with 1,000-2,000 variants each, then I can scatter the calculation across a cluster of machines and the slowest finishes in less than 3 hours (for one phenotype, excluding the Step 1 time).

However, if I have ~200,000 variants split into lists with ~10,000 variants each (big genes! so about 20 lists total) then after 30 hours only about 50% of them are completed. It also looks like the thing uses about 20-50GB RAM per list but only one CPU core. So that makes it a bit "cost-unfriendly" in the cloud. They usually don't sell boxes with 1 core and 50GB RAM so you end up paying for cores you're not using.

This is on SAIGE 0.36.6

What do you think?

1) Are these numbers about expected or am I doing something crazy wrong?
2) Would updating to the latest version speed us up? By a lot?
3) What about BLAS? It seems like some parts of step 2 use BLAS but I'm not seeing a lot of that in some initial testing? Do you recommend something like OpenBLAS or MKL turned on? And how many threads?
4) Any other recommendations?

Thanks as always!

**Comment by matuskosut** [comment]
Hi @apoliakov 

I would be interested if you could try to compare the latest saige version from bioconda (https://github.com/weizhouUMICH/SAIGE/issues/272). I was creating that package pretty recently and so the latest 0.42.1 is available there. The dependencies are compiled with much newer versions of boost than the default setup here is using and it installs with blas (it is mainly linked to eigen3 dependency as far I remember).

Plus if you are looking into higher performance in cloud, maybe you could compare with Regenie? It is a full C++ implementation from Regeneron team and it provides pretty similar options for gwas analysis: https://rgcgithub.github.io/regenie/options/
I packaged it into conda: https://anaconda.org/bioconda/regenie but they also provide docker option.

Unfortunately I am not a researcher, so I don't usually run these big analysis so I hope Wei will address your questions.

**Comment by apoliakov** [comment]
Hi @matuskosut - nice to meet you.

I believe that Regenie is a single-variant test (outputting one result per variant). So that is analogous to SAIGE. But here I am talking about SAIGE-Gene which is a gene-level (or list-level) test. The extra difficulty is that some genes are much bigger than others. That accounts for a lot of the problem. And of course the meaning of the computation is different.

Thanks for the pointer to bioconda SAIGE. I might try a small test and if I succeed, I'll post numbers here. Cheers!

**Comment by weizhou0** [comment]
Hi @apoliakov, 

We are also aware of this problem. For large genes with thousands of markers, we think the most time/memory-consuming step is to get eigenvalues and eigenvectors for the m x m matrix, where m is the number is markers. We are currently working on solving this problem. 

Thanks,
Wei

**Comment by apoliakov** [comment]
Hi @weizhou0 . Interesting! So it looks like my numbers aren't far off from what's expected?
Maybe some approximate method like "irlba" would help? Or something similar...
Let us know if you have updates!

**Comment by apoliakov** [comment]
@weizhouUMICH happy to report that after testing 0.43 seems to be about 1.8x faster than 0.38. The profile across genes is still similar: big genes take much longer but the whole curve is "squished down" a bit.

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
