### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by Sathish9** [weizhouUMICH/SAIGE#278]
I am getting the following error"

** libs
g++ -std=gnu++11 -shared -L/gpfs1/scratch/90days/uqsperiy/software/R-4.0.3/lib64/R/lib -L/gpfs1/scratch/90days/uqsperiy/software/pcre-8.44/lib -o SAIGE.so RcppExports.o test.o matrixMultiEigen.o SAIGE_fitGLMM_fast.o SAIGE_readDosage_bgen.o SAIGE_readDosage_vcf.o SAIGE_GENE_readDosageMatrix_vcf.o ../thirdParty/bgen/build/src/IndexQuery.cpp.2.o ../thirdParty/bgen/build/src/MissingValue.cpp.2.o ../thirdParty/bgen/build/src/bgen.cpp.2.o ../thirdParty/bgen/build/src/zlib.cpp.2.o ../thirdParty/bgen/build/src/View.cpp.2.o ../thirdParty/bgen/build/db/libdb.a ../thirdParty/bgen/build/3rd_party/zstd-1.1.0/libzstd.a ../thirdParty/bgen/build/3rd_party/sqlite3/libsqlite3.a ../thirdParty/bgen/build/3rd_party/boost_1_55_0/libboost.a -L/gpfs1/scratch/90days/uqsperiy/software/R-4.0.3/lib64/R/lib -lRlapack -L/gpfs1/scratch/90days/uqsperiy/software/R-4.0.3/lib64/R/lib -lRblas -lgfortran -lm -lquadmath -L../bgen/3rd_party/boost_1_55_0/boost/iostreams -L../thirdParty/cget/lib/ -L../thirdParty/cget/lib64/ -lsavvy -lhts -lsuperlu -L/gpfs1/scratch/90days/uqsperiy/software/R-4.0.3/lib64/R/lib -lR
/usr/bin/ld: cannot find -lsavvy
/usr/bin/ld: cannot find -lhts
/usr/bin/ld: cannot find -lsuperlu
collect2: error: ld returned 1 exit status
make: *** [/gpfs1/scratch/90days/uqsperiy/software/R-4.0.3/lib64/R/share/make/shlib.mk:10: SAIGE.so] Error 1
ERROR: compilation failed for package ‘SAIGE’

I am using r version 4 GCC >7 and CMAKE higher than the specified version.

Regards,

Sathish

**Comment by weizhouUMICH** [comment]
Hi @Sathish9, 

Could you please try to use the conda to install? 
https://github.com/weizhouUMICH/SAIGE/issues/272

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
