### ISSUE TITLE
step2_SPAtests.R do nothing without --chrom parameters even --LOCO=FALSE

### ISSUE THREAD

**Issue by xiekunwhy** [weizhouUMICH/SAIGE#279]
Hi,

step2_SPAtests.R do nothing without --chrom parameters even --LOCO=FALSE, I think this is a bug!

Best,
Kun

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
