### ISSUE TITLE
Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) 

### ISSUE THREAD

**Issue by FinSalMar** [weizhouUMICH/SAIGE#28]
I am running Step 2 with a dosage file and I am unable to figure out how to trouble shoot this error. ANy ideas for how this can be fixed?

**Error:**
.....
numPassMarker:  50 
Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions
Calls: SPAGMMATtest ... Score_Test_Sparse -> colSums -> colSums -> <Anonymous>
Execution halted

**Input:**

```
Rscript step2_SPAtests.R \
--dosageFile=file.traw \
--dosageFileNrowSkip=1 \
--dosageFileNcolSkip=6 \
--dosageFilecolnamesSkip="CHR","SNP","(C)M","POS","COUNTED","ALT" \
--chrom=$number \
--minMAF=0.0001 \
--sampleFile=sample.file.txt \
--GMMATmodelFile=file.rda \
--varianceRatioFile=file.varianceRatio.txt \
--SAIGEOutputFile=output.file\
--numLinesOutput=2 \
--IsOutputAFinCaseCtrl=TRUE
```

**Comment by weizhouUMICH** [comment]
Are you using version 0.29?

**Comment by mswaters** [comment]
Version 0.26

**Comment by mswaters** [comment]
Yes, and it now works! Thanks

**Comment by mswaters** [comment]
Is LOCO now the default with v0.29?

**Comment by weizhouUMICH** [comment]
Yes, you may specify LOCO=TRUE for both steps to turn on the feature.
Please note currently this can only work for autosomal variants.

Wei Zhou
Ph.D. Candidate
Bioinformatic Program
University of Michigan-Ann Arbor
