### ISSUE TITLE
How to convert vcf file to bgen file?

### ISSUE THREAD

**Issue by AfzalBioinfo** [weizhouUMICH/SAIGE#280]
We are trying to convert vcf file to bgen file. But unable to find any resources for the same.

**Comment by dvh13** [comment]
https://www.well.ox.ac.uk/~gav/qctool_v2/

qctool_v2.0.8-CentOS_Linux7.6.1810-x86_64/qctool   -g your.vcf.gz -og your.bgen  -vcf-genotype-field GP -ofiletype bgen_v1.2 -bgen-bits 8

regards, david

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. 
It supports PLINK, VCF.BCF, BGEN and SAV. 
It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
