### ISSUE TITLE
Convergence issues

### ISSUE THREAD

**Issue by silviaadiz** [weizhouUMICH/SAIGE#281]
Hi!
I'm trying to fit my null models with two and four covariates, respectively. 
Both of them stopped at retry 10 (I'm guessing this was iteration 10/20?...) because large variance estimate was observed and models did not converge. I then increased the model tolerance to 0.025 but I'm not sure whether this will worsen my results. Is tolerance statistically crucial? I set 20 iterations but both model fittings stopped at 10th, so increasing tolerance may not work either (job is not done yet).

**EDIT**:  Before 10th iteration I got _tau: (1, 3.915726e+15), large variance estimate observed, retry (10) ..._ Should I increase the number of iterations? I do not know why variance is so large... Fitting the null already takes around 7h using 30 threads, so I'm willing to work with my data before retrying with more iterations. 

Also, I got the following warning, just in case it has anything to do: _Warning: arma::inv_sympd(), matrix is singular or not positive definite, use arma::inv() instead_

Thank you!

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
