### ISSUE TITLE
SPAGMMATtest IsOutput inCaseCtrl like output for group

### ISSUE THREAD

**Issue by mcolosimo-p4** [weizhouUMICH/SAIGE#282]
Hi,

Are you planning on adding options like `IsOutputAFinCaseCtrl` and `IsOutputNinCaseCtrl` to SPAGMMATtest for Genes (i.e., groupTests)? At a minimum we would like a number of carriers.

We are currently using v0.36.5.

Thanks,
Marc

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
