### ISSUE TITLE
Error in R/SAIGE_SPATest.R:1865

### ISSUE THREAD

**Issue by cxfustc** [weizhouUMICH/SAIGE#283]
Shouldn't it be like this 'Z = t(A1) * g1'?

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
