### ISSUE TITLE
Issue with SPAGMMATtest -> scoreTest_SAIGE_binaryTrait_cond_sparseSigma

### ISSUE THREAD

**Issue by fdegenhardt-ikmb** [weizhouUMICH/SAIGE#284]
Dear SAIGE developers, 

I am having a problem with the SPAGMMATtest for the X-Chromosome. I get the error 

  Error in if (out.score["pval.noadj"] > 0.05) { :
    missing value where TRUE/FALSE needed
  Calls: SPAGMMATtest -> scoreTest_SAIGE_binaryTrait_cond_sparseSigma
  Execution halted

This is only true for specific variants here, and does not arise when these variants are excluded.
Help on this would be highly appreciated.

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
