### ISSUE TITLE
Could you provide the newest version of .tar.gz file for local R package installation?

### ISSUE THREAD

**Issue by yystat** [weizhouUMICH/SAIGE#285]
Hi,

Thanks for providing this awesome package! May I ask whether you could provide the R installation package for the latest version? 

Currently your latest R package is `v.0.29.5` wheres the latest code is `0.43 (Updated on November 21, 2020)`, and the current pipeline won't work since more options are added to the pipeline and the old package gives `unused arguments` error.

Since I can only install the R package locally (I don't have admin privilege for my Univ. server), I would really appreciate it if you could also release the `.tar.gz` file for local installation.

Thank you very much!
Josh

**Comment by matuskosut** [comment]
Hi @yystat 

have you considered using conda to install saige? You can install conda without admin privileges and then follow: https://github.com/weizhouUMICH/SAIGE/issues/272

**Comment by yystat** [comment]
@matuskosut thanks! miniconda works great!
