### ISSUE TITLE
Interaction in covariates

### ISSUE THREAD

**Issue by Natalia22123** [weizhouUMICH/SAIGE#286]
Hello, 

I was wondering how to indicate in the fitNULLGLMM function the interaction between covariates. I would like to use as covariate in my model "sex*age". Is it possible?

Thank you,

Natalia

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! 
You will need to make the interaction column and include as covariate. 
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei

**Comment by Zzaroro** [comment]
Hello, 

What if I want to include the interaction between SNP and covariates?

Thanks,
Meredith
