### ISSUE TITLE
Sample order in phenotype file, plink and imputation file

### ISSUE THREAD

**Issue by tbrunetti** [weizhouUMICH/SAIGE#287]
Hello,

I am using SAIGE version 0.39, and I wanted to confirm that the vcf sample order of the phenotype/covariate file, imputation files, and plink files doesn't matter as long as the sample IDs all match?

Tonya

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! 
The sample ID orders do not need to match. 
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
