### ISSUE TITLE
Saving the GRM

### ISSUE THREAD

**Issue by FrederikFilip** [weizhouUMICH/SAIGE#289]
Is it possible to output the GRM used by SAIGE when running single-variant association tests?

Is it possible to provide a pre-calculated GRM?

Thank you

**Comment by weizhouUMICH** [comment]
Hi @FrederikFilip, 
Yes you can just specify it with the sparse GRM file (even though it may not be sparse) and use --useSparseGRMtoFitNULL=TRUE to fit the null model. 

We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
