### ISSUE TITLE
LOCO for non-human data

### ISSUE THREAD

**Issue by FinSalMar** [weizhouUMICH/SAIGE#29]
I am running SAIGE with non-human data (29 autosomes), however, when I run using the LOCO argument it automatically assumes 22 autosomes when specifying chromosomeStartIndexVec (see below). Is there a way to override this so that it will consider all 29 autosomes in my dataset. 

> ....
> Leave-one-chromosome-out is activated
> chromosomeStartIndexVec:  0 3922 5051 7056 9077 10853 12642 13835 14336 17521 20104 22092 24181 26491 28662 30754 32575 33590 35109 36783 38618 39973 
> 11115  samples have genotypes
> ....

**Comment by weizhouUMICH** [comment]
Hi @FinSalMar, 

Sorry for ignoring your request for long. We don't have the option to handle  non-human data yet, as the GRM constructed using non-human data may need further considerations. 

Thanks!
Wei
