### ISSUE TITLE
Error in STEP2 with quantitative trait

### ISSUE THREAD

**Issue by Natalia22123** [weizhouUMICH/SAIGE#290]
Hello,

I have run the STEP1 and STEP2 with binary traits without problems, but when I tryied to run a quantitative trait I get this error in STEP2:
Error in if (var1 < (.Machine$double.xmin)) { : 
missing value where TRUE/FALSE needed
Calls: SPAGMMATtest -> scoreTest_SAIGE_quantitativeTrait_sparseSigma

I have no idea about this problem...

Thank you!

**Comment by lanjblue** [comment]
I have the same error message when running quantitative traits.. Have you figured out what's the problem? Thank you!

**Comment by weizhouUMICH** [comment]
Sorry for the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
