### ISSUE TITLE
Can I use .bed file instead of .vcf file for the step two of SAIGE-GENE?

### ISSUE THREAD

**Issue by garyzhubc** [weizhouUMICH/SAIGE#291]
Can I use .bed file instead of .vcf file for the step two of SAIGE-GENE?

**Comment by weizhouUMICH** [comment]
Sorry for the late reply! 
Yes the PLINK file is now supported in Step 2. 
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
