### ISSUE TITLE
fixing SAIGE to read haploid X chr data from bgen (from TOPMED-r2 imputation output)

### ISSUE THREAD

**Issue by dvh13** [weizhouUMICH/SAIGE#294]
Hi Wei,

Am getting errors with X chr with SAIGE 0.41

The output from new TOPMED-r2 imputation seems genuinely haploid. Not the males coded as 0|2 workaround that you had before. This seems to extend to dosages and probabilities, as well as genotype. See the vcf below.

Is there any chance of a modification to SAIGE to read this type of data? And a new docker image. I have converted vcf to bgens, and have written scripts for bgen.

I would like to use the dosages or probabilities, not the genotypes.

thanks, david

chrX	2781514	chrX:2781514:C:A	C	A	.	PASS	AF=0.337915;MAF=0.337915;R2=0.49808;IMPUTED;INFO=0.557814;AN=53179;AC=17970	GT:DS:HDS:GP	0:0.105:0.105:0.
895,0.105	0:0.108:0.108:0.892,0.108	0:0.041:0.041:0.959,0.041	1|0:1.168:0.908,0.26:0.068,0.696,0.236	0:0.003:0.003:0.997,0.003	0|0:0.389:0.214,0.174:0.649,0.31
4,0.037	0|0:0.195:0.13,0.064:0.814,0.178,0.008	1:0.95:0.95:0.05,0.95	1:0.822:0.822:0.178,0.822	0|0:0.233:0.039,0.194:0.774,0.218,0.008	0|0:0.4:0.389,0.011:0.604,0.392,0.004	
0|0:0.242:0.094,0.148:0.772,0.214,0.014	1:0.869:0.869:0.131,0.869	0|1:1.081:0.109,0.971:0.026,0.868,0.106	0:0.478:0.478:0.522,0.478	0:0.105:0.105:0.895,0.105	1:0.811:
0.811:0.189,0.811	0:0.137:0.137:0.863,0.137	0:0.131:0.131:0.869,0.131	0|0:0.325:0.288,0.037:0.685,0.304,0.011	0:0.148:0.148:0.852,0.148	1|0:0.848:0.844,0.005:0.
155,0.841,0.004	0|0:0.003:0.002,0.002:0.997,0.003,0	0|0:0.309:0.286,0.023:0.697,0.296,0.007	0:0.034:0.034:0.966,0.034	0|0:0.276:0.079,0.197:0.74,0.245,0.016	0:0.095:0.095:0.
905,0.095	0:0.447:0.447:0.553,0.447	0|0:0.331:0.142,0.189:0.696,0.277,0.027	1|0:0.97:0.917,0.053:0.079,0.873,0.049	0|0:0.022:0.006,0.016:0.978,0.022,0	0|0:0.231:0.215,
0.016:0.772,0.224,0.003	1|1:1.4:0.708,0.691:0.09,0.42,0.49 etc

**Comment by dvh13** [comment]
Just to be clear, I am hoping for an option

--HaploidMaleChrXData=TRUE

(to work for vcf or bgen input, and for GT DS or GP field)

Others using TOPMED-r2 have had this problem.

Happy xmas, david

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
