### ISSUE TITLE
docker saige  error

### ISSUE THREAD

**Issue by tianbu** [weizhouUMICH/SAIGE#295]
Dear Weizhou,

I pulled the docker image as "docker pull wzhou88/saige:0.43.2"
and run the step1_fitNULLGLMM.R --help but got an error saying " 
Error: package or namespace load failed for ‘SAIGE’ in rbind(info, getNamespaceInfo(env, "S3methods")):
 number of columns of matrices must match (see arg 2)"

Would you please help me to have a look? Thank you!

**Comment by APLevine** [comment]
I am having the same problem with SAIGE 0.44.2.
Is the solution to this issue known?
Thank you.

**Comment by tianbu** [comment]
Make sure there is no R directory and .Rprofile under ~/. You can rename them or move them temporary to get the docker pipeline work.

**Comment by APLevine** [comment]
That worked! Thank you very much.

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
