### ISSUE TITLE
Step 2: Why doesn't the correct sample file format work and what if the header is included in the sample file?

### ISSUE THREAD

**Issue by garyzhubc** [weizhouUMICH/SAIGE#297]
![image](https://user-images.githubusercontent.com/30366447/103129412-86a02380-464d-11eb-9461-725414b37a35.png)

The second format of sample file seems to be the one asked in the instructions (except without headers). When I run this it gave me empty output file with only header i.e. `Gene Pvalue Nmarker_MACCate_1 Nmarker_MACCate_2 Nmarker_MACCate_3 Nmarker_MACCate_4 Nmarker_MACCate_5 Nmarker_MACCate_6 Nmarker_MACCate_7 Nmarker_MACCate_8 markerIDs markerAFs Pvalue_Burden Pvalue_SKAT`. 

The first format of sample file was able to output these fields successfully. But it has four columns with family ID, individual ID, sex information and missingness so it doesn't look like the format asked in the instructions. Can someone explain why the first one end up working but not the second one?

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
