### ISSUE TITLE
Unable to load shared object /home/endrebak/anaconda3/lib/R/library/SAIGE/libs/SAIGE.so

### ISSUE THREAD

**Issue by endrebak** [weizhouUMICH/SAIGE#3]
```
endrebak@hunt-genes-home ~/local> R CMD INSTALL SAIGE_0.18.tar.gz
...
...
...
installing to /home/endrebak/anaconda3/lib/R/library/SAIGE/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
During startup - Warning message:
Setting LC_CTYPE failed, using "C"
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/home/endrebak/anaconda3/lib/R/library/SAIGE/libs/SAIGE.so':
  /home/endrebak/anaconda3/lib/R/library/SAIGE/libs/SAIGE.so: undefined symbol: _ZN7genfile4bgen4View6createERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/home/endrebak/anaconda3/lib/R/library/SAIGE'
```

Suggestions for how to fix this?

**Comment by endrebak** [comment]
Also, an unmentioned requirement in your README is boost. 

The simplest way to install is anaconda

`conda install boost`.

**Comment by ilarsf** [comment]
Hi Endre,

I would recommend to try the following:

R CMD INSTALL SAIGE_0.18_R_x86_64-pc-linux-gnu.tar.gz

In your case you will have to use the R binary of your condo installation
after you have installed the R libraries: Rcpp, RcppArmadillo,
RcppParallel, data.table, SPAtest, RcppEigen, Matrix.

Best,
Lars

**Comment by endrebak** [comment]
Thanks for the suggestion Lars. 

I think the problem was that the dropbox link contains an archive that is not compatible with `R CMD INSTALL`. When I used the `tar.gz` in the repo it worked :)

**Comment by endrebak** [comment]
Another guy in my group made the same mistake. You should probably fix this to avoid more confusion 😆

**Comment by endrebak** [comment]
f
