### ISSUE TITLE
Clarity about some arguments in `step1` 

### ISSUE THREAD

**Issue by agilly** [weizhouUMICH/SAIGE#301]
In the code and detailed help, there are many options that seemingly relate to taking into account low MAC categories when performing sparse kinship computation and step1. I am particulary curious about some of them and am looking for practical guidance as to when/how to use them. I presume, given that they seem to either deal with the sparse GRM or with rare MAC categories, that they are relevant for set analysis:

### `--isCateVarianceRatio`
If I understand this correctly, this option enables variance ratio calculation for specific MAC categories defined by `--cateVarRatioMinMACVecExclude` and `--cateVarRatioMaxMACVecInclude`. to account for the fact that relatedness structures in these categories might differ. Is this correct, and what are the authors' recommendation regarding these arguments? Activating this mode significantly slows down the computation of step1.

### `--useSparseSigmaConditionerforPCG`

I am not sure what the consequences of enabling this are. If this is an option then the sparse matrix is not used by default for preconditioning the conjugate gradient. Can the authors expand on when to use this option?

### `--useSparseSigmaforInitTau`

Same question here, does using the sparse matrix improve or speed up convergence?

TIA,

Arthur

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the more detailed documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
