### ISSUE TITLE
Using old step 1 with new step 2?

### ISSUE THREAD

**Issue by apoliakov** [weizhouUMICH/SAIGE#302]
Hello!

Some of our projects have been using version 0.38 for some time and we started testing the upgrade path to 0.43. 
1) it looks like LOCO is now TRUE by default? But it does seem to make things go slower. I had a STEP 1 that took 4 hours without LOCO and >12 hours with.

2) I can't seem to use Step 1 results from v 0.38 with Step 2 in 0.43. Alas. We get weirdo R errors like
```
[1] "Error in innerProduct(g, y) : "
[1] "  Not compatible with requested type: [type=NULL; target=double]."
```
Is this right?

If we have, say, a whole bunch of 0.38 step 1 results saved up for reuse, is there any way to convert them to work with 0.43?

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. The step 1 results from 0.43 can be used for step 2 in 1.0.0. Do you still have the need to convert 0.38 step 1 to 0.43 step 1? If so, I can share some R scripts for the conversion. Thanks.

V1.0.0 has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
