### ISSUE TITLE
Error in SPAGMMATtest samples used in glmm model fit do not have dosages

### ISSUE THREAD

**Issue by rnbeaumont** [weizhouUMICH/SAIGE#306]
Hi,

I have installed version 0.43.3 of SAIGE and am getting the following error which I was not getting using a previous version of SAIGE

Number of samples in the vcf file: 200643
10000  sample IDs are found in the vcf file
Error in SPAGMMATtest(vcfFile = opt$vcfFile, vcfFileIndex = opt$vcfFileIndex,  :
  ERROR!81247 samples used in glmm model fit do not have dosages

I have double checked the VCF file and all samples in the model appear in the VCF file. I am using the same files I previously used with SAIGE version 0.39 which worked without issue. Are you able to help with this error?

Thanks

Rob

**Comment by ConnieXuhm** [comment]
Hi, I met the same problem. Have you solved the non-dosage problem? Thanks!

**Comment by rnbeaumont** [comment]
I've not been able to solve this issue yet. If anyone does manage to solve the issue it would be great to know how they did it

**Comment by aokulabasile** [comment]
I have also run into the same issue when providing a vcf with DS as input. Any help with this would be greatly appreciated. Thanks!

**Comment by aokulabasile** [comment]
I was able to figure out this issue.  For me, It was due to the sample ids in the plink files used in step 1 not matching the sample ids in my VCF.  Restricting the samples in my VCF file to only those used to fit the Null GLMM in step 1, and making sure the ids match fixed the problem.  Good luck to others with this issue.

**Comment by lessdata** [comment]
@rnbeaumont I think the authors have fixed this issue. You may try the latest release. Unfortunately, it seems that only 0.43.3 is affected. In the SAIGE_SPATest.R of release 0.43.3, Sample IDs are hardcoded by the 10000 ids of the toy dataset. That is why it always shows "10000 sample IDs are found in the vcf file" in the logs.

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
