### ISSUE TITLE
minInfo and negative INFO scores

### ISSUE THREAD

**Issue by frahimov** [weizhouUMICH/SAIGE#308]
Hello. The X chromosome summary statistics file contains lots of negative imputationInfo scores, even though I applied --minInfo=0.8.  Is this normal? And what causes this?

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
