### ISSUE TITLE
SAIGE Step 1 error line 12: 6843 Killed

### ISSUE THREAD

**Issue by Melb1** [weizhouUMICH/SAIGE#309]
Hi SAIGE team 

I am running SAIGE GRM on 65K samples and getting this error 

SAIGE line 12: 6843 Killed

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
