### ISSUE TITLE
Step2 error: "Error in t(B^2) %*% mu21 : non-conformable arguments"

### ISSUE THREAD

**Issue by sboer** [weizhouUMICH/SAIGE#31]
Hi!

I have discovered a new problem using SAIGE version 0.26.6 in some of the phenotypes, running step 2. 

This is the last part of the log-file:

numPassMarker:  48
   user  system elapsed
  6.748   0.236   6.978
[1] 76
numPassMarker:  48
Error in t(B^2) %*% mu21 : non-conformable arguments
Calls: SPAGMMATtest ... rbind -> scoreTest_SAIGE_binaryTrait -> Score_Test_Sparse
Execution halted

This is the code:

Rscript /mnt/work/R_packages/x86_64-pc-linux-gnu-library/3.4/SAIGE/extdata/step2_SPAtests.R \
--dosageFile=/path/to/genofile.dose \
--dosageFileNrowSkip=0 \
--dosageFileNcolSkip=5 \
--dosageFilecolnamesSkip=CHR,SNP,POS,A1,A2 \
--minMAF=0.0001 \
--sampleFile=/path/to/samplefile.txt \
--GMMATmodelFile=phenotype.rda \
--varianceRatioFile=phenotype.varianceRatio.txt \
--SAIGEOutputFile=phenotype_results.txt \
--numLinesOutput=2 \
--IsOutputAFinCaseCtrl=TRUE 

Running step 1 did not show any errors. 
I have run the phenotypes with an older SAIGE version previously with no errors. 
I am also running the script in parallel, with most of the phenotypes working, so the code itself seems to be ok. 

Googling have given me no answers to the problem. 
Do you know what can cause this?

Thanks alot for any help!

Sigrid``

**Comment by weizhouUMICH** [comment]
Hi Sigrid, 

Could you please try v0.29 to see if the error is there?

Thanks,
Wei

**Comment by sboer** [comment]
I thought I was up to date but obviously not ;) I will download the new version and give it a try. Thanks!

**Comment by sboer** [comment]
I downloaded the new version, but where did the /extdata go..? I cannot find any of the scripts (step1_fitNULLGLMM.R  and step2_SPAtests.R)

**Comment by weizhouUMICH** [comment]
The development branch contains the source code for the new version. The extdata is still there. I removed the inst/extdata since the two folders are exactly the same.

**Comment by sboer** [comment]
Great, I was not sure whether I could use it or not. 
Thanks!

Sigrid

**Comment by sboer** [comment]
It worked with the new version!
Thanks!
