### ISSUE TITLE
How is missing data handled in SAIGE-GENE?

### ISSUE THREAD

**Issue by garyzhubc** [weizhouUMICH/SAIGE#311]
How is missing data handled in SAIGE-GENE?

**Comment by weizhouUMICH** [comment]
Here is the option to specify the way to handle missing dosages/genotypes. 

https://github.com/weizhouUMICH/SAIGE/blob/master/extdata/step2_SPAtests.R#L45

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
