### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by mferreiradasilva** [weizhouUMICH/SAIGE#314]
Trying to install SAIGE according to the instructions. Used ```devtools::install_github("weizhouUMICH/SAIGE")``` and at some point started getting the following warning:

``` Warning in writeBin(block, con) : problem writing to connection```

As I understand, that can mean a problem in available disk space. Afterwards, got the following error:

```
Error in rawToChar(block[seq_len(ns)]) :
  embedded nul in string: 's_s\n\n  ///n      boost::asio::transfer_at_least(1),o\n\n  /// "Invalid response\\n";\n   \0\0\0\0\0\0sponse_st'
Error: Failed to install 'SAIGE' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmppJJ25E/file3da3430dd23c0/SAIGE_0.44.1.tar.gz’ had non-zero exit status
```

Is the error caused by the previous warning i.e. no available space?

Thanks.

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
