### ISSUE TITLE
Is it only possible to do step 2 in SAIGE for each chromosome individually?

### ISSUE THREAD

**Issue by mferreiradasilva** [weizhouUMICH/SAIGE#317]
Given that it's mandatory to specify "chrom" when using a VCF file, even if LOCO is set to FALSE, does this mean each SPA needs to be done for each chromosome individually?

**Comment by weizhouUMICH** [comment]
Yes for the VCF file input, Step 2 can only be run for each chromosome individually.

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
