### ISSUE TITLE
Single variant association error in "step 2"

### ISSUE THREAD

**Issue by bw-dpm** [weizhouUMICH/SAIGE#319]
Hi
we have been trying to use SAIGE for single variant associations on a binary trait. The fit of a null logistic mixed model ("step 1") runs successfully but the single variant association test ("step 2") keeps failing with the following error:

_Error in if (markerInfo >= 0 & markerInfo <= 1) { : 
  argument is of length zero
Calls: SPAGMMATtest
Execution halted_

(See attached "step2_output.txt" for the complete output generated in step 2).

The error seems to originate in the SPAGMMATtest function definition @ line 771 of SAIGE_SPATest.R: 
`Gx = getGenoOfnthVar_vcfDosage(mth)`. The Gx object returned by  this call is NULL.

Attached files:
- step2_output.txt: the complete output of step 2 
- step1_step2_options.txt : the options used in step 1 and step 2
- vcf_file.txt: the meta-information/header and first data line of the vcf file

Additional information:
- SAIGE version: 0.44
- The vcf file is a TopMed imputed dataset (chromosome 21) generated by the University of Michigan server (see file meta-information in attached vcf_file.txt for version details).

Thank you very much for your help! Best
Franco Giulianini

[step1_step2_options.txt](https://github.com/weizhouUMICH/SAIGE/files/6191549/step1_step2_options.txt)
[step2_output.txt](https://github.com/weizhouUMICH/SAIGE/files/6191550/step2_output.txt)
[vcf_file.txt](https://github.com/weizhouUMICH/SAIGE/files/6191551/vcf_file.txt)

**Comment by weizhouUMICH** [comment]
Hi Franco, 

Thanks so much for providing the files! The issues may be due to the mismatch of the chrom string. Can you specify --chr = "chr21" instead of "21". Thanks!

Wei

**Comment by kavitashah** [comment]
@weizhouUMICH 
Hi I am getting the following error. Please help me out in solving the error.

Warning: missing FMT field (GT)
Error in if (markerInfo >= 0 & markerInfo <= 1) { :
  argument is of length zero
Calls: SPAGMMATtest
Thanks
Indra

**Comment by weizhouUMICH** [comment]
Hi Indra @kavitashah, 

Is the error seen at the begining of the analysis? It seems the VCF is not read appropriately. Have you checked the --chr string? 

Thanks,
Wei

**Comment by michelemarongiu79** [comment]
Hi Jenny,
I have the same error.
Were you able to solve?

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
