### ISSUE TITLE
Difference of p.value and p.value.NA in output files

### ISSUE THREAD

**Issue by Wall-Facer** [weizhouUMICH/SAIGE#32]
Hi,

I am currently running GWAS with SAIGE. Everything went well, just we are a bit confused of annotating the output files. There are two columns for P-value, one is "p.value" and another one is "p.value.NA". Could you please provide some information on what is the difference? Thanks in advance!

Best regards,
Tenghao

**Comment by weizhouUMICH** [comment]
Hi Tenghao, 

You may check this page 
https://github.com/weizhouUMICH/SAIGE/wiki/SAIGE-Hands-On-Practical
for the information 

Thanks,
Wei

CHR: chromosome
POS: genome position 
SNPID: variant ID
Allele1: Ref allele
Allele2: Alt allele
AC_Allele2: allele count of Alt allele
AF_Allele2: allele frequency of Alt allele
N: sample size
BETA: effect size
SE: standard error of BETA
Tstat: score statistic
p.value: p value with SPA applied
p.value.NA: p value when SPA is not applied
Is.SPA.converge: whether SPA is converged or not
varT: estimated variance of score statistic with sample related incorporated
varTstar: variance of score statistic without sample related incorporated

**Comment by sariya** [comment]
@weizhouUMICH 

Hi - I have a follow up on this. The column description is helpful. It would be good to know which pvalue to be used for downstream analyses (manhattan plot, gene based):
 
p.value: p value with SPA applied
p.value.NA: p value when SPA is not applied


Would you say `p.value.NA` is FDR adjusted?


Thank you.

**Comment by Alireza-Majd** [comment]
Hi Sariya, 
It shouldn't be FDR adjusted, you can do FDR adjustment using either column `p.valye.NA` or `p.value`.
The advantage of using column p.value is when the ratio of cases to controls is a concern and you decide to continue the analysis with the values when SPA is applied.
