### ISSUE TITLE
Clarification for gwas with related individuals

### ISSUE THREAD

**Issue by rbutleriii** [weizhouUMICH/SAIGE#320]
Per the paper, SAIGE should be able to run with related individuals as it is GRM aware. But for individual variant analysis, the wiki says to skip step0, where the sparse GRM is created.

Just to make sure, even with related individuals in the population, single variant association tests don't need step0?

**Comment by weizhouUMICH** [comment]
Hi @rbutleriii, 

Full GRM is used in SAIGE, but it is not pre-estimated, as with large sample sizes, the full GRM takes much memory to store. 
SAIGE estimates the elements in the full GRM on the fly using the provided Plink file when fitting the null model in step 1. 

The sparse GRM generated in Step 0 is for estimating the variance ratio for gene-based tests, so it is not needed for single-variant tests.  Hope this flowchart helps https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE#flowchart

Thanks,
Wei
