### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by psnehal** [weizhouUMICH/SAIGE#324]
Sometimes my step 1 is failing when I run the saige on Centos 7 system . I am getting "159336 Segmentation fault      (core dumped)" error for that job. Out of 4 times I tried to run the job, it failed 2 times and was successful 2 times. Does anyone come across this problem?

**Comment by mferreiradasilva** [comment]
This is probably an installation problem.

Follow this guide: https://github.com/weizhouUMICH/SAIGE/issues/118

It worked for me.

**Comment by matuskosut** [comment]
@mferreiradasilva @psnehal if you are using conda, you might as well install directly [r-saige](https://anaconda.org/bioconda/r-saige):
```
conda install -c bioconda r-saige
```

Feel free to tag me if you spot some issues with this [conda package](https://anaconda.org/bioconda/r-saige).
