### ISSUE TITLE
error when running X chromosome

### ISSUE THREAD

**Issue by xchangchop** [weizhouUMICH/SAIGE#326]
Hi Wei,
I got an error when running X chromosome. I did get the result for the first 4079 markers, but got the following errors when running the 4080th markers. I also tested a subset of X chromosome, and got the similar issue that I can run through some markers, but can not get the full result. 

numPassMarker:  4079 
[1] 3227655
Error in if (out.score["pval.noadj"] > 0.05) { : 
  missing value where TRUE/FALSE needed
Calls: SPAGMMATtest -> scoreTest_SAIGE_binaryTrait_cond_sparseSigma
Execution halted

**Comment by weizhouUMICH** [comment]
Hi @xchangchop, 
I think this problem has been fixed in the newer version. Can you please try it? 

Thanks,
Wei

**Comment by xchangchop** [comment]
Thank you Wei. I installed the R-SAIGE on bioconda following the instructions from matuskosut (https://github.com/weizhouUMICH/SAIGE/issues/272).  I did update saige to the latest version using "conda update r-saige".

**Comment by matuskosut** [comment]
Hi @xchangchop ,

you should try to update, I recently update the version on conda to `0.44.2` https://anaconda.org/bioconda/r-saige/files

**Comment by xchangchop** [comment]
Thank you both! Works this time.
