### ISSUE TITLE
LOCO with bgen chunk files (not split by chromosome)

### ISSUE THREAD

**Issue by sboer** [weizhouUMICH/SAIGE#334]
Hi! I was wondering whether it is possible to run analysis with LOCO = TRUE, using bgen files, split in chunks (with each file/chunk containing several chromosomes)? Could not find anything in the manual or --help function. Tried both not to specify --CHR, and to specify several chr (according to the file analysed) but nothing seemed to work. 

Thanks!

Sigrid

**Comment by weizhouUMICH** [comment]
Hi Sigrid, 

The LOCO=TRUE currently only works with bgen or vcf files containing a single chromosome. The reason for this setting is to avoid checking the chromosome for each testing marker, which can cost much time. 

Thanks,
Wei

**Comment by sboer** [comment]
Good to know, thanks Wei :)

Sigrid

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
