### ISSUE TITLE
Issue with SAIGE-Gene step 2 (v0.44.2)

### ISSUE THREAD

**Issue by longmanz** [weizhouUMICH/SAIGE#335]
Dear Wei,

I have encountered an issue when running SAIGE-Gene: 

From the output results of Step 2, it seemed that the software loaded the same (i.e., the 1st) variant in the gene for multiple times rather than loading the correct variants for that gene for association tests. An example output file is as follows:

###
Gene Pvalue Nmarker_MACCate_1 Nmarker_MACCate_2 markerIDs markerAFs Pvalue_Burden Pvalue_SKAT
ACAP3 0.606 0 4 rs72896218;rs72896218;rs72896218;rs72896218 0.0095;0.0095;0.0095;0.0095; 0.606 0.606
......
###

I have checked my --groupFile and it looks okay. The number of variants for the gene in the group file matched that in the output file. I am not sure what I did wrong. Could you please give me some suggestions?

Many thanks in advance! 

Best,
Longda

Update on Apr 25: By using the latest v0.44.5 I still encounter this issue. Is there anything I need to pay attention to when generating the --groupFile file (e.g., sort rsID based on position for each gene)?

**Comment by weizhouUMICH** [comment]
Hi @longmanz, 

Thanks for reporting this issue! Is this error only seen for this gene or every gene? The only thing that matters in the group file is the order of rsIDs based on the genome position. For this single gene, could you please share the more complete log messages? 

Thanks,
Wei

**Comment by christopherdkoch** [comment]
@longmanz Were you able to resolve this? I'm seeing the same thing.

**Comment by liwangchang** [comment]
@longmanz Were you able to resolve this? I'm seeing the same thing.

**Comment by longmanz** [comment]
Dear @weizhouUMICH and all,
Sorry I was not responsive over the last few weeks. 
I still obverse that same thing with v0.44.5. I do not have a good solution at the moment.

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
