### ISSUE TITLE
SAIGE Install fails - savvy.

### ISSUE THREAD

**Issue by aelkhouly85** [weizhouUMICH/SAIGE#336]
Hello 

I'm trting to install the latest Saige using Conda but it is not getting successful because of the below issue, can you please help?

[ 33%] Building CXX object CMakeFiles/sav.dir/src/sav/import.cpp.o
[ 50%] Building CXX object CMakeFiles/sav.dir/src/sav/head.cpp.o
[ 50%] Building CXX object CMakeFiles/sav.dir/src/sav/merge.cpp.o
[ 58%] Building CXX object CMakeFiles/sav.dir/src/sav/rehead.cpp.o
[ 66%] Building CXX object CMakeFiles/sav.dir/src/sav/index.cpp.o
[ 75%] Building CXX object CMakeFiles/sav.dir/src/sav/sort.cpp.o
[ 91%] Building CXX object CMakeFiles/sav.dir/src/sav/utility.cpp.o
[ 91%] Building CXX object CMakeFiles/sav.dir/src/sav/stat.cpp.o
In file included from /tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/include/savvy/reader.hpp:13:0,
                 from /tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/src/sav/concat.cpp:9:
/tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/include/savvy/csi.hpp:10:10: fatal error: shrinkwrap/gz.hpp: No such file or directory
 #include <shrinkwrap/gz.hpp>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/sav.dir/build.make:76: CMakeFiles/sav.dir/src/sav/concat.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/include/savvy/reader.hpp:13:0,
                 from /tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/src/sav/index.cpp:9:
/tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/include/savvy/csi.hpp:10:10: fatal error: shrinkwrap/gz.hpp: No such file or directory
 #include <shrinkwrap/gz.hpp>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/sav.dir/build.make:128: CMakeFiles/sav.dir/src/sav/index.cpp.o] Error 1
In file included from /tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/include/savvy/reader.hpp:13:0,
                 from /tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/src/sav/rehead.cpp:9:
/tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/include/savvy/csi.hpp:10:10: fatal error: shrinkwrap/gz.hpp: No such file or directory
 #include <shrinkwrap/gz.hpp>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/include/savvy/reader.hpp:13:0,
                 from /tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/src/sav/head.cpp:8:
/tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/include/savvy/csi.hpp:10:10: fatal error: shrinkwrap/gz.hpp: No such file or directory
 #include <shrinkwrap/gz.hpp>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/sav.dir/build.make:154: CMakeFiles/sav.dir/src/sav/rehead.cpp.o] Error 1
make[2]: *** [CMakeFiles/sav.dir/build.make:102: CMakeFiles/sav.dir/src/sav/head.cpp.o] Error 1
In file included from /tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/include/savvy/reader.hpp:13:0,
                 from /tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/src/sav/stat.cpp:11:
/tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/include/savvy/csi.hpp:10:10: fatal error: shrinkwrap/gz.hpp: No such file or directory
 #include <shrinkwrap/gz.hpp>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/sav.dir/build.make:180: CMakeFiles/sav.dir/src/sav/stat.cpp.o] Error 1
In file included from /tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/src/sav/main.cpp:14:0:
/tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/include/sav/sort.hpp:13:10: fatal error: shrinkwrap/zstd.hpp: No such file or directory
 #include <shrinkwrap/zstd.hpp>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/sav.dir/build.make:63: CMakeFiles/sav.dir/src/sav/main.cpp.o] Error 1
In file included from /tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/src/sav/sort.cpp:7:0:
/tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/include/sav/sort.hpp:13:10: fatal error: shrinkwrap/zstd.hpp: No such file or directory
 #include <shrinkwrap/zstd.hpp>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/sav.dir/build.make:167: CMakeFiles/sav.dir/src/sav/sort.cpp.o] Error 1
In file included from /tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/src/sav/export.cpp:9:0:
/tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/savvy-2.0.1/include/sav/sort.hpp:13:10: fatal error: shrinkwrap/zstd.hpp: No such file or directory
 #include <shrinkwrap/zstd.hpp>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/sav.dir/build.make:89: CMakeFiles/sav.dir/src/sav/export.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/sav.dir/all] Error 2
gmake: *** [all] Error 2
Command failed: ['/path/path/path/SAIGE/0.44.5/envs/RSAIGE/bin/cmake', '--build', u'/tmp/RtmpBsny8R/R.INSTALL46254803656d/SAIGE/thirdParty/cget/cget/build/tmp-26ff8f0417844f4fb68dcb122aa38ddf/build', '--config', 'Release', '--', '-j', '32']
Failed to build package statgen/savvy
ERROR: configuration failed for package ‘SAIGE’
* removing ‘/path/path/path/SAIGE/0.44.5/envs/RSAIGE/lib/R/library/SAIGE’
Error: Failed to install 'SAIGE' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmpd6E7dz/file3ab61532d401/SAIGE_0.44.5.tar.gz’ had non-zero exit status

**Comment by aelkhouly85** [comment]
In could remove this issue by using different cmake version , but now it is stopped here.


Install the project...
-- Install configuration: "Release"
-- Installing: /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/cget/cget/pkg/xiaoyeli__superlu/install/lib64/pkgconfig/superlu.pc
-- Installing: /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/cget/cget/pkg/xiaoyeli__superlu/install/lib64/libsuperlu.a
-- Installing: /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/cget/cget/pkg/xiaoyeli__superlu/install/include/supermatrix.h
-- Installing: /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/cget/cget/pkg/xiaoyeli__superlu/install/include/slu_Cnames.h
-- Installing: /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/cget/cget/pkg/xiaoyeli__superlu/install/include/slu_dcomplex.h
-- Installing: /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/cget/cget/pkg/xiaoyeli__superlu/install/include/slu_scomplex.h
-- Installing: /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/cget/cget/pkg/xiaoyeli__superlu/install/include/slu_util.h
-- Installing: /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/cget/cget/pkg/xiaoyeli__superlu/install/include/superlu_enum_consts.h
-- Installing: /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/cget/cget/pkg/xiaoyeli__superlu/install/include/slu_sdefs.h
-- Installing: /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/cget/cget/pkg/xiaoyeli__superlu/install/include/slu_ddefs.h
-- Installing: /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/cget/cget/pkg/xiaoyeli__superlu/install/include/slu_cdefs.h
-- Installing: /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/cget/cget/pkg/xiaoyeli__superlu/install/include/slu_zdefs.h
Successfully installed xiaoyeli/superlu
invalid lock file in /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/bgen
Setting top to                           : /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/bgen 
Setting out to                           : /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/bgen/build 
Checking for 'gcc' (C compiler)          : /xx/xx/xx/SAIGE/0.44.5/envs/RSAIGE/bin/x86_64-conda_cos6-linux-gnu-cc 
Checking for 'g++' (C++ compiler)        : /xx/xx/xx/xx/xx/envs/RSAIGE/bin/x86_64-conda_cos6-linux-gnu-c++ 
zlib                                     : not found 
The configuration failed
(complete log in /tmp/RtmpS4c3u3/R.INSTALL3f3418b2f990/SAIGE/thirdParty/bgen/build/config.log)
ERROR: configuration failed for package ‘SAIGE’
* removing ‘/gpfs/software/genomics/SAIGE/0.44.5/envs/RSAIGE/lib/R/library/SAIGE’
Error: Failed to install 'SAIGE' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmp5OR29G/file33e43e5371ee/SAIGE_0.44.5.tar.gz’ had non-zero exit status

**Comment by aelkhouly85** [comment]
fixed by making sure the below variable are set correctly.

FLAGPATH=`which python | sed 's|/bin/python$||'`
export LDFLAGS="-L${FLAGPATH}/lib"
export CPPFLAGS="-I${FLAGPATH}/include"

**Comment by jingydz** [comment]
> fixed by making sure the below variable are set correctly.
> 
> FLAGPATH=`which python | sed 's|/bin/python$||'` export LDFLAGS="-L${FLAGPATH}/lib" export CPPFLAGS="-I${FLAGPATH}/include"

Has anyone else successfully installed this way?
