### ISSUE TITLE
an error for the case of only one rare variant within a region  

### ISSUE THREAD

**Issue by iamhere218** [weizhouUMICH/SAIGE#337]
Hi Wei,

I had an error message as follows when running SAIGE-Gene on my data. 

Garbage collection 14 = 8+2+4 (level 2) ... 
78.8 Mbytes of cons cells used (59%)
21.7 Mbytes of vectors used (34%)
Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions
Calls: SPAGMMATtest -> groupTest -> colSums -> colSums -> <Anonymous>
  Execution halted

I figured that I have only one rare variant with that specific region.   Could you please take a look at this issue when there is only one rare variant without additional rare variants to be collapsed with?   Would it be possible to have a single-marker analysis result instead? Or should I combine the regions avoiding to have only one rare variant?    It would be appreciated if I can have your suggestion.   Thank you.

**Comment by weizhouUMICH** [comment]
Hi @iamhere218, 

Thanks for reporting this issue. I will fix the issue and update you. 

Wei

**Comment by sarah-n-wright** [comment]
I am getting the same issue, and having difficulty identifying ahead of time which regions it will occur in (as it is also sometimes occurring for regions with > 1 marker). Would it be possible to catch this error rather than halting execution to allow the remaining regions to be tested?

**Comment by weizhouUMICH** [comment]
Sorry for my late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
