### ISSUE TITLE
Error in SPAGMMATtest

### ISSUE THREAD

**Issue by ionicbond2005** [weizhouUMICH/SAIGE#339]
Dear Sir/Madam:

I was trying to use SAIGE to conduct a rare variant study and I am trying to get step2_SPAtests.R running. However, when the process ends, it always throws me an error message. 

group-based test will be performed
Any dosages <=  0.2  for genetic variants with MAC <= 10 are set to be 0 in group tests
Garbage collection 14 = 8+2+4 (level 2) ...
79.2 Mbytes of cons cells used (59%)
35.6 Mbytes of vectors used (46%)
1152  samples have been used to fit the glmm null model
Error in SPAGMMATtest(vcfFile = opt$vcfFile, vcfFileIndex = opt$vcfFileIndex,  :
  chromosome 0 is out of the range of null model LOCO results

Would you mind telling me what causes this error message and how should I fix it?

Thank you very much
Samuel Li

**Comment by weizhouUMICH** [comment]
Hi Samuel @ionicbond2005,

The issue is because --chr is not specified. Please specify --chr as the string matching in the chrom column in the vcf files. 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
