### ISSUE TITLE
Conda environment steps - update

### ISSUE THREAD

**Issue by matuskosut** [weizhouUMICH/SAIGE#340]
Hi Wei,

I noticed that conda environment steps were last updated in Oct 2019 (#118 ). It has been some time since R introduced version 4.0 and packages on conda support it. Saige is also built with R 4.0 support in conda packages https://anaconda.org/bioconda/r-saige (https://github.com/weizhouUMICH/SAIGE/issues/272) so I don't expect any problems when running build.

Most of the dependencies in `conda_env/createCondaEnvSAIGE_steps.txt` are actually available in conda-forge (including cget). It is better to use that channel where possible, than to combine too many channels as to avoid cross-channel dependency conflicts.

Related pull request: https://github.com/weizhouUMICH/SAIGE/pull/328

The proposed setup is hopefully cleaner:
```
conda create -n RSAIGE r-essentials r-base=4.0.3 python=2.7
conda activate RSAIGE
conda install -n RSAIGE -c conda-forge cmake gettext lapack r-matrix r-rcpp r-rcpparmadillo r-data.table r-bh r-spatest r-rcppeigen r-devtools r-skat r-rcppparallel r-optparse bgenix boost openblas superlu cget
conda install -n RSAIGE -c bioconda savvy
conda env export > environment-RSAIGE.yml
```

I usually recommend using r-saige straight from conda (https://github.com/weizhouUMICH/SAIGE/issues/272), instead of compiling, but since these are still used - for example for GATE it makes sense to keep them up to date.

**Comment by weizhouUMICH** [comment]
Hi @matuskosut, 

Of course! Thanks so much for all your help and efforts in making the installation much easier!!

Wei
