### ISSUE TITLE
Number of threads parameter step2_SPAtests.R

### ISSUE THREAD

**Issue by rkarlssonlinner** [weizhouUMICH/SAIGE#341]
Hi,

When I run step1_fitNULLGLMM.R, then I can control the number of threads with the --nThreads parameter, which works well. However, this parameter is, AFAIK, missing from step2_SPAtests.R. Am I misunderstanding something here? Will this parameter be implemented in step2_SPAtests.R?

Thanks!

**Comment by weizhouUMICH** [comment]
Hi @rkarlssonlinner, 
 each Step 2 job uses one CPU.  
For single-variant association tests,  to split genome for multiple jobs at the same time,  if the input is bgen, you may use the parameter --idstoIncludeFile to query by marker IDs for each job and if the input is vcf, you may specify --start and --end to run jobs by regions. 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
using R that automatically uses multiple CPUs slows down the Step 2, which only uses 1 CPU. The bash command
`export MKL_NUM_THREADS=1; export MKL_DYNAMIC=false; export OMP_NUM_THREADS=1; export OMP_DYNAMIC=false; `

can be used to ensure the program only uses one CPU. 

Thanks,
Wei
