### ISSUE TITLE
 *** caught segfault *** address (nil), cause 'memory not mapped'

### ISSUE THREAD

**Issue by ionicbond2005** [weizhouUMICH/SAIGE#346]
Hi all,

I am trying to get step 2 working but when I submit my job, it immediately return an error message

 *** caught segfault ***
address (nil), cause 'memory not mapped'

I see group file may be one of the reason that cause this problem and below are the first 2 lines of my group file.

LINC02593       1:853105_C/T
SAMD11  1:861301_G/A    1:865541_G/A    1:865544_C/T    1:865575_C/G    1:865590_TGAA/T 1:865601_C/G    1:865607_C/G    1:865655_T/G    1:865670_G/C    1:865692_C/T    1:865707_T/C    1:866427_C/T    1:871186_G/A    1:871216_G/A    1:871258_A/G    1:871262_G/A    1:874455_C/T    1:874501_C/T    1:874517_C/T    1:874672_C/T    1:874717_C/G    1:874732_A/C    1:876529_C/A    1:876567_G/C    1:876649_G/A    1:876678_C/G    1:877867_C/T    1:878051_CG/C   1:878175_A/AG   1:878285_GGA/G  1:878382_C/A    1:878409_C/T    1:878638_G/A    1:878645_G/A    1:879184_C/T    1:879330_C/T    1:879408_CCCA/C 1:879435_G/A    1:879439_G/A    1:879453_G/A    1:879480_G/A    1:879522_CCT/C

I also try to see whether it is the vcf that gives me the problem and here is the first record of my vcf

1       752697  .       G       A       467.70  PASS    AC=1;AF=0.0002341;AN=4272;AS_BaseQRankSum=3.3;AS_FS=0;AS_FilterSt
atus=PASS;AS_InbreedingCoeff=-0.0002;AS_MQ=60;AS_MQRankSum=0;AS_QD=11.41;AS_ReadPosRankSum=1.2;AS_SOR=0.818;AS_VQSLOD=19.
1931;AS_culprit=MQRankSum;BaseQRankSum=3.31;DP=82512;ExcessHet=3.0103;FS=0;InbreedingCoeff=-0.0002;MLEAC=1;MLEAF=0.000234
1;MQ=60;MQRankSum=0;PG=0,33,70;QD=11.41;ReadPosRankSum=1.21;SOR=0.818;ANNO=Intergenic;ANNOFULL=Intergenic    GT:AD:DP:GQ:
PL:PP       0/0:39,0:39:99:0,105,1575:0,138,1645    0/0:36,0:36:99:0,99,1485:0,132,1555 

Below are the code that I submitted

Rscript /hpcdata/pid/list/Apps/SAIGE/extdata/step2_SPAtests.R \
--vcfFile="some.vcf" \
--vcfFileIndex="some.vcf.tbi" \
--vcfField=GT \
--chrom=1 \
--minMAF=0 \
--minMAC=0.5 \
--maxMAFforGroupTest=0.01 \
--GMMATmodelFile="/step1.rda" \
--varianceRatioFile="step1/binary_cate.varianceRatio.txt" \
--SAIGEOutputFile=SAIGE-binary-5-6-2021-chrom1.txt \
--numLinesOutput=1 \
--IsSingleVarinGroupTest=TRUE \
--sparseSigmaFile="/step1/binary_cate.varianceRatio.txt_relatednessCutoff_0.125_2000_randomMarkersUsed.sparseSigma.mtx" \
--groupFile="/some-EPACTS.group" \
--sampleFile="some-vcf-sample-list.txt" \
--IsOutputBETASEinBurdenTest=TRUE

Thank you very much

Samuel Li

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
