### ISSUE TITLE
fillNULLGLLM error

### ISSUE THREAD

**Issue by rtooze** [weizhouUMICH/SAIGE#349]
Hi, 

I have a problem with stage 4 of the workflow - fitNULLGLMM. Error messages attached. 

Many thanks
Rebecca
<img width="1032" alt="Screenshot 2021-05-22 at 07 21 01" src="https://user-images.githubusercontent.com/82944820/119324820-281cb700-bc78-11eb-89c0-ce7a4684f33b.png">

**Comment by weizhouUMICH** [comment]
Sorry for the late reply! We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
