### ISSUE TITLE
Error in if (MAF >= testMinMAF & markerInfo >= minInfo)

### ISSUE THREAD

**Issue by WeiWei060512** [weizhouUMICH/SAIGE#35]
Hi, 

I am running SAIGE on ~700 GWAS samples. I got the error message from step2. Any help would be appreciated.

Many thanks,
Wei Wei

.
.
.
[1] 6728
numPassMarker:  973
   user  system elapsed
  5.998   0.836  10.529
[1] 6730
numPassMarker:  973
Error in if (MAF >= testMinMAF & markerInfo >= minInfo) { :
  missing value where TRUE/FALSE needed
Calls: SPAGMMATtest
Execution halted

**Comment by weizhouUMICH** [comment]
Are you using bgen input?

**Comment by WeiWei060512** [comment]
Yes, I'm using dosage files in plain text. 

Thanks.

**Comment by weizhouUMICH** [comment]
I see. You are not using bgen but using plain text? 
Could you please share the command line you are using? 
Thanks!

**Comment by WeiWei060512** [comment]
Thanks for your reply. I've solved this problem by cleaning my input file. 

It's working on auto chromosomes, but chromosome X failed STEP1,

Here is the command line for STEP1, 

Rscript $SCRIPT_STEP1 \
        --plinkFile=${INPUT} \
        --phenoFile=${PHENO} \
        --phenoCol=${STATUS} \
        --covarColList=sex,age,pca \
        --sampleIDColinphenoFile=iid \
        --traitType=binary \
        --outputPrefix=${OUTPUT_PREFIX} \
        --LOCO=FALSE

Thanks.

**Comment by weizhouUMICH** [comment]
Hi @WeiWei060512, sorry for my late reply. 
Have you solved the problem? 
Generally, we use all autosomes for step 1 instead of splitting by chromosomes.

**Comment by cwu365** [comment]
Hi @WeiWei060512, Hi Wei Zhou, 
I got the same error today. Could you please let me know how you solved the issue by 'clean your input file'? 
Thanks so much for your help. 

"Error in if (MAF >= testMinMAF & markerInfo >= minInfo) { :
  missing value where TRUE/FALSE needed
Calls: SPAGMMATtest' 

here is my code i used for step2: 
Rscript ${mntdir}/step2_SPAtests.R \
--vcfFile=${efsdir}/wes/freeze5/100k.rare.vcf.gz \
--vcfFileIndex=${efsdir}/wes/freeze5/100k.rare.vcf.gz.tbi \
--vcfField=GT \
--chrom=22 \
--minMAF=0.0001 \
--minMAC=3 \
--sampleFile=${efsdir}/wes.100k.ids \
--GMMATmodelFile=${efsdir}/wes/${phe}_noautoimmune.rda \
--varianceRatioFile=${efsdir}/wes/${phe}_noautoimmune.varianceRatio.txt \
--SAIGEOutputFile=${efsdir}/wes/results2/${phe}_22_noautoimmune_saige.results.txt \
--numLinesOutput=2 \
--IsOutputAFinCaseCtrl=TRUE

**Comment by weizhouUMICH** [comment]
Hi @cwu365, 

Would you mind sharing more details of the log file?

Thanks,
Wei
