### ISSUE TITLE
Error running burden tests on autosomes + chrX at the same time

### ISSUE THREAD

**Issue by Alexander-Stuckey** [weizhouUMICH/SAIGE#350]
I am attempting to run step2 of SAIGE-GENE on autosomes and chrX at the same time.
I have set
`--is_rewrite_XnonPAR_forMales='TRUE'` and
`--X_PARregion='10001-2781479,155701383-156030895'`

However, I get the following error on all chromosomes, including chrX

Error in if (positionL[i] <= XPARregion[j, 2] & positionL[i] >= XPARregion[j,  : 
  argument is of length zero
Calls: SPAGMMATtest -> processMale_XnonPAR

If I run chrX by itself or disable is_rewrite_XnonPAR_forMales it runs fine.

Is what I am trying even possible? Or would you always recommend running chrX seperately?

Cheers,
Alex

**Comment by weizhouUMICH** [comment]
Hi @Alexander-Stuckey, 

Sorry for the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
