### ISSUE TITLE
Can I run SAIGE for every chromosome separately?

### ISSUE THREAD

**Issue by hehongyi** [weizhouUMICH/SAIGE#352]
Hi @weizhouUMICH

I have plink files for every chromosome separately and I am in trouble with merging these files. So can I fit the null model using lightly pruned variants only in chromosome 1, and then perform association test for variants in chromosome 1?

Best,

**Comment by weizhouUMICH** [comment]
Hi Hehongyi, 

We don't recommend doing this. Actually we are using leave-one-chromosome-out (LOCO=TRUE) for Step 1. 

We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
