### ISSUE TITLE
leave-one-chromosome-out can't be conducted

### ISSUE THREAD

**Issue by r-mustafa** [weizhouUMICH/SAIGE#353]
Hi,

I running step1 with LOCO=TRUE for binary trait. The process finished and generated three output files, _group2_chr22_30markers.SAIGE.results.txt  
group2_chr22.rda                          
group2_chr22.varianceRatio.txt_ 

but there is error message as shown below:

_WARNING: leave-one-chromosome-out is activated! Note this option will only be applied to autosomal variants
WARNING: Genetic variants needs to be ordered by chromosome and position in the Plink file
chromosomeStartIndexVec: NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA 0
chromosomeEndIndexVec: NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA 1255682
WARNING: The number of autosomal chromosomes is less than 2 and leave-one-chromosome-out can't be conducted!_

The plink files are available by chromosome, and the position of SNPs has been ordered. 
1255682 is the number of SNPs in chr22 (this is the case for other chromosomes as well).

Any thoughts?

I appreciate any help on this.

Many thanks,
Rima

**Comment by weizhouUMICH** [comment]
Hi Rima, 
Sorry fo the late reply! We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
