### ISSUE TITLE
Error with numeric headers in step 1

### ISSUE THREAD

**Issue by yningvu** [weizhouUMICH/SAIGE#354]
Hi,

I had come across an error when parsing the phenoFile in step1. My headers contain some numerical ones, and the error message is as follow

Error in fitNULLGLMM(plinkFile = opt$plinkFile, phenoFile = opt$phenoFile,  :
  ERROR! column for 1936 does not exist in the phenoFile

After a double-check, I'm sure the column 1936 is there. Then I changed the column headers into strings, and it worked well.

**Comment by weizhouUMICH** [comment]
Sorry for the late reply! We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
