### ISSUE TITLE
Install error-Failed to build package statgen/savvy

### ISSUE THREAD

**Issue by Alexander-Mei** [weizhouUMICH/SAIGE#355]
I tried to install SAIGE, using the both 2 method: 
1, devtools::install_github("weizhouUMICH/SAIGE"); 
or 2, src_branch=master
repo_src_url=https://github.com/weizhouUMICH/SAIGE
git clone --depth 1 -b $src_branch $repo_src_url
R CMD INSTALL --library=path_to_final_SAIGE_library SAIGE

but got the error: 
Failed to build package statgen/savvy
   ERROR: configuration failed for package ‘SAIGE’
─  removing ‘/tmp/Rtmpm1heSP/Rinstd456f00687f/SAIGE’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'SAIGE' from GitHub:
  System command error

**Comment by lanxianmei** [comment]
Hello, have you solved the problem? I have the same problem.

**Comment by weizhouUMICH** [comment]
Sorry for the late reply! We have just released a new version 1.0.0. It has substantial computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests and clearer log output. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
