### ISSUE TITLE
https://pheweb.org/MGI-BioVU/about

### ISSUE THREAD

**Issue by Shicheng-Guo** [weizhouUMICH/SAIGE#357]
Dear Wei, 

Do you know how to download summary statistics for this pheweb server?

https://pheweb.org/MGI-BioVU/about

Thanks. 

Shicheng

**Comment by weizhouUMICH** [comment]
Hi Shicheng, 
You may download the results here
https://phewascatalog.org/labwas
Thanks,
Wei
