### ISSUE TITLE
SAIGE step2 error

### ISSUE THREAD

**Issue by lanjblue** [weizhouUMICH/SAIGE#360]
I just installed the newest SAIGE version using docker://wzhou88/saige:0.44.6.1. On the second step, it failed with the following error msg:

16805  samples have been used to fit the glmm null model
Leave chromosome  7  out will be applied
chromosome  1  model results are removed to save memory
chromosome  2  model results are removed to save memory
chromosome  3  model results are removed to save memory
chromosome  4  model results are removed to save memory
chromosome  5  model results are removed to save memory
chromosome  6  model results are removed to save memory
chromosome  8  model results are removed to save memory
chromosome  9  model results are removed to save memory
chromosome  10  model results are removed to save memory
chromosome  11  model results are removed to save memory
chromosome  12  model results are removed to save memory
chromosome  13  model results are removed to save memory
chromosome  14  model results are removed to save memory
chromosome  15  model results are removed to save memory
chromosome  16  model results are removed to save memory
chromosome  17  model results are removed to save memory
chromosome  18  model results are removed to save memory
chromosome  19  model results are removed to save memory
chromosome  20  model results are removed to save memory
chromosome  21  model results are removed to save memory
chromosome  22  model results are removed to save memory
Single variance ratio is provided, so categorical variance ratio won't be used!
variance Ratio is  0.9931717
94863  sample IDs are found in sample file
isCondition is  FALSE
Setting genomic region 7:1:250000000
WARNING: Open VCF failed
[1] 94863     4
[1] "IID"          "IndexInModel" "IndexDose.x"  "IndexDose.y"
16805  samples were used in fitting the NULL glmm model and are found in sample file
sparse kinship matrix is not used
Missing dosages will be mean imputed for the analysis
Analysis started at  1627062466 Seconds
minMAC:  1
minMAF:  0
Minimum MAF of markers to be tested is  2.975305e-05
It is a binary trait
Analyzing  290  cases and  16515  controls
isCondition is  FALSE
Analysis started at  1627062466 Seconds
Warning: missing FMT field (DS)
Error in if (markerInfo >= 0 & markerInfo <= 1) { :
  argument is of length zero
Calls: SPAGMMATtest
Execution halted

I don't understand what's wrong?

thank you!

**Comment by michelemarongiu79** [comment]
Hi lanjblue,
i have the same error.
Were you able to solve?

**Comment by lanjblue** [comment]
For that analysis, I wasn't able to fix the problem, so I switched back to older version 0.42.1.

**Comment by weizhouUMICH** [comment]
Sorry for the very late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
