### ISSUE TITLE
Problem installing savvy

### ISSUE THREAD

**Issue by Reavyr** [weizhouUMICH/SAIGE#362]
When trying to install SAIGE either with

export CFLAGS="-fPIC"; export CXXFLAGS="-fPIC"; cget install -f requirements.txt

or

R CMD INSTALL --library=/home/user/software/R-4.0.0/library SAIGE

I get:

Scanning dependencies of target sav
[ 16%] Building CXX object CMakeFiles/sav.dir/src/sav/main.cpp.o
[ 41%] Building CXX object CMakeFiles/sav.dir/src/sav/head.cpp.o
[ 75%] Building CXX object CMakeFiles/sav.dir/src/sav/sort.cpp.o
[ 91%] Building CXX object CMakeFiles/sav.dir/src/sav/concat.cpp.o
[ 91%] Building CXX object CMakeFiles/sav.dir/src/sav/export.cpp.o
[ 91%] Building CXX object CMakeFiles/sav.dir/src/sav/import.cpp.o
[ 91%] Building CXX object CMakeFiles/sav.dir/src/sav/index.cpp.o
[ 91%] Building CXX object CMakeFiles/sav.dir/src/sav/merge.cpp.o
[ 91%] Building CXX object CMakeFiles/sav.dir/src/sav/rehead.cpp.o
[ 91%] Building CXX object CMakeFiles/sav.dir/src/sav/stat.cpp.o
[ 91%] Building CXX object CMakeFiles/sav.dir/src/sav/utility.cpp.o
In file included from /home/user/software/SAIGE/thirdParty/cget/cget/build/tmp-3455d2ae89894b2481d478654b43c4f4/savvy-2aa2af64142a9f729b03e7bf84b6b39beb23b6d3/include/savvy/sav_reader.hpp:12:0,
                 from /homes/user/software/SAIGE/thirdParty/cget/cget/build/tmp-3455d2ae89894b2481d478654b43c4f4/savvy-2aa2af64142a9f729b03e7bf84b6b39beb23b6d3/include/sav/sort.hpp:10,
                 from /home/user/software/SAIGE/thirdParty/cget/cget/build/tmp-3455d2ae89894b2481d478654b43c4f4/savvy-2aa2af64142a9f729b03e7bf84b6b39beb23b6d3/src/sav/main.cpp:14:
/home/user/software/SAIGE/thirdParty/cget/cget/build/tmp-3455d2ae89894b2481d478654b43c4f4/savvy-2aa2af64142a9f729b03e7bf84b6b39beb23b6d3/include/savvy/s1r.hpp: In member function ‘std::fstream savvy::s1r::writer::close()’:
/home/user/software/SAIGE/thirdParty/cget/cget/build/tmp-3455d2ae89894b2481d478654b43c4f4/savvy-2aa2af64142a9f729b03e7bf84b6b39beb23b6d3/include/savvy/s1r.hpp:829:14: error: ‘std::fstream’ has no member named ‘swap’
         ofs_.swap(ret);
              ^
/home/user/software/SAIGE/thirdParty/cget/cget/build/tmp-3455d2ae89894b2481d478654b43c4f4/savvy-2aa2af64142a9f729b03e7bf84b6b39beb23b6d3/include/savvy/s1r.hpp:830:16: error: use of deleted function ‘std::basic_fstream<char>::basic_fstream(const std::basic_fstream<char>&)’
         return ret;

**Comment by weizhouUMICH** [comment]
Sorry for the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
