### ISSUE TITLE
Error in SAIGE on bioconda

### ISSUE THREAD

**Issue by Amelia-uoft** [weizhouUMICH/SAIGE#364]
Hello,

I am very new to R-SAIGE. I tried to follow https://github.com/weizhouUMICH/SAIGE/issues/272 to install SAIGE package and run your example. I typed "step1_fitNULLGLMM.R --help
step2_SPAtests.R --help
createSparseGRM.R --help"
They all worked. However, I always got the following output when I ran your example. Could you please let me know you suggestions to help solve the problem? Many thanks!

step1_fitNULLGLMM.R     \

        --plinkFile=nfam_100_nindep_0_step1_includeMoreRareVariants_poly \

        --phenoFile=pheno_1000samples.txt_withdosages_withBothTraitTypes.txt \

Loading required package: optparse
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
BLAS/LAPACK: /Users/briolaisnew2/opt/anaconda3/envs/saige/lib/libopenblasp-r0.3.17.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] optparse_1.6.6 SAIGE_0.44.5  

loaded via a namespace (and not attached):
[1] compiler_4.0.5     Matrix_1.3-4       Rcpp_1.0.7         getopt_1.20.3     
[5] grid_4.0.5         RcppParallel_5.1.4 lattice_0.20-44   
$plinkFile
[1] ""

$phenoFile
[1] ""

$phenoCol
[1] ""

$traitType
[1] "binary"

$invNormalize
[1] FALSE

$covarColList
[1] ""

$sampleIDColinphenoFile
[1] "IID"

$tol
[1] 0.02

$maxiter
[1] 20

$tolPCG
[1] 1e-05

$maxiterPCG
[1] 500

$nThreads
[1] 1

$SPAcutoff
[1] 2

$numRandomMarkerforVarianceRatio
[1] 30

$skipModelFitting
[1] FALSE

$memoryChunk
[1] 2

$tauInit
[1] "0,0"

$LOCO
[1] TRUE

$traceCVcutoff
[1] 0.0025

$ratioCVcutoff
[1] 0.001

$outputPrefix
[1] "~/"

$IsOverwriteVarianceRatioFile
[1] FALSE

$IsSparseKin
[1] FALSE

$numRandomMarkerforSparseKin
[1] 2000

$isCateVarianceRatio
[1] FALSE

$relatednessCutoff
[1] 0.125

$cateVarRatioMinMACVecExclude
[1] "0.5,1.5,2.5,3.5,4.5,5.5,10.5,20.5"

$cateVarRatioMaxMACVecInclude
[1] "1.5,2.5,3.5,4.5,5.5,10.5,20.5"

$isCovariateTransform
[1] TRUE

$isDiagofKinSetAsOne
[1] FALSE

$useSparseSigmaConditionerforPCG
[1] FALSE

$useSparseSigmaforInitTau
[1] FALSE

$useSparseGRMtoFitNULL
[1] FALSE

$minMAFforGRM
[1] 0.01

$minCovariateCount
[1] -1

$includeNonautoMarkersforVarRatio
[1] FALSE

$FemaleOnly
[1] FALSE

$MaleOnly
[1] FALSE

$sexCol
[1] ""

$FemaleCode
[1] "1"

$MaleCode
[1] "0"

$noEstFixedEff
[1] FALSE

$help
[1] FALSE

tauInit  is  0 0 
cateVarRatioMinMACVecExclude  is  0.5 1.5 2.5 3.5 4.5 5.5 10.5 20.5 
cateVarRatioMaxMACVecInclude  is  1.5 2.5 3.5 4.5 5.5 10.5 20.5 
Markers in the Plink file with MAF >=  0.01  will be used to construct GRM
Error in fitNULLGLMM(plinkFile = opt$plinkFile, phenoFile = opt$phenoFile,  : 
  WARNING: The variance ratio file ~/.varianceRatio.txt already exists. The new variance ratios will be output to ~/.varianceRatio.txt. In order to avoid overwriting the file, please remove the ~/.varianceRatio.txt or use the argument outputPrefix_varRatio to specify a different prefix to output the variance ratio(s). Otherwise, specify IsOverwriteVarianceRatioFile=TRUE so the file will be overwritten with new variance ratio(s)
Execution halted
zsh: command not found: --plinkFile=nfam_100_nindep_0_step1_includeMoreRareVariants_poly
zsh: command not found: --phenoFile=pheno_1000samples.txt_withdosages_withBothTraitTypes.txt

**Comment by Amelia-uoft** [comment]
The example script is working on my computer now.

**Comment by jingydz** [comment]
I encountered the same problem as you did, and I solved it by adding the command "--IsOverwriteVarianceRatioFile=TRUE".
