### ISSUE TITLE
Not sure if LOCO=TRUE worked

### ISSUE THREAD

**Issue by adanordeidet** [weizhouUMICH/SAIGE#366]
Hi,

I am new to using SAIGE and I am trying to do a test run. I have run step1_fitNULLGLMM, with plink files as genotype data, and I have a binary phenotype. I want to use LOCO, and set --LOCO=TRUE. However, I am not sure if LOCO was used.

The start of the screen output state that LOCO is activated:

tauInit  is  0 0
cateVarRatioMinMACVecExclude  is  0.5 1.5 2.5 3.5 4.5 5.5 10.5 20.5
cateVarRatioMaxMACVecInclude  is  1.5 2.5 3.5 4.5 5.5 10.5 20.5
Markers in the Plink file with MAF >=  0.01  will be used to construct GRM
WARNING: leave-one-chromosome-out is activated! Note this option will only be applied to autosomal variants
WARNING: Genetic variants needs to be ordered by chromosome and position in the Plink file
chromosomeStartIndexVec:  0 31930 60927 85399 106357 127125 147860 167161 184761 200788 218105 237994 255943 267590 279461 291011 303912 317014 326180 338581 347850 352885
chromosomeEndIndexVec:  31929 60926 85398 106356 127124 147859 167160 184760 200787 218104 237993 255942 267589 279460 291010 303911 317013 326179 338580 347849 352884 358955
35171  samples have genotypes
formula is  ht_code~BirthYear+Sex+PC1+PC2+PC3+PC4+PC5+PC6+PC7+PC8+PC9+PC10
35292  samples have non-missing phenotypes
35171  samples will be used for analysis
qr transformation has been performed on covariates
colnames(data.new) is  Y minus1 BirthYear Sex PC1 PC2 PC3 PC4 PC5 PC6 PC7 PC8 PC9 PC10
out.transform$Param.transform$qrr:  13 13
ht_code  is a binary trait
glm:

However, at the end of the screen output, it said that the LOCO command was not found:

closed the plinkFile!
./myscript_step1_fitNULLGLMM.sh: line 10: --LOCO=TRUE: command not found

How do I know if LOCO was used?

**Comment by weizhouUMICH** [comment]
Hi, 
Sorry for the late reply! We have just released a new version 1.0.0. 
It definitely uses LOCO by default for both steps. 
It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
