### ISSUE TITLE
Open VCF failed

### ISSUE THREAD

**Issue by lgb-cyber** [weizhouUMICH/SAIGE#368]
Hello, I am running the step2_SPAtests.R. However, it reported error : Open VCF failed and the step2 stopped.
![image](https://user-images.githubusercontent.com/69227718/133224752-d1d509e3-4bb6-41cf-99e4-50d421407cc0.png)
This is what my VCF file looks like, is there anything wrong ?
![image](https://user-images.githubusercontent.com/69227718/133224375-e6ebf343-b36c-4fc0-8b59-102cfbe35491.png)
looking forward to answer, thanks!

**Comment by weizhouUMICH** [comment]
Sorry for the very late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
