### ISSUE TITLE
SAIGE-0.44.6.1         step2_SPAtests.R  Error

### ISSUE THREAD

**Issue by liwangchang** [weizhouUMICH/SAIGE#371]
1000  samples were used in fitting the NULL glmm model and are found in sample file
sparse kinship matrix is not used
Missing dosages will be mean imputed for the analysis
Analysis started at  1632365348 Seconds
minMAC:  1 
minMAF:  1e-04 
Minimum MAF of markers to be tested is  5e-04 
It is a binary trait
Analyzing  0  cases and  0  controls 
isCondition is  FALSE 
Analysis started at  1632365348 Seconds
Error in obj.null$XV %*% G : 
  requires numeric/complex matrix/vector arguments
Calls: SPAGMMATtest ... scoreTest_SAIGE_binaryTrait_cond_sparseSigma -> Score_Test
Execution halted

What causes this error

**Comment by weizhouUMICH** [comment]
Sorry for the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
