### ISSUE TITLE
Can SAIGE handle NAs in phenotype file

### ISSUE THREAD

**Issue by adanordeidet** [weizhouUMICH/SAIGE#372]
Hi,

I want to perform single-variant association tests, and I have one file containing data on multiple binary phenotypes (one column for each phenotype, with 1/0/NA). I know that I have to run step1 for each phenotype (specified by phenoCol) and that it has to be 1 and 0 in the phenotype column. But I want to know if there can be NAs as well? 

If there cannot be NAs, I guess I will have to make one phenotype file for each phenotype, to only have 1 and 0 in the column.

**Comment by weizhouUMICH** [comment]
Hi @adanordeidet, 

Yes, any sample with missing (NA) for the phenotype or any covariates will be removed from the analysis. 

Thanks,
Wei
