### ISSUE TITLE
Same script but different results

### ISSUE THREAD

**Issue by Abdelrahman-Galal** [weizhouUMICH/SAIGE#373]
For some reason I decided to re-run a GWAS with exactly the same script (same phenotype file , same data , same parameters ) , however the results for step-1 and step-2 are different between the two runs (not exactly the same either in calculation in logs , size of the output files or summary stats numbers).

I have doubled check that everything is the same,so is that a normal behavior or I am missing something here?

I use SAIGE version 0.43.1

Thanks.

**Comment by weizhouUMICH** [comment]
Hi @Abdelrahman-Galal, 

Sorry for the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. 
Can you please try it to see how the results look like? The results may be different between very old versions and newer versions, as some change might have been made to improve the program's performance for lager data sizes. But it is unusual if the results are very different for the same markers. 

We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
