### ISSUE TITLE
SAIGE combined pathway enrichment analysis? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [weizhouUMICH/SAIGE#374]
Dear Wei, 

Have you ever test which pathway enrichment approaches would be the best recombination with SAIGE? for example, MAGMA, VEGAS2

Thanks

Shicheng

**Comment by weizhouUMICH** [comment]
Dear Shicheng, 

We didn't try the pathway enrichment analysis before. 

Thanks,
Wei
