### ISSUE TITLE
SAIGE single variant error for allocate large memory

### ISSUE THREAD

**Issue by ypnngaa-py** [weizhouUMICH/SAIGE#378]
Hi, 
I am using SAIGE to analyze UKB WES data. Sample size is about 180K after filtering. To reduce the burden, the plink file for null model only contains common variants (MAF>0.01)
So far I have no luck running the null model as it failed to allocate large size of memory. 200G mem is close to the limit of the cluster I have access to.  Let me know if this is expected and if there is a workaround. 

Look forward to hearing from you.  Thanks!

See below for the running log error message:

> 178604  samples have non-missing phenotypes
21027  samples in geno file do not have phenotypes
178604  samples will be used for analysis
qr transformation has been performed on covariates
Error: cannot allocate vector of size 177.9 Gb
Execution halted
Warning message:
system call failed: Cannot allocate memory

**Comment by weizhouUMICH** [comment]
Sorry for my late reply.

We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/

The program will be maintained by multiple SAIGE developers there. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
