### ISSUE TITLE
Error at step2 running gene-based testing: has N = 0 (mismatch with header block)

### ISSUE THREAD

**Issue by xmduumich** [weizhouUMICH/SAIGE#383]
Dear Wei Zhou,

When running SAIGE-GENE we observed this error message: 

ERROR:  has N = 0 (mismatch with header block)

I cannot find documentation to interpret or troubleshoot what cause this. Could you help me to figure out what it means and how to resolve it? 

Here I attach the .log file from running step2_SPAtests.R.

[step2_GB_PDFF_4_7_QCed_chr22.log](https://github.com/weizhouUMICH/SAIGE/files/7643127/step2_GB_PDFF_4_7_QCed_chr22.log)
Thank you for your help!

**Comment by weizhouUMICH** [comment]
Sorry for my late reply.

We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/

The program will be maintained by multiple SAIGE developers there. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
