### ISSUE TITLE
Error Step 2: The number of samples specified in the sample file does not equal to the number of samples in the bgen file

### ISSUE THREAD

**Issue by Mahmedturk** [weizhouUMICH/SAIGE#384]
Hi, This is my first time doing the RSAIGE analyses, kindly excuse me if it's a basic question. After doing successfully step 1 on chromosome 22 i get the below error on step 2.  Any help would be greatly appreciated.

Error in SPAGMMATtest(vcfFile = opt$vcfFile, vcfFileIndex = opt$vcfFileIndex,  : 
  ERROR! The number of samples specified in the sample file does not equal to the number of samples in the bgen file
Execution halted

**Comment by weizhouUMICH** [comment]
Hi @Mahmedturk, 
The sample file contains one column without any header for all sample IDs that match the order in the bgen file. Can you have a check? 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/

The program will be maintained by multiple SAIGE developers there. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei

**Comment by raminsalmas** [comment]
> 

You mean the size of samples here is not the same as case-control samples?
