### ISSUE TITLE
Burden test produced lower P value than SKAT-O

### ISSUE THREAD

**Issue by aoxiang88** [weizhouUMICH/SAIGE#387]
Hi Weizhou,

Thanks for your amazing tool. 

I applied the SAIGE-GENE (version 0.44.2) in UK Biobank 200k WES data,  there I found a gene has lower p-value produced by burden test than SKAT-O. Is this case reasonable? My understanding is that SKAT-O will always produce lower p-value than both burden test and SKAT. 

Another stupid question regarding to the p-value is: say I have a set of rare variants for one gene, if I add more rare variants from the same gene in the set, am I able to obtain lower p-value from the larger set than the fewer set?  

Best,

Xao

**Comment by weizhouUMICH** [comment]
Hi Xao, 
SKAT-O does not always have the the lower p-value than burden and SKAT, so it is reasonable a gene can have a lower p-value produced by the burden test. It is possible that the the most of the variants tested in the gene are causal and have the same effect direction. For the second question, it is not necessary adding more variants leads to lower p-value. The power of the tests can be affected by whether the assumptions of the different tests are met. 

Thanks,
Wei
