### ISSUE TITLE
"isSparse" not found

### ISSUE THREAD

**Issue by oalavijeh** [weizhouUMICH/SAIGE#389]
Dear Wei, 

Thank you such an amazing tool! I was trying to run SAIGE on a quantitative trait and when running SPA_test step2 I keep getting an error:

"Error in scoreTest_SAIGE_quantitativeTrait_sparseSigma(G0, obj.model.sub$obj.noK, : objest "isSparse' not found 
Execution halted

I have tried setting "isSparse" to TRUE,FALSE and just deleting it but this does not work. 

I am working in an airlock using biobank data so cannot easily share code I am afraid but can offer screenshots if needed. 

Many thanks for your help

**Comment by weizhouUMICH** [comment]
Hi @oalavijeh, 

Which version of SAIGE are you using? 

Thanks,
Wei

**Comment by oalavijeh** [comment]
Dear Wei, 

We are using SAIGE-GENE v0.42.1

Many thanks

Omid

**Comment by weizhouUMICH** [comment]
Hi Omid, 

Sorry for my late reply. 

We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/

The program will be maintained by multiple SAIGE developers there. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
