### ISSUE TITLE
Update cmd.sh examples to reflect minMAC limitations

### ISSUE THREAD

**Issue by carbocation** [weizhouUMICH/SAIGE#39]
In the README you note, "Since the SPA test always provides close to 0 p-values for variants with MAC < 3, please use at least minMAC = 3 to filter out the results"

In the cmd.sh examples, however, every example for which minMAC is specified has it set to 1. Might be good to update cmd.sh to reflect the README. I'd be happy to submit a pull request. (Or, you could consider programmatically blocking any minMAC < 3 if the results are never going to be sensible.)

**Comment by weizhouUMICH** [comment]
Just updated. Thanks!

**Comment by carbocation** [comment]
Thanks! I'll close this issue to keep your issues list clean.
