### ISSUE TITLE
pcg did not converge

### ISSUE THREAD

**Issue by ytao0210** [weizhouUMICH/SAIGE#394]
When I used saige to run the step1, an error occurred:
"pcg did not converge. You may increase maxiter number.
iter from getPCG1ofSigmaAndVector 500" 
how can i solve this problem?

**Comment by weizhouUMICH** [comment]
This is usually because the GRM is close to singular and non-invertible. Can you check if there are twins or duplicated samples in the data set?

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/

The program will be maintained by multiple SAIGE developers there. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
