### ISSUE TITLE
Error in step2 of saige gene for some genes in group file

### ISSUE THREAD

**Issue by aokulabasile** [weizhouUMICH/SAIGE#396]
Hello,

I am encountering the following error when running step 2 of Saige GENE v 0.42.1:

"Error in array(a, dim = c(nrow(Gmat), ncol(Gmat))) : object 'a' not found
Calls: SPAGMMATtest -> groupTest -> array
Execution halted" 

I've attached the log file and the group file to this issue.  As you can see SAIGE-GENE runs successfully for a a number of genes in the group file until it gets to gene _ADAM12_ where it encounters the above error.  I can't figure it out what it is about this gene that is causing the error. As recommended, variants are sorted by position, and follow the recommended variant naming of chrX:POS_REF/ALT. Any advice would be greatly appreciated. 

**Group file:** 
[chr10_r2_above_0.3.dose_samps.renamed_sample.subset_n393.vep_annotated_groupfile.txt](https://github.com/weizhouUMICH/SAIGE/files/7937612/chr10_r2_above_0.3.dose_samps.renamed_sample.subset_n393.vep_annotated_groupfile.txt)

**Log file:**
[saige_gene_assoc_test_17547499_1.log](https://github.com/weizhouUMICH/SAIGE/files/7937662/saige_gene_assoc_test_17547499_1.log)

Thank you!

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/

The program will be maintained by multiple SAIGE developers there. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
