### ISSUE TITLE
Categorical covariates not working yet, but including sex is okay?

### ISSUE THREAD

**Issue by endrebak** [weizhouUMICH/SAIGE#4]
I do not understand this section from the `fitNULLGLMM` R docs:

```
covarColList: vector of characters. Covariates to be used in the glm
          model e.g c("Sex", "Age")

qCovarCol: vector of characters. Categorical covariates to be used in
          the glm model (NOT work yet)
```

Isn't sex a categorical variable?

**Comment by ilarsf** [comment]
Yes, you're right, this is somewhat confusing. Categorical covariates can
be nominal, ordinal or dichotomous.
In this cases, Wei is referring to nominal and ordinal covariates as "
qCovarCol".
--> Nominal and ordinal covariates were not properly implemented in the glm
model yet.
.
Dichotomous and quantitative covariates should be included in the "
covarColList"
