### ISSUE TITLE
Issues with --useSparseGRMtoFitNULL=TRUE

### ISSUE THREAD

**Issue by eugenegardner** [weizhouUMICH/SAIGE#401]
Hello,

Apologies if this has been asked already, but I did search through the already posted issues...

I was wondering if some assistance/direction could be provided when running SAIGE-GENE+. Based on the BioRxiv manuscript, my assumption is that enabling SAIGE-GENE+ simply means toggling the --useSparseGRMtoFitNULL option to TRUE? When I do this, I see VASTLY different p. values for known associations (an example is 1x10-16 changed to 1x10-5) for a continuous trait. I am unsure if this is due to:

1. How I have calculated the sparse GRM. This was done using the UKBiobank provided GENETIC plink files (I think this is correct).
2. Something internal to SAIGE-GENE+ that I don't understand.

I would go back to just using --useSparseGRMtoFitNULL=FALSE. However, runtimes for step1 for the entire UK Biobank dataset have proved excessive when trying to analyse traits across all ~400k European samples.

I would appreciate any tips/suggestions would be much appreciated.

**Comment by weizhouUMICH** [comment]
Hi @eugenegardner, 

Thanks for your question! Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. Note that the SAIGE-GENE+ collapsed ultra-rare variants to solve the inflation issue observed in the SKAT and SKAT-O tests for binary phenotypes with unbalanced case-control ratios. Here you may find several options to create a sparse GRM. 

https://saigegit.github.io//SAIGE-doc/docs/createSparseGRM.html

Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
