### ISSUE TITLE
segfaults on newer SAIGE in Docker. Older versions still work.

### ISSUE THREAD

**Issue by pettyalex** [weizhouUMICH/SAIGE#404]
My group has seen segfaults whenever we run the step2 analysis with the released SAIGE docker image with version 0.44.1 or newer. 

I've seen a collection of similar reports in other issues, but I wanted to specifically mention that we tried every single version that is released, and the newest one that is working for us is 0.43.2. 

Is it possible that the docker image is using base libraries that are too old? I noticed that the README recommends R 3.6.1, but the docker image is shipping R 3.5.1. Is the docker image working for anyone with recent releases?

https://github.com/weizhouUMICH/SAIGE/issues/382
https://github.com/weizhouUMICH/SAIGE/issues/369
https://github.com/weizhouUMICH/SAIGE/issues/346

**Comment by weizhouUMICH** [comment]
Hi @pettyalex, 

Sorry fo the late reply!  We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/

The program will be maintained by multiple SAIGE developers there. The docker image has been updated. I've previously successfully used the docker image for version 0.99.3 on both Google cloud and DNAnexus. Please feel free to try the version 1.0.0 and report issues if any. 

Thanks!
Wei
