### ISSUE TITLE
Effect size

### ISSUE THREAD

**Issue by mkierczak** [weizhouUMICH/SAIGE#405]
Hi! I am working with simulated data where I know the exact effect size. When running SAIGE SPA tests, I see my simulated signals (single common variant)correctly being the ones with the lowest p-value but the BETAs are way off from what I am simulating. I tried to change kernel to `linear` as well ass setting Beta distribution params for common and rare alleles to `Beta(1,1)` with no improvement. In my toy example, effects ate supposed to be around 1. BETAs I observe, are really spread with no systematic error as far as I can see. Could you possibly have some hints for me?

**Comment by saigegit** [comment]
Hi @mkierczak, 
It is known that the beta estimation based on the score test statistics is biased, especially for rare variants. We now just have released a new version 1.0.0 of SAIGE/SAIGE-GENE, in which we implemented the the effect size estimation through the Firth's Bias-Reduced Logistic Regression. Please feel free to try it and open the issue in the new github. 
https://github.com/saigegit/SAIGE
Thanks,
Wei
