### ISSUE TITLE
permutation test to phewas analysis to decrease the burden of multiple testing correction

### ISSUE THREAD

**Issue by Shicheng-Guo** [weizhouUMICH/SAIGE#406]
Dear Wei, 

I am wondering Is there any possibility to perform permutation test to phewas analysis with SAIGE to decease the burden of multiple test correction? 

Thanks. 

Shicheng

**Comment by weizhouUMICH** [comment]
Dear Shicheng, 

We didn't try the permutation test before. I will let you know if I come up with some ideas. 

Thanks,
Wei
