### ISSUE TITLE
Build is not reproducible due to symlinks

### ISSUE THREAD

**Issue by carbocation** [weizhouUMICH/SAIGE#41]
I am trying to make a reproducible build, in order to fork this package to permit separate .bim/.bed/.fam files (see #40 ). However, I cannot easily reproduce your build, because this .git repo is full of symlinks. E.g.:

```
~/code/SAIGE/thirdParty/cget/bin $ ls -l
sav -> /net/hunt/zhowei/project/imbalancedCaseCtrlMixedModel/Rpackage_SPAGMMAT/SAIGE/thirdParty/cget/cget/pkg/statgen__savvy/install/bin/sav
```

As you can see, this file (and many others) symlink to something that expects to be at the path /net/hunt/zhowei . Is it possible to remove the symlinks and to instead include the dependencies?

**Comment by weizhouUMICH** [comment]
Hello @carbocation, 

I tried to manually replace the symlinks and the compilation failed after then. It seems that the way to solve the symlinks issue is after you download the SAIGE folder, rm -r cget in the thirdParty folder and re-download and install the savvy library 

https://github.com/statgen/savvy/

Thanks,
Wei
