### ISSUE TITLE
calculating odds ratio

### ISSUE THREAD

**Issue by ukbsc** [weizhouUMICH/SAIGE#43]
Hi,

How can we convert the beta from step 2 to odds ratio?

The exp(beta) gave me values from 1 to 30 for the top 10 hits.  

Thanks,
Amy

**Comment by weizhouUMICH** [comment]
Hi Amy,

The odds ratio is supposed to be calculated using exp(beta).  The penalized
quasi-likelihood followed by SPA test does a good job to estimate p-values,
but may perform poorly in estimating the parameters (e.g. beta), especially
for those rare variants. The best way to estimate odds ratio accurately
would be using the Firth test with related samples excluded.

Thanks,
Wei

**Comment by sboer** [comment]
Does this mean that using betas and SE for meta analysis is not a good idea? Should you rather use the p-value?

Thanks, 
Sigrid

**Comment by weizhouUMICH** [comment]
Betas and SE for not-so-variants, e,g. with MAC >= 20, may be fine to use
for meta-analysis.

**Comment by sboer** [comment]
Thanks for clarifying!

**Comment by oalavijeh** [comment]
Could I ask if there is example code for this? I have summary stats from a SAIGE-GENE analysis collapsed per gene. How would I apply Firth testing to this dataset to get the OR. I have been pulling the variants that make up the signal and simply counting how many of these are found in my cases/controls and doing a simple OR calculation this way. Is there a better method using summary stats? 

Many thanks
