### ISSUE TITLE
SAIGE step 1 error

### ISSUE THREAD

**Issue by fadista** [weizhouUMICH/SAIGE#44]
Hi,

I got this error message when fitting the null model (SAIGE step1) on a UK Biobank binary trait:

`Loading required package: optparse
Error in SPAtest:::Saddle_Prob_fast(q = qtilde, g = g, mu = mu, gNA = g[NAset],  : 
  argument "output" is missing, with no default
Calls: fitNULLGLMM ... scoreTest_SPAGMMAT_forVarianceRatio_binaryTrait -> <Anonymous>
Execution halted
`

My step 1 command was:
`/services/tools/R-3.2.1/bin/Rscript --vanilla /home/projects/ssi_gen1/data/UKbiobank/genotype/scripts/step1_fitNULLGLMM.R \
	--plinkFile=/home/projects/ssi_gen1/data/UKbiobank/genotype/SAIGE/step1_SAIGE.ch1-22_clean \
	--phenoFile=/home/projects/ssi_gen1/data/UKbiobank/genotype/SAIGE/hernias_pheno_plus_covariates.txt \
	--phenoCol=SPECIFIC5 \
	--covarColList=sex,yob,pca1,pca2,pca3,pca4 \
	--sampleIDColinphenoFile=IID \
	--traitType=binary \
	--outputPrefix=/home/projects/ssi_gen1/data/UKbiobank/genotype/SAIGE/SPECIFIC5 \
	--nThreads=16 \
	--LOCO=TRUE`
Do you know what might be the problem? Thanks

**Comment by weizhouUMICH** [comment]
Hi,
Use the version 0.29.3 will solve the problem.
Thanks,
Wei

**Comment by esohkevin** [comment]
Hi,

I'm still getting this error with version 1.1.{4,5} pulled from docker hub with singularity.
I have tried changing my R versions but that couldn't solve the problem.
Any idea what might be wrong?

Thanks
