### ISSUE TITLE
Running step2 on subset of dosage file

### ISSUE THREAD

**Issue by FloWuenne** [weizhouUMICH/SAIGE#47]
Hi there,

I want to run SAIGE on some binary traits from the UKBB and wanted to know whether its possible to perform step2, association testing only on a subset of samples and variants from an existing bgen file? Is this already possible or do we have to subset our dosage file for the samples and variants we would like to test for every binary trait we want to test?

Thank you for the help,
Best,

Florian

**Comment by chinium14** [comment]
Hello, 

The options are already possible. 
1. For using a subset of samples, you may use the subset of samples in step 1, so in step 2, it will automatically only test the subset of samples that used in step 1.  
Note that in step 1, for different phenotypes, you just need to specify different phenotype files and use the same plink file. SAIGE automatically subsets the plink file according to the phenotype file. 
All samples used in step 1 are required to have non-missing dosages in step 2.

2. To test a subset of variants in bgen, you may specify a list of variant ids using the argument idstoIncludeFile. It specifies a file with a column for variant ids that you'd like to test. 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
Hello,

The options are already possible.

For using a subset of samples, you may use the subset of samples in step 1, so in step 2, it will automatically only test the subset of samples that used in step 1.
Note that in step 1, for different phenotypes, you just need to specify different phenotype files and use the same plink file. SAIGE automatically subsets the plink file according to the phenotype file.
All samples used in step 1 are required to have non-missing dosages in step 2.

To test a subset of variants in bgen, you may specify a list of variant ids using the argument idstoIncludeFile. It specifies a file with a column for variant ids that you'd like to test.

Thanks,
Wei

**Comment by FloWuenne** [comment]
Hi, 

thanks for the explanation regarding which samples are used in step2 based on building the model in step1. 

I finally got around to trying the option to only run association testing for a subset of markers using the idstoIncludeFile flag. I tried to only use 1 SNP from the UKBB imputed .bgen data files and I got the following error when trying to run step2 of SAIGE using 1 test SNP of the bgen file:

 *** caught segfault ***
address 0x51a9b880, cause 'memory not mapped'

Traceback:
 1: .Call("_SAIGE_getDosage_bgen_withquery", PACKAGE = "SAIGE")
 2: getDosage_bgen_withquery()
 3: SPAGMMATtest(dosageFile = opt$dosageFile, dosageFileNrowSkip = opt$dosageFileNrowSkip,     dosageFileNcolSkip = opt$dosageFileNcolSkip, dosageFilecolnamesSkip = dosageFilecolnames,     vcfFile = opt$vcfFile, vcfFileIndex = opt$vcfFileIndex, vcfField = opt$vcfField,     bgenFile = opt$bgenFile, bgenFileIndex = opt$bgenFileIndex,     savFile = opt$savFile, savFileIndex = opt$savFileIndex, chrom = opt$chrom,     start = opt$start, end = opt$end, sampleFile = opt$sampleFile,     GMMATmodelFile = opt$GMMATmodelFile, varianceRatioFile = opt$varianceRatioFile,     SAIGEOutputFile = opt$SAIGEOutputFile, minMAF = opt$minMAF,     minMAC = opt$minMAC, numLinesOutput = opt$numLinesOutput,     IsOutputAFinCaseCtrl = opt$IsOutputAFinCaseCtrl, LOCO = opt$LOCO,     idstoIncludeFile = opt$idstoIncludeFile)

Any idea where this might be coming from? I thought it might be related to the 8 bit compression again but even when I subset for a small number of variants and rerun on the 8bit compressed bgen file I get this error.

Any idea what could be causing this issue?

**Comment by weizhouUMICH** [comment]
Hi @FloWuenne, 

Would you mind trying the new version 0.36.2? Sorry I've missed your issue. 

Best,
Wei

**Comment by FloWuenne** [comment]
Hi @weizhouUMICH ,

I tested the new version of SAIGE on our HPC using the Docker container that I transformed into a Singularity .sif file. It seems to work perfectly fine now. The only thing that I have not yet figured out, is how to use the **--idstoIncludeFile** flag. When I supply a file that contains some variant IDs without a header, it does not seem to consider it and still computes all variants... 

The memory issue however seems resolved, thanks!

**Comment by weizhouUMICH** [comment]
Hi @FloWuenne, 
Sorry for my late reply. The idstoIncludeFile does not need a header but each line in this file corresponds to the rsid field in bgen files. 
If you specify a file for idstoIncludeFile and no IDs match in the bgen file, the log will output "No queried variant is found in the bgen file! All variants bgen file will be analyzed". 

Thanks!

Wei

**Comment by FloWuenne** [comment]
The suggestions from @weizhouUMICH work and this issue can be closed.
