### ISSUE TITLE
step 2 unexpectedly terminate

### ISSUE THREAD

**Issue by momo1210** [weizhouUMICH/SAIGE#48]
Hi,
I got an issue for step2, which unexpectedly terminate with a message:

"Analysis started at  1537078520 Seconds
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abort (core dumped)
"
Does anyone aware of what kind of problem is this?
Thanks!

**Comment by weizhouUMICH** [comment]
Hello, 

Could you please share a more detailed log file. e.g. what is the format of the your dosage file? 

Thanks,
Wei

**Comment by momo1210** [comment]
Hi Wei,

I just used your example file and example code and got the error message as below.


 SPAGMMATtest(
+ vcfFile= "genotype_10markers.vcf.gz",
+ vcfFileIndex="genotype_10markers.vcf.gz.tbi",
+ vcfField="GT",
+ chrom=1,
+ minMAF=0.0001,
+ minMAC=5,
+ sampleFile="sampleIDindosage.txt",
+ GMMATmodelFile="example.rda",
+ varianceRatioFile="example.varianceRatio.txt",
+ SAIGEOutputFile="example.SAIGE.vcf.dosage.out.txt",
+ numLinesOutput=2,
+ IsOutputAFinCaseCtrl=TRUE,
+ )
1000  samples have been used to fit the glmm null model
obj.glmm.null$LOCO:  FALSE
Leave-one-chromosome-out option is not applied
variance Ratio is  1
1000  sample IDs are found in sample file
[1] 1000    4
[1] "IID"          "IndexInModel" "IndexDose.x"  "IndexDose.y"
1000  samples were used in fitting the NULL glmm model and are found in sample file
minMAC:  5
minMAF:  1e-04
Minimum MAF of markers to be testd is  0.0025
Analysis started at  1537465735 Seconds
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abort (core dumped)

Any idea about this?

I used SAIGE_0.29.3 version and fantasia as the server to run.


Thanks!

Min-Lee

________________________________

**Comment by weizhouUMICH** [comment]
Hi Min-Lee, 

Thank you for letting me know about the error. A bug was found in the savvy library for reading vcf and sav dosages and has now been fixed. You may try the new version 0.29.4 on vcf files and please let me know if you have any other question. 

Thanks,
Wei

**Comment by momo1210** [comment]
Wei, Thanks!
After re-install 0.29.4, I still got the same error message for step2.

> library(SAIGE)
> SPAGMMATtest(
+ vcfFile= "genotype_10markers.vcf.gz",
+ vcfFileIndex="genotype_10markers.vcf.gz.tbi",
+ vcfField="GT",
+ chrom=1,
+ minMAF=0.0001,
+ minMAC=5,
+ sampleFile="sampleIDindosage.txt",
+ GMMATmodelFile="example.rda",
+ varianceRatioFile="example.varianceRatio.txt",
+ SAIGEOutputFile="example.SAIGE.vcf.dosage.out.txt",
+ numLinesOutput=2,
+ IsOutputAFinCaseCtrl=TRUE,
+ )
1000  samples have been used to fit the glmm null model
obj.glmm.null$LOCO:  FALSE
Leave-one-chromosome-out option is not applied
variance Ratio is  1
1000  sample IDs are found in sample file
[1] 1000    4
[1] "IID"          "IndexInModel" "IndexDose.x"  "IndexDose.y"
1000  samples were used in fitting the NULL glmm model and are found in sample file
minMAC:  5
minMAF:  1e-04
Minimum MAF of markers to be testd is  0.0025
Analysis started at  1537563549 Seconds
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
Abort (core dumped)

Could you please check it again?
Thanks!
Min-Lee
