### ISSUE TITLE
Step 1 error

### ISSUE THREAD

**Issue by yzharold** [weizhouUMICH/SAIGE#49]
Hi Wei, 

I have tried to run SAIGE on a large data set with 340,000 individuals and it showed the following error message, 

Warning message:
package ‘SAIGE’ was built under R version 3.4.4 
Loading required package: optparse
$plinkFile
[1] "/hpc/grid/hgcb/workspace/users/yez/UKBB/SAIGE_BINARY/data/ukb_v3_imp_unrelated_hwe10_ALL_HQ_genotyped_merged_cleaned_pruned"

$phenoFile
[1] "/hpc/grid/hgcb/workspace/users/yez/UKBB/SAIGE_BINARY/data/ukbb_n340409_qtnormBMI.phe.cov"

$phenoCol
[1] "binaryBMI"

$traitType
[1] "binary"

$invNormalize
[1] FALSE

$covarColList
[1] "PC1,PC2,PC3,PC4,PC5,PC6,PC5,PC6,PC7,PC8,PC9,PC10"

$sampleIDColinphenoFile
[1] "IID"

$numMarkers
[1] 30

$nThreads
[1] 24

$skipModelFitting
[1] FALSE

$traceCVcutoff
[1] 1

$ratioCVcutoff
[1] 1

$LOCO
[1] TRUE

$outputPrefix
[1] "/hpc/grid/hgcb/workspace/users/yez/UKBB/SAIGE_BINARY/results/UKBB_SAIGE_step1_test"

$help
[1] FALSE

24  threads are set to be used  
Leave-one-chromosome-out is activated
chromosomeStartIndexVec:  0 28088 57702 83499 108995 131872 157626 178886 198156 214035 232879 251734 269521 283027 295004 305462 316430 326497 337098 345371 353896 359145 
487409  samples have genotypes
formula is  binaryBMI~PC1+PC2+PC3+PC4+PC5+PC6+PC5+PC6+PC7+PC8+PC9+PC10 
340409  samples have non-missing phenotypes
147006  samples in geno file do not have phenotypes
340403  samples will be used for analysis
colnames(data.new) is  Y minus1 PC1 PC2 PC3 PC4 PC5 PC6 PC7 PC8 PC9 PC10 
out.transform$Param.transform$qrr:  11 11 
binaryBMI  is a binary trait

Call:  glm(formula = formula.new, family = binomial, data = data.new)

Coefficients:
   minus1        PC1        PC2        PC3        PC4        PC5        PC6  
 3.068310  -0.016061  -0.012399   0.001987   0.059132  -0.043205  -0.016568  
      PC7        PC8        PC9       PC10  
 0.010491  -0.001013   0.021151   0.007057  

Degrees of Freedom: 340403 Total (i.e. Null);  340392 Residual
Null Deviance:	    471900 
Residual Deviance: 123900 	AIC: 124000
[1] "Start reading genotype plink file here"
nbyte: 121853
nbyte: 85101
reserve: 31015448576

M: 364446, N: 487409
size of genoVecofPointers: 23
here
setgeno mark1
setgeno mark2
setgeno mark5
setgeno mark6
time: 2.10495e+06
[1] "Genotype reading is done"
inital tau is  1 0.5 
iGet_Coef:  1 
iter from getPCG1ofSigmaAndVector 15
iter from getPCG1ofSigmaAndVector 12
iter from getPCG1ofSigmaAndVector 14
iter from getPCG1ofSigmaAndVector 13
iter from getPCG1ofSigmaAndVector 14
iter from getPCG1ofSigmaAndVector 15
iter from getPCG1ofSigmaAndVector 15
iter from getPCG1ofSigmaAndVector 13
iter from getPCG1ofSigmaAndVector 14
iter from getPCG1ofSigmaAndVector 13
iter from getPCG1ofSigmaAndVector 14
iter from getPCG1ofSigmaAndVector 13
Tau:[1] 1.0 0.5
Fixed-effect coefficients:
               [,1]
 [1,]  3.0682561398
 [2,] -0.0152217094
 [3,] -0.0111878449
 [4,]  0.0004227166
 [5,]  0.0554068275
 [6,] -0.0415724479
 [7,] -0.0142366933
 [8,]  0.0095465006
 [9,] -0.0020530727
[10,]  0.0213206727
[11,]  0.0076414300
...
 *** caught segfault ***
address 0xd6e38, cause 'memory not mapped'

Traceback:
 1: .Call("_SAIGE_getCoefficients", PACKAGE = "SAIGE", Yvec, Xmat,     wVec, tauVec, maxiterPCG, tolPCG)
 2: getCoefficients(Y, X, W, tau, maxiter = maxiterPCG, tol = tolPCG)
 3: Get_Coef(y, X, tau, family, alpha0, eta0, offset, verbose = verbose,     maxiterPCG = maxiterPCG, tolPCG = tolPCG, maxiter = maxiter)
 4: glmmkin.ai_PCG_Rcpp_Binary(plinkFile, fit0, tau = c(0, 0), fixtau = c(0,     0), maxiter = maxiter, tol = tol, verbose = TRUE, nrun = 30,     tolPCG = tolPCG, maxiterPCG = maxiterPCG, subPheno = dataMerge_sort,     obj.noK = obj.noK, out.transform = out.transform, tauInit = tauInit,     memoryChunk = memoryChunk, LOCO = LOCO, chromosomeStartIndexVec = chromosomeStartIndexVec,     chromosomeEndIndexVec = chromosomeEndIndexVec, traceCVcutoff = traceCVcutoff)
 5: system.time(modglmm <- glmmkin.ai_PCG_Rcpp_Binary(plinkFile,     fit0, tau = c(0, 0), fixtau = c(0, 0), maxiter = maxiter,     tol = tol, verbose = TRUE, nrun = 30, tolPCG = tolPCG, maxiterPCG = maxiterPCG,     subPheno = dataMerge_sort, obj.noK = obj.noK, out.transform = out.transform,     tauInit = tauInit, memoryChunk = memoryChunk, LOCO = LOCO,     chromosomeStartIndexVec = chromosomeStartIndexVec, chromosomeEndIndexVec = chromosomeEndIndexVec,     traceCVcutoff = traceCVcutoff))
 6: fitNULLGLMM(plinkFile = opt$plinkFile, phenoFile = opt$phenoFile,     phenoCol = opt$phenoCol, traitType = opt$traitType, invNormalize = opt$invNormalize,     covarColList = covars, qCovarCol = NULL, sampleIDColinphenoFile = opt$sampleIDColinphenoFile,     nThreads = opt$nThreads, numMarkers = opt$numMarkers, skipModelFitting = opt$skipModelFitting,     traceCVcutoff = opt$traceCVcutoff, ratioCVcutoff = opt$ratioCVcutoff,     LOCO = opt$LOCO, outputPrefix = opt$outputPrefix)
An irrecoverable exception occurred. R is aborting now ...

 *** caught segfault ***
address 0x1042ac, cause 'memory not mapped'

 *** caught segfault ***
address 0xd2e08, cause 'memory not mapped'

 *** caught segfault ***
address 0x1083b4, cause 'memory not mapped'

 *** caught segfault ***
address 0x15628, cause 'memory not mapped'

 *** caught segfault ***
address 0xacd3c, cause 'memory not mapped'

 *** caught segfault ***
address 0xd7294, cause 'memory not mapped'

 *** caught segfault ***
address 0xd3238, cause 'memory not mapped'

 *** caught segfault ***
address 0xdd23c, cause 'memory not mapped'

 *** caught segfault ***
address 0xd81d4, cause 'memory not mapped'

 *** caught segfault ***
address 0x40630, cause 'memory not mapped'

 *** caught segfault ***
address 0xf2dcc, cause 'memory not mapped'

 *** caught segfault ***
address 0xd6f74, cause 'memory not mapped'

 *** caught segfault ***
address 0xdc184, cause 'memory not mapped'
...
Traceback:
 1: .Call("_SAIGE_getCoefficients", PACKAGE = "SAIGE", Yvec, Xmat,     wVec, tauVec, maxiterPCG, tolPCG)
 2: getCoefficients(Y, X, W, tau, maxiter = maxiterPCG, tol = tolPCG)
 3: Get_Coef(y, X, tau, family, alpha0, eta0, offset, verbose = verbose,     maxiterPCG = maxiterPCG, tolPCG = tolPCG, maxiter = maxiter)
 4: glmmkin.ai_PCG_Rcpp_Binary(plinkFile, fit0, tau = c(0, 0), fixtau = c(0,     0), maxiter = maxiter, tol = tol, verbose = TRUE, nrun = 30,     tolPCG = tolPCG, maxiterPCG = maxiterPCG, subPheno = dataMerge_sort,     obj.noK = obj.noK, out.transform = out.transform, tauInit = tauInit,     memoryChunk = memoryChunk, LOCO = LOCO, chromosomeStartIndexVec = chromosomeStartIndexVec,     chromosomeEndIndexVec = chromosomeEndIndexVec, traceCVcutoff = traceCVcutoff)
 5: system.time(modglmm <- glmmkin.ai_PCG_Rcpp_Binary(plinkFile,     fit0, tau = c(0, 0), fixtau = c(0, 0), maxiter = maxiter,     tol = tol, verbose = TRUE, nrun = 30, tolPCG = tolPCG, maxiterPCG = maxiterPCG,     subPheno = dataMerge_sort, obj.noK = obj.noK, out.transform = out.transform,     tauInit = tauInit, memoryChunk = memoryChunk, LOCO = LOCO,     chromosomeStartIndexVec = chromosomeStartIndexVec, chromosomeEndIndexVec = chromosomeEndIndexVec,     traceCVcutoff = traceCVcutoff))
 6: fitNULLGLMM(plinkFile = opt$plinkFile, phenoFile = opt$phenoFile,     phenoCol = opt$phenoCol, traitType = opt$traitType, invNormalize = opt$invNormalize,     covarColList = covars, qCovarCol = NULL, sampleIDColinphenoFile = opt$sampleIDColinphenoFile,     nThreads = opt$nThreads, numMarkers = opt$numMarkers, skipModelFitting = opt$skipModelFitting,     traceCVcutoff = opt$traceCVcutoff, ratioCVcutoff = opt$ratioCVcutoff,     LOCO = opt$LOCO, outputPrefix = opt$outputPrefix)
An irrecoverable exception occurred. R is aborting now ...
/home/yez07/.lsbatch/1536322785.995250: line 8: 395109 Segmentation fault      (core dumped) Rscript --vanilla /hpc/grid/hgcb/workspace/users/yez/UKBB/SAIGE_BINARY/rpgm/step1_fitNULLGLMM.R --plinkFile=/hpc/grid/hgcb/workspace/users/yez/UKBB/SAIGE_BINARY/data/ukb_v3_imp_unrelated_hwe10_ALL_HQ_genotyped_merged_cleaned_pruned --phenoFile=/hpc/grid/hgcb/workspace/users/yez/UKBB/SAIGE_BINARY/data/ukbb_qtnormBMI.phe.cov --phenoCol=binaryBMI --covarColList=PC1,PC2,PC3,PC4,PC5,PC6,PC5,PC6,PC7,PC8,PC9,PC10 --sampleIDColinphenoFile=IID --traitType=binary --outputPrefix=/hpc/grid/hgcb/workspace/users/yez/UKBB/SAIGE_BINARY/results/UKBB_SAIGE_step1_test --nThreads=24 --LOCO=TRUE

...

Started at Sun Sep  9 14:33:28 2018.
Terminated at Wed Sep 19 14:34:08 2018.
Results reported at Wed Sep 19 14:34:08 2018.

I have checked all the phenotypes and genotypes, they should be in the format as suggested by the SAIGE manual, and I have tried twice, which took me 20 days from start of submitting to quitting from the cluster. It would be really helpful if you could provide me some details how I should hunt down the issues. The message above is not a complete error message, if you want, I could upload the original log file. 

Thanks a lot in advance!

Harold

**Comment by weizhouUMICH** [comment]
Hello Harold, 

Could you please upload the original log file? Also can you try LOCO=FALSE to see if the error is because of the LOCO option? 

Thank you,
Wei

**Comment by yzharold** [comment]
Thanks a lot Wei, here is the original log file for the running. 
[test_SAIGE_UKBB_step1_v3.log](https://github.com/weizhouUMICH/SAIGE/files/2405325/test_SAIGE_UKBB_step1_v3.log)
Let me know if you get it. 

I will re-run the analyses by changing the option LOCO=FALSE and also update you again soon. 

Thanks a lot!

Harold

**Comment by weizhouUMICH** [comment]
Hi Harold, 

Thank you very much for providing the log file. I'm so sorry I was not able to figure out the possible reason that caused the error at this time. Did you try running the example data to see whether they can be run successfully?

Thanks,
Wei

**Comment by yzharold** [comment]
Yes, I did, right after I post my question, I did a test on your example data, it worked, all the results are fine, there is no error from the logs. I have not tried the LOCO=FALSE yet, I will do that soon. 

Thanks,

Harold

**Comment by weizhouUMICH** [comment]
Hi Harold,

 If could also try using fewer PCs, for example, PC1-4, as covariates, to
see if the errors can be reproduced, that would be helpful.
Thanks,
Wei

**Comment by yzharold** [comment]
Thanks for your suggestions, I will add another test run for PC1-4 as well. I started the one with LOCO=FALSE, it is not done yet. 

Harold

**Comment by yzharold** [comment]
Hi Wei, 

The LOCO=FALSE was done, still encounter the same issue with the computation, here is the log file. 
The model with PC1-4 is still runn

[test_SAIGE_UKBB_step1_falseLOCO.log](https://github.com/weizhouUMICH/SAIGE/files/2464688/test_SAIGE_UKBB_step1_falseLOCO.log)

ing. 

Harold

**Comment by yzharold** [comment]
Hi Wei, 

This is quite frustrating that the PC1-4 run is also not successful, it showed similar error message, do you have solution to run chromosome by chromosome instead of all the 22 chromosomes at the same time?

Here is the log file. 

Thanks a lot,
[test_SAIGE_UKBB_step1_trueLOCO_PC1_PC4.log](https://github.com/weizhouUMICH/SAIGE/files/2469655/test_SAIGE_UKBB_step1_trueLOCO_PC1_PC4.log)


Harold

**Comment by weizhouUMICH** [comment]
Hi Harold, 

I'm sorry I couldn't figure out the issue of your jobs. The software has evolved a lot since then. Please reopen the issue if you still encounter this issue with the latest version 0.36.3.1

Thanks!
Wei

**Comment by frahimov** [comment]
Hi Wei, 
May I ask what "colnames(data.new) is  Y minus1"  stands for here? minus1 has its own coefficient too.
Thank you
Fedik
