### ISSUE TITLE
Load SAIGE package error

### ISSUE THREAD

**Issue by jdpleiness** [weizhouUMICH/SAIGE#50]
I am getting an error when attempting to load the SAIGE library in R. I am using the latest package version `SAIGE_0.29.4.2_R_x86_64-pc-linux-gnu.tar.gz` in R version 3.5.1.

The package installs successfully, however when I attempt to load the package I get the following error:
```bash
> library(SAIGE)
Error: package or namespace load failed for ‘SAIGE’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/SAIGE/libs/SAIGE.so':
  libhts.so.2: cannot open shared object file: No such file or directory
```

I have installed all required dependencies successfully as well.

**Comment by weizhouUMICH** [comment]
It seems the libhts is required by the savvy and it is not installed in the system. 
https://github.com/statgen/savvy/blob/master/requirements.txt

Could you please try install the htslib to see if SAIGE library can be loaded? 

Thanks
