### ISSUE TITLE
Only header printed in output without error when using VCF - step 2

### ISSUE THREAD

**Issue by jinshaw16** [weizhouUMICH/SAIGE#51]
Dear Wei,

Sorry to disturb you. I just downloaded the latest version of SAIGE to run in R version 3.5.1 (SAIGE_0.29.4.2). I have installed the package into R successfully and all the dependencies. 

Stage 1 ran without problems and stage 2 also appears to run well (although extremely quickly) according to the log file (attached). Just without actually carrying out any SPA tests.

The output file contains only a header. Is this behaviour you have found before?  I tried the example you provide in the package and that runs without problems and does print the summary statistics out, so I've been trying to compare the files in my analysis to the example. The potential problems I can think of are:
1) Our SNP ID's contain colons - is this OK?
2) Our VCF file contains multiple types of information, whereas the VCF files in the example contain either only DS or only GT. Is this a problem? 

I have tried to attach a picture showing the first few lines of our VCF file.

Any advice or suggestions you have to get round this problem would be much appreciated.

Best wishes,

Jamie

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/14347839/46075296-faf37000-c181-11e8-9f45-dcc3f818129d.png">

[slurm-2462623.txt](https://github.com/weizhouUMICH/SAIGE/files/2419329/slurm-2462623.txt)

**Comment by weizhouUMICH** [comment]
Dear Jamie,

Thank you for the detailed info, which is very helpful for debugging!  I think the possible solution is to change 22 to be ‘chr22’ for the chrom option, since in the input vcf the chrom column is ‘chr22’

Thanks,
Wei

**Comment by jinshaw16** [comment]
Dear Wei,

Thank you for this and for responding so quickly! Sorry I didn't spot it - that has indeed solved the problem.

Best wishes,

Jamie
