### ISSUE TITLE
memory not mapped

### ISSUE THREAD

**Issue by RickvdSpek** [weizhouUMICH/SAIGE#53]
Dear Wei,

When running SPAGMMATtest I get the following error:

 *** caught segfault ***
address 0x2cce0950, cause 'memory not mapped'

Traceback:
 1: .Call("_SAIGE_getGenoOfnthVar_vcfDosage", PACKAGE = "SAIGE",     mth)
 2: getGenoOfnthVar_vcfDosage(mth)
 3: SPAGMMATtest(dosageFile = opt$dosageFile, dosageFileNrowSkip = opt$dosageFileNrowSkip,     dosageFileNcolSkip = opt$dosageFileNcolSkip, dosageFilecolnamesSkip = dosageFilecolnames,     vcfFile = opt$vcfFile, vcfFileIndex = opt$vcfFileIndex, vcfField = opt$vcfField,     bgenFile = opt$bgenFile, bgenFileIndex = opt$bgenFileIndex,     savFile = opt$savFile, savFileIndex = opt$savFileIndex, chrom = opt$chrom,     start = opt$start, end = opt$end, sampleFile = opt$sampleFile,     GMMATmodelFile = opt$GMMATmodelFile, varianceRatioFile = opt$varianceRatioFile,     SAIGEOutputFile = opt$SAIGEOutputFile, minMAF = opt$minMAF,     minMAC = opt$minMAC, numLinesOutput = opt$numLinesOutput,     IsOutputAFinCaseCtrl = opt$IsOutputAFinCaseCtrl, LOCO = opt$LOCO)
aborting ...
Segmentation fault

The error occurs when reading in the first genotype from a vcf.
            Gx = getGenoOfnthVar_vcfDosage(mth)

I've tried running SAIGE_0.29.3 and SAIGE_0.26 on R/3.2.2, R/3.3.3 and R/3.4.1. And tried SAIGE_0.29.4 on R/3.5.1. Unfortunately, nothing worked...

I've checked the integrity of the input vcf's and everything seems to be fine.
The machine has 50G of memory which should be plenty (in the error report it states that max_vmem=1G)

Can you help me out?
Thanks!

Kind regards,

Rick

**Comment by weizhouUMICH** [comment]
Dear Rick, 

Would  you mind sharing the log file with the specified parameters, so I can have a look? 

Thanks,
Wei

**Comment by RickvdSpek** [comment]
Sure, see attachment
[command_log.txt](https://github.com/weizhouUMICH/SAIGE/files/2436659/command_log.txt)

**Comment by RickvdSpek** [comment]
Dear Wei,

Nevermind, found it. The input vcf contains more individuals than the .rda file. Adjusting that solved the problem.
Thanks!

Kind regards,
Rick
