### ISSUE TITLE
Problems with step 2

### ISSUE THREAD

**Issue by rnbeaumont** [weizhouUMICH/SAIGE#54]
I am having some problems with running step 2. Sometimes it runs OK, but with one phenotype I get the following error when running step 2:

Error in X1 %*% Z : non-conformable arguments
Calls: SPAGMMATtest ... rbind -> scoreTest_SAIGE_binaryTrait -> Score_Test_Sparse

I am running SAIGE for each chromosome, and some chromosomes fail fairly quickly while others produce results for a number of SNPs before failing. Do you have any tips for locating the source of this error?

**Comment by fadista** [comment]
Hi.

Did you find out the reason for this error? It happens to me only on chrX. Thanks.

**Comment by weizhouUMICH** [comment]
Hi, 
This error has been fixed in more recent versions. Please try the most recent version. 
Thanks!
Wei
