### ISSUE TITLE
v0.29.3, mismatched .bgen / sample file?, possibly spurious p-values?

### ISSUE THREAD

**Issue by ttasa** [weizhouUMICH/SAIGE#55]
I’ve been pulling my hair out after running several phenotypes on UKBB data with SAIGE 0.29.3 and I think there’s possibly a major subtle error with analysing BGEN files and matching samples to genotypes. 
So my set-up.
SAIGE v0.29.3
UKBB data (females) with some extra SNP/sample quality control Example phenotype ICD-10: C50.
Two runs. 1) All individuals (~200k individuals) 2) 70% random subset of all individuals 
Covariates : PC 1-10 + genotyping array + age
Step1 was performed separately for two runs.

Post-gwas I realized that

 1) The resulting p-values do not correlate AT ALL (R~0) with published UKBB results published in Broad (Obtained from http://www.nealelab.is/uk-biobank: GWAS round 2 results;Phenotype  codes: 20001_1002 and 20110_5)

   2)  P-values from two independent runs on same SNPs do not correlate at all (R2 ~ 0) when the second run includes a random set of 70% of individuals included in the first run. I’d expect some variation but not complete randomness. These two sets have of course separately prepared SAIGE step1 files. 
So, let’s get to one very specific SNP example from reported Broad UKBB results.   

`[.. tmp]$ head -n 1 20001_1002.gwas.imputed_v3.female.tsv `

variant	minor_allele	minor_AF	expected_case_minor_AC	low_confidence_variant	n_complete_samples	AC	ytx	beta	se	tstat	pval

`[.. tmp]$ grep '16:52583143' 20110_5.gwas.imputed_v3.female.tsv`
 
16:52583143:C:T	T	2.38169e-01	7.35753e+03	false	181587	8.64969e+04	7.74807e+03	8.66331e-03	1.07545e-03	8.05556e+00	7.95925e-16`

`[.. tmp]$ grep '16:52583143' 20001_1002.gwas.imputed_v3.female.tsv`
16:52583143:C:T	T	2.37886e-01	3.79095e+03	false	194153	9.23725e+04	4.43882e+03	9.23515e-03	7.44827e-04	1.23991e+01	2.72692e-35

 Both files report SNP rs4784226 as highly significant 7.95925e-16 and 2.72692e-35. It’s located in TOX3 which has been previously associated with breast cancer so in general believable.  Now, I used the same .bgen and .sample files that I used for SAIGE converted to plink format for both full and 70% subset files and ran the same above variant with Plink (without any covariates so not fully accurate but should give an impression and general direction)

`[ttasa tmp]$ cat 70.subset.assoc`
 CHR         SNP         BP   A1      F_A      F_U   A2        CHISQ            P           OR 
  16   rs4784226   52583143    T   0.2793   0.2346    C        168.8    1.376e-38        1.264 
`[ttasa tmp]$ cat full.subset.assoc `
 CHR         SNP         BP   A1      F_A      F_U   A2        CHISQ            P           OR 
  16   rs4784226   52583143    T   0.2779   0.2348    C        225.7     5.29e-51        1.254 

Highly Significant as expected. Good.

Finally, the same associations for full and 70% subset in SAIGE with the same files. I even made sure that the .rda files have sampleIDs exactly in the same order as .bgen sample files. 

`[ttasa tmp]$ cat full.subset.SAIGE.txt`

CHR POS SNPID Allele1 Allele2 AC_Allele2 AF_Allele2 N BETA SE Tstat p.value p.value.NA Is.SPA.converge varT varTstar AF.Cases AF.Controls
16 52583143 rs4784226 C T 104920.84705882 0.237797124017088 220610 -0.0129622632987871 0.0158383131362089 -51.6729181990579 0.413122052356741 0.413122052356741 1 3986.41170974307 3984.41153515242 0.235538119616612 0.237913247430448
`[ttasa tmp]$ cat 70.subset.SAIGE.txt`
CHR POS SNPID Allele1 Allele2 AC_Allele2 AF_Allele2 N BETA SE Tstat p.value p.value.NA Is.SPA.converge varT varTstar AF.Cases AF.Controls
16 52583143 rs4784226 C T 73403.8666666659 0.237665261471977 154427 0.00166033434253792 0.0189936795017733 4.60232559648286 0.930341569371726 0.930341569371726 1 2771.92700203257 2771.92700203257 0.238265772630296 0.237618325328505

SAIGE step 1 used different covariates from both Broad and my fast Plink examples but that should not allow for so hugely different results. P-values here are 0.94 and 0.41.   Please note that the AF.Cases and AF.Controls in SAIGE are completely different from Plink. I am quite sure we’d expect these to be concordant. 

If needed I can provide you the data snippets needed to reproduce the results.  Thanks for looking into it.

**Comment by weizhouUMICH** [comment]
Hi, 
Would you mind sharing the log file so I can talk a look? 
Thanks,
Wei

**Comment by ttasa** [comment]
That wass exactly what the problem is.
<img width="1069" alt="screen shot 2018-10-04 at 09 25 07" src="https://user-images.githubusercontent.com/5450949/46456518-d6b61580-c7b7-11e8-9e94-8623cadac945.png">

2 top rows in the bgen sample file (original format specification) are an extra. However, since no error messages are given then I somehow assumed that everything was  OK and the available 220610 samples were matched to bgen samples...Especially considering that the two rows are default header specification anyway.
 Obviously not as shown below.
![screen shot 2018-10-04 at 09 34 20](https://user-images.githubusercontent.com/5450949/46456780-be92c600-c7b8-11e8-926e-e2926cc8b65c.png)
In the second case I removed the first two rows. Now, the answer is more like we expected.

As the .sample file with extra two rows is the somehow the default format then at a minimum I would suggest that the run should fail if the number of sample IDs does not match .bgen samples. Automatic removal of 1/2 top sample rows could be nice also.
If I didn't have a comparison set then this kind of mistake could have  been easily missed. There's a pretty big chance that quite a few others have also got mismatched results like these and proceeded with the analysis from there. 
Thank you.

**Comment by ttasa** [comment]
In light of the above.
Would you say that SAIGE matches sample file IDs correctly with .bgen samples and then uses correct subset of samples in association phase if the number of samples used for STEP 1 is smaller than the whole set in .bgen as below?

<img width="639" alt="screen shot 2018-10-04 at 13 31 29" src="https://user-images.githubusercontent.com/5450949/46468908-7e443f80-c7da-11e8-9e49-e5133b46d445.png">

Thanks again!

**Comment by weizhouUMICH** [comment]
Yes, you are right. SAIGE match samples from step 1 and samples in the dosage files automatically

**Comment by catlisboa** [comment]
Hey! How did you solve this?
