### ISSUE TITLE
Error when doing R CMD INSTALL of SAIGE_0.29.tar.gz and github sourcecode

### ISSUE THREAD

**Issue by jiwonslee** [weizhouUMICH/SAIGE#58]
When I do a R CMD INSTALL on my windows machine, I get this error:

c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/jq650/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/jq650/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/jq650/Documents/R/win-library/3.5/RcppParallel/include" -I"C:/Users/jq650/Documents/R/win-library/3.5/data.table/include" -I"C:/Users/jq650/Documents/R/win-library/3.5/SPAtest/include" -I"C:/Users/jq650/Documents/R/win-library/3.5/RcppEigen/include" -I"C:/Users/jq650/Documents/R/win-library/3.5/Matrix/include" -I"C:/Program Files/R/R-3.5.1/library/methods/include"     -fopenmp    -O2 -Wall  -mtune=generic -c SAIGE_readDosage_bgen.cpp -o SAIGE_readDosage_bgen.o
In file included from SAIGE_readDosage_bgen.cpp:6:0:
../thirdParty/bgen/genfile/include/genfile/bgen/bgen.hpp:18:28: fatal error: genfile/zlib.hpp: No such file or directory
 #include <genfile/zlib.hpp>
                            ^

**Comment by weizhouUMICH** [comment]
Hi @jiwonslee, 
So sorry for delayed reply! SAIGE and SAIGE-GENE do not work for windows system. Please try ubuntu. 
Thanks!
Wei
