### ISSUE TITLE
interface to use kinship matrix as in GMMAT?

### ISSUE THREAD

**Issue by chenwenan** [weizhouUMICH/SAIGE#59]
Hi, Weizhou

Thanks for developing this useful package. 
Is there an R function available to use kinship matrix directly to do the logistic mixed model association test instead of requiring the plink file to estimate the GRM?

Thanks,

Wenan

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
