### ISSUE TITLE
SAIGE-GENE

### ISSUE THREAD

**Issue by sk0427** [weizhouUMICH/SAIGE#60]
Hello, Weizhou

I enjoyed your talk in ASHG2018 about SAIGE-GENE.
I try to do the gene-based or sliding window analysis.
I missed URL in your presentation. Could you tell me the access for it?

Thanks

**Comment by weizhouUMICH** [comment]
Hello, 
Thank you for being interested in SAIGE-GENE. I just uploaded a cleaner version for SAIGE-GENE. You may find it in the branch master-gene. Please have a look at the cmd.sh in the extdata folder for the specific script to run gene-based tests. 

Thanks,
Wei

**Comment by sk0427** [comment]
Dear Wei

Thank you so very much!
I will try on my dataset

Many thanks,

Satoshi
