### ISSUE TITLE
SAIGE step2 output has p.value & SE of 0

### ISSUE THREAD

**Issue by xmduumich** [weizhouUMICH/SAIGE#64]
Dear Wei,
We noticed that some of the variants has p.value & SE of 0 in the output files for some of the traits we run using SAIGE. Here's the script of step2: 
##########bgen file
 #--minMAF=0.0001
Rscript /mnt/speliotes-lab/Projects/UK_ATLAS/IndivProj/Jessica/SAIGE/code/step2_SPAtests.R \
        --vcfFile=/scratch2/xmdu/Resource/UKB_Genotyped_not_imputed/UKB_genotyped_not_in_bgen_merge_allwhite_filtered_SNP_0.01_indiv_0.01.DS.fillmiss.vcf.gz \
        --vcfFileIndex=/scratch2/xmdu/Resource/UKB_Genotyped_not_imputed/UKB_genotyped_not_in_bgen_merge_allwhite_filtered_SNP_0.01_indiv_0.01.DS.fillmiss.vcf.gz.tbi \
        --vcfField=DS \
        --minMAC=3 \
        --chrom=1 \
        --sampleFile=/scratch2/xmdu/Resource/UKB_Genotyped_not_imputed/UKB_genotyped_not_in_bgen_merge_allwhite_filtered_SNP_0.01_indiv_0.01.DS.fillmiss.vcf.eid \
        --GMMATmodelFile=/mnt/speliotes-lab/Projects/UK_ATLAS/IndivProj/Ryan/SAIGE/result/cholesterol_med/UKB_cholesterol_med_pheno_white_geno.rda \
        --varianceRatioFile=/mnt/speliotes-lab/Projects/UK_ATLAS/IndivProj/Ryan/SAIGE/result/cholesterol_med/UKB_cholesterol_med_pheno_white_geno.varianceRatio.txt \
        --SAIGEOutputFile=/mnt/speliotes-lab/Projects/UK_ATLAS/IndivProj/Ryan/SAIGE/result/cholesterol_med/UKB_cholesterol_med_pheno_white_geno.SAIGE.bgen.chr1.txt \
        --numLinesOutput=2 \
        --IsOutputAFinCaseCtrl=TRUE

This does not happen for every trait we run. we have about 40 variants for one trait and 14 for the other. The p.value.NA looks just normal for those variants. Here's an example of the weird p.values: 
![image](https://user-images.githubusercontent.com/16599781/49399166-8ce1a100-f70e-11e8-9019-31ce22ba74f5.png)

Do you know why this happened? Right now we just filtered out these variants, which does not seem to be the ideal solution.  Our SAIGE version is 0.29.

Best,
Xiaomeng

**Comment by weizhouUMICH** [comment]
Dear Xiaomeng, 

The these variants all have AC_allele2 around 3. We have noticed that SPA tests may not perform well for variants with MAC <= 3. Could you please try to apply a minMAC = 3.5 or 4? 

Thanks,
Wei

**Comment by akhilpampana** [comment]
Hello,  I am getting the same error as was reported above. The only thing is I am getting this value for significant hits based on other gwas analyses previously reported. May I know how to resolve this issue?
