### ISSUE TITLE
Step 1 running time

### ISSUE THREAD

**Issue by demodw** [weizhouUMICH/SAIGE#65]
Hi,

I'm trying to run SAIGE with UK Biobank data. To estimate the GRM I have selected the 93k SNPs used for kinship estimation that was also used in the SAIGE publication. My sample consists of ~380.000 individuals. 

The step has been running for well over 30 hours now. I'm using a Xeon E5-2683 CPU, using 27 threads. The same analysis was done using BOLT-LMM in <4 hours (GRM+Association).  According to the main publication the time spent should be ~1.5 times that of BOLT-LMM. 

I'm using the following options:

`	--plinkFile=ukb_cal_kinship_v2
	--phenoFile=phenoFile.all.tsv
	--phenoCol=Outcome
	--covarColList=Batch,Sex,Age,Age2,PC1,PC2,PC3,PC4
	--sampleIDColinphenoFile=IID
	--traitType=binary
	--outputPrefix=testrun
	--nThreads=27
`

Am I doing something wrong?

Thanks in advance!

**Comment by weizhouUMICH** [comment]
Hi, 

Sorry for replying late!
If the problem has not been solved yet, would you mind providing the log file of the job? How many iterations have been run? 
How many CPU hours did the job cost? 

Thanks,
Wei

**Comment by Ojami** [comment]
Hi! 
I have a similar experience; but, I noticed the time taken for binary phenotypes is much more compared to a continuous one.  SAIGE step 1 took ~7 days for a binary trait (40 threads) with similar ~140 K marker size and ~ 380~ sample size. For a continuous trait the time was ~2 days (20 threads).
I don't use BOLT-LMM for binary traits, but it's faster (~5 hr with 20 threads) for continuous traits (at least under my machine).  
The time limiting step of SAIGE for me is in variance ratio estimation. I wonder if there is something can be done to improve this feature of SAIGE.

Bes/Oveis

**Comment by weizhouUMICH** [comment]
Hi Oveis,

Usually we see binary phenotypes take less time than continuous ones, PCG
takes fewer iterations to converge for binary phenotypes.
It is very unusual for step 1 to use 7 days on 40 CPUs. Could you please
have a look at the log file to see how the algorithm converged?
I guess the tau estimate might become very large.

Thanks,
Wei

**Comment by Ojami** [comment]
Hi Wei,

So sorry for my mistake. Yes, you are right, it took ~7 days for a continuous trait (not a binary). Unfortunately I didn't save the log file back then, but I remember that both tau and variance ratio estimation was long. SAIGE started with 30 markers for this estimation, and it finished it's estimation with 190 markers. 
I will rerun that trati again (specially it has high heritability) probably with lower number of sample sizes and markers (93 K from UKB), to share the log file.
But, again, the same analysis is faster in BOLT-LMM. 

Thanks
Oveis
