### ISSUE TITLE
How to get the coefficients of each covariate ?

### ISSUE THREAD

**Issue by dhlee111** [weizhouUMICH/SAIGE#67]
Hi, Wenzhou, 

I have a question about how to get the coefficients of covariates (as BETA values),other than SNPs and the P-value of the them. is there any options I missed ? 
Thank you, 

DH

**Comment by weizhouUMICH** [comment]
Hi DH,

You may load the step 1 .rda model file in R and call modglmm$coefficients.
You may see the details of the model file here

https://github.com/weizhouUMICH/SAIGE/wiki/SAIGE-Hands-On-Practical


#open R
R
#load the model file in R
load("/home/topmed/SAIGE-hands-on/extdata/myoutput/example.rda")
names(modglmm)
modglmm$theta

#theta: a vector of length 2. The first element is the dispersion
parameter estimate and the second one is the variance component
parameter estimate
#coefficients: fixed effect parameter estimates
#linear.predictors: a vector of length N (N is the sample size)
containing linear predictors
#fitted.values: a vector of length N (N is the sample size) containing
fitted mean values on the original scale
#Y: a vector of length N (N is the sample size) containing final working vector
#residuals: a vector of length N (N is the sample size) containing
residuals on the original scale


Thanks,
Wei

**Comment by dhlee111** [comment]
Weizhou,

Thank you very much for the quick response, 
One more question, I can not find the p-values of the coefficients, 
Is there any options for the p-values of coefficients

Thanks,

DH,  

> 2019. 1. 3. 오후 3:31, weizhouUMICH <notifications@github.com> 작성:
> 
> modglmm)

**Comment by weizhouUMICH** [comment]
Hi DH,

Sorry currently SAIGE does not output the p-values for fixed effect
coefficients.

Wei
