### ISSUE TITLE
Centos 6

### ISSUE THREAD

**Issue by yiyunalu** [weizhouUMICH/SAIGE#68]
I am using centos 6 but kept having trouble using SAIGE.
Does SAIGE compatible with Centos 6?

**Comment by weizhouUMICH** [comment]
Hi @yiyunalu, 
Sorry for taking so long to get back to you! SAIGE does not easily compile with Centos 6.  We have been struggling on the platform compatibility issue for long and decided that using conda environment file is the easiest way for users having Centos6 (the 5th approach). 
https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE#installing-saige

Please reopen if you still encounter this issue. 
Thanks!
Wei

**Comment by yiyunalu** [comment]
Hi!

I’m no longer working there. Please submit a ticket.


Best,
Yi

发自我的iPhone
