### ISSUE TITLE
Conditional analysis

### ISSUE THREAD

**Issue by joshchiou** [weizhouUMICH/SAIGE#70]
Hi,

Does SAIGE support conditional analysis? If not is there a way to add in covariates without re-running step 1?

Thanks
Josh

**Comment by weizhouUMICH** [comment]
Hi,
The new version of SAIGE now supports conditional analysis by specifying --condition in step 2. 

https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE#installing-saige
Thanks
Wei
