### ISSUE TITLE
error in loading/compiling SAIGE package

### ISSUE THREAD

**Issue by aleph9999** [weizhouUMICH/SAIGE#72]
I was trying to install this package on server and come up with following error:

In which I directly use R CMD INSTALL from archived version
Error: package or namespace load failed for ‘SAIGE’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/u/home/a/aleph999/R/x86_64-pc-linux-gnu-library/3.5/SAIGE/libs/SAIGE.so':
  /u/local/compilers/gcc/4.9.3/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /u/home/a/aleph999/R/x86_64-pc-linux-gnu-library/3.5/SAIGE/libs/SAIGE.so)

while I already set LD_PATH with newer version of GCC/6.3.0
After I set R_LD_LIBRARY_PATH to new version, now loading error changed
Error: package or namespace load failed for ‘SAIGE’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/u/home/a/aleph999/R/x86_64-pc-linux-gnu-library/3.5/SAIGE/libs/SAIGE.so':
  /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /u/home/a/aleph999/R/x86_64-pc-linux-gnu-library/3.5/SAIGE/libs/SAIGE.so)
and I am unable to proceed further with this error

UPDATE: I found it is because of different version between pre-compiled version and current version in our server. Where our server is Centos 6 with GLIBC version up to 2.12 and I can do nothing unless ask administrator to update this. Anyone have experience on this?

On the other hand I was also trying to build from source code directly and come up with error in cmake, after I updated cmake with miniconda  and use R built on gcc/6.3.0, now the error become 
-lsavvy not found.
/usr/bin/ld: cannot find -lsavvy
collect2: error: ld returned 1 exit status

I tried to install savvy otherwise with cget and pass to library path with following error occurs. In addition to compiler skipping message like this:
/usr/bin/ld: skipping incompatible /u/local/compilers/gcc/6.3.0/lib/libgfortran.so when searching for -lgfortran

/usr/bin/ld: /u/home/a/aleph999/savvy/lib/../lib64/libsavvy.a(region.cpp.o): relocation R_X86_64_PC32 against undefined symbol `memcmp@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

It seems like there is some issue on savvy installation. Any tips?

**Comment by chenwenyan2015** [comment]
well , I have the same issue, how to solve it

**Comment by weizhouUMICH** [comment]
Hi, 
1. For savvy library, I've modified the configure file to re-download and install the savvy library when install the SAIGE library. 
2. More details are added for installing SAIGE
https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE#installing-saige

Could you please try the new version to see if the problems persist? 

Thanks,
Wei

**Comment by jbsom** [comment]
The problem persists for me...
g++ -std=gnu++11 -I"/data4/packages/r-3.5.1/lib64/R/include" -DNDEBUG -I ../thirdParty/bgen/db/include -I ../thirdParty/bgen/genfile/include -I ../thirdParty/bgen/genfile/include/genfile -I ../thirdParty/bgen/genfile/include/genfile/bgen -I ../thirdParty/bgen/db/include/db -I ../thirdParty/bgen/3rd_party/boost_1_55_0 -I ../thirdParty/bgen/3rd_party/zstd-1.1.0 -I ../thirdParty/bgen/3rd_party/zstd-1.1.0/lib -I ../thirdParty/bgen/3rd_party/zstd-1.1.0/lib/compress -I ../thirdParty/bgen/3rd_party/zstd-1.1.0/lib/decompress -I ../thirdParty/bgen/3rd_party/sqlite3 -I ../thirdParty/bgen/3rd_party/boost_1_55_0/boost/iostreams -I ../thirdParty/cget/include -I ../thirdParty/cget/lib -D SQLITE_ENABLE_COLUMN_METADATA -O3 -fpic -Wall -Wextra -pedantic  -DARMA_64BIT_WORD=1  -I"/data4/packages/r-3.5.1/lib64/R/library/Rcpp/include" -I"/data4/packages/r-3.5.1/lib64/R/library/RcppArmadillo/include" -I"/data4/packages/r-3.5.1/lib64/R/library/RcppParallel/include" -I"/data4/packages/r-3.5.1/lib64/R/library/data.table/include" -I"/data4/packages/r-3.5.1/lib64/R/library/SPAtest/include" -I"/data4/packages/r-3.5.1/lib64/R/library/RcppEigen/include" -I"/data4/packages/r-3.5.1/lib64/R/library/Matrix/include" -I"/data4/packages/r-3.5.1/lib64/R/library/methods/include" -I/data4/packages/zlib-1.2.11/include -I/data4/packages/bzip2-1.0.6/include -I/data4/packages/pcre-8.38/include -I/data4/packages/curl-7.50.3/include -I/data4/packages/xz-5.2.2/include   -fpic  -I/data4/packages/zlib-1.2.11/include -I/data4/packages/bzip2-1.0.6/include -I/data4/packages/pcre-8.38/include -I/data4/packages/curl-7.50.3/include -I/data4/packages/xz-5.2.2/include -c SAIGE_readDosage_vcf.cpp -o SAIGE_readDosage_vcf.o
SAIGE_readDosage_vcf.cpp:1:55: fatal error: ../thirdParty/cget/include/savvy/reader.hpp: No such file or directory
 #include "../thirdParty/cget/include/savvy/reader.hpp"
                                                       ^
compilation terminated.
make: *** [SAIGE_readDosage_vcf.o] Error 1
ERROR: compilation failed for package ‘SAIGE’
* removing ‘/data4/packages/r-3.5.1/lib64/R/library/SAIGE’
* restoring previous ‘/data4/packages/r-3.5.1/lib64/R/library/SAIGE’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/RtmpEWaLuP/file6647528af5eb/SAIGE_0.35.8.2.tar.gz’ had non-zero exit status

**Comment by weizhouUMICH** [comment]
Hi,

Was the savvy library downloaded?
In the configure file, the following command lines are used to download and
install the savvy library.
Thanks,
Wei
#install savvy library
rm -rf thirdParty/cget
cget install -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC" --prefix
thirdParty/cget -f thirdParty/requirements.txt
