### ISSUE TITLE
SAIGE output use scientific notations for positions

### ISSUE THREAD

**Issue by xmduumich** [weizhouUMICH/SAIGE#74]
Dear developers of SAIGE,

We found that the raw out put of SAIGE step2 will use a scientific notation of positions if the position of that variant ends with multiple zeroes. For example, 99000000 will be written as 9.9e+7. This will cause issues when the raw output files are used to match with other resources with chr:pos markers.

We think that it is because of the default settings of the R software. Should be easy to fix. 

Best,
Xiaomeng

**Comment by weizhouUMICH** [comment]
Dear Xiaomeng, 

SAIGE uses the write.table function in R to output. Would you mind trying to add  

options(scipen=999)

to the R script for SAIGE jobs to avoid scientific notations? 

Thanks,
Wei

**Comment by carbocation** [comment]
There is a real downside to using `options(scipen=999)`, which is that P values will be represented like this:

```
0.000000000000000000000000452717769531568
```

Would it be possible to transform the position to text prior to emitting it?

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
