### ISSUE TITLE
Step 2 error: Mat::operator(): index out of bounds

### ISSUE THREAD

**Issue by jjfarrell** [weizhouUMICH/SAIGE#76]
I am getting this error using v0.29.5 for step2.  This is reading a dosage file. Any suggestions? 

I have been getting early terminations with other chromosomes without an error message.  I tried this with a vcf.gz file as input and having similar problems. 

```
283845  samples have been used to fit the glmm null model
obj.glmm.null$LOCO:  FALSE
Leave-one-chromosome-out option is not applied
variance Ratio is  1
488165  sample IDs are found in sample file
[1] 488165      4
[1] "IID"          "IndexInModel" "IndexDose.x"  "IndexDose.y"
283845  samples were used in fitting the NULL glmm model and are found in sample file
minMAC:  10
minMAF:  1e-04
Minimum MAF of markers to be testd is  1e-04
Analysis started at  1.55e+09 Seconds
setgenoTest here

file extenstion is gz
set GenoTestObj from dosage gz file!
NSampleTest 488193
Mtest 1158119

Testing markers: 1158119 , samples: 488193
isVariant:  TRUE
It is a binary trait
Analyzing  41113  cases and  242732  controls

error: Mat::operator(): index out of bounds
Error in getGenoOfnthVar_plainDosage(mth, dosageFileNrowSkip, dosageFileNcolSkip) :
  Mat::operator(): index out of bounds
Calls: SPAGMMATtest -> getGenoOfnthVar_plainDosage

```

**Comment by weizhouUMICH** [comment]
Hi, 
 The number of samples in the sample file must be equal to the number of samples in the vcf or dosages files. But in the sample file, there are 488165 samples and in the vcf file, there are 488193 samples. 
I think this is the problem. 
Sorry for the confusion. 
An error message about this inconsistence is now output in the new SAIGE version. 

Thanks,
Wei
