### ISSUE TITLE
errors running saige-gene

### ISSUE THREAD

**Issue by mjsduncan** [weizhouUMICH/SAIGE#77]
hi, i have been trying to run the group association tests as discussed in issue #60 .
installing the 'master-gene' branch produces an error to do to a file link on a local server:
```
devtools::install("../saige/SAIGE/")
✔  checking for file ‘/home/mozi/R/saige/SAIGE/DESCRIPTION’ ...
   cp: cannot stat 'SAIGE/thirdParty/cget/share/shrinkwrap/shrinkwrap-config-version.cmake': No such file or directory
   cp: cannot stat 'SAIGE/thirdParty/cget/share/shrinkwrap/shrinkwrap-config.cmake': No such file or directory
    ERROR
   copying to build directory failed
```
which are linked to someone's local files:
```
$ ll thirdParty/cget/share/shrinkwrap/
total 16
drwxr-xr-x 2 mozi mozi 4096 Mar  8 16:50 ./
drwxr-xr-x 3 mozi mozi 4096 Mar  8 16:50 ../
lrwxrwxrwx 1 mozi mozi  173 Mar  8 16:50 shrinkwrap-config.cmake -> /net/hunt/zhowei/project/imbalancedCaseCtrlMixedModel/Rpackage_SPAGMMAT/SAIGE/thirdParty/cget/cget/pkg/jonathonl__shrinkwrap/install/share/shrinkwrap/shrinkwrap-config.cmake
lrwxrwxrwx 1 mozi mozi  181 Mar  8 16:50 shrinkwrap-config-version.cmake -> /net/hunt/zhowei/project/imbalancedCaseCtrlMixedModel/Rpackage_SPAGMMAT/SAIGE/thirdParty/cget/cget/pkg/jonathonl__shrinkwrap/install/share/shrinkwrap/shrinkwrap-config-version.cmake
```
i would be happy to help with testing and debugging if the missing files are supplied.

thanks for sharing your code!

**Comment by weizhouUMICH** [comment]
Hi, 
Can you try again? I modified the configure file so the savvy library in the cget folder will be re-downloaded and installed while installing the SAIGE library.
Here are more detailed information for installing SAIGE. Please let me know how it works. 
https://github.com/weizhouUMICH/SAIGE/wiki/Genetic-association-tests-using-SAIGE

Thanks,
Wei
