### ISSUE TITLE
group association testing on unbalanced sample sets

### ISSUE THREAD

**Issue by mjsduncan** [weizhouUMICH/SAIGE#78]
i couldn't install branch `master-gene` to try saige group association testing (issue #77 ) so i installed branch `master-gene-finngen` and successfully ran `createSparseGSM` and `fitNULLGLMM` on a small data set of of 30 cases and 500 control autosomal genomes.  running `SPAGMMATtest` crashed the R session in Rstudio (running on ubuntu 18.04 linux) with the output in this screenshot:
![saige output before crash](https://user-images.githubusercontent.com/5019970/54710212-8b04e780-4b1d-11e9-8ab1-ed3674c8d3b0.png).

first question:  is the warning message missing a "not" and indicating that `SPAGMMATtest` isn't appropriate for my ~1:17 ratio sample set?

second question:  would more detailed error info be worth generating for your development process?

i have successfully run individual variant testing on this data set using the `master` branch.

thanks for sharing your code!

**Comment by weizhouUMICH** [comment]
You are right. We haven't implemented the approach to account for case-control imbalance for binary traits yet. According to our simulation results, SAIGE-GENE has inflated type I error rates for binary traits with prevalence < 20% when the maximum MAF cutoff in the tested genes is 1%.  
Sorry for the confusion! I just corrected the message and uploaded the version 0.35.8.1. 
Please feel free let me know if there is any issue to install. 
Thanks!

Best,
Wei
