### ISSUE TITLE
SAIGE for windows?

### ISSUE THREAD

**Issue by bvilhjal** [weizhouUMICH/SAIGE#79]
Hi, 

First, congratulations on this beautiful work!  

We are in the unusual position of wanting to run SAIGE on windows machines (due to data access restrictions).  Do you plan to release SAIGE for windows?

Cheers,
Bjarni

**Comment by weizhouUMICH** [comment]
Hi Bjarni, 

Thank you!
It could be a challenging to make a windows version for SAIGE as it uses several C++ libraries that may not work for windows. Would docker image work for you? I'll upload a docker image soon. 

Best,
Wei

**Comment by bvilhjal** [comment]
Hi Wei, 

Thanks a lot for the reply.  I don't think a docker image would be ok.  We might try to compile it for Windows ourselves. I'll keep you updated if we succeed.

Best,
Bjarni
