### ISSUE TITLE
Build failing: cannot find -lboost_iostreams

### ISSUE THREAD

**Issue by glp-p4** [weizhouUMICH/SAIGE#80]

**Comment by hamfry** [comment]
Have you found how to solve this error?

**Comment by glp-p4** [comment]
There appear to be many recent improvements to the SAIGE build process since I encountered that problem, so I am not sure if it still applies or not. However, at the time, my solution was that I needed to make sure the libboost version 1.55 libraries (this specific version appears to be needed) were placed in the /usr/lib folder.
