### ISSUE TITLE
Very few variants in the final output of SAIGE step2

### ISSUE THREAD

**Issue by datasciene** [weizhouUMICH/SAIGE#81]
Hi Wei,
I am having final output from SAIGE (0.29) step2, but the result file contains very few variants as compared to the input vcf file (hard call genotypes) given to step2. Can you explain the plausible reason for that? Why most of the variants are absent in the final output? I tried the same with the toy data supplied with package and found similar trend. Does it mean that whatever variants are reported in the final output file were eligible to be calculated by SAIGE for association output, and rest were not? I am using the standard command given in the cmd.sh for 2nd step.
Thanks
Monu

**Comment by weizhouUMICH** [comment]
Hi Monu,

I wonder if it is because of the minMAF or minMAC arguments. What do you
use for those two?

Thanks,
Wei

**Comment by datasciene** [comment]
Hi,
I am giving minMAC=1 and minMAF=0 in both the cases (i.e. toy data  and my data)
For toy data, console shows something like this:
`minMAC:  1 
minMAF:  0 
Minimum MAF of markers to be testd is  5e-04`

For my data, console shows something like this:
`minMAC:  1 
minMAF:  0 
Minimum MAF of markers to be testd is  0.000718`

My input vcf at 2nd step contains ~15k variants and many of them may have MAF below 0.000718. So I was wondering how software is defining the MAF of 0.000718 or 5e-04 in my or toy data respectively by itself even when I am giving minMAF=0?

Thanks.

**Comment by weizhouUMICH** [comment]
The higher one in minMAC and minMAF will be used, so the minimum MAF =
1/(2*sample size) in the jobs

**Comment by datasciene** [comment]
Thank you.
