### ISSUE TITLE
SAIGE Install fails - SAIGE_readDosage_vcf.cpp:1:55: fatal error: ../thirdParty/cget/include/savvy/reader.hpp: No such file or directory

### ISSUE THREAD

**Issue by jbsom** [weizhouUMICH/SAIGE#83]
OS: CentOS release 6.2 (Final)
R: R version 3.5.1 (2018-07-02) -- "Feather Spray"
Python: Python 3.5.2
GCC: gcc (GCC) 6.2.0

Installing SAIGE using the R library devtools from github fails when building thirdparty package savvy.

> devtools::install_github("weizhouUMICH/SAIGE") 
                    .
g++ -std=gnu++11 -I"/data4/packages/r-3.5.1/lib64/R/include" -DNDEBUG -I ../thirdParty/bgen/db/include -I ../thirdParty/bgen/genfile/include -I ../thirdParty/bgen/genfile/include/genfile -I ../thirdParty/bgen/genfile/include/genfile/bgen -I ../thirdParty/bgen/db/include/db -I ../thirdParty/bgen/3rd_party/boost_1_55_0 -I ../thirdParty/bgen/3rd_party/zstd-1.1.0 -I ../thirdParty/bgen/3rd_party/zstd-1.1.0/lib -I ../thirdParty/bgen/3rd_party/zstd-1.1.0/lib/compress -I ../thirdParty/bgen/3rd_party/zstd-1.1.0/lib/decompress -I ../thirdParty/bgen/3rd_party/sqlite3 -I ../thirdParty/bgen/3rd_party/boost_1_55_0/boost/iostreams -I ../thirdParty/cget/include -I ../thirdParty/cget/lib -D SQLITE_ENABLE_COLUMN_METADATA -O3 -fpic -Wall -Wextra -pedantic  -DARMA_64BIT_WORD=1  -I"/data4/packages/r-3.5.1/lib64/R/library/Rcpp/include" -I"/data4/packages/r-3.5.1/lib64/R/library/RcppArmadillo/include" -I"/data4/packages/r-3.5.1/lib64/R/library/RcppParallel/include" -I"/data4/packages/r-3.5.1/lib64/R/library/data.table/include" -I"/data4/packages/r-3.5.1/lib64/R/library/SPAtest/include" -I"/data4/packages/r-3.5.1/lib64/R/library/RcppEigen/include" -I"/data4/packages/r-3.5.1/lib64/R/library/Matrix/include" -I"/data4/packages/r-3.5.1/lib64/R/library/methods/include" -I/data4/packages/zlib-1.2.11/include -I/data4/packages/bzip2-1.0.6/include -I/data4/packages/pcre-8.38/include -I/data4/packages/curl-7.50.3/include -I/data4/packages/xz-5.2.2/include   -fpic  -I/data4/packages/zlib-1.2.11/include -I/data4/packages/bzip2-1.0.6/include -I/data4/packages/pcre-8.38/include -I/data4/packages/curl-7.50.3/include -I/data4/packages/xz-5.2.2/include -c SAIGE_readDosage_vcf.cpp -o SAIGE_readDosage_vcf.o
SAIGE_readDosage_vcf.cpp:1:55: fatal error: ../thirdParty/cget/include/savvy/reader.hpp: No such file or directory
 #include "../thirdParty/cget/include/savvy/reader.hpp"
                                                       ^
compilation terminated.
make: *** [SAIGE_readDosage_vcf.o] Error 1
ERROR: compilation failed for package ‘SAIGE’
* removing ‘/data4/packages/r-3.5.1/lib64/R/library/SAIGE’
* restoring previous ‘/data4/packages/r-3.5.1/lib64/R/library/SAIGE’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/RtmpOn03eW/file7d3878cacbfb/SAIGE_0.35.8.1.tar.gz’ had non-zero exit status
>

Thanks.

**Comment by weizhouUMICH** [comment]
Hi, 

The savvy library seems not installed. 
With the command 
devtools::install_github("weizhouUMICH/SAIGE")
The savvy library should be installed automatically. 
Would you mind trying again to see if the savvy library has been installed? 

Thanks,
Wei

**Comment by jbsom** [comment]
Sure thing. I give it a try and get back to you shortly.

Thanks for your time!

Regards,
John

**Comment by jbsom** [comment]
Wei,

The build failed with the same error. I have attached the build log for you to review. It looks like the build for savvy fails.

Thanks for your assistance it is much appreciated.

Regards,
John



Command failed: ['/data4/bin/cmake', '--build', '/tmp/RtmpFwlDAT/R.INSTALL14f0ca076f8/SAIGE/thirdParty/cget/cg

et/build/tmp-a3a37b423bdf4c568b5b2f8eda1a1821/build', '--config', 'Release', '--', '-j', '12']

Failed to build package statgen/savvy
                .
                .
                .

compilation terminated.

make: *** [SAIGE_readDosage_vcf.o] Error 1

ERROR: compilation failed for package ‘SAIGE’

* removing ‘/data4/packages/r-3.5.1/lib64/R/library/SAIGE’

* restoring previous ‘/data4/packages/r-3.5.1/lib64/R/library/SAIGE’

Error in i.p(...) :

  (converted from warning) installation of package ‘/tmp/Rtmp8ppKge/file12a84b50590d/SAIGE_0.35.8.1.tar.gz’ had non-zero exit status

>


From: "Bury, John" <JBury@som.umaryland.edu>
Date: Tuesday, April 2, 2019 at 10:10 AM
To: weizhouUMICH/SAIGE <reply@reply.github.com>, weizhouUMICH/SAIGE <SAIGE@noreply.github.com>
Cc: Author <author@noreply.github.com>, "Bury, John" <JBury@som.umaryland.edu>
Subject: Re: [weizhouUMICH/SAIGE] SAIGE Install fails - SAIGE_readDosage_vcf.cpp:1:55: fatal error: ../thirdParty/cget/include/savvy/reader.hpp: No such file or directory (#83)

Sure thing. I give it a try and get back to you shortly.

Thanks for your time!

Regards,
John

**Comment by jbsom** [comment]
Wei,

Just checing in to see if you had a chance to review the build log I sent.

Also, I have successfully built a copy of savvy v1.2.0 independent of SAIGE. Is there a way to point the installation of SAIGE to use this copy of savvy?

Thanks.
John

From: "Bury, John" <JBury@som.umaryland.edu>
Date: Tuesday, April 2, 2019 at 11:08 AM
To: weizhouUMICH/SAIGE <reply@reply.github.com>, weizhouUMICH/SAIGE <SAIGE@noreply.github.com>
Cc: Author <author@noreply.github.com>, "Bury, John" <JBury@som.umaryland.edu>
Subject: Re: [weizhouUMICH/SAIGE] SAIGE Install fails - SAIGE_readDosage_vcf.cpp:1:55: fatal error: ../thirdParty/cget/include/savvy/reader.hpp: No such file or directory (#83)

Wei,

The build failed with the same error. I have attached the build log for you to review. It looks like the build for savvy fails.

Thanks for your assistance it is much appreciated.

Regards,
John



Command failed: ['/data4/bin/cmake', '--build', '/tmp/RtmpFwlDAT/R.INSTALL14f0ca076f8/SAIGE/thirdParty/cget/cg

et/build/tmp-a3a37b423bdf4c568b5b2f8eda1a1821/build', '--config', 'Release', '--', '-j', '12']

Failed to build package statgen/savvy
                .
                .
                .

compilation terminated.

make: *** [SAIGE_readDosage_vcf.o] Error 1

ERROR: compilation failed for package ‘SAIGE’

* removing ‘/data4/packages/r-3.5.1/lib64/R/library/SAIGE’

* restoring previous ‘/data4/packages/r-3.5.1/lib64/R/library/SAIGE’

Error in i.p(...) :

  (converted from warning) installation of package ‘/tmp/Rtmp8ppKge/file12a84b50590d/SAIGE_0.35.8.1.tar.gz’ had non-zero exit status

>


From: "Bury, John" <JBury@som.umaryland.edu>
Date: Tuesday, April 2, 2019 at 10:10 AM
To: weizhouUMICH/SAIGE <reply@reply.github.com>, weizhouUMICH/SAIGE <SAIGE@noreply.github.com>
Cc: Author <author@noreply.github.com>, "Bury, John" <JBury@som.umaryland.edu>
Subject: Re: [weizhouUMICH/SAIGE] SAIGE Install fails - SAIGE_readDosage_vcf.cpp:1:55: fatal error: ../thirdParty/cget/include/savvy/reader.hpp: No such file or directory (#83)

Sure thing. I give it a try and get back to you shortly.

Thanks for your time!

Regards,
John

**Comment by jdpleiness** [comment]
I am also getting the same error when using the devtools method to install SAIGE.

OS: CentOS Linux release 7.6.1810 (Core)
R version: 3.5.2
Python version: 2.7.5
GCC version: 6.2.0

```
/usr/bin/ld: cannot find -lsavvy
collect2: error: ld returned 1 exit status
make: *** [SAIGE.so] Error 1
ERROR: compilation failed for package ‘SAIGE’
* removing ‘/usr/lib64/R/library/SAIGE’
Error in i.p(...) :
(converted from warning) installation of package ‘/tmp/RtmpBFOMXL/file6dff701eff61/SAIGE_0.35.8.2.tar.gz’ had non-zero exit status
Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
Execution halted
```

I have attempted to install savvy using cget as mentioned in issue #72 but also came back with a `usr/bin/ld: final link failed: Bad value` type error.

**Comment by jdpleiness** [comment]
Note that specifying devtools to use release v0.29.5 by referencing the version as such `devtools::install_github("weizhouUMICH/SAIGE", ref= "v0.29.5")` solves this issue for me, and savvy is successfully installed.

**Comment by agilly** [comment]
I can confirm this @jdpleiness on Ubuntu 18.04 with R 3.6.1. Same error, same solution. Hope this will be fixed in the next release.

**Comment by apoliakov** [comment]
I had a possibly same issue using R 3.6 on CentOS 7, using devtools::install_github('weizhouUMICH/SAIGE')

It turned out that 
1) saige tries to build savvy (this thing https://github.com/statgen/savvy)
2) savvy needs Cmake3 

So I followed these steps to install CMake3 and make it default
https://stackoverflow.com/questions/48831131/cmake-on-linux-centos-7-how-to-force-the-system-to-use-cmake3

After that, it worked like a charm.

**Comment by carbocation** [comment]
For me, this issue was solved by installing **zlib1g-dev** (`sudo apt-get install zlib1g-dev`) as per the [libStatGen instructions](https://github.com/statgen/libStatGen). Those instructions also recommend installing `g++` (which I did not need to install) and `libssl-dev` (which I already had installed).

**Comment by wym0072003** [comment]
@apoliakov  works, thank you so much!

**Comment by Mahantesh-Biradar** [comment]
I'm trying to install SAIGE using this command devtools::install_github("weizhouUMICH/SAIGE", ref= "v0.29.5") and I'm getting the following error, can you please help me solve this?

Error: Failed to install 'SAIGE' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   over-long path
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   over-long path
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   over-long path
E> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
E>   over-long path
E>  ERROR
E> copying to build directory failed
In addition: Warning message:
In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\MAHAN~1\AppData\Local\Temp\RtmpiMUgLB\fileb0b4416e4a48.tar.gz" -C "C:/Users/MAHAN~1/AppData/Local/Temp/RtmpiMUgLB/remotesb0b461735d66"’ returned error code 1
