### ISSUE TITLE
Error at fitting the null model

### ISSUE THREAD

**Issue by claireginger** [weizhouUMICH/SAIGE#84]
Hi, I got the following msg when fitting the null model for a binary trait; this never happened to me before, any ideas what might be causing the issue? Thanks a lot

iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 1
iter from getPCG1ofSigmaAndVector 0
Timing stopped at: 34827.47 86.238 1568.199 
Error in if (tau[2] == 0) break : missing value where TRUE/FALSE needed

Here is the input i specified: 
fitNULLGLMM(plinkFile = ***,
                phenoFile = *** ,
                phenoCol = ***,
                traitType = "binary" ,
                covarColList = *** ,
                sampleIDColinphenoFile = "IID",
                outputPrefix = ***,
                memoryChunk = 1)

**Comment by weizhouUMICH** [comment]
Hi, 

Can you show the first several lines of the log file? 

Thanks,
Wei

**Comment by claireginger** [comment]
Thanks Wei, here is the full log
[saige_log.txt](https://github.com/weizhouUMICH/SAIGE/files/3036422/saige_log.txt)

**Comment by weizhouUMICH** [comment]
Hi @claireginger, 
Would you mind trying 0.36.2 to see if the issue has been fixed? 
Best,
Wei
