### ISSUE TITLE
Problem running example files

### ISSUE THREAD

**Issue by fhuider** [weizhouUMICH/SAIGE#85]
Hi, I've been trying to run a single variant association test using the example files in extdata. During step 1 for the binary trait, I encounter an error when running the following code from the extdata directory:
Rscript step1_fitNULLGLMM.R     \
        --plinkFile=./input/nfam_100_nindep_0_step1_includeMoreRareVariants_poly \
        --phenoFile=./input/pheno_1000samples.txt_withdosages_withBothTraitTypes.txt \
        --phenoCol=y_binary \
        --covarColList=x1,x2 \
        --sampleIDColinphenoFile=IID \
        --traitType=binary        \
        --outputPrefix=./output/example_binary \
        --nThreads=4 \
        --LOCO=FALSE

I attached the error message in a .txt file. I get similar error messages for all the steps involved (i.e. all steps in cmd.sh) and google searches have yielded nothing. Any help would be hugely appreciated! 

Best wishes,
Floris

[error log.txt](https://github.com/weizhouUMICH/SAIGE/files/3054032/error.log.txt)

**Comment by luanjianan** [comment]
I got the same error message. help please!

**Comment by weizhouUMICH** [comment]
Hi,

The SPAcutoff argument is in the 0.35.XX version but the SAIGE version
shown in the log file is 0.29.5.
The example scripts for 0.29.5 can be found
https://github.com/weizhouUMICH/SAIGE/releases
in the source code folder.

Thanks,
Wei

**Comment by luanjianan** [comment]
Thank you Wei for the prompt reply.  yes, just noticed what we downloaded is version 0.29.5, while we followed the link for a binary install file which is the webpage you mentioned above.

Thank you for help very much.

 with best regards,
Jian'an

**Comment by weizhouUMICH** [comment]
Hi JIan'an, 

So sorry for the confusion. I just fixed the readme file. Please use the latest version 0.35.8.2 for both single-variant and gene-based tests. 

Thanks,
Wei
