### ISSUE TITLE
Releases above v0.29.5

### ISSUE THREAD

**Issue by koelling** [weizhouUMICH/SAIGE#86]
Thank you for building this great tool!

One question regarding the versions currently available: At the moment the latest release on Github is v0.29.5. However, in the change log you mention version numbers going up to v0.35.8.1. Would you consider this version to be "stable" already (ie. is it free of known bugs and well-tested)? Or is v0.29.5 still the version you would recommend people use right now?

If v0.35.8.1 is stable, could you please tag it in Github so that it generates a proper `tar.gz` for it?

**Comment by weizhouUMICH** [comment]
Hi, 
Sorry for the confusion. Now the version 0.35.8.2 has been added to the release. 

Thanks,
Wei

**Comment by koelling** [comment]
Great, thank you!
