### ISSUE TITLE
fitNULLGLMM.R error

### ISSUE THREAD

**Issue by cizydorczyk** [weizhouUMICH/SAIGE#9]
Hello,

I am very interested in running SAIGE,  and I have managed to install it successfully, but when I try to run it with my data, I get the following error:

```
$ Rscript ~/Software/SAIGE-master/extdata/step1_fitNULLGLMM.R --plinkFile=./snps.unique_seg.maf_0.05 --phenoFile=./snps.phe --phenoCol=y --sampleIDColinphenoFile=IID --traitType=binary --outputPrefix=./saige_output_test --nThreads=8
Warning message:
package ‘SAIGE’ was built under R version 3.4.3 
Loading required package: optparse
$plinkFile
[1] "./snps.unique_seg.maf_0.05"

$phenoFile
[1] "./snps.phe"

$phenoCol
[1] "y"

$covarColList
[1] ""

$sampleIDColinphenoFile
[1] "IID"

$centerVariables
[1] ""

$skipModelFitting
[1] FALSE

$traitType
[1] "binary"

$outputPrefix
[1] "./saige_output_test"

$numMarkers
[1] 30

$nThreads
[1] 8

$invNormalize
[1] FALSE

$help
[1] FALSE

8  threads are set to be used  
155  samples have genotypes
formula is  y~ 
Error in parse(text = x, keep.source = FALSE) : 
  <text>:2:0: unexpected end of input
1: y~
   ^
Calls: fitNULLGLMM ... formula -> formula.character -> formula -> eval -> parse
Execution halted
```
As far as I can tell, my data is formatted properly. Unfortunately, I cannot figure out what the problem might seem to be. I have 155 samples with phenotypes denoted "0" or "1", with no covariates. 

However, when I tried running it with an artificial covariate, and I instead get the following error message (perhaps because the covariate is just random numbers? But I don't have any covariates to include in the true analysis):

```
Error in if (max(abs(tau - tau0)/(abs(tau) + abs(tau0) + tol)) < tol) break : 
  missing value where TRUE/FALSE needed
Calls: fitNULLGLMM -> system.time -> glmmkin.ai_PCG_Rcpp_Binary
In addition: Warning messages:
1: glm.fit: algorithm did not converge 
2: glm.fit: algorithm did not converge 
Timing stopped at: 11.22 3.952 2.234
Execution halted
```

It may be difficult to troubleshoot without me giving more info - I can provide more information as needed, but am not sure what to provide up front. Note that I am using R 3.4.1, but I doubt this would be the issue.

Any help would be greatly appreciated!

Thank you,
Conrad Izydorczyk

**Comment by weizhouUMICH** [comment]
Hello Conrad, 
I'm glad to help! Could you please provide more details, such as a toy example, for me to try to debug? 
Thanks,
Wei

**Comment by cizydorczyk** [comment]
Hello Wei,

I have attached the sample set of files I have tried to run fitNULLGLMM.R
on but got the previously mentioned errors. They consist of 155 isolates
with ~ 33K SNPs. "snps.phe" is the phenotypes file, with isolate IDs in
column "IID", base-pair positions (not used) in column "BP", and the
phenotype in column "y". As previously mentioned, I do not have any
covariates to go along with this data set.

Please let me know if you require anything further.

Thank you,
Conrad Izydorczyk

**Comment by weizhouUMICH** [comment]
Hi Conrad, 

Sorry I haven't seen the attachment. Would you mind re-sending it? You may send to my email zhowei@umich.edu if you'd like. 

Thanks,
Wei

**Comment by cizydorczyk** [comment]
If it helps, I get the same error if I comment out the covariates line in the cmd.sh sample script:

```
#step 1: fit the NULL GLMM
Rscript step1_fitNULLGLMM.R \
	--plinkFile=./input/plinkforGRM_1000samples_10kMarkers \
	--phenoFile=./input/pheno_1000samples.txt \
	--phenoCol=y \
	#--covarColList=X2,X3 \
	--sampleIDColinphenoFile=IID \
	--traitType=binary \
	--outputPrefix=./output/example \
	--nThreads=4
```
Error:
```
...
1000  samples have genotypes
formula is  y~ 
Error in parse(text = x, keep.source = FALSE) : 
  <text>:2:0: unexpected end of input
1: y~
   ^
Calls: fitNULLGLMM ... formula -> formula.character -> formula -> eval -> parse
Execution halted
```

**Comment by weizhouUMICH** [comment]
Hi Conrad, 
I just uploaded the version 0.25 and this version handles models that have no covariates. 
Could you please give it a try? 
Thanks,
Wei
