### ISSUE TITLE
step 2 consumes too much CPU

### ISSUE THREAD

**Issue by chenwenyan2015** [weizhouUMICH/SAIGE#90]
![image](https://user-images.githubusercontent.com/31087691/56341289-248beb80-61e7-11e9-9855-66a2e7657fa1.png)
How can I set up to reduce CPU usage

**Comment by weizhouUMICH** [comment]
Hi, step 2 should only use 1 CPU per job. Are you running gene-based or single-variant tests?

**Comment by chenwenyan2015** [comment]
Hi，wei. I run single-variant tests with 80 phenotypes at the same time in step2. I think that's why it consumes too much CUP. Anyway, thanks for your reply.
