### ISSUE TITLE
Can SAIGE do analysis on ChrX?

### ISSUE THREAD

**Issue by luanjianan** [weizhouUMICH/SAIGE#91]
Can SAIGE do analysis on ChrX (including PAR and non-PAR regions)?

**Comment by luanjianan** [comment]
I tried but SAIGE failed with error message: 
Loading required package: optparse
Error in names(x) <- value :
  'names' attribute [9] must be the same length as the vector [0]
Calls: fitNULLGLMM ... scoreTest_SPAGMMAT_forVarianceRatio_quantitativeTrait -> colnames<-
Execution halted

**Comment by tmarcket** [comment]
I am also having the same issue described above. I am trying to use only variants from chrX to fit the null model and I am receiving the following error:

2119 th marker
G0 0 0 2 0 0 0 0 1 0 0 
[1] "OK2"
Error in names(x) <- value : 
'names' attribute [13] must be the same length as the vector [0]
Calls: fitNULLGLMM ... scoreTest_SPAGMMAT_forVarianceRatio_binaryTrait -> colnames<-
Execution halted

Is SAIGE not capable of building the RDA file from chrX alone?

**Comment by weizhouUMICH** [comment]
Hi, 

please check 
the version (0.35.8.9) and the binary installation file can be found in the branch https://github.com/weizhouUMICH/SAIGE/tree/forChrXOnly

An argument includeNonautoMarkersforVarRatio = TRUE in step 1 is added to allow for using non-autosomal markers to estimate the variance ratios. 

I will merge this to the master branch after having more tests. 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
I’m closing this issue and please reopen it if problem is not solved. 
Thanks!
Wei
