### ISSUE TITLE
Change default behavior of running on full file if no SNPs found in range?

### ISSUE THREAD

**Issue by carbocation** [weizhouUMICH/SAIGE#97]
In step 2, we can query with --rangestoIncludeFile to run the analysis on a subset of sites. However, if that file doesn't include any sites found in the BGEN, then the full BGEN is read. It seems that if you set a range and no variants are within that range, the expected default behavior would be for no variants to be emitted within that range.

https://github.com/weizhouUMICH/SAIGE/blob/fc0f8ae66481f77ddc90841378cba195d1af8845/src/SAIGE_readDosage_bgen.cpp#L217-L228

**Comment by weizhouUMICH** [comment]
Agree! I will modify the code in the next version. Thank you!!

**Comment by weizhouUMICH** [comment]
Sorry fo the late reply! We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
