### ISSUE TITLE
issue installing SAIGE (undefined symbol sgesvx_)

### ISSUE THREAD

**Issue by changd15** [weizhouUMICH/SAIGE#98]
I am installing SAIGE from the source code. Unfortunately, it fails with the following error:

installing to /gnet/is2/p01/home/changd15/Rlib/3.5.1-Bioc-3.8-prd/SAIGE/libs
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘SAIGE’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/gnet/is2/p01/home/changd15/Rlib/3.5.1-Bioc-3.8-prd/SAIGE/libs/SAIGE.so':
  /gnet/is2/p01/home/changd15/Rlib/3.5.1-Bioc-3.8-prd/SAIGE/libs/SAIGE.so: undefined symbol: sgesvx_
Error: loading failed
Execution halted
ERROR: loading failed

I am using R v3.5.1, gcc v6.3 and cmake v3.8.2. I think this has to do the Makevars file? but not quite sure how to fix this. Any help is greatly appreciated!

**Comment by weizhouUMICH** [comment]
By googling, it seems have something to do with the LAPACK library. 
Would you mind trying the steps in this file to install 
https://github.com/weizhouUMICH/Docker/blob/master/SAIGE/Dockerfile

Thanks!

**Comment by heichiyidui** [comment]
I met similar problem : liblapack.so.3: undefined symbol: chetrd_hb2st_
I updated the lapack package.
Then updated the so files in /usr/lib64/R/lib to links to the files liblapack.so and libblas.so I've just updated in /usr/lib64 .

**Comment by wavefancy** [comment]
@heichiyidui  and @changd15 ,

Please try my conda way if you still have the problem. I struggled one day, finally succeeded. Please check [here](https://github.com/wavefancy/WallaceBroad/tree/master/SAIGE). 


Best regards
Wallace

**Comment by jinghuazhao** [comment]
I intended update to SAIGE 0.36 and found this page. I have the same error message but got around with 
module load python/2.7
virtualenv py27
source py27/bin/activate
pip install cget
R CMD INSTALL SAIGE
...
" ... SAIGE.so: undefined symbol: sgecon_"
from here I renamed the configure to be configure.sav in the SAIGE directory (otherwise it starts all over again) and amend the last command with additional options
g++  ... -L.../lib64 -llapack -o SAIGE.so
and re-run R CMD INSTALL SAIGE
I would like to add that wscript is python 2 syntax so would be good to point out.

**Comment by weizhouUMICH** [comment]
We have just released a new version 1.0.0. It has computational efficiency improvements for both Step 1 and Step 2 for single-variant and set-based tests. We have created a new program github page https://github.com/saigegit/SAIGE with the documentation provided https://saigegit.github.io/SAIGE-doc/
The program will be maintained by multiple SAIGE developers there. The docker image has been updated. Please feel free to try the version 1.0.0 and report issues if any.

Thanks!
Wei
