### ISSUE TITLE
Problem running SAIGE in docker

### ISSUE THREAD

**Issue by choishingwan** [weizhouUMICH/SAIGE#99]
Hi,
I have installed the SAIGE using a docker image appproach and when i try to run the command and error message appears as below:

Rscript step1_fitNULLGLMM.R
Error: package or namespace load failed for ‘SAIGE’:
 .onLoad failed in loadNamespace() for 'RcppParallel', details:
  call: dyn.load(tbb, local = FALSE, now = TRUE)
  error: unable to load shared object '/hpc/users/wuh13/.Rlib/RcppParallel/lib/libtbb.so.2':
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /hpc/users/wuh13/.Rlib/RcppParallel/lib/libtbb.so.2)
Execution halted

Is there any solution for this error? Thanks!

**Comment by weizhouUMICH** [comment]
Hi, are you loading a docker image? If so, the RcppParallel is supposed to be called from the container. Thanks!

**Comment by weizhouUMICH** [comment]
Hi @choishingwan , 
I’m closing this issue because it has been inactive for a few months. 
Please reopen if you still encounter this issue with the version 0.36.3.1 
Thank you!
Wei
